helios::rendering::RenderingDevice
bool helios::rendering::RenderingDevice::initialized_
Reflects the initialization state of this device.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::init, initialized.
const helios::util::log::Logger& helios::rendering::RenderingDevice::logger_
The logger used with this RenderingDevice class.
Defaults to HELIOS_LOG_SCOPE.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::init.
virtual helios::rendering::RenderingDevice::~RenderingDevice()=default
virtual void helios::rendering::RenderingDevice::init()=0
Initializes this rendering device.
Should be called when the graphics context was created and before any rendering operations are performed. Implementing classes should load pointers to underlying GL functions or provide similar API-specific setup. std::runtime_error if initialization of the device fails.
virtual void helios::rendering::RenderingDevice::beginRenderPass(helios::rendering::RenderPass &renderPass) const noexcept=0
Signals this device that the application is now ready to begin a new render pass.
Implementing classes should prepare the rendering surface at this point and clear specific buffers. This method should be called at the start of each frame before any drawing occurs. renderPass The RenderPass that is about to be processed by the rendering device.
Referenced by render.
virtual void helios::rendering::RenderingDevice::doRender(helios::rendering::RenderPass &renderPass) const noexcept=0
Advises this RenderingDevice to process the specified RenderPass.
A `RenderPass` consists of `RenderCommand`s this RenderDevice executes, i.e. binding meshes, materials and shaders as well as drawing geometry. renderPass A reference to the RenderPass that holds the `RenderCommand`s to be executed.
Referenced by render.
virtual void helios::rendering::RenderingDevice::endRenderPass(helios::rendering::RenderPass &renderPass) const noexcept=0
Ends the specified render pass of this RenderingDevice.
This method should be called when the renderPass was processed by the RenderingDevice, before the window swaps the buffers. Implementing classes should take care of unbinding frame buffers and/or flushing command buffers. renderPass The RenderPass that was processed by the rendering device.
Referenced by render.
void helios::rendering::RenderingDevice::render(helios::rendering::RenderPass &renderPass) const
Convenience method to subsequently call `beginRenderPass`, `doRender`, and `endRenderPass` (in this order) with the specified `RenderPass`.
renderPass The RenderPass to process by this RenderingDevice.
References beginRenderPass, doRender, endRenderPass.
virtual helios::rendering::text::TextRenderer & helios::rendering::RenderingDevice::textRenderer() const noexcept=0
Returns the text renderer associated with this device.
Use this to register font families and access text rendering capabilities. Reference to the `TextRenderer` implementation. TextRenderer::addFontFamily()
virtual helios::rendering::text::FontResourceProvider & helios::rendering::RenderingDevice::fontResourceProvider() const noexcept=0
Returns the font resource provider associated with this device.
Use this to load fonts and access glyph data for text rendering. Fonts should be loaded before creating `TextRenderPrototype` instances that reference them. Reference to the `FontResourceProvider` implementation. FontResourceProvider::loadFont()
References fontResourceProvider.
Referenced by fontResourceProvider.
bool helios::rendering::RenderingDevice::initialized() const noexcept
Returns the initialized state of this rendering device.
This method is guaranteed to return `true` if the device was successfully initialized, otherwise `false`. `true` if the device was successfully initialized, `false` otherwise.
References initialized, initialized_.
Referenced by initialized.