helios::engine::state::types::StateTransitionRule
using helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionIdType = StateTransitionIdType<StateType>
StateType helios::engine::state::types::StateTransitionRule< StateType >::from_
The state this rule applies to.
StateTransitionIdType helios::engine::state::types::StateTransitionRule< StateType >::transitionId_
The transition ID that triggers this rule.
StateType helios::engine::state::types::StateTransitionRule< StateType >::to_
The target state after transition.
GuardCallback<StateType> helios::engine::state::types::StateTransitionRule< StateType >::guard_
Optional guard callback.
helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionRule(const StateType from, const StateTransitionIdType transitionId, const StateType to, GuardCallback< StateType > guard=nullptr)
Constructs a transition rule.
from The source state. transitionId The transition that triggers this rule. to The target state. guard Optional guard callback (default: nullptr).
References helios::engine::state::types::StateTransitionRule< StateType >::from, helios::engine::state::types::StateTransitionRule< StateType >::guard, helios::engine::state::types::StateTransitionRule< StateType >::to, helios::engine::state::types::StateTransitionRule< StateType >::transitionId.
StateType helios::engine::state::types::StateTransitionRule< StateType >::from() const noexcept
Returns the source state.
The state this rule applies to.
Referenced by helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionRule.
StateType helios::engine::state::types::StateTransitionRule< StateType >::to() const noexcept
Returns the target state.
The state after transition.
Referenced by helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionRule.
StateTransitionIdType helios::engine::state::types::StateTransitionRule< StateType >::transitionId() const noexcept
Returns the transition identifier.
The transition ID that triggers this rule.
Referenced by helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionRule.
GuardCallback< StateType > helios::engine::state::types::StateTransitionRule< StateType >::guard() const noexcept
Returns the guard callback.
The guard function pointer, or nullptr if no guard.
Referenced by helios::engine::state::types::StateTransitionRule< StateType >::StateTransitionRule.