helios::engine::mechanics::scoring::ScorePoolManager
std::vector<ScorePool> helios::engine::mechanics::scoring::ScorePoolManager::pools_
Collection of score pools managed by this manager.
std::vector<helios::engine::mechanics::scoring::types::ScoreValueContext> helios::engine::mechanics::scoring::ScorePoolManager::scores_
Pending score contexts to be processed on flush.
ScorePool & helios::engine::mechanics::scoring::ScorePoolManager::addScorePool(helios::engine::core::data::ScorePoolId scorePoolId) noexcept
Creates and registers a new score pool.
scorePoolId Unique identifier for the new pool. Reference to the newly created ScorePool.
References scorePool.
ScorePool * helios::engine::mechanics::scoring::ScorePoolManager::scorePool(const helios::engine::core::data::ScorePoolId scorePoolId) noexcept
Retrieves a score pool by ID.
scorePoolId The ID of the pool to find. Pointer to the ScorePool, or nullptr if not found.
References scorePool.
Referenced by addScorePool, scorePool, helios::engine::mechanics::scoring::systems::ScoreObserverSystem::update.
void helios::engine::mechanics::scoring::ScorePoolManager::flush(helios::engine::runtime::world::GameWorld &gameWorld, helios::engine::runtime::world::UpdateContext &update_context) noexcept override
Flushes pending score updates to their respective pools.
Processes all pending ScoreValueContext entries and adds them to the appropriate score pools based on their scorePoolId. gameWorld Reference to the game world. update_context Reference to the update context.
bool helios::engine::mechanics::scoring::ScorePoolManager::submit(const helios::engine::mechanics::scoring::commands::UpdateScoreCommand &updateScoreCommand) noexcept override
Submits a score update command for processing.
updateScoreCommand The command containing score context. True if the command was accepted.
void helios::engine::mechanics::scoring::ScorePoolManager::init(helios::engine::runtime::world::GameWorld &gameWorld) override
Initializes the manager and registers it as the score command handler.
gameWorld Reference to the game world.
References helios::engine::runtime::world::GameWorld::registerScoreCommandHandler.
virtual void helios::engine::mechanics::scoring::ScorePoolManager::reset()
Resets all managed score pools to zero.
Iterates through all registered pools and calls their reset() method, clearing all scores and resetting totals.