helios::engine::modules::ui::widgets::components::UiTextComponent
helios::rendering::text::TextRenderable* helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_
Pointer to the underlying text renderable. Not owned.
Referenced by renderable, renderable, UiTextComponent, UiTextComponent, update.
std::string helios::engine::modules::ui::widgets::components::UiTextComponent::text_
The current text content.
Referenced by setText, setText, update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isDirty_
True if the text content needs to be updated.
Referenced by reset, setText, setText, update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize_
True if the AABB bounds need to be recalculated.
Referenced by needsResize, resizeComplete, update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled_
Whether this component is enabled.
Referenced by disable, enable, isEnabled.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References isEnabled_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::enable() noexcept
Enables this component.
References isEnabled_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::disable() noexcept
Disables this component.
References isEnabled_.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(helios::rendering::text::TextRenderable *renderable)
Constructs a UiTextComponent with the given renderable.
renderable Pointer to the TextRenderable. Must not be nullptr.
References renderable, renderable_.
Referenced by operator=, operator=, UiTextComponent, UiTextComponent.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(const UiTextComponent &other)
Copy constructor.
other The component to copy from.
References renderable_, UiTextComponent.
UiTextComponent & helios::engine::modules::ui::widgets::components::UiTextComponent::operator=(const UiTextComponent &)=default
References UiTextComponent.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(UiTextComponent &&) noexcept=default
References UiTextComponent.
UiTextComponent & helios::engine::modules::ui::widgets::components::UiTextComponent::operator=(UiTextComponent &&) noexcept=default
References UiTextComponent.
const helios::rendering::text::TextRenderable * helios::engine::modules::ui::widgets::components::UiTextComponent::renderable() const noexcept
Returns the underlying text renderable as const pointer.
Const pointer to the TextRenderable. Never nullptr.
References renderable, renderable_.
Referenced by renderable, UiTextComponent.
helios::rendering::text::TextRenderable * helios::engine::modules::ui::widgets::components::UiTextComponent::renderable() noexcept
Returns the underlying text renderable as a pointer.
Pointer to the TextRenderable. Never nullptr.
References renderable_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::reset() noexcept
Resets the component to its initial state.
References isDirty_.
Referenced by onAcquire, onRelease.
void helios::engine::modules::ui::widgets::components::UiTextComponent::onAcquire() noexcept
Called when the component is acquired from an object pool.
Resets the component to its initial dirty state.
References reset.
void helios::engine::modules::ui::widgets::components::UiTextComponent::onRelease() noexcept
Called when the component is released back to an object pool.
Resets the component to its initial dirty state.
References reset.
void helios::engine::modules::ui::widgets::components::UiTextComponent::update()
Updates the text content if dirty.
Applies the template to the current value and updates the renderable.
References isDirty_, needsResize_, renderable_, text_.
Referenced by setText, setText.
void helios::engine::modules::ui::widgets::components::UiTextComponent::setText(const std::string &text)
Sets the text content and immediately updates the renderable.
No-op if the new text is identical to the current content. Otherwise marks the component as dirty and calls update(). text The new text content.
References isDirty_, text_, update.
void helios::engine::modules::ui::widgets::components::UiTextComponent::setText(std::string &&text)
Sets the text content by move and immediately updates the renderable.
Sets the text content and immediately updates the renderable. No-op if the new text is identical to the current content. Otherwise marks the component as dirty and calls update(). text The new text content.
References isDirty_, text_, update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize() const noexcept
Checks if the AABB bounds need recalculation.
True if a resize is needed, false otherwise.
References needsResize_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::resizeComplete() noexcept
Marks the resize as complete.
References needsResize_.