helios::rendering::RenderPassFactory
const helios::util::log::Logger& helios::rendering::RenderPassFactory::logger_
Shared logger instance for all RenderPassFactory objects.
Referenced by makeRenderCommand.
static RenderPassFactory & helios::rendering::RenderPassFactory::getInstance()
Returns the singleton instance of `RenderPassFactory`.
A reference to the single `RenderPassFactory` instance.
Referenced by helios::engine::modules::scene::systems::SceneRenderingSystem::update.
RenderPass helios::rendering::RenderPassFactory::buildRenderPass(const helios::scene::Snapshot &snapshot) const
Builds a `RenderPass` from a given `Snapshot`.
This method orchestrates the creation of a `RenderQueue` and populates it with render commands derived from the `SnapshotItem`s within the snapshot. It also sets up frame-specific uniform values (view and projection matrices) for the `RenderPass`. snapshot A const reference to the snapshot containing the scene data for which the `RenderPass` is to be built. A fully constructed `RenderPass` object containing the render queue and frame-specific uniforms. populateRenderQueue()
References populateRenderQueue, helios::rendering::shader::ProjectionMatrix, helios::scene::Snapshot::projectionMatrix, helios::rendering::shader::ViewMatrix, helios::scene::Snapshot::viewMatrix, helios::scene::Snapshot::viewport.
Referenced by helios::engine::modules::scene::systems::SceneRenderingSystem::update.
void helios::rendering::RenderPassFactory::populateRenderQueue(const helios::scene::Snapshot &snapshot, helios::rendering::RenderQueue &renderQueue) const
Populates an existing `RenderQueue` with render commands based on a `Snapshot`.
This method clears the specified `RenderQueue` before adding new commands. Each `SnapshotItem` in the snapshot is processed via `makeRenderCommand()`. snapshot A const reference to the `Snapshot` providing scene data. renderQueue A reference to the `RenderQueue` to be filled. This queue will be cleared before new commands are added. makeRenderCommand()
References helios::rendering::RenderQueue::clear, makeRenderCommand, helios::scene::Snapshot::snapshotItems.
Referenced by buildRenderPass.
void helios::rendering::RenderPassFactory::makeRenderCommand(const helios::scene::SnapshotItem &snapshotItem, helios::rendering::RenderQueue &renderQueue) const noexcept
Emits render commands from a `SnapshotItem` to the render queue.
This method extracts necessary data from the `SnapshotItem`, sets up the object uniform values (e.g., model matrix), and delegates to the `Renderable` to emit its render commands to the queue. snapshotItem A const reference to the `SnapshotItem` from which to create render commands. renderQueue A reference to the `RenderQueue` to emit commands to. If the `Renderable` pointer in the `SnapshotItem` is `nullptr`, a warning is logged and no commands are emitted.
References logger_, helios::rendering::shader::ModelMatrix.
Referenced by populateRenderQueue.