helios::engine::modules::spatial::transform::components::ComposeTransformComponent
helios::core::spatial::Transform helios::engine::modules::spatial::transform::components::ComposeTransformComponent::transform_
The local transformation (translation, rotation, scale).
bool helios::engine::modules::spatial::transform::components::ComposeTransformComponent::isDirty_
Flag indicating if the transform has changed since the last update.
helios::math::mat4f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::worldTransform_
The computed world transformation matrix.
bool helios::engine::modules::spatial::transform::components::ComposeTransformComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::spatial::transform::components::ComposeTransformComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::enable() noexcept
Enables this component.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::disable() noexcept
Disables this component.
helios::engine::modules::spatial::transform::components::ComposeTransformComponent::ComposeTransformComponent()=default
Default constructor.
Referenced by ComposeTransformComponent, ComposeTransformComponent, operator=, operator=, setLocalRotation, setLocalScale, setLocalTranslation, translateLocalBy.
helios::engine::modules::spatial::transform::components::ComposeTransformComponent::ComposeTransformComponent(const ComposeTransformComponent &other)
Copy constructor.
other The component to copy from.
References ComposeTransformComponent.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::operator=(const ComposeTransformComponent &)=default
References ComposeTransformComponent.
helios::engine::modules::spatial::transform::components::ComposeTransformComponent::ComposeTransformComponent(ComposeTransformComponent &&) noexcept=default
References ComposeTransformComponent.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::operator=(ComposeTransformComponent &&) noexcept=default
References ComposeTransformComponent.
bool helios::engine::modules::spatial::transform::components::ComposeTransformComponent::isDirty() const noexcept
Checks if the transform is dirty.
True if the transform has changed, false otherwise.
References isDirty.
Referenced by isDirty.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::clearDirty() noexcept
Clears the dirty flag.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::onAcquire() noexcept
Resets the dirty flag to true when acquired.
Makes sure the transform is considered after the component was acquired.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::onRelease() noexcept
Resets the dirty flag to true when released.
Makes sure the entities dirty-state is reset to the default state.
helios::math::mat4f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::localTransform() const noexcept
Returns the local transformation matrix.
The 4x4 matrix representing local translation, rotation, and scale.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::setLocalScale(const helios::math::vec3f &scale) noexcept
Sets the local scale.
scale The new scale vector. Reference to this component for chaining.
References ComposeTransformComponent.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::setLocalRotation(const helios::math::mat4f &rotation) noexcept
Sets the local rotation matrix.
rotation The new rotation matrix. Reference to this component for chaining.
References ComposeTransformComponent.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::setLocalTranslation(const helios::math::vec3f &translation) noexcept
Sets the local translation (position).
translation The new position vector. Reference to this component for chaining.
References ComposeTransformComponent.
ComposeTransformComponent & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::translateLocalBy(const helios::math::vec3f &translation) noexcept
Translates the component locally by a delta vector.
translation The vector to add to the current position. Reference to this component for chaining.
References ComposeTransformComponent.
helios::math::vec3f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::localTranslation() const noexcept
Returns the local translation vector.
The position relative to the parent.
helios::math::mat4f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::localRotation() const noexcept
Returns the local rotation matrix.
The rotation relative to the parent.
helios::math::vec3f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::localScaling() const noexcept
Returns the local scaling vector.
The scale relative to the parent.
void helios::engine::modules::spatial::transform::components::ComposeTransformComponent::setWorldTransform(const helios::math::mat4f &m) noexcept
Sets the world transform matrix directly.
m The new world transform matrix.
const helios::math::mat4f & helios::engine::modules::spatial::transform::components::ComposeTransformComponent::worldTransform() noexcept
Returns the current world transform matrix.
Const reference to the world transform.
helios::math::vec3f helios::engine::modules::spatial::transform::components::ComposeTransformComponent::worldTranslation() noexcept
Extracts the world translation from the world transform.
The global position vector.