helios::engine::ecs::SparseSet
std::vector<size_t> helios::engine::ecs::SparseSet< T >::sparse_
Maps EntityId to dense storage index.
Contains `Tombstone` for empty slots.
std::vector<EntityId> helios::engine::ecs::SparseSet< T >::denseToSparse_
Reverse mapping from dense index to EntityId.
Used during swap-and-pop removal to update the sparse array.
std::vector<T> helios::engine::ecs::SparseSet< T >::storage_
Contiguous storage of elements.
helios::engine::ecs::SparseSet< T >::SparseSet()=default
Default constructor creating an empty sparse set.
Referenced by helios::engine::ecs::SparseSet< T >::operator=, helios::engine::ecs::SparseSet< T >::operator=, helios::engine::ecs::SparseSet< T >::SparseSet, helios::engine::ecs::SparseSet< T >::SparseSet.
helios::engine::ecs::SparseSet< T >::SparseSet(const size_t capacity)
Constructs a sparse set with pre-allocated capacity.
capacity The initial capacity to reserve for all internal vectors.
helios::engine::ecs::SparseSet< T >::SparseSet(const SparseSet &)=delete
Copy operations are deleted to prevent accidental duplication.
References helios::engine::ecs::SparseSet< T >::SparseSet.
SparseSet & helios::engine::ecs::SparseSet< T >::operator=(const SparseSet &)=delete
Copy assignment is deleted.
References helios::engine::ecs::SparseSet< T >::SparseSet.
helios::engine::ecs::SparseSet< T >::SparseSet(SparseSet &&) noexcept=default
Move constructor.
References helios::engine::ecs::SparseSet< T >::SparseSet.
SparseSet & helios::engine::ecs::SparseSet< T >::operator=(SparseSet &&) noexcept=default
Move assignment operator.
References helios::engine::ecs::SparseSet< T >::SparseSet.
T * helios::engine::ecs::SparseSet< T >::emplace(const EntityId idx, Args &&...args)
Constructs and inserts an element at the given index.
Forwards arguments to construct `T` in-place. Args Constructor argument types. idx The EntityId to associate with the element. args Arguments forwarded to the `T` constructor. Pointer to the inserted element, or `nullptr` if the index is already occupied.
References helios::engine::ecs::SparseSet< T >::emplace, helios::engine::ecs::Tombstone.
Referenced by helios::engine::ecs::SparseSet< T >::emplace.
T * helios::engine::ecs::SparseSet< T >::insert(const EntityId idx, T &&obj)
Inserts an element at the given index.
If the sparse array is too small, it is resized to accommodate the index. Empty slots are filled with `Tombstone`. idx The EntityId to associate with the element. obj The element to insert (moved). Pointer to the inserted element, or `nullptr` if the index is already occupied.
References helios::engine::ecs::Tombstone.
bool helios::engine::ecs::SparseSet< T >::remove(const EntityId idx) override
Removes the element at the given index using swap-and-pop.
Uses the swap-and-pop technique for O(1) removal: 1. Move the last element to the position of the removed element 2. Update the sparse array entry for the moved element 3. Pop the last element from dense storage 4. Mark the removed slot as Tombstone idx The EntityId of the element to remove. `true` if the element was removed, `false` if not found.
References helios::engine::ecs::Tombstone.
T * helios::engine::ecs::SparseSet< T >::get(const EntityId idx)
Retrieves the element at the given index.
idx The EntityId to look up. Pointer to the element, or `nullptr` if not found.
References helios::engine::ecs::Tombstone.
Referenced by helios::engine::ecs::SparseSet< T >::raw.
const T * helios::engine::ecs::SparseSet< T >::get(const EntityId idx) const
Retrieves the element at the given index.
idx The EntityId to look up. Const Pointer to the element, or `nullptr` if not found.
References helios::engine::ecs::Tombstone.
bool helios::engine::ecs::SparseSet< T >::contains(const EntityId idx) const override
Checks whether an element is registered for the specified EntityId.
idx The entityId to test. True if this sparse set contains the entityId, otherwise false.
References helios::engine::ecs::Tombstone.
void * helios::engine::ecs::SparseSet< T >::raw(const helios::engine::core::data::EntityId id) override
Returns a raw void pointer to the element at the given index.
id The EntityId to look up. Raw pointer to the element, or `nullptr` if not found.
References helios::engine::ecs::SparseSet< T >::get.
Iterator helios::engine::ecs::SparseSet< T >::begin()
Returns an iterator to the beginning of the dense storage.
Iterator pointing to the first element.
Iterator helios::engine::ecs::SparseSet< T >::end()
Returns an iterator to the end of the dense storage.
Iterator pointing past the last element.
ConstIterator helios::engine::ecs::SparseSet< T >::begin() const
Returns a const iterator to the beginning of the dense storage.
ConstIterator pointing to the first element.
ConstIterator helios::engine::ecs::SparseSet< T >::end() const
Returns a const iterator to the end of the dense storage.
ConstIterator pointing past the last element.