helios::engine::mechanics::damage::components::DamageDealerComponent
std::array<float, helios::engine::core::data::MAX_COLLISION_LAYERS> helios::engine::mechanics::damage::components::DamageDealerComponent::damageRegistry_
Damage values indexed by collision layer.
bool helios::engine::mechanics::damage::components::DamageDealerComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::damage::components::DamageDealerComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::damage::components::DamageDealerComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::damage::components::DamageDealerComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent()=default
Referenced by DamageDealerComponent, DamageDealerComponent, operator=, operator=, setDamage.
helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent(const DamageDealerComponent &other)
Copy constructor.
other The component to copy from.
References DamageDealerComponent.
DamageDealerComponent & helios::engine::mechanics::damage::components::DamageDealerComponent::operator=(const DamageDealerComponent &)=default
References DamageDealerComponent.
helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent(DamageDealerComponent &&) noexcept=default
References DamageDealerComponent.
DamageDealerComponent & helios::engine::mechanics::damage::components::DamageDealerComponent::operator=(DamageDealerComponent &&) noexcept=default
References DamageDealerComponent.
DamageDealerComponent & helios::engine::mechanics::damage::components::DamageDealerComponent::setDamage(const float damage, const uint32_t otherLayerId) noexcept
Sets the damage dealt to entities on a specific layer.
damage The damage value to deal. otherLayerId The target collision layer ID (must be a power of 2). Reference to this component for method chaining.
References damage, DamageDealerComponent, setDamage.
Referenced by setDamage.
float helios::engine::mechanics::damage::components::DamageDealerComponent::damage(const uint32_t otherLayerId) const noexcept
Returns the damage dealt to entities on a specific layer.
otherLayerId The target collision layer ID (must be a power of 2). The damage value for the specified layer.
Referenced by setDamage.