helios::engine::ecs::GameObject
using helios::engine::ecs::GameObject::ComponentTypeId = helios::engine::core::data::ComponentTypeId
helios::util::Guid helios::engine::ecs::GameObject::guid_
Unique identifier for this GameObject.
Generated during construction and remains constant for the lifetime of the object. Used for lookups in GameWorld and command targeting.
Referenced by GameObject, GameObject, guid.
std::vector<std::unique_ptr<Component> > helios::engine::ecs::GameObject::components_
Type-indexed storage for components attached to this GameObject.
Components are stored at indices corresponding to their `ComponentTypeId::value()`. The vector is resized dynamically when component types with higher IDs are added. Slots for component types not attached to this GameObject contain nullptr. This storage model provides O(1) access and modification at the cost of potential sparse memory usage (nullptr entries for unused component type IDs). The vector may contain nullptr entries. Use `components()` for iteration over non-null components, which returns a cached, filtered view.
Referenced by add, finalizeAttach, get, get, getOrAdd, has, onAcquire, onRelease, setActive, updateCache.
bool helios::engine::ecs::GameObject::isActive_
Active state flag for this GameObject.
Inactive GameObjects are skipped during iteration and updates. When the state changes, onActivate() or onDeactivate() is called on all components.
Referenced by finalizeAttach, GameObject, isActive, setActive.
bool helios::engine::ecs::GameObject::needsUpdate_
Flag indicating whether the component cache needs to be rebuilt.
Set to true when components are added or removed. The cache is lazily rebuilt on the next call to `components()`.
Referenced by invalidateCache, updateCache.
std::vector<helios::engine::ecs::Component*> helios::engine::ecs::GameObject::componentView_
Cached view of non-null component pointers for mutable access.
Rebuilt from `components_` when `needsUpdate_` is true. Provides filtered access excluding nullptr entries.
Referenced by components, updateCache.
std::vector<const helios::engine::ecs::Component*> helios::engine::ecs::GameObject::componentConstView_
Cached view of non-null component pointers for const access.
Rebuilt from `components_` when `needsUpdate_` is true. Provides filtered access excluding nullptr entries.
Referenced by components, updateCache.
void helios::engine::ecs::GameObject::invalidateCache() noexcept
Invalidates the component cache, forcing a rebuild on next access.
Called automatically when components are added or removed.
References needsUpdate_.
Referenced by add, getOrAdd.
void helios::engine::ecs::GameObject::updateCache() const
Rebuilds the component cache if invalidated.
Iterates through `components_` and populates `componentView_` and `componentConstView_` with non-null entries. This operation is O(n) where n is the size of the components vector.
References componentConstView_, components_, componentView_, needsUpdate_.
Referenced by components, components.
helios::engine::ecs::GameObject::GameObject()
Constructs a new GameObject with a unique Guid.
The Guid is automatically generated and remains constant for the lifetime of this object.
References guid_.
helios::engine::ecs::GameObject::GameObject(bool isActive)
Constructs a new GameObject with a specified active state.
isActive Initial active state. If false, the object starts inactive.
References guid_, isActive, isActive_.
virtual helios::engine::ecs::GameObject::~GameObject()=default
Virtual destructor for proper polymorphic cleanup.
T & helios::engine::ecs::GameObject::add(Args &&... args)
Adds a new component of type T to the GameObject.
The component is created in-place, stored at the index corresponding to its `ComponentTypeId`, and attached to this GameObject (`onAttach()` is called). If the type ID exceeds the current vector capacity, the vector is resized. **Complexity:** O(1) amortized. Resize operations are O(n) but occur infrequently. T The type of component to add. Must derive from Component. Args Argument types for the component's constructor. args Arguments forwarded to the component's constructor. Reference to the newly created component. No component of type T is already attached (asserts in debug mode). The component is stored directly at `components_[ComponentTypeId::id<T>().value()]`.
References components_, finalizeAttach, has, helios::engine::core::data::ComponentTypeId::id, invalidateCache.
Referenced by getOrAdd.
helios::engine::ecs::Component * helios::engine::ecs::GameObject::getOrAdd(std::unique_ptr< helios::engine::ecs::Component > component)
Adds a pre-constructed component if no component of the same type exists.
If a component with the same `ComponentTypeId` already exists, returns the existing component without taking ownership of the passed pointer. Otherwise, stores the component at its type-indexed position and takes ownership. **Complexity:** O(1) amortized. May trigger resize if type ID exceeds capacity. component Unique pointer to the component to add. Ownership is transferred only if no component of the same type exists. Pointer to the existing or newly added component, or nullptr if the input was nullptr. Uses `component->typeId()` for runtime type identification.
References components_, finalizeAttach, has, invalidateCache.
std::remove_cvref_t< T > & helios::engine::ecs::GameObject::getOrAdd(Args &&... args)
Retrieves an existing component of type T, or creates and adds it if not present.
Convenience method that combines `get<T>()` and `add<T>()`. If the component already exists, the constructor arguments are ignored. **Complexity:** O(1) amortized. T The type of component to retrieve or add. Must derive from Component. Args Argument types for the component's constructor. args Arguments forwarded to the component's constructor if creation is needed. Reference to the existing or newly created component.
References add, get.
std::remove_cvref_t< T > * helios::engine::ecs::GameObject::get() const
Retrieves a component of type T.
Performs a direct array access using the component's type ID. If the type ID is out of bounds or the slot is nullptr, returns nullptr. **Complexity:** O(1) - Direct index access without hashing. T The type of component to retrieve. cv-qualifiers are stripped. Pointer to the component if found, nullptr otherwise.
References components_, helios::engine::core::data::ComponentTypeId::id.
Referenced by helios::engine::runtime::world::GameWorld::addGameObject, getOrAdd, hasDisabledComponent, hasEnabledComponent, helios::engine::runtime::spawn::behavior::initializers::DelayedComponentEnablerInitializer< ComponentTypes >::initialize, helios::engine::runtime::spawn::behavior::initializers::EmitterInitializer::initialize, helios::engine::runtime::spawn::behavior::initializers::RandomDirectionInitializer::initialize.
helios::engine::ecs::Component * helios::engine::ecs::GameObject::get(const ComponentTypeId componentTypeId) const noexcept
Retrieves a component by its runtime ComponentTypeId.
Performs a direct array access using the provided type ID value. Useful when the component type is not known at compile time. **Complexity:** O(1) - Direct index access. componentTypeId The runtime type ID of the component. Pointer to the component if found, nullptr otherwise.
References components_, has.
bool helios::engine::ecs::GameObject::has(const ComponentTypeId componentTypeId) const noexcept
Checks if a component with the given type ID exists.
Performs bounds checking and nullptr verification. **Complexity:** O(1) - Bounds check + nullptr comparison. componentTypeId The runtime type ID of the component to check. True if a component with this type ID exists, false otherwise.
References components_.
Referenced by add.
bool helios::engine::ecs::GameObject::has() const
Checks if the GameObject has a component of type T.
Delegates to `has(ComponentTypeId)` using the compile-time type ID. **Complexity:** O(1) - Direct index bounds check + nullptr comparison. T The type of component to check for. cv-qualifiers are stripped. True if the component exists, false otherwise.
References has, helios::engine::core::data::ComponentTypeId::id.
Referenced by get, getOrAdd, has.
bool helios::engine::ecs::GameObject::hasEnabledComponent() const
Checks if the GameObject has a component of type T and returns true if this component is enabled.
T The type of component to check for existence and if it's enabled. true if the component exists and is enabled, false otherwise.
References get.
bool helios::engine::ecs::GameObject::hasDisabledComponent() const
Checks if the GameObject has a component of type T and returns true if this component is disabled.
T The type of component to check for existence and if it's disabled. true if the component exists and is disabled, false otherwise.
References get.
const helios::util::Guid & helios::engine::ecs::GameObject::guid() const noexcept
Returns the unique identifier for this GameObject.
Const reference to the Guid, valid for the lifetime of this object.
References guid_.
Referenced by helios::engine::runtime::world::GameWorld::removeGameObject, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
bool helios::engine::ecs::GameObject::isActive() const noexcept
Checks if this GameObject is currently active.
True if the GameObject is active, false otherwise. Inactive GameObjects are typically skipped during updates and rendering.
References isActive_.
Referenced by GameObject.
std::span< helios::engine::ecs::Component *const > helios::engine::ecs::GameObject::components() noexcept
Returns a span over all attached (non-null) components.
Provides access to a cached, filtered view of components. The cache is lazily rebuilt when components are added or removed. **Complexity:** O(1) if cache is valid, O(n) on first call after modification. Span of non-null component pointers for mutable access. Modifying the underlying vector bypasses lifecycle callbacks. Use `add()` for proper component management.
References componentView_, updateCache.
Referenced by helios::engine::runtime::world::GameWorld::clone, helios::engine::runtime::spawn::behavior::initializers::DelayedComponentEnablerInitializer< ComponentTypes >::initialize.
std::span< const helios::engine::ecs::Component *const > helios::engine::ecs::GameObject::components() const noexcept
Returns a const span over all attached (non-null) components.
Provides read-only access to a cached, filtered view of components. **Complexity:** O(1) if cache is valid, O(n) on first call after modification. Span of non-null component pointers for const access.
References componentConstView_, updateCache.
void helios::engine::ecs::GameObject::setActive(bool active) noexcept
Sets the active state of this GameObject.
When the active state changes, this method notifies all attached components by calling onActivate() or onDeactivate() accordingly. If the new state equals the current state, no action is taken. (add()) active The new active state.
References components_, isActive_.
Referenced by helios::engine::runtime::pooling::GameObjectPoolManager::release.
void helios::engine::ecs::GameObject::onAcquire()
Called when this GameObject is acquired from a pool.
Notifies all attached components by calling their `onAcquire()` method. Used by the pool system to reset or initialize component state before reuse. GameObjectPool Component::onAcquire
References components_.
void helios::engine::ecs::GameObject::onRelease()
Called when this GameObject is released back to a pool.
Notifies all attached components by calling their `onRelease()` method. Used by the pool system to clean up component state before pooling. GameObjectPool Component::onRelease
References components_.
Referenced by helios::engine::runtime::pooling::GameObjectPoolManager::release.
void helios::engine::ecs::GameObject::finalizeAttach(helios::engine::ecs::Component *component=nullptr)
Finalizes attachment of components by calling lifecycle callbacks.
If a specific component is passed, only that component is finalized. Otherwise, all unattached components are finalized. Calls `onAttach()` followed by `onActivate()` or `onDeactivate()` based on the GameObject's active state. component Optional pointer to a specific component to finalize. If nullptr, all components are processed.
References components_, isActive_.
Referenced by add, getOrAdd.