helios::engine::modules::spatial::transform::components::RotationStateComponent
float helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotationAngle_
Current heading rotation angle in degrees.
helios::math::vec3f helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotationAxis_
Axis around which heading rotation occurs.
float helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotationAngle_
Current spin rotation angle in degrees.
helios::math::vec3f helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotationAxis_
Axis around which spin rotation occurs.
bool helios::engine::modules::spatial::transform::components::RotationStateComponent::needsUpdate_
Dirty flag indicating matrices need recalculation.
helios::math::mat4f helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotationMatrix_
Cached spin rotation matrix.
helios::math::mat4f helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotationMatrix_
Cached heading rotation matrix.
helios::math::mat4f helios::engine::modules::spatial::transform::components::RotationStateComponent::composedRotationMatrix_
Cached composed rotation matrix (heading * spin).
bool helios::engine::modules::spatial::transform::components::RotationStateComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::spatial::transform::components::RotationStateComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::enable() noexcept
Enables this component.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::disable() noexcept
Disables this component.
helios::engine::modules::spatial::transform::components::RotationStateComponent::RotationStateComponent()=default
Default constructor.
Referenced by operator=, operator=, RotationStateComponent, RotationStateComponent.
helios::engine::modules::spatial::transform::components::RotationStateComponent::RotationStateComponent(const RotationStateComponent &other)
Copy constructor.
other The component to copy from. Copies rotation axes but resets angles and matrices.
References RotationStateComponent.
RotationStateComponent & helios::engine::modules::spatial::transform::components::RotationStateComponent::operator=(const RotationStateComponent &)=default
References RotationStateComponent.
helios::engine::modules::spatial::transform::components::RotationStateComponent::RotationStateComponent(RotationStateComponent &&) noexcept=default
References RotationStateComponent.
RotationStateComponent & helios::engine::modules::spatial::transform::components::RotationStateComponent::operator=(RotationStateComponent &&) noexcept=default
References RotationStateComponent.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::setHeadingRotationAngle(float angle)
Sets the heading rotation angle.
angle The new heading rotation angle in degrees (wrapped to 0-360).
References setHeadingRotationAngle.
Referenced by setHeadingRotationAngle.
float helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotationAngle() const noexcept
Returns the current heading rotation angle.
The heading rotation angle in degrees.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::setHeadingRotationAxis(helios::math::vec3f axis)
Sets the heading rotation axis.
axis The new rotation axis (should be normalized).
helios::math::vec3f helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotationAxis() const noexcept
Returns the heading rotation axis.
The current heading rotation axis.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::setSpinRotationAngle(float angle)
Sets the spin rotation angle.
angle The new spin rotation angle in degrees (wrapped to 0-360).
float helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotationAngle() const noexcept
Returns the current spin rotation angle.
The spin rotation angle in degrees.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::setSpinRotationAxis(helios::math::vec3f axis)
Sets the spin rotation axis.
axis The new spin rotation axis (should be normalized).
helios::math::vec3f helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotationAxis() const noexcept
Returns the spin rotation axis.
The current spin rotation axis.
const helios::math::mat4f & helios::engine::modules::spatial::transform::components::RotationStateComponent::spinRotation() noexcept
Returns the spin rotation matrix.
Triggers matrix update if dirty. Const reference to the spin rotation matrix.
const helios::math::mat4f & helios::engine::modules::spatial::transform::components::RotationStateComponent::headingRotation() noexcept
Returns the heading rotation matrix.
Triggers matrix update if dirty. Const reference to the heading rotation matrix.
const helios::math::mat4f & helios::engine::modules::spatial::transform::components::RotationStateComponent::rotation() noexcept
Returns the composed rotation matrix (heading * spin).
Triggers matrix update if dirty. Const reference to the composed rotation matrix.
void helios::engine::modules::spatial::transform::components::RotationStateComponent::update()
Recalculates rotation matrices if dirty.
Updates spinRotationMatrix_, headingRotationMatrix_, and composedRotationMatrix_ based on current angles and axes.