helios::engine::state::types::StateTransitionContext
using helios::engine::state::types::StateTransitionContext< StateType >::StateTransitionIdType = typename StateTransitionId<StateType>::Type
StateType helios::engine::state::types::StateTransitionContext< StateType >::from_
The state being transitioned from.
StateTransitionIdType helios::engine::state::types::StateTransitionContext< StateType >::transitionId_
The transition that triggered this change.
StateType helios::engine::state::types::StateTransitionContext< StateType >::to_
The state being transitioned to.
helios::engine::state::types::StateTransitionContext< StateType >::StateTransitionContext(const StateType from, const StateType to, const StateTransitionIdType transitionId)
Constructs a transition context.
from The source state. to The target state. transitionId The transition identifier.
References helios::engine::state::types::StateTransitionContext< StateType >::from, helios::engine::state::types::StateTransitionContext< StateType >::to, helios::engine::state::types::StateTransitionContext< StateType >::transitionId.
StateType helios::engine::state::types::StateTransitionContext< StateType >::to() const noexcept
Returns the target state.
The state being transitioned to.
Referenced by helios::engine::state::types::StateTransitionContext< StateType >::StateTransitionContext.
StateType helios::engine::state::types::StateTransitionContext< StateType >::from() const noexcept
Returns the source state.
The state being transitioned from.
Referenced by helios::engine::state::types::StateTransitionContext< StateType >::StateTransitionContext.
StateTransitionIdType helios::engine::state::types::StateTransitionContext< StateType >::transitionId() const noexcept
Returns the transition identifier.
The ID of the transition.
Referenced by helios::engine::state::types::StateTransitionContext< StateType >::StateTransitionContext.