helios::engine::mechanics::gamestate::types::GameStateTransitionRule
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::from_
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionId_
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::to_
GameStateTransitionType helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionType_
GuardCallback helios::engine::mechanics::gamestate::types::GameStateTransitionRule::guard_
helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule(const GameState from, const GameStateTransitionId transitionId, const GameState to, const GameStateTransitionType transitionType, GuardCallback guard=nullptr)
Constructs a transition rule.
from The source state. transitionId The transition identifier. to The target state. transitionType The type of transition. guard Optional guard callback.
References from, guard, to, transitionId, transitionType.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::from() const noexcept
Returns the source state.
Referenced by GameStateTransitionRule.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::to() const noexcept
Returns the target state.
Referenced by GameStateTransitionRule.
GameStateTransitionType helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionType() const noexcept
Returns the transition type.
Referenced by GameStateTransitionRule.
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionId() const noexcept
Returns the transition identifier.
Referenced by GameStateTransitionRule.
GuardCallback helios::engine::mechanics::gamestate::types::GameStateTransitionRule::guard() const noexcept
Returns the guard callback, or nullptr if none.
Referenced by GameStateTransitionRule.