helios::rendering::text::TextRenderable
std::shared_ptr<const helios::rendering::text::TextRenderPrototype> helios::rendering::text::TextRenderable::textRenderPrototype_
Shared prototype containing shader and text properties.
Referenced by emit, localAABB, shareTextRenderPrototype, TextRenderable, textRenderPrototype, writeUniformValues.
std::optional<helios::rendering::text::TextShaderPropertiesOverride> helios::rendering::text::TextRenderable::textShaderPropertiesOverride_
Optional overrides for text shader properties.
Referenced by setTextShaderPropertiesOverride, TextRenderable, textShaderPropertiesOverride, writeUniformValues.
std::unique_ptr<helios::rendering::text::TextMesh> helios::rendering::text::TextRenderable::textMesh_
Positioning and styling data (font, position, scale).
Referenced by emit, localAABB, setText, text, textMesh, textMesh, TextRenderable.
helios::rendering::text::TextRenderable::TextRenderable(std::unique_ptr< helios::rendering::text::TextMesh > textMesh, std::shared_ptr< const helios::rendering::text::TextRenderPrototype > renderPrototype, const std::optional< helios::rendering::text::TextShaderPropertiesOverride > &textShaderPropertiesOverride=std::nullopt)
Constructs a TextRenderable with the given text mesh and configuration.
textMesh Unique pointer to the text mesh containing text content, font, and layout data. renderPrototype Shared prototype with shader and font configuration. textShaderPropertiesOverride Optional overrides for shader properties (e.g., text color). std::invalid_argument If `renderPrototype` is null.
References textMesh, textMesh_, textRenderPrototype_, textShaderPropertiesOverride, textShaderPropertiesOverride_.
std::optional< helios::rendering::text::TextShaderPropertiesOverride > helios::rendering::text::TextRenderable::textShaderPropertiesOverride() noexcept
Returns the optional shader properties override.
Optional containing the override if set.
References textShaderPropertiesOverride_.
Referenced by setTextShaderPropertiesOverride, TextRenderable.
void helios::rendering::text::TextRenderable::setTextShaderPropertiesOverride(helios::rendering::text::TextShaderPropertiesOverride textShaderPropertiesOverride) noexcept
Sets the shader properties override.
textShaderPropertiesOverride The override to apply.
References textShaderPropertiesOverride, textShaderPropertiesOverride_.
const helios::math::aabbf & helios::rendering::text::TextRenderable::localAABB() const noexcept override
Returns the local-space axis-aligned bounding box.
The AABB is computed based on the text layout and font metrics. Reference to the local-space AABB.
References textMesh_, textRenderPrototype_.
void helios::rendering::text::TextRenderable::setText(std::string text) noexcept
Updates the text string.
text The new text to render.
References text, textMesh_.
std::string_view helios::rendering::text::TextRenderable::text() const noexcept
Returns the current text string.
View of the text string.
References textMesh_.
Referenced by setText.
std::shared_ptr< const helios::rendering::text::TextRenderPrototype > helios::rendering::text::TextRenderable::shareTextRenderPrototype() const noexcept
Returns the text render prototype.
**PERF-NOTE:** This method returns a copy of the `shared_ptr`, triggering atomic reference counting. For read-only access in rendering loops, consider using `textRenderPrototype_.get()` directly or adding a `const TextRenderPrototype&` overload. Shared pointer to the prototype.
References textRenderPrototype_.
const helios::rendering::text::TextRenderPrototype & helios::rendering::text::TextRenderable::textRenderPrototype() const noexcept
Returns a const ref to the TextRenderPrototype used by this TextRenderable.
This method provides direct access to the prototype without incrementing the reference count, making it suitable for use in hot rendering paths. A const ref to the TextRenderPrototype.
References textRenderPrototype_.
const helios::rendering::text::TextMesh & helios::rendering::text::TextRenderable::textMesh() const noexcept
Returns the text mesh.
The text mesh contains the text content, font, and cached layout data. Reference to the text mesh.
References textMesh_.
Referenced by TextRenderable.
helios::rendering::text::TextMesh & helios::rendering::text::TextRenderable::textMesh() noexcept
Returns a mutable reference to the text mesh.
Mutable reference to the text mesh.
References textMesh_.
void helios::rendering::text::TextRenderable::writeUniformValues(helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept override
Writes uniform values to the given map.
Applies the prototype's text properties first, then any instance-specific overrides. Used by the render pipeline to configure the text shader. uniformValueMap The map to write uniform values to.
References textRenderPrototype_, textShaderPropertiesOverride_.
Referenced by emit.
void helios::rendering::text::TextRenderable::emit(helios::rendering::RenderQueue &renderQueue, helios::rendering::shader::UniformValueMap &objectUniformValues, helios::rendering::shader::UniformValueMap &materialUniformValues) const override
Emits a text render command to the render queue.
Creates a `TextRenderCommand` with the current text, prototype, and uniform values, then adds it to the render queue for processing by the `TextRenderer`. renderQueue The render queue to emit the command to. objectUniformValues Object-specific uniform values (e.g., model matrix). materialUniformValues Material uniform values (will be merged with text properties).
References helios::rendering::RenderQueue::add, textMesh_, textRenderPrototype_, writeUniformValues.