helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig
SpawnProfileConfig& helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::parent_
Parent profile this rule belongs to.
helios::engine::core::data::SpawnRuleId helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::ruleId_
Unique identifier for this rule.
std::unique_ptr<const helios::engine::runtime::spawn::policy::SpawnCondition> helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::condition_
Condition determining when to spawn.
std::unique_ptr<const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider> helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::amountProvider_
Provider determining how many to spawn.
helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig(SpawnProfileConfig &parent, helios::engine::core::data::SpawnRuleId ruleId)
Constructs a SpawnRuleConfig.
parent The parent profile config. ruleId Unique identifier for this rule.
Referenced by amount, condition, fixedAmount, timerCondition, timerWithAvailabilityCondition.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerCondition(const float intervalSeconds)
Sets a timer-based spawn condition.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerWithAvailabilityCondition(const float intervalSeconds)
Sets a combined condition: timer + pool availability.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::condition(std::unique_ptr< const helios::engine::runtime::spawn::policy::SpawnCondition > customCondition)
Sets a custom spawn condition.
customCondition Ownership is transferred. Reference to this config for chaining.
References SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::fixedAmount(const size_t count)
Sets a fixed spawn amount.
count Number of entities to spawn per trigger. Reference to this config for chaining.
References SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::amount(std::unique_ptr< const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider > customProvider)
Sets a custom amount provider.
customProvider Ownership is transferred. Reference to this config for chaining.
References SpawnRuleConfig.
std::unique_ptr< helios::engine::runtime::spawn::policy::SpawnRule > helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::build()
Builds the SpawnRule from this configuration.
The assembled SpawnRule.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::done()
Finalizes the rule and returns to the parent profile config.
Reference to the parent SpawnProfileConfig.