helios::engine::modules::effects::gfx::components::SpinComponent
float helios::engine::modules::effects::gfx::components::SpinComponent::rotationSpeed_
Rotation speed in degrees per second.
helios::math::vec3f helios::engine::modules::effects::gfx::components::SpinComponent::rotationAxis_
The axis around which the entity spins.
float helios::engine::modules::effects::gfx::components::SpinComponent::currentRotation_
Current accumulated rotation angle in degrees.
bool helios::engine::modules::effects::gfx::components::SpinComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::effects::gfx::components::SpinComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::effects::gfx::components::SpinComponent::enable() noexcept
Enables this component.
void helios::engine::modules::effects::gfx::components::SpinComponent::disable() noexcept
Disables this component.
helios::engine::modules::effects::gfx::components::SpinComponent::SpinComponent(const float rotationSpeed, const helios::math::vec3f rotationAxis)
Constructs a SpinComponent.
rotationSpeed Speed of rotation in degrees per second. rotationAxis The axis to rotate around.
Referenced by operator=, operator=, SpinComponent, SpinComponent.
helios::engine::modules::effects::gfx::components::SpinComponent::SpinComponent(const SpinComponent &other)
Copy constructor.
other The component to copy from.
References SpinComponent.
SpinComponent & helios::engine::modules::effects::gfx::components::SpinComponent::operator=(const SpinComponent &)=default
References SpinComponent.
helios::engine::modules::effects::gfx::components::SpinComponent::SpinComponent(SpinComponent &&) noexcept=default
References SpinComponent.
SpinComponent & helios::engine::modules::effects::gfx::components::SpinComponent::operator=(SpinComponent &&) noexcept=default
References SpinComponent.
helios::math::vec3f helios::engine::modules::effects::gfx::components::SpinComponent::axis()
Returns the rotation axis.
The normalized rotation axis vector.
References axis.
Referenced by axis.
float helios::engine::modules::effects::gfx::components::SpinComponent::speed() const
Returns the rotation speed.
Speed in degrees per second.
float helios::engine::modules::effects::gfx::components::SpinComponent::rotation() const
Returns the current accumulated rotation.
Current rotation angle in degrees.
void helios::engine::modules::effects::gfx::components::SpinComponent::setRotation(float currentRotation)
Sets the current accumulated rotation.
currentRotation The new rotation angle in degrees.