helios::engine::builder::gameObject::builders::configs::SceneNodeConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::gameObject_
Non-owning pointer to the target GameObject.
void helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::ensureRenderableComponent()
Validates that a RenderableComponent exists.
void helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::ensureSceneNode(const bool shouldBeAvailable)
Validates SceneNodeComponent presence.
shouldBeAvailable Whether the component should exist.
helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::SceneNodeConfig(const helios::engine::ecs::GameObject gameObject)
Constructs a SceneNodeConfig for the given GameObject.
gameObject Target GameObject to configure.
Referenced by inherit, parent, parent.
SceneNodeConfig & helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent(helios::scene::SceneNode *parent)
Creates a SceneNode and parents it to the given node.
parent Parent SceneNode in the scene graph. Reference to this config for chaining.
References parent, SceneNodeConfig, helios::engine::modules::rendering::renderable::components::RenderableComponent::shareRenderable.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::attachTo, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo, parent, parent.
SceneNodeConfig & helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent(helios::engine::ecs::GameObject parent)
Creates a SceneNode and parents it to another GameObject's node.
Establishes both scene graph and ECS hierarchy relationships: Adds HierarchyComponent to both entities if not present Sets parent-child relationship in HierarchyComponent Parents the SceneNode to the parent GameObject's SceneNode parent Parent GameObject whose SceneNode will be the parent. Reference to this config for chaining.
References parent, SceneNodeConfig, helios::engine::modules::rendering::renderable::components::RenderableComponent::shareRenderable.
SceneNodeConfig & helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::inherit(helios::math::TransformType transformType)
Sets the transform inheritance mode.
transformType Which transforms to inherit from parent. Reference to this config for chaining.
References SceneNodeConfig.