helios::ecs::EntityManager
using helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::EntityRegistry_type = TEntityRegistry
using helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::Handle_type = THandle
using helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::StrongId_type = Handle_type::StrongId_type
using helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::ComponentTypeId_type = ComponentTypeId<Handle_type>
using helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::ComponentOpsRegistry_type = ComponentOpsRegistry<Handle_type>
std::vector<std::unique_ptr<SparseSetBase> > helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::components_
Component storage indexed by type ID.
Todosort after size()
EntityRegistry_type helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::registry_
Entity registry owned by this EntityManager.
const size_t helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::capacity_
Initial capacity for the underlying sparse sets.
helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::EntityManager(const size_t capacity=TCapacity)
Constructs an EntityManager with the given capacity.
Creates an internally owned `EntityRegistry` initialized with the specified capacity. capacity Initial capacity for the registry and sparse sets. Defaults to `TCapacity`.
helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::EntityManager(EntityRegistry_type &registry, const size_t capacity=TCapacity)
Constructs an EntityManager with an external registry.
registry External EntityRegistry to use for handle allocation. capacity Initial capacity for the sparse sets. Defaults to `TCapacity`. DeprecatedPrefer the capacity-only constructor which creates its own registry internally.
Handle_type helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::create(StrongId_type strongId=StrongId_type{})
Creates a new entity.
Delegates to the underlying `EntityRegistry` to allocate a new handle. A valid `EntityHandle` for the newly created entity. EntityRegistry::create
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::isValid(const Handle_type handle) const noexcept
Checks if an entity handle is valid.
handle The handle to validate. `true` if the handle refers to a living entity.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::isValid(const EntityId entityId) const noexcept
Checks if an entity ID is valid.
entityId The entity ID to validate. `true` if the entity ID refers to a living entity.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::destroy(const Handle_type handle)
Destroys an entity and invalidates its handle.
Increments the entity's version in the registry, making all existing handles to this entity stale. Does automatically remove its components from storage. handle The handle of the entity to destroy. `true` if the entity was destroyed, `false` if already invalid.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw.
T * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::get(const Handle_type handle) const
Retrieves a component for the given entity.
T The component type to retrieve. handle The entity whose component to retrieve. Pointer to the component, or `nullptr` if the entity is invalid or does not have the requested component.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplaceOrGet.
SparseSet< T > * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::getSparseSet()
Returns the SparseSet for a component type.
T The component type. Pointer to the SparseSet, or `nullptr` if the type has no storage.
const SparseSet< T > * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::getSparseSet() const
Returns the SparseSet for a component type (const).
T The component type. Const pointer to the SparseSet, or `nullptr` if the type has no storage.
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has(const Handle_type handle) const
Checks whether an entity has a specific component.
T The component type to check for. handle The entity to query. `true` if the entity has the component, `false` if the handle is invalid or the component is not attached.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::clone, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::get, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::remove.
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has(const Handle_type handle, const ComponentTypeId_type typeId) const
Checks whether an entity has a component by type ID.
handle The entity to query. typeId The component type identifier. `true` if the entity has the component, `false` otherwise.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::types::ComponentTypeId< THandle >::value.
void helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable(const Handle_type handle, const ComponentTypeId_type typeId) const
Enables a component by type ID.
Calls the component's `enable()` method if registered. handle The entity whose component to enable. typeId The component type identifier.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::disable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable.
void helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::disable(const Handle_type handle, const ComponentTypeId_type typeId) const
Disables a component by type ID.
Calls the component's `disable()` method if registered. handle The entity whose component to disable. typeId The component type identifier.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
void helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable(const Handle_type handle, const ComponentTypeId_type typeId, const bool enable) const
Enables or disables a component by type ID.
handle The entity whose component to modify. typeId The component type identifier. enable `true` to enable, `false` to disable.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw.
T * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplace(const Handle_type handle, Args &&...args)
Constructs and attaches a component to an entity.
If the component type has not been registered yet, a new `SparseSet` is created. The component is constructed in-place with the provided arguments. Returns `nullptr` if the component already exists or if the handle was invalid. T The component type to emplace. Args Constructor argument types. handle The entity to attach the component to. args Arguments forwarded to the component constructor. Pointer to the newly created component, or `nullptr` if the handle is invalid.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplaceOrGet.
T * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplaceOrGet(const Handle_type handle, Args &&...args)
Returns existing component or creates a new one.
T The component type. Args Constructor argument types. handle The entity. args Arguments forwarded to the constructor if creating. Pointer to the existing or newly created component, or `nullptr` if the handle is invalid.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplace, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::get, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw.
bool helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::remove(const Handle_type &handle)
Removes a specific component from an entity.
Unlike `destroy()`, this only removes a single component type while keeping the entity and other components intact. T The component type to remove. handle The entity whose component to remove. `true` if the component was removed, `false` if the handle was invalid, the component was not attached, or removal was blocked by `onRemove`. destroy SparseSet::remove
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw.
std::generator< ComponentTypeId_type > helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::componentTypeIds(const Handle_type handle) const
Returns a generator over all component type IDs attached to an entity.
handle The entity to query. Generator yielding ComponentTypeId for each attached component.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::clone.
void helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::clone(const Handle_type source, const Handle_type target)
Clones all components from source entity to target entity.
Iterates through all components on the source and copies them to the target using the registered clone function. Skips components that already exist on the target. source The entity to clone from. target The entity to clone to.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::componentTypeIds, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw.
void * helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw(const Handle_type handle, const ComponentTypeId_type typeId) const
Returns raw void pointer to a component.
handle The entity. typeId The component type identifier. Raw pointer to the component, or `nullptr` if not found.
References helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::types::ComponentTypeId< THandle >::value.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::clone, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::destroy, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplaceOrGet, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::remove.
Handle_type helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::handle(const EntityId entityId) const
Reconstructs an EntityHandle from an EntityId.
entityId The entity ID. EntityHandle with current version from the registry.
Referenced by helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::componentTypeIds, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::destroy, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::disable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplace, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::emplaceOrGet, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::enable, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::get, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::isValid, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::isValid, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw, helios::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::remove.