helios::rendering::RenderTarget
unsigned int helios::rendering::RenderTarget::width_
The width of the render target in pixels.
unsigned int helios::rendering::RenderTarget::height_
The height of the render target in pixels.
helios::rendering::ViewportKey helios::rendering::RenderTarget::viewportKey_
Passkey instance to authorize `Viewport::setRenderTarget`.
std::vector<std::shared_ptr<helios::rendering::Viewport> > helios::rendering::RenderTarget::viewports_
A list of viewports owned by this render target.
TodoThe list should be sorted after a meaningful key, like the viewport's z-Index.
helios::rendering::RenderTarget::RenderTarget()=default
Default constructor.
helios::rendering::RenderTarget::RenderTarget(std::shared_ptr< helios::rendering::Viewport > viewport, unsigned int width=0, unsigned int height=0)
Constructs a RenderTarget with an initial viewport and dimensions.
viewport The default viewport for this RenderTarget. The viewport defines the rectangular area where the image is drawn. width The initial width of the render target in pixels. height The initial height of the render target in pixels. std::invalid_argument if viewport is a nullptr. addViewport()
References addViewport, height, width.
std::shared_ptr< helios::rendering::Viewport > helios::rendering::RenderTarget::addViewport(std::shared_ptr< helios::rendering::Viewport > viewport)
Adds a viewport to this render target and establishes a parent-child relationship.
Makes sure the viewport is informed about any possible bounds updates by calling onRenderTargetResize afterwards. viewport A shared pointer to the `Viewport` to be added. The newly added viewport as a shared pointer. std::invalid_argument if viewport is a nullptr, or if the viewport already has a parent RenderTarget.
Referenced by RenderTarget.
std::span< const std::shared_ptr< helios::rendering::Viewport > > helios::rendering::RenderTarget::viewports() noexcept
Returns a read-only view of all viewports owned by this RenderTarget.
A span of shared pointers to the viewports.
void helios::rendering::RenderTarget::setSize(unsigned int width, unsigned int height) noexcept
Resizes this RenderTarget to the specified dimensions and propagates the change to every viewport.
width The new width of the render target in pixels. height The new height of the render target in pixels. TodoA LayoutManager could be introduced to manage the arrangement of multiple viewports. helios::rendering::Viewport::onRenderTargetResize()
References height, width.
unsigned int helios::rendering::RenderTarget::width() const noexcept
Gets the width of the render target.
The width in pixels.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::beginRenderPass, RenderTarget, setSize.
unsigned int helios::rendering::RenderTarget::height() const noexcept
Gets the height of the render target.
The height in pixels.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::beginRenderPass, RenderTarget, setSize.