helios::engine::modules::spatial::transform::components::ScaleComponent
float helios::engine::modules::spatial::transform::components::ScaleComponent::width_
Width of the entity.
float helios::engine::modules::spatial::transform::components::ScaleComponent::height_
Height of the entity.
float helios::engine::modules::spatial::transform::components::ScaleComponent::depth_
Depth of the entity.
helios::core::units::Unit helios::engine::modules::spatial::transform::components::ScaleComponent::unit_
Unit of measurement for the dimensions.
bool helios::engine::modules::spatial::transform::components::ScaleComponent::isDirty_
Flag indicating if the scale has changed.
helios::engine::modules::spatial::transform::components::ScaleComponent::ScaleComponent(const float width, const float height, const float depth, helios::core::units::Unit unit)
Constructs a ScaleComponent with specified dimensions and unit.
width Width of the entity. height Height of the entity. depth Depth of the entity. unit Unit of measurement (default: Meter).
References unit.
Referenced by ScaleComponent.
helios::engine::modules::spatial::transform::components::ScaleComponent::ScaleComponent(const ScaleComponent &other)
Copy constructor.
other The component to copy from.
References ScaleComponent.
void helios::engine::modules::spatial::transform::components::ScaleComponent::onAttach(helios::engine::ecs::GameObject *gameObject) noexcept override
Called when the component is attached to a GameObject.
gameObject Pointer to the parent GameObject.
References helios::engine::ecs::Component::gameObject.
void helios::engine::modules::spatial::transform::components::ScaleComponent::onAcquire() noexcept override
Resets the dirty flag to true when acquired.
Makes sure scaling is considered once the component was acquired.
void helios::engine::modules::spatial::transform::components::ScaleComponent::onRelease() noexcept override
Resets the dirty flag to true when released.
Makes sure the entities dirty-state is reset to the default state.
void helios::engine::modules::spatial::transform::components::ScaleComponent::clearDirty() noexcept
Clears the dirty flag.
bool helios::engine::modules::spatial::transform::components::ScaleComponent::isDirty() const noexcept
Checks if the scale has changed.
True if dirty, false otherwise.
helios::core::units::Unit helios::engine::modules::spatial::transform::components::ScaleComponent::unit() const noexcept
Retrieves the unit of measurement.
The unit enum value.
Referenced by ScaleComponent, setScale.
helios::math::vec3f helios::engine::modules::spatial::transform::components::ScaleComponent::scaling() const noexcept
Retrieves the scaling vector (width, height, depth).
A vec3f containing the dimensions.
void helios::engine::modules::spatial::transform::components::ScaleComponent::setScale(const float width, const float height, const float depth, const helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the dimensions and unit of the entity.
width New width. height New height. depth New depth. unit New unit of measurement (default: Meter).
References helios::core::units::Meter, unit.