helios::engine::modules::ui::layout::components::TimeFormatterComponent
std::string helios::engine::modules::ui::layout::components::TimeFormatterComponent::format_
The format string used by std::vformat (expects minutes, seconds).
std::string helios::engine::modules::ui::layout::components::TimeFormatterComponent::elapsedLabel_
Label displayed instead of "00:00" when remaining time reaches zero.
bool helios::engine::modules::ui::layout::components::TimeFormatterComponent::hasElapsedLabel_
True if an elapsed label has been configured.
bool helios::engine::modules::ui::layout::components::TimeFormatterComponent::hideWhenZero_
True if the output should be empty when remaining time reaches zero.
TimeDisplayMode helios::engine::modules::ui::layout::components::TimeFormatterComponent::displayMode_
The active display mode (elapsed or remaining).
Declared mutable because format() may fall back to Elapsed when duration is zero.
void helios::engine::modules::ui::layout::components::TimeFormatterComponent::setFormat(std::string format, const TimeDisplayMode displayMode=TimeDisplayMode::Elapsed)
Sets the format string and display mode.
format A std::vformat-compatible string (e.g. "{:02d}:{:02d}"). displayMode The display mode to use. Defaults to Elapsed.
References helios::engine::modules::ui::layout::types::Elapsed, format.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build.
std::string helios::engine::modules::ui::layout::components::TimeFormatterComponent::format(const float elapsed, const float duration=0) const
Formats the given time values into a display string.
If duration is zero, the display mode falls back to Elapsed. elapsed Elapsed time in seconds. duration Total duration in seconds. Zero disables Remaining mode. The formatted time string.
References helios::engine::modules::ui::layout::types::Elapsed, helios::engine::modules::ui::layout::types::Remaining.
Referenced by setFormat.
void helios::engine::modules::ui::layout::components::TimeFormatterComponent::setElapsedLabel(std::string label)
Sets the label shown in place of "00:00" when remaining time reaches zero.
In Remaining mode, once the remaining time drops to one second or below, this label is returned by format() instead of the numeric output. Implicitly enables the elapsed label. label The label string to display (e.g. "TIME UP").
std::string helios::engine::modules::ui::layout::components::TimeFormatterComponent::elapsedLabel()
Returns the elapsed label.
The configured elapsed label string.
bool helios::engine::modules::ui::layout::components::TimeFormatterComponent::hasElapsedLabel() const
Returns whether an elapsed label is configured.
True if an elapsed label has been set.
void helios::engine::modules::ui::layout::components::TimeFormatterComponent::setHideWhenZero(const bool hideWhenZero) noexcept
Sets whether to hide the output when remaining time reaches zero.
hideWhenZero True to return an empty string at zero remaining time.
References hideWhenZero.
bool helios::engine::modules::ui::layout::components::TimeFormatterComponent::hideWhenZero() const
Returns whether the output is hidden at zero remaining time.
True if hidden when zero.
Referenced by setHideWhenZero.