helios::engine::modules::physics::collision::events::TriggerCollisionEvent
const helios::util::Guid helios::engine::modules::physics::collision::events::TriggerCollisionEvent::source_
GUID of the GameObject that initiated or detected the collision.
const helios::util::Guid helios::engine::modules::physics::collision::events::TriggerCollisionEvent::match_
GUID of the GameObject that was collided with.
const helios::math::vec3f helios::engine::modules::physics::collision::events::TriggerCollisionEvent::contact_
The world-space contact point of the collision.
helios::engine::modules::physics::collision::events::TriggerCollisionEvent::TriggerCollisionEvent(const helios::util::Guid source, const helios::util::Guid match, const helios::math::vec3f contact)
Constructs a TriggerCollisionEvent.
source GUID of the GameObject that detected or initiated the collision. match GUID of the GameObject that was collided with. contact The world-space position where the collision occurred.
References contact, match, source.
helios::math::vec3f helios::engine::modules::physics::collision::events::TriggerCollisionEvent::contact() const noexcept
Returns the contact point in world space.
The 3D position where the collision occurred.
Referenced by TriggerCollisionEvent.
helios::util::Guid helios::engine::modules::physics::collision::events::TriggerCollisionEvent::source() const noexcept
Returns the GUID of the source GameObject.
The source is the entity that detected/reported the collision. Use `GameWorld::find()` to retrieve the actual GameObject. GUID of the collision reporter.
Referenced by TriggerCollisionEvent.
helios::util::Guid helios::engine::modules::physics::collision::events::TriggerCollisionEvent::match() const noexcept
Returns the GUID of the matched GameObject.
The match is the entity that was collided with. Use `GameWorld::find()` to retrieve the actual GameObject. GUID of the collided entity.
Referenced by TriggerCollisionEvent.