helios::engine::runtime::pooling::GameObjectPool
std::vector<size_t> helios::engine::runtime::pooling::GameObjectPool::activeIndex_
Maps active GameObject EntityIds to their index in activeGameObjects_.
Enables O(1) lookup for release operations.
Referenced by acquire, lock, release, releaseAndRemove.
std::vector<size_t> helios::engine::runtime::pooling::GameObjectPool::versionIndex_
Tracks version numbers for active EntityHandles.
Used to validate that a release operation targets the correct entity version.
Referenced by acquire, lock, release, releaseAndRemove.
std::vector<helios::engine::ecs::EntityHandle> helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_
List of EntityHandles for currently active (in-use) GameObjects.
Referenced by acquire, activeCount, activeGameObjects, GameObjectPool, release, releaseAndRemove.
std::vector<helios::engine::ecs::EntityHandle> helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_
List of EntityHandles for currently inactive (available) GameObjects.
Referenced by acquire, addInactive, GameObjectPool, inactiveCount, inactiveGameObjects, release.
size_t helios::engine::runtime::pooling::GameObjectPool::poolSize_
The maximum number of objects this pool manages.
Referenced by GameObjectPool, size.
helios::engine::core::data::EntityId helios::engine::runtime::pooling::GameObjectPool::minEntityId_
Minimum EntityId in the pool (used for sparse array offset).
Referenced by addInactive, lock.
helios::engine::core::data::EntityId helios::engine::runtime::pooling::GameObjectPool::maxEntityId_
Maximum EntityId in the pool (used for sparse array sizing).
Referenced by addInactive, lock.
size_t helios::engine::runtime::pooling::GameObjectPool::delta_
Offset for sparse array indexing (equals minEntityId_ after lock).
Referenced by acquire, lock, release, releaseAndRemove.
const helios::util::Guid helios::engine::runtime::pooling::GameObjectPool::guid_
Unique identifier for this pool instance.
Referenced by GameObjectPool, guid.
bool helios::engine::runtime::pooling::GameObjectPool::locked_
True if the pool is locked and ready for acquire/release operations.
Referenced by addInactive, isLocked, lock.
helios::engine::runtime::pooling::GameObjectPool::GameObjectPool(size_t poolSize)
Constructs a GameObjectPool with the specified capacity.
Pre-allocates internal storage for the given pool size. The pool starts empty; use `addInactive()` or a factory to populate it. poolSize The maximum number of GameObjects this pool can manage.
References activeGameObjects_, guid_, inactiveGameObjects_, poolSize_.
helios::util::Guid helios::engine::runtime::pooling::GameObjectPool::guid() const noexcept
Returns the unique identifier of this pool.
The Guid assigned to this pool instance.
References guid_.
size_t helios::engine::runtime::pooling::GameObjectPool::size() const noexcept
Returns the maximum capacity of this pool.
The pool size specified at construction.
References poolSize_.
Referenced by addInactive.
bool helios::engine::runtime::pooling::GameObjectPool::acquire(helios::engine::ecs::EntityHandle &entityHandle)
Acquires an inactive GameObject from the pool.
Removes a EntityHandle from the inactive list and adds it to the active tracking structures. The caller is responsible for activating the actual GameObject in the GameWorld. entityHandle Receives the EntityHandle of the acquired object on success. True if an object was acquired, false if the pool is exhausted.
References activeGameObjects_, activeIndex_, delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::core::data::EntityTombstone, inactiveGameObjects_, helios::engine::ecs::EntityHandle::versionId, versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::isLocked() const noexcept
Checks if the pool is locked.
True if the pool is locked and ready for acquire/release operations.
References locked_.
void helios::engine::runtime::pooling::GameObjectPool::lock() noexcept
Locks the pool for acquire/release operations.
After locking, no more EntityHandles can be added via `addInactive()`. The sparse arrays are sized based on the min/max EntityIds added.
References activeIndex_, delta_, helios::engine::core::data::EntityTombstone, locked_, maxEntityId_, minEntityId_, versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::addInactive(const helios::engine::ecs::EntityHandle entityHandle)
Adds a EntityHandle to the inactive list without acquiring it.
Used during pool initialization to register pre-created GameObjects. Fails if the pool is already at capacity. entityHandle The EntityHandle of the GameObject to add. True if added successfully, false if pool is full.
References activeCount, helios::engine::ecs::EntityHandle::entityId, inactiveCount, inactiveGameObjects_, helios::engine::ecs::EntityHandle::isValid, locked_, maxEntityId_, minEntityId_, size.
bool helios::engine::runtime::pooling::GameObjectPool::release(const helios::engine::ecs::EntityHandle entityHandle)
Releases a GameObject back to the pool by its EntityHandle.
Validates the EntityHandle against both the GameWorld and the active tracking list. Uses swap-and-pop for O(1) removal from the active list. The object is marked inactive and added to the inactive list for future acquisition. entityHandle The unique identifier of the GameObject to release. True if the object was successfully released, false if the EntityHandle was not found in the GameWorld or not tracked as active.
References activeGameObjects_, activeIndex_, delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::core::data::EntityTombstone, inactiveGameObjects_, helios::engine::ecs::EntityHandle::isValid, helios::engine::ecs::EntityHandle::versionId, versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove(const helios::engine::ecs::EntityHandle entityHandle)
Releases and permanently removes a GameObject from the pool.
Unlike `release()`, this method does not add the EntityHandle back to the inactive list. Use this when a pooled object is being destroyed rather than recycled. entityHandle The unique identifier of the GameObject to remove. True if removed successfully, false if EntityHandle was not active.
References activeGameObjects_, activeIndex_, delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::core::data::EntityTombstone, helios::engine::ecs::EntityHandle::isValid, helios::engine::ecs::EntityHandle::versionId, versionIndex_.
size_t helios::engine::runtime::pooling::GameObjectPool::activeCount() const noexcept
Returns the number of active game objects.
The number of active game objects.
References activeGameObjects_.
Referenced by addInactive.
size_t helios::engine::runtime::pooling::GameObjectPool::inactiveCount() const noexcept
Returns the number of inactive game objects.
The number of inactive game objects.
References inactiveGameObjects_.
Referenced by addInactive.
std::span< helios::engine::ecs::EntityHandle > helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects()
Returns a span of all inactive EntityHandles.
Span of inactive EntityHandles.
References inactiveGameObjects_.
std::span< helios::engine::ecs::EntityHandle > helios::engine::runtime::pooling::GameObjectPool::activeGameObjects()
Returns a span of all active EntityHandles.
Span of active EntityHandles.
References activeGameObjects_.