helios::engine::mechanics::combat::components::LastAttackerComponent
helios::engine::mechanics::combat::types::AttackContext helios::engine::mechanics::combat::components::LastAttackerComponent::lastAttackContext_
Context of the most recent attack received.
helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent()=default
Referenced by LastAttackerComponent.
helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent(const LastAttackerComponent &other)
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References LastAttackerComponent.
void helios::engine::mechanics::combat::components::LastAttackerComponent::setLastAttackContext(const helios::engine::mechanics::combat::types::AttackContext lastAttackContext) noexcept
Sets the last attack context.
lastAttackContext The attack context to store.
References lastAttackContext.
helios::engine::mechanics::combat::types::AttackContext helios::engine::mechanics::combat::components::LastAttackerComponent::lastAttackContext() const noexcept
Returns the last attack context.
The stored AttackContext.
Referenced by setLastAttackContext.
void helios::engine::mechanics::combat::components::LastAttackerComponent::reset()
Resets the component to its initial state.
Referenced by onAcquire, onRelease.
void helios::engine::mechanics::combat::components::LastAttackerComponent::onAcquire() noexcept override
References reset.
void helios::engine::mechanics::combat::components::LastAttackerComponent::onRelease() noexcept override
References reset.