helios::engine::runtime::spawn::commands::SpawnCommand
const size_t helios::engine::runtime::spawn::commands::SpawnCommand::spawnBudget_
The number of GameObjects to spawn.
const helios::engine::core::data::SpawnProfileId helios::engine::runtime::spawn::commands::SpawnCommand::spawnProfileId_
const helios::engine::runtime::spawn::SpawnContext helios::engine::runtime::spawn::commands::SpawnCommand::spawnContext_
helios::engine::runtime::spawn::commands::SpawnCommand::SpawnCommand(const helios::engine::core::data::SpawnProfileId spawnProfileId, const helios::engine::runtime::spawn::SpawnContext &spawnContext, const size_t spawnBudget=1)
References spawnBudget, spawnContext, spawnProfileId.
void helios::engine::runtime::spawn::commands::SpawnCommand::execute(helios::engine::runtime::world::GameWorld &gameWorld) const noexcept override
Direct execution is a no-op; dispatching is required.
gameWorld The game world (unused).
virtual void helios::engine::runtime::spawn::commands::SpawnCommand::accept(helios::engine::runtime::world::GameWorld &gameWorld, helios::engine::runtime::messaging::command::WorldCommandDispatcher &dispatcher) const noexcept override
Accepts a dispatcher for command routing.
gameWorld The game world. dispatcher The dispatcher to route this command to.
helios::engine::core::data::SpawnProfileId helios::engine::runtime::spawn::commands::SpawnCommand::spawnProfileId() const noexcept
Returns the target pool ID.
The GameObjectPoolId to spawn from.
Referenced by SpawnCommand.
size_t helios::engine::runtime::spawn::commands::SpawnCommand::spawnBudget() const noexcept
Returns the spawn budget.
The number of objects to spawn.
Referenced by SpawnCommand.
const helios::engine::runtime::spawn::SpawnContext & helios::engine::runtime::spawn::commands::SpawnCommand::spawnContext() const noexcept
Referenced by SpawnCommand.