helios::rendering::text::TextRenderCommand
const helios::rendering::text::TextRenderPrototype* helios::rendering::text::TextRenderCommand::textRenderPrototype_
Non-owning pointer to the render prototype.
The prototype must remain valid for the lifetime of this command.
helios::rendering::shader::UniformValueMap helios::rendering::text::TextRenderCommand::textUniformValues_
Uniform values specific to this text instance.
std::string helios::rendering::text::TextRenderCommand::text_
The text string to render.
helios::rendering::text::DrawProperties helios::rendering::text::TextRenderCommand::drawProperties_
Positioning and styling data.
helios::rendering::text::TextRenderCommand::TextRenderCommand(const TextRenderCommand &)=delete
References TextRenderCommand.
Referenced by operator=, operator=, TextRenderCommand, TextRenderCommand, TextRenderCommand, ~TextRenderCommand.
TextRenderCommand & helios::rendering::text::TextRenderCommand::operator=(const TextRenderCommand &)=delete
References TextRenderCommand.
helios::rendering::text::TextRenderCommand::TextRenderCommand(TextRenderCommand &&) noexcept=default
References TextRenderCommand.
TextRenderCommand & helios::rendering::text::TextRenderCommand::operator=(TextRenderCommand &&) noexcept=default
References TextRenderCommand.
helios::rendering::text::TextRenderCommand::~TextRenderCommand()=default
References TextRenderCommand.
helios::rendering::text::TextRenderCommand::TextRenderCommand(std::string text, const helios::rendering::text::TextRenderPrototype *textRenderPrototype, const helios::rendering::text::DrawProperties drawProperties, const helios::rendering::shader::UniformValueMap &textUniformValues) noexcept
Constructs a text render command.
text The text string to render. textRenderPrototype Non-owning pointer to the prototype (must outlive this command). drawProperties Position, scale, and font selection. textUniformValues Uniform values for the text shader. `textRenderPrototype` must not be null.
References drawProperties, text, TextRenderCommand, textRenderPrototype, textUniformValues.
std::string_view helios::rendering::text::TextRenderCommand::text() const noexcept
Returns the text string.
View of the text to render.
Referenced by TextRenderCommand.
const helios::rendering::text::TextRenderPrototype * helios::rendering::text::TextRenderCommand::textRenderPrototype() const noexcept
Returns the render prototype.
Non-owning pointer to the prototype.
Referenced by TextRenderCommand.
const helios::rendering::text::DrawProperties & helios::rendering::text::TextRenderCommand::drawProperties() const noexcept
Returns the draw properties.
Reference to positioning and styling data.
Referenced by TextRenderCommand.
const helios::rendering::shader::UniformValueMap & helios::rendering::text::TextRenderCommand::textUniformValues() const noexcept
Returns the text-specific uniform values.
Reference to the uniform value map.
Referenced by TextRenderCommand.