helios::engine::game::components::scene::SceneNodeComponent
const helios::math::vec3f helios::engine::game::components::scene::SceneNodeComponent::canonicalSize_
Original mesh dimensions from the SceneNode's AABB.
Used as reference for setSize() calculations. Defaults to (1,1,1) if no renderable or mesh is available.
Referenced by SceneNodeComponent, setSize.
helios::scene::SceneNode* helios::engine::game::components::scene::SceneNodeComponent::sceneNode_
Non-owning pointer to the associated SceneNode.
Referenced by rotation, scaling, sceneNode, SceneNodeComponent, setRotation, setScale, setTranslation, translation.
helios::engine::game::components::scene::SceneNodeComponent::SceneNodeComponent(helios::scene::SceneNode *sceneNode)
Constructs a SceneNodeComponent linked to a SceneNode.
sceneNode Pointer to the SceneNode to control. Must not be nullptr.
References canonicalSize_, sceneNode, sceneNode_.
Referenced by setRotation, setScale, setSize, setTranslation.
SceneNodeComponent & helios::engine::game::components::scene::SceneNodeComponent::setSize(float width, float height, float depth, helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the world-space size of the object.
This operation sets the scale of the underlying SceneNode according to the canonical size of the Renderable represented by the SceneNode. width Desired width in the specified unit. height Desired height in the specified unit. depth Desired depth in the specified unit. unit Unit of measurement (default: Meter). Reference to this component for method chaining. Calculates scale factors based on canonical mesh size and applies them.
References canonicalSize_, helios::core::units::from, helios::core::units::Meter, SceneNodeComponent, setScale.
SceneNodeComponent & helios::engine::game::components::scene::SceneNodeComponent::setScale(const helios::math::vec3f &scale) noexcept
Sets the scale of the SceneNode directly.
scale Scale factors for each axis. Reference to this component for method chaining.
References sceneNode_, SceneNodeComponent.
Referenced by setSize.
SceneNodeComponent & helios::engine::game::components::scene::SceneNodeComponent::setRotation(const helios::math::mat4f &rotation) noexcept
Sets the rotation of the SceneNode.
rotation Rotation matrix to apply. Reference to this component for method chaining.
References rotation, sceneNode_, SceneNodeComponent.
SceneNodeComponent & helios::engine::game::components::scene::SceneNodeComponent::setTranslation(const helios::math::vec3f &translation) noexcept
Sets the translation of the SceneNode.
translation Position vector in world space. Reference to this component for method chaining.
References sceneNode_, SceneNodeComponent, translation.
helios::math::vec3f helios::engine::game::components::scene::SceneNodeComponent::translation() const noexcept
Returns the current local translation of the SceneNode.
Translation vector in local space.
References sceneNode_.
Referenced by setTranslation.
helios::math::mat4f helios::engine::game::components::scene::SceneNodeComponent::rotation() const noexcept
Returns the current local rotation of the SceneNode.
Rotation as 4x4 matrix.
References sceneNode_.
Referenced by setRotation.
helios::math::vec3f helios::engine::game::components::scene::SceneNodeComponent::scaling() const noexcept
Returns the current local scale of the SceneNode.
Scale factors for each axis.
References sceneNode_.
helios::scene::SceneNode * helios::engine::game::components::scene::SceneNodeComponent::sceneNode() const noexcept
Returns the underlying SceneNode.
Non-owning pointer to the associated SceneNode.
References sceneNode_.
Referenced by SceneNodeComponent.