helios::engine::runtime::world::System
std::unique_ptr<Concept> helios::engine::runtime::world::System::pimpl_
helios::engine::runtime::world::System::System()=default
Default constructor creating an empty System.
Referenced by operator=, operator=, System, System.
helios::engine::runtime::world::System::System(T system)
Wraps a concrete system in a type-erased System.
T The concrete system type, must satisfy `HasUpdate<T>`. system The concrete system instance to wrap (moved into internal storage).
helios::engine::runtime::world::System::System(const System &)=delete
References System.
System & helios::engine::runtime::world::System::operator=(const System &)=delete
References System.
System & helios::engine::runtime::world::System::operator=(System &&)=default
References System.
helios::engine::runtime::world::System::System(System &&) noexcept=default
References System.
void helios::engine::runtime::world::System::update(UpdateContext &updateContext) noexcept
Delegates to the wrapped system's `update()` method.
updateContext The current frame's update context. System must be initialized (pimpl_ != nullptr).
References update.
Referenced by update.
void helios::engine::runtime::world::System::init(GameWorld &gameWorld) noexcept
Delegates to the wrapped system's `init()` method, if present.
If the concrete type satisfies `HasInit<T>`, its `init()` is called. Otherwise this is a no-op. gameWorld The GameWorld for one-time initialization. System must be initialized (pimpl_ != nullptr).
void * helios::engine::runtime::world::System::underlying() noexcept
Returns a type-erased pointer to the wrapped system instance.
Pointer to the underlying concrete system. System must be initialized (pimpl_ != nullptr).
const void * helios::engine::runtime::world::System::underlying() const noexcept
Returns a type-erased pointer to the wrapped system instance.
Pointer to the underlying concrete system. System must be initialized (pimpl_ != nullptr).