helios::engine::mechanics::health::components::HealthComponent
float helios::engine::mechanics::health::components::HealthComponent::maxHealth_
Maximum health value.
float helios::engine::mechanics::health::components::HealthComponent::health_
Current health value.
bool helios::engine::mechanics::health::components::HealthComponent::isEnabled_
Whether this component is enabled.
HealthDepletedBehavior helios::engine::mechanics::health::components::HealthComponent::healthDepletedBehavior_
Flags controlling the response when health reaches zero.
bool helios::engine::mechanics::health::components::HealthComponent::isDirty_
True if the health value was modified since the last clear.
bool helios::engine::mechanics::health::components::HealthComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::health::components::HealthComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::health::components::HealthComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent()=default
Referenced by HealthComponent, HealthComponent, operator=, operator=.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(const float maxHealth)
Constructs a HealthComponent with the given maximum health.
maxHealth The maximum health value.
References maxHealth.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(const HealthComponent &other)
Copy constructor.
other The component to copy from.
References HealthComponent.
HealthComponent & helios::engine::mechanics::health::components::HealthComponent::operator=(const HealthComponent &)=default
References HealthComponent.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(HealthComponent &&) noexcept=default
References HealthComponent.
HealthComponent & helios::engine::mechanics::health::components::HealthComponent::operator=(HealthComponent &&) noexcept=default
References HealthComponent.
void helios::engine::mechanics::health::components::HealthComponent::setHealthDepletedBehavior(const HealthDepletedBehavior behavior) noexcept
Sets the health depletion response behaviour.
behavior Bitmask of HealthDepletedBehavior flags.
References setHealthDepletedBehavior.
Referenced by setHealthDepletedBehavior.
HealthDepletedBehavior helios::engine::mechanics::health::components::HealthComponent::healthDepletedBehavior() const noexcept
Returns the health depletion response behaviour.
Current HealthDepletedBehavior flags.
void helios::engine::mechanics::health::components::HealthComponent::takeDamage(const float damage) noexcept
Applies damage to this entity.
Health is clamped to a minimum of 0. damage The amount of damage to apply.
void helios::engine::mechanics::health::components::HealthComponent::heal(const float amount) noexcept
Heals this entity.
Health is clamped to the maximum health value. amount The amount to heal.
void helios::engine::mechanics::health::components::HealthComponent::setMaxHealth(const float maxHealth) noexcept
Sets the maximum health value.
maxHealth The new maximum health.
References maxHealth.
bool helios::engine::mechanics::health::components::HealthComponent::isAlive() const noexcept
Checks if the entity is alive.
True if health is greater than 0.
Referenced by helios::engine::mechanics::health::HealthManager::flush.
float helios::engine::mechanics::health::components::HealthComponent::health() const noexcept
Returns the current health value.
The current health.
float helios::engine::mechanics::health::components::HealthComponent::maxHealth() const noexcept
Returns the maximum health value.
The maximum health.
Referenced by HealthComponent, setMaxHealth.
bool helios::engine::mechanics::health::components::HealthComponent::isDirty() const noexcept
Checks whether the health value has been modified.
True if modified since the last clearDirty() call.
void helios::engine::mechanics::health::components::HealthComponent::clearDirty() noexcept
Resets the dirty flag.
void helios::engine::mechanics::health::components::HealthComponent::reset()
Resets health to maximum.
Referenced by onAcquire, onRelease.
void helios::engine::mechanics::health::components::HealthComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Resets health to maximum value.
References reset.
void helios::engine::mechanics::health::components::HealthComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Resets health to maximum value.
References reset.