helios::rendering::mesh::Mesh
bool helios::rendering::mesh::Mesh::needsUpdate_
Flag indicating whether the mesh requires updates to its computed data.
This variable is used to track whether the mesh's derived properties, such as its axis-aligned bounding box (AABB), are outdated and need to be recalculated. It is marked as mutable to allow modification within const member functions.
Referenced by aabb.
helios::math::aabbf helios::rendering::mesh::Mesh::aabb_
Represents the axis-aligned bounding box (AABB) for the mesh.
This member variable stores the computed or cached AABB for the mesh in 3D space. The AABB is a minimal bounding box aligned with the coordinate axes that encloses all the vertices of the mesh. It is marked mutable to allow updates during read-only operations, such as recalculating bounds as vertex positions are modified or updated dynamically. helios::math::aabb
Referenced by aabb.
std::shared_ptr<const std::vector<Vertex> > helios::rendering::mesh::Mesh::vertices_
Shared pointer to the raw, immutable vertices.
Referenced by aabb, helios::ext::opengl::rendering::model::OpenGLMesh::init, Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, vertices.
std::shared_ptr<const std::vector<unsigned int> > helios::rendering::mesh::Mesh::indices_
Shared pointer to the raw, immutable indices.
Referenced by indexCount, indices, helios::ext::opengl::rendering::model::OpenGLMesh::init, Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
std::shared_ptr<const helios::rendering::mesh::MeshConfig> helios::rendering::mesh::Mesh::meshConfig_
Shared pointer to the MeshConfig used with this Mesh.
Referenced by Mesh, Mesh, meshConfig, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
const helios::util::log::Logger& helios::rendering::mesh::Mesh::logger_
Shared logger instance for all Mesh objects.
Referenced by Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
helios::rendering::mesh::Mesh::Mesh()=default
Referenced by helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
virtual void helios::rendering::mesh::Mesh::init()=0
Initializes the Mesh by setting up vertex attributes and buffers with the underlying GL API. This method should be called _once_ by the derived class before using this Mesh in a rendering pass.
Todostd::shared_ptr<const std::vector<Texture>> textures_; std::runtime_error if the Mesh could not be initialized.
virtual helios::rendering::mesh::Mesh::~Mesh()=default
helios::rendering::mesh::Mesh::Mesh(std::shared_ptr< const std::vector< Vertex > > vertices, std::shared_ptr< const std::vector< unsigned int > > indices, std::shared_ptr< const helios::rendering::mesh::MeshConfig > meshConfig)
Creates a new Mesh instance.
vertices A shared_ptr to a vector of Vertex. indices A shared_ptr to a vector of indices. meshConfig A shared_ptr to the MeshConfig used with this Mesh. std::invalid_argument if either "vertices", "indices" or meshConfig is a null shared_ptr
References indices, indices_, logger_, meshConfig, meshConfig_, vertices, vertices_.
helios::rendering::mesh::Mesh::Mesh(const helios::rendering::asset::shape::Shape &shape, std::shared_ptr< const helios::rendering::mesh::MeshConfig > meshConfig)
Creates a new Mesh instance from the specified Shape.
shape A const reference to the Shape. meshConfig A shared_ptr to the MeshConfig used with this Mesh. std::invalid_argument if meshConfig is a null shared_ptr, or if the shape contained null data.
References indices, indices_, logger_, meshConfig, meshConfig_, vertices, vertices_.
unsigned int helios::rendering::mesh::Mesh::indexCount() const noexcept
Returns the index count of this Mesh.
The number of indices handled by this Mesh.
References indices_.
const std::vector< Vertex > & helios::rendering::mesh::Mesh::vertices() const noexcept
Returns a const reference to the underlying vertices. The returned data is guaranteed to be a valid reference to existing data.
A const ref to the vector of Vertex.
References vertices_.
Referenced by Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
const std::vector< unsigned int > & helios::rendering::mesh::Mesh::indices() const noexcept
Returns a const reference to the underlying indices. The returned data is guaranteed to be a valid reference to existing data.
A const ref to the vector of indices.
References indices_.
Referenced by Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
const helios::rendering::mesh::MeshConfig & helios::rendering::mesh::Mesh::meshConfig() const noexcept
Returns a const reference to MeshConfig used with this Mesh. The returned MeshConfig is guaranteed to be a valid reference to existing data.
The MeshConfig used with this Mesh.
References meshConfig_.
Referenced by Mesh, Mesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh, helios::ext::opengl::rendering::model::OpenGLMesh::OpenGLMesh.
const helios::math::aabbf & helios::rendering::mesh::Mesh::aabb() const noexcept
Retrieves the axis-aligned bounding box (AABB) of the mesh.
The method calculates and returns the AABB of the mesh, which encloses the mesh's vertices. If the mesh requires an update to its bounding box, this method recomputes the bounds based on the vertex positions and caches the result for future calls. The returned AABB represents the minimal rectangle in 3D space that contains all the vertices of the mesh. Reference to the computed axis-aligned bounding box.
References aabb_, needsUpdate_, vertices_.