helios::engine::runtime::messaging::command::types::CommandTypeId
using helios::engine::runtime::messaging::command::types::CommandTypeId::ComponentType = helios_engine_common_tag_CommandTypes
size_t helios::engine::runtime::messaging::command::types::CommandTypeId::id_
The underlying ID value.
helios::engine::runtime::messaging::command::types::CommandTypeId::CommandTypeId(const size_t id)
Constructs a CommandTypeId with a specific value.
id The type ID value.
References id.
Referenced by id, operator==.
helios::engine::runtime::messaging::command::types::CommandTypeId::CommandTypeId(helios::core::types::no_init_t)
Constructs an uninitialized CommandTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::runtime::messaging::command::types::CommandTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID.
Referenced by helios::engine::runtime::messaging::command::CommandHandlerRegistry::has, helios::engine::runtime::messaging::command::CommandHandlerRegistry::registerHandler, helios::engine::runtime::messaging::command::CommandHandlerRegistry::tryHandler.
static CommandTypeId helios::engine::runtime::messaging::command::types::CommandTypeId::id()
Returns the CommandTypeId for a specific command type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The command type. The unique CommandTypeId for type T.
References CommandTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by CommandTypeId, helios::engine::runtime::messaging::command::CommandHandlerRegistry::has, helios::engine::runtime::messaging::command::CommandHandlerRegistry::registerHandler, helios::engine::runtime::messaging::command::CommandHandlerRegistry::tryHandler.
bool operator==(CommandTypeId, CommandTypeId) noexcept=default
References CommandTypeId.