helios::engine::modules::ui::widgets::components::MenuComponent
std::vector<helios::engine::ecs::EntityHandle> helios::engine::modules::ui::widgets::components::MenuComponent::menuItems_
Entity handles of the menu items.
helios::engine::core::data::MenuId helios::engine::modules::ui::widgets::components::MenuComponent::menuId_
Unique identifier for this menu.
size_t helios::engine::modules::ui::widgets::components::MenuComponent::selectedIndex_
Currently selected item index.
size_t helios::engine::modules::ui::widgets::components::MenuComponent::previousSelectedIndex_
Previously selected item index.
size_t helios::engine::modules::ui::widgets::components::MenuComponent::defaultSelectedIndex_
Default selection index when menu is focused.
bool helios::engine::modules::ui::widgets::components::MenuComponent::isDirty_
Whether the menu state has changed.
void helios::engine::modules::ui::widgets::components::MenuComponent::setMenuId(helios::engine::core::data::MenuId id) noexcept
Sets the menu identifier.
id The menu ID.
helios::engine::core::data::MenuId helios::engine::modules::ui::widgets::components::MenuComponent::menuId() const noexcept
Returns the menu identifier.
The MenuId for this menu.
void helios::engine::modules::ui::widgets::components::MenuComponent::setSelectedIndex(const size_t index) noexcept
Sets the currently selected item index.
Marks the menu as dirty if the index changes. index The index to select.
References markDirty.
Referenced by selectDefaultIndex.
void helios::engine::modules::ui::widgets::components::MenuComponent::selectDefaultIndex()
Resets selection to the default index.
References setSelectedIndex.
size_t helios::engine::modules::ui::widgets::components::MenuComponent::selectedIndex() const noexcept
Returns the currently selected item index.
The selected index.
Referenced by helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
void helios::engine::modules::ui::widgets::components::MenuComponent::addMenuItem(const helios::engine::ecs::GameObject menuItem)
Adds a menu item to the end of the list.
menuItem The GameObject to add as a menu item.
References helios::engine::ecs::GameObject::entityHandle, markDirty.
std::span< helios::engine::ecs::EntityHandle > helios::engine::modules::ui::widgets::components::MenuComponent::menuItems() noexcept
Returns a span of all menu item handles.
Span of EntityHandle for all menu items.
Referenced by helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
void helios::engine::modules::ui::widgets::components::MenuComponent::clearDirty()
Clears the dirty flag.
void helios::engine::modules::ui::widgets::components::MenuComponent::markDirty()
Marks the menu as dirty.
Referenced by addMenuItem, setSelectedIndex.
bool helios::engine::modules::ui::widgets::components::MenuComponent::isDirty() const noexcept
Returns whether the menu state has changed.
True if dirty.
size_t helios::engine::modules::ui::widgets::components::MenuComponent::previousSelectedIndex() const noexcept
Returns the index of the previous selected menu index.
The index of the previous selected menu item.
void helios::engine::modules::ui::widgets::components::MenuComponent::insert(const helios::engine::ecs::GameObject menuItem, const size_t index)
Inserts a menu item at a specific index.
Resizes the internal vector if necessary. If the item already exists at the index, no action is taken. menuItem The GameObject to insert. index The index at which to insert.
References helios::engine::ecs::GameObject::entityHandle.