helios::engine::runtime::world::Session
ecs::GameObject helios::engine::runtime::world::Session::gameObject_
std::optional<ecs::GameObject> helios::engine::runtime::world::Session::playerEntity_
helios::engine::runtime::world::Session::Session(const ecs::GameObject go)
Constructs a session with the given GameObject.
Automatically adds GameStateComponent, UiFocusComponent, and MatchStateComponent to the GameObject. go The GameObject to use as the session entity.
void helios::engine::runtime::world::Session::setPlayerEntity(const ecs::GameObject go) noexcept
Sets the player entity for this session.
go The GameObject representing the player.
std::optional< ecs::GameObject > helios::engine::runtime::world::Session::playerEntity() const noexcept
Returns the player entity if set.
Optional containing the player GameObject, or nullopt.
Referenced by helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerActive, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerInactive.
void helios::engine::runtime::world::Session::reset()
Resets the session state.
bool helios::engine::runtime::world::Session::isPaused() const noexcept
Checks if the game is currently paused.
True if the game state is Paused.
References helios::engine::mechanics::gamestate::components::GameStateComponent::gameState, helios::engine::mechanics::gamestate::types::Paused.
void helios::engine::runtime::world::Session::setGameState(const GameState gameState) noexcept
Sets the current game state.
gameState The new game state.
References gameState.
void helios::engine::runtime::world::Session::setMatchStateFrom(const MatchStateTransitionContext matchStateTransitionContext) noexcept
Sets the current match state.
matchStateTransitionContext
GameState helios::engine::runtime::world::Session::gameState() const noexcept
Returns the current game state.
The current game state, or Undefined if not available.
References helios::engine::mechanics::gamestate::components::GameStateComponent::gameState, helios::engine::mechanics::gamestate::types::Undefined.
Referenced by setGameState.
MatchState helios::engine::runtime::world::Session::matchState() const noexcept
Returns the current match state.
The current match state, or Undefined if not available.
References helios::engine::mechanics::match::components::MatchStateComponent::matchState, helios::engine::mechanics::match::types::Undefined.
MatchStateTransitionId helios::engine::runtime::world::Session::matchStateTransitionId() const noexcept
Returns the current match state transition ID.
The transition ID, or Undefined if not available.
References helios::engine::mechanics::match::components::MatchStateComponent::matchStateTransitionId, helios::engine::mechanics::match::types::Undefined.
void helios::engine::runtime::world::Session::setFocusedEntity(std::optional< helios::engine::ecs::GameObject > gameObject) noexcept
Sets the currently focused UI entity.
gameObject The entity to focus, or nullopt to clear focus.
References setFocusedEntity.
Referenced by setFocusedEntity.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::world::Session::focusedEntity() noexcept
Returns the currently focused UI entity.
The focused entity, or nullopt if none is focused.
References focusedEntity.
Referenced by focusedEntity.
void helios::engine::runtime::world::Session::addViewportIds(const std::vector< helios::engine::core::data::ViewportId > &viewportIds) noexcept
Replaces the active viewport IDs with the provided list.
viewportIds The new list of active viewport IDs.
References addViewportIds, viewportIds.
Referenced by addViewportIds.
std::span< const helios::engine::core::data::ViewportId > helios::engine::runtime::world::Session::viewportIds() const noexcept
Returns the currently active viewport IDs.
Read-only span of viewport identifiers.
References viewportIds.
Referenced by addViewportIds, viewportIds.
void helios::engine::runtime::world::Session::clearViewportIds() noexcept
Clears all active viewport IDs.