helios::engine::mechanics::spawn::components::EmittedByComponent
helios::engine::ecs::EntityHandle helios::engine::mechanics::spawn::components::EmittedByComponent::source_
Handle of the entity that emitted this object.
bool helios::engine::mechanics::spawn::components::EmittedByComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::spawn::components::EmittedByComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::spawn::components::EmittedByComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::spawn::components::EmittedByComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent()=default
Default constructor.
Referenced by EmittedByComponent, EmittedByComponent, operator=, operator=.
helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent(const EmittedByComponent &other)
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References EmittedByComponent.
EmittedByComponent & helios::engine::mechanics::spawn::components::EmittedByComponent::operator=(const EmittedByComponent &)=default
References EmittedByComponent.
helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent(EmittedByComponent &&) noexcept=default
References EmittedByComponent.
EmittedByComponent & helios::engine::mechanics::spawn::components::EmittedByComponent::operator=(EmittedByComponent &&) noexcept=default
References EmittedByComponent.
void helios::engine::mechanics::spawn::components::EmittedByComponent::setSource(const helios::engine::ecs::EntityHandle source) noexcept
Sets the source entity that emitted this object.
source Handle of the emitting entity.
References setSource, source.
Referenced by setSource.
helios::engine::ecs::EntityHandle helios::engine::mechanics::spawn::components::EmittedByComponent::source() const noexcept
Returns the handle of the source entity.
Handle of the entity that emitted this object.
Referenced by setSource.
void helios::engine::mechanics::spawn::components::EmittedByComponent::reset()
Resets the component to its initial state.
Referenced by onAcquire, onRelease.
void helios::engine::mechanics::spawn::components::EmittedByComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Resets the source handle to prevent stale references.
References reset.
void helios::engine::mechanics::spawn::components::EmittedByComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Resets the source handle to prevent stale references.
References reset.