helios::engine::modules::physics::motion::components::Move2DComponent
float helios::engine::modules::physics::motion::components::Move2DComponent::DEFAULT_MOVEMENT_SPEED_THRESHOLD
Default minimum movement speed before the ship stops completely.
Referenced by resetToDefaults.
float helios::engine::modules::physics::motion::components::Move2DComponent::DEFAULT_MOVEMENT_ACCELERATION
Default movement acceleration in units per second squared.
Referenced by Move2DComponent, resetToDefaults.
float helios::engine::modules::physics::motion::components::Move2DComponent::DEFAULT_MOVEMENT_SPEED
Default base movement speed in units per second.
Referenced by resetToDefaults.
float helios::engine::modules::physics::motion::components::Move2DComponent::DEFAULT_MOVEMENT_DAMPENING
Default exponential decay factor for movement when input stops.
Referenced by resetToDefaults.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementSpeedThreshold_
Minimum movement speed before the ship stops completely.
Referenced by Move2DComponent, movementSpeedThreshold, resetToDefaults, setMovementSpeedThreshold.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementAcceleration_
Movement acceleration in units per second squared.
Referenced by Move2DComponent, Move2DComponent, movementAcceleration, resetToDefaults, setMovementAcceleration.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementSpeed_
Base movement speed in units per second.
Referenced by Move2DComponent, Move2DComponent, Move2DComponent, movementSpeed, resetToDefaults, setMoveIntent, setMovementSpeed, speedRatio.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementDampening_
Exponential decay factor for movement when input stops.
Referenced by Move2DComponent, movementDampening, resetToDefaults, setMovementDampening.
float helios::engine::modules::physics::motion::components::Move2DComponent::currentMovementSpeed_
Current movement speed after applying input and dampening.
Referenced by currentMovementSpeed, reset, setCurrentMovementSpeed, setMoveIntent.
bool helios::engine::modules::physics::motion::components::Move2DComponent::stateChanged_
Indicates whether input is currently being received.
Referenced by reset, setMoveIntent, stateChanged.
float helios::engine::modules::physics::motion::components::Move2DComponent::throttle_
Current throttle value from input (0.0 to 1.0).
Referenced by reset, setMoveIntent, throttle.
helios::math::vec2f helios::engine::modules::physics::motion::components::Move2DComponent::direction_
Current steering input as 2D direction vector.
Referenced by direction, reset, setMoveIntent.
helios::math::vec3f helios::engine::modules::physics::motion::components::Move2DComponent::velocity_
Current velocity vector in world space.
Referenced by reset, setVelocity, speedRatio, velocity.
helios::math::vec3f helios::engine::modules::physics::motion::components::Move2DComponent::inheritedVelocity_
Inherited velocity from parent or external forces.
Used for momentum inheritance when detaching from parent objects.
Referenced by inheritedVelocity, reset, setInheritedVelocity.
bool helios::engine::modules::physics::motion::components::Move2DComponent::useInstantAcceleration_
Flag for instant acceleration mode.
When true, the entity accelerates instantly to target speed rather than smoothly ramping up.
Referenced by Move2DComponent, Move2DComponent, setUseInstantAcceleration, useInstantAcceleration.
bool helios::engine::modules::physics::motion::components::Move2DComponent::isEnabled_
Whether this component is enabled.
Referenced by disable, enable, isEnabled.
void helios::engine::modules::physics::motion::components::Move2DComponent::reset()
Resets this component's properties to default values.
References currentMovementSpeed_, direction_, inheritedVelocity_, stateChanged_, throttle_, velocity_.
Referenced by onAcquire, onRelease.
bool helios::engine::modules::physics::motion::components::Move2DComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References isEnabled_.
void helios::engine::modules::physics::motion::components::Move2DComponent::enable() noexcept
Enables this component.
References isEnabled_.
void helios::engine::modules::physics::motion::components::Move2DComponent::disable() noexcept
Disables this component.
References isEnabled_.
helios::engine::modules::physics::motion::components::Move2DComponent::Move2DComponent()=default
Default constructor with default physics parameters.
Referenced by Move2DComponent, Move2DComponent, operator=, operator=.
helios::engine::modules::physics::motion::components::Move2DComponent::Move2DComponent(float movementSpeed, float movementAcceleration=DEFAULT_MOVEMENT_ACCELERATION)
Constructs a Move2DComponent with a specified movement speed.
movementSpeed The maximum movement speed in units per second. movementAcceleration The acceleration rate (default: DEFAULT_MOVEMENT_ACCELERATION).
References DEFAULT_MOVEMENT_ACCELERATION, movementAcceleration, movementAcceleration_, movementSpeed, movementSpeed_.
helios::engine::modules::physics::motion::components::Move2DComponent::Move2DComponent(float movementSpeed, bool useInstantAcceleration)
Constructs a Move2DComponent with instant acceleration mode.
movementSpeed The maximum movement speed in units per second. useInstantAcceleration If true, acceleration is instant.
References movementSpeed, movementSpeed_, useInstantAcceleration, useInstantAcceleration_.
helios::engine::modules::physics::motion::components::Move2DComponent::Move2DComponent(const Move2DComponent &other)
Copy constructor.
other The component to copy from.
References Move2DComponent, movementAcceleration_, movementDampening_, movementSpeed_, movementSpeedThreshold_, useInstantAcceleration_.
Move2DComponent & helios::engine::modules::physics::motion::components::Move2DComponent::operator=(const Move2DComponent &)=default
References Move2DComponent.
helios::engine::modules::physics::motion::components::Move2DComponent::Move2DComponent(Move2DComponent &&) noexcept=default
References Move2DComponent.
Move2DComponent & helios::engine::modules::physics::motion::components::Move2DComponent::operator=(Move2DComponent &&) noexcept=default
References Move2DComponent.
void helios::engine::modules::physics::motion::components::Move2DComponent::move(helios::math::vec3f direction, float throttle)
Sets the movement direction and throttle.
direction Normalized 3D direction vector. throttle Magnitude of the stick input (0.0 to 1.0). Deprecateduse setMoveIntent
References direction, move, setMoveIntent, throttle.
Referenced by helios::engine::runtime::spawn::behavior::initializers::RandomDirectionInitializer::initialize, move.
void helios::engine::modules::physics::motion::components::Move2DComponent::setMoveIntent(helios::math::vec3f direction, float throttle)
Sets the movement direction and throttle.
direction Normalized 3D direction vector. throttle Magnitude of the stick input (0.0 to 1.0).
References currentMovementSpeed_, direction, direction_, helios::math::EPSILON_LENGTH, movementSpeed_, stateChanged_, throttle, throttle_.
Referenced by move.
void helios::engine::modules::physics::motion::components::Move2DComponent::onAcquire() noexcept
Calls reset() when this Component is acquired.
reset()
References reset.
void helios::engine::modules::physics::motion::components::Move2DComponent::onRelease() noexcept
Calls reset() when this Component is released.
reset()
References reset.
bool helios::engine::modules::physics::motion::components::Move2DComponent::useInstantAcceleration() const noexcept
Returns whether instant acceleration mode is enabled.
True if acceleration is instant, false for smooth ramping.
References useInstantAcceleration_.
Referenced by Move2DComponent, setUseInstantAcceleration.
void helios::engine::modules::physics::motion::components::Move2DComponent::setUseInstantAcceleration(const bool useInstantAcceleration) noexcept
Sets the instant acceleration mode.
useInstantAcceleration True to enable instant acceleration, false for smooth ramping.
References useInstantAcceleration, useInstantAcceleration_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setInheritedVelocity(helios::math::vec3f inheritedVelocity)
Sets the inherited velocity from parent or external forces.
inheritedVelocity The velocity vector to inherit.
References inheritedVelocity, inheritedVelocity_.
helios::math::vec3f helios::engine::modules::physics::motion::components::Move2DComponent::inheritedVelocity() const noexcept
Returns the inherited velocity vector.
The inherited velocity from parent or external forces.
References inheritedVelocity_.
Referenced by setInheritedVelocity.
void helios::engine::modules::physics::motion::components::Move2DComponent::setVelocity(helios::math::vec3f velocity) noexcept
Sets the current velocity vector.
velocity The new velocity vector.
References velocity, velocity_.
float helios::engine::modules::physics::motion::components::Move2DComponent::currentMovementSpeed() const noexcept
Returns the current movement speed.
The current movement speed.
References currentMovementSpeed_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setCurrentMovementSpeed(float speed) noexcept
Sets the current movement speed.
speed The new movement speed.
References currentMovementSpeed_.
bool helios::engine::modules::physics::motion::components::Move2DComponent::stateChanged() const noexcept
Checks if input is currently active.
True if input is active, false otherwise.
References stateChanged_.
const helios::math::vec2f & helios::engine::modules::physics::motion::components::Move2DComponent::direction() const noexcept
Returns the current steering input direction.
Const reference to the 2D steering input vector.
References direction_.
Referenced by helios::engine::runtime::spawn::behavior::initializers::RandomDirectionInitializer::initialize, move, setMoveIntent.
float helios::engine::modules::physics::motion::components::Move2DComponent::throttle() const noexcept
Returns the current throttle value (0.0 to 1.0).
Current throttle magnitude from input.
References throttle_.
Referenced by move, setMoveIntent.
const helios::math::vec3f & helios::engine::modules::physics::motion::components::Move2DComponent::velocity() const noexcept
Returns the current velocity vector.
Const reference to the 3D velocity vector in world space.
References velocity_.
Referenced by setVelocity.
float helios::engine::modules::physics::motion::components::Move2DComponent::speedRatio() const noexcept
Returns the current speed as a ratio of maximum speed.
A value between 0.0 (stationary) and 1.0 (maximum speed).
References helios::math::EPSILON_LENGTH, movementSpeed_, velocity_.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementSpeedThreshold() const noexcept
Returns the minimum movement speed threshold.
Movement speed threshold below which movement stops.
References movementSpeedThreshold_.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementAcceleration() const noexcept
Returns the movement acceleration in units per second squared.
Movement acceleration value.
References movementAcceleration_.
Referenced by Move2DComponent.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementSpeed() const noexcept
Returns the maximum movement speed in units per second.
Maximum movement speed value.
References movementSpeed_.
Referenced by Move2DComponent, Move2DComponent.
float helios::engine::modules::physics::motion::components::Move2DComponent::movementDampening() const noexcept
Returns the movement dampening factor.
Exponential decay factor for movement.
References movementDampening_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setMovementSpeedThreshold(float value) noexcept
Sets the minimum movement speed threshold.
value New threshold value.
References movementSpeedThreshold_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setMovementAcceleration(float value) noexcept
Sets the movement acceleration in units per second squared.
value New acceleration value.
References movementAcceleration_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setMovementSpeed(float value) noexcept
Sets the maximum movement speed in units per second.
value New maximum speed value.
References movementSpeed_.
void helios::engine::modules::physics::motion::components::Move2DComponent::setMovementDampening(float value) noexcept
Sets the movement dampening factor.
value New dampening factor (exponential decay).
References movementDampening_.
void helios::engine::modules::physics::motion::components::Move2DComponent::resetToDefaults() noexcept
Resets all physics parameters to their default values.
References DEFAULT_MOVEMENT_ACCELERATION, DEFAULT_MOVEMENT_DAMPENING, DEFAULT_MOVEMENT_SPEED, DEFAULT_MOVEMENT_SPEED_THRESHOLD, movementAcceleration_, movementDampening_, movementSpeed_, movementSpeedThreshold_.