helios::core::ecs::View
TEntityManager* helios::core::ecs::View< TEntityManager, Components >::em_
std::tuple<SparseSet<Components>*... > helios::core::ecs::View< TEntityManager, Components >::includeSets_
Pointers to the SparseSets of the included components.
std::vector<std::function<bool(EntityId)> > helios::core::ecs::View< TEntityManager, Components >::excludeChecks_
List of exclusion predicates. Stores functions that return true if an entity should be EXCLUDED. Operates on EntityId (index) because the SparseSet uses it internally.
bool helios::core::ecs::View< TEntityManager, Components >::filterEnabledOnly_
Flag to filter only enabled components.
bool helios::core::ecs::View< TEntityManager, Components >::filterActiveOnly_
helios::core::ecs::View< TEntityManager, Components >::View(TEntityManager *em)
Constructs the view and retrieves the necessary component sets.
em Pointer to the EntityManager to retrieve sets and construct Entities.
Referenced by helios::core::ecs::View< TEntityManager, Components >::exclude, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator, helios::core::ecs::View< TEntityManager, Components >::whereEnabled.
View & helios::core::ecs::View< TEntityManager, Components >::exclude()
Excludes entities that have a specific component.
Entities possessing the specified component type will be skipped during iteration. Multiple exclusions can be chained. ```cpp // Skip entities with Shield or Invincible for (auto [e, health] : world->view<HealthComponent>() .exclude<ShieldComponent>() .exclude<InvincibleComponent>()) { // Only vulnerable entities } ``` T The component type to exclude. Reference to this View for method chaining.
References helios::core::ecs::View< TEntityManager, Components >::View.
bool helios::core::ecs::View< TEntityManager, Components >::empty()
References helios::core::ecs::View< TEntityManager, Components >::begin, helios::core::ecs::View< TEntityManager, Components >::end.
View & helios::core::ecs::View< TEntityManager, Components >::whereEnabled()
Filters to only include entities with enabled components.
Components must implement `isEnabled()` returning bool. Components without this method are assumed to be enabled. Reference to this View for method chaining.
References helios::core::ecs::View< TEntityManager, Components >::View.
Iterator helios::core::ecs::View< TEntityManager, Components >::begin()
Returns an iterator to the first valid entity.
Uses the first component type's SparseSet as the lead. If the first entity is invalid, advances to the next valid one. Iterator to the first valid entity, or end() if none found.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid.
Referenced by helios::core::ecs::View< TEntityManager, Components >::empty.
Iterator helios::core::ecs::View< TEntityManager, Components >::end()
Returns an iterator to the end (past the last entity).
End iterator for comparison.
Referenced by helios::core::ecs::View< TEntityManager, Components >::empty, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.