helios::core::ecs::TypedHandleWorld
std::tuple<TEntityManagers...> helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManagers_
auto & helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManager()
Returns a reference to the EntityManager that owns handles of type `THandle`.
Uses `HandleToManager` to resolve the tuple index at compile time. A `static_assert` fires if no manager matches. THandle The handle type identifying the target domain. Mutable reference to the matching EntityManager.
Referenced by helios::core::ecs::TypedHandleWorld< TEntityManagers >::addEntity, helios::core::ecs::TypedHandleWorld< TEntityManagers >::findEntity, helios::core::ecs::TypedHandleWorld< TEntityManagers >::view.
const auto & helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManager() const
Returns a const reference to the EntityManager that owns handles of type `THandle`.
THandle The handle type identifying the target domain. Const reference to the matching EntityManager.
auto helios::core::ecs::TypedHandleWorld< TEntityManagers >::addEntity()
Creates a new entity in the domain identified by `THandle`.
Delegates to the matching `EntityManager::create()` and wraps the result in an `Entity` facade. THandle The handle type identifying the target domain. An `Entity` wrapping the newly created handle.
References helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::core::ecs::TypedHandleWorld< TEntityManagers >::findEntity(THandle handle)
Looks up an existing entity by its handle.
Validates the handle via the owning `EntityManager`. If valid, returns an `Entity` facade; otherwise returns `std::nullopt`. THandle The handle type (and thus the domain) to search. handle The entity handle to resolve. `std::optional<Entity>` — engaged if the handle is valid.
References helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::core::ecs::TypedHandleWorld< TEntityManagers >::view()
Creates a `View` for iterating entities with specific components.
The view operates on the `EntityManager` identified by `THandle`. The first component type in `TComponents` serves as the lead set for iteration. THandle The handle type selecting the domain. TComponents The component types to include in the view. A `View` over the matching EntityManager. View
References helios::core::ecs::TypedHandleWorld< TEntityManagers >::entityManager.