helios::rendering::LegacyRenderPass
helios::rendering::RenderQueue helios::rendering::LegacyRenderPass::renderQueue_
The `RenderQueue` for this pass, containing all render commands.
helios::rendering::shader::UniformValueMap helios::rendering::LegacyRenderPass::frameUniformValues_
Uniform values specific to the current frame.
This map contains uniforms that change once per frame, such as the view and the projection matrices.
const helios::rendering::Viewport* helios::rendering::LegacyRenderPass::viewport_
Non-owning pointer to the `Viewport` processed by this pass.
The caller must ensure the viewport remains valid for the lifetime of this pass.
const helios::util::log::Logger& helios::rendering::LegacyRenderPass::logger_
Shared logger instance for all LegacyRenderPass objects.
helios::rendering::LegacyRenderPass::~LegacyRenderPass()=default
helios::rendering::LegacyRenderPass::LegacyRenderPass(const LegacyRenderPass &)=delete
Prevent copying. A LegacyRenderPass is not intended to be copied.
References LegacyRenderPass.
Referenced by LegacyRenderPass, LegacyRenderPass, LegacyRenderPass, operator=, operator=.
LegacyRenderPass & helios::rendering::LegacyRenderPass::operator=(const LegacyRenderPass &)=delete
Prevent copy assignment. A LegacyRenderPass is not intended to be copied.
References LegacyRenderPass.
helios::rendering::LegacyRenderPass::LegacyRenderPass(LegacyRenderPass &&) noexcept=default
Allow move.
References LegacyRenderPass.
LegacyRenderPass & helios::rendering::LegacyRenderPass::operator=(LegacyRenderPass &&) noexcept=default
Allow move assignment.
References LegacyRenderPass.
helios::rendering::LegacyRenderPass::LegacyRenderPass(const helios::rendering::Viewport *viewport, helios::rendering::RenderQueue renderQueue, const helios::rendering::shader::UniformValueMap &frameUniformValues) noexcept
Creates a new `LegacyRenderPass` with the specified viewport, render queue, and frame uniforms.
The render queue is moved into this pass. The viewport pointer must remain valid for the lifetime of this pass. viewport Non-owning pointer to the viewport this LegacyRenderPass is processing. renderQueue The `RenderQueue` to be processed with this pass (moved). frameUniformValues Frame-specific uniform values (e.g., view/projection matrices).
References frameUniformValues, LegacyRenderPass, renderQueue, viewport.
const RenderQueue & helios::rendering::LegacyRenderPass::renderQueue() const noexcept
Returns a const ref to the `RenderQueue` this `LegacyRenderPass` holds.
A const ref to this `LegacyRenderPass`' `RenderQueue`.
Referenced by LegacyRenderPass.
const Viewport & helios::rendering::LegacyRenderPass::viewport() const noexcept
Returns a const ref to the `Viewport` this `LegacyRenderPass` holds.
A const ref to this `LegacyRenderPass`' `Viewport`.
Referenced by LegacyRenderPass.
void helios::rendering::LegacyRenderPass::setFrameUniformValues(const helios::rendering::shader::UniformValueMap &frameUniformValues) noexcept
Sets the frame-specific uniform values for this pass.
frameUniformValues The `UniformValueMap` containing frame-specific uniform values.
References frameUniformValues.
const helios::rendering::shader::UniformValueMap & helios::rendering::LegacyRenderPass::frameUniformValues() const noexcept
Returns a const reference to this `LegacyRenderPass`' `UniformValueMap`.
The map might be empty. A const reference to this `LegacyRenderPass`' `UniformValueMap` for the current frame.
Referenced by LegacyRenderPass, setFrameUniformValues.