helios::core::spatial::Transform
bool helios::core::spatial::Transform::needsUpdate_
Flag indicating whether this Transform needs to recompute its transformation matrix.
helios::math::mat4f helios::core::spatial::Transform::rotation_
The rotation component of the transformation, stored as a 4x4 matrix.
helios::math::vec3f helios::core::spatial::Transform::scale_
The scaling component of the transformation, stored as a 3D vector.
helios::math::vec3f helios::core::spatial::Transform::translation_
The translation component of the transformation, stored as a 3D vector.
helios::math::mat4f helios::core::spatial::Transform::cached_
The cached 4x4 matrix, computed from scale, rotation and translation (in this order: T * (R * S)).
helios::math::mat4f helios::core::spatial::Transform::updateCache() const
Internal helper function to compute the full 4x4 affine transformation matrix.
The newly computed transformation matrix.
helios::core::spatial::Transform::~Transform()=default
helios::core::spatial::Transform::Transform()=default
Constructs a new Transform object with the default identity transformation, i.e. scale (1, 1, 1), rotation 4x4_id, translate (0, 0, 0).
helios::core::spatial::Transform::Transform(const helios::math::mat4f &rotation, helios::math::vec3f scale, helios::math::vec3f translation) noexcept
Constructs a new Transformation matrix from the specified rotation, scale and translation.
rotation The initial rotation matrix. scale The initial scaling vector. translation The initial translation vector.
References rotation, translation.
void helios::core::spatial::Transform::setRotation(const math::mat4f &rotation) noexcept
Sets the rotation component of this Transform. Marks this Transform object as dirty.
rotation A const ref to the new rotation matrix.
References rotation.
void helios::core::spatial::Transform::setTranslation(const math::vec3f &translation) noexcept
Sets the translation component of this Transform. Marks this Transform object as dirty.
translation A const ref to the new translation vector.
References translation.
void helios::core::spatial::Transform::setScale(const math::vec3f &scale) noexcept
Sets the scale component of this Transform. Marks this Transform object as dirty.
scale A const ref to the new scale vector.
helios::math::mat4f helios::core::spatial::Transform::rotation() const noexcept
Returns the current rotation component of this Transform object.
The current 4x4 rotation matrix.
Referenced by setRotation, Transform.
helios::math::vec3f helios::core::spatial::Transform::translation() const noexcept
Returns the current translation component of this Transform object.
The current 3D translation vector.
Referenced by setTranslation, Transform.
helios::math::vec3f helios::core::spatial::Transform::scaling() const noexcept
Returns the current scale component of this Transform object.
The current 3D scale vector.
helios::math::mat4f helios::core::spatial::Transform::transform() const noexcept
Returns the 4x4 transformation matrix combined from scale, rotation, and translation.
The current 4x4 affine transformation matrix.
Referenced by helios::scene::CameraSceneNode::lookAtLocal.
bool helios::core::spatial::Transform::needsUpdate() const noexcept
Checks whether this Transform needs to be updated, e.g. because the various components changed.
true if this Transform is considered to be dirty, otherwise false.