helios::ext::opengl::rendering::OpenGLDevice
std::unique_ptr<helios::ext::opengl::rendering::OpenGLGlyphTextRenderer> helios::ext::opengl::rendering::OpenGLDevice::textRenderer_
Text renderer for FreeType-based glyph rendering.
std::unique_ptr<helios::ext::opengl::rendering::OpenGLMeshRenderer> helios::ext::opengl::rendering::OpenGLDevice::meshRenderer_
Mesh renderer for geometry rendering.
std::unique_ptr<helios::rendering::text::FontResourceProvider> helios::ext::opengl::rendering::OpenGLDevice::fontResourceProvider_
Font resource provider for loading fonts and retrieving glyph data.
helios::ext::opengl::rendering::OpenGLDevice::~OpenGLDevice() override=default
helios::ext::opengl::rendering::OpenGLDevice::OpenGLDevice(std::unique_ptr< helios::ext::opengl::rendering::OpenGLMeshRenderer > meshRenderer, std::unique_ptr< helios::ext::opengl::rendering::OpenGLGlyphTextRenderer > textRenderer, std::unique_ptr< helios::rendering::text::FontResourceProvider > fontResourceProvider)
Constructs an OpenGLDevice with the given renderers and font provider.
meshRenderer The mesh renderer for geometry rendering. textRenderer The text renderer for glyph-based text rendering. fontResourceProvider The font resource provider for loading fonts.
References fontResourceProvider, textRenderer.
void helios::ext::opengl::rendering::OpenGLDevice::init() override
Initializes the OpenGL device to access modern OpenGL.
This method must be called **after** the helios application's `setCurrent()` was called for creating a current context. This OpenGL device will then load from this context. This method uses the `gladLoadGL` method in conjunction with `glfwGetProcAddress`, which returns the address of the specific OpenGL core. https://www.glfw.org/docs/latest/group__context.html#ga35f1837e6f666781842483937612f163 TodoProvide abstraction for glfwGetProcAddress.
References helios::rendering::RenderingDevice::initialized_, helios::rendering::RenderingDevice::logger_.
void helios::ext::opengl::rendering::OpenGLDevice::beginRenderPass(helios::rendering::RenderPass &renderPass) const noexcept override
Begins a new render pass.
This implementation makes sure that the rendering surface is cleared with the current clear color, which can be configured via `clearColor()`. renderPass The render pass to begin. clear() clearColor()
References helios::rendering::Color, helios::rendering::Depth, helios::rendering::RenderTarget::height, helios::rendering::Stencil, helios::rendering::RenderTarget::width.
void helios::ext::opengl::rendering::OpenGLDevice::doRender(helios::rendering::RenderPass &renderPass) const noexcept override
Processes render commands and draws geometry and text.
Iterates through all render commands in the render queue, binds the appropriate shaders and VAOs, applies uniform values, and issues draw calls. After processing geometry, delegates any text render commands to `renderTextCommands()`. renderPass The render pass containing the render queue to be processed. renderTextCommands()
References renderMeshCommands, renderTextCommands.
void helios::ext::opengl::rendering::OpenGLDevice::renderMeshCommands(const helios::rendering::RenderPass &renderPass) const noexcept
Renders all mesh commands in the render pass.
Iterates through the mesh render commands in the render queue and delegates each command to the `OpenGLMeshRenderer` for rendering. renderPass The render pass containing mesh render commands.
Referenced by doRender.
void helios::ext::opengl::rendering::OpenGLDevice::renderTextCommands(const helios::rendering::RenderPass &renderPass) const noexcept
Renders all text commands in the render pass.
Iterates through the text render commands in the render queue and delegates each command to the `OpenGLGlyphTextRenderer` for rendering. renderPass The render pass containing text render commands.
Referenced by doRender.
void helios::ext::opengl::rendering::OpenGLDevice::endRenderPass(helios::rendering::RenderPass &renderPass) const noexcept override
Ends the specified render pass.
The current implementation does nothing. renderPass The render pass to end.
helios::rendering::text::TextRenderer & helios::ext::opengl::rendering::OpenGLDevice::textRenderer() const noexcept
Returns a reference to the text renderer.
Use this to register font families before rendering text. Reference to the `TextRenderer` interface. OpenGLGlyphTextRenderer::addFontFamily()
Referenced by OpenGLDevice.
helios::rendering::text::FontResourceProvider & helios::ext::opengl::rendering::OpenGLDevice::fontResourceProvider() const noexcept override
Returns a reference to the font resource provider.
Use this to load fonts before creating `TextRenderPrototype` instances. Reference to the `FontResourceProvider` implementation.
Referenced by OpenGLDevice.