helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig
helios::engine::core::data::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::profileId_
Profile this rule is bound to.
helios::engine::core::data::SpawnRuleId helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::ruleId_
Unique identifier for the rule.
std::unique_ptr<const helios::engine::runtime::spawn::policy::SpawnCondition> helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::condition_
Condition determining when to spawn.
std::unique_ptr<const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider> helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::amountProvider_
Provider determining how many to spawn.
helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::SchedulerConfig(helios::engine::core::data::SpawnProfileId profileId, helios::engine::core::data::SpawnRuleId ruleId)
Constructs a SchedulerConfig.
profileId The spawn profile this rule targets. ruleId Unique identifier for this rule.
References profileId.
Referenced by amount, condition, fixedAmount, timerCondition, timerWithAvailabilityCondition.
SchedulerConfig & helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::timerCondition(const float intervalSeconds)
Sets a timer-based spawn condition.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References SchedulerConfig.
SchedulerConfig & helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::timerWithAvailabilityCondition(const float intervalSeconds)
Sets a combined condition: timer + pool availability.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References SchedulerConfig.
SchedulerConfig & helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::condition(std::unique_ptr< const helios::engine::runtime::spawn::policy::SpawnCondition > customCondition)
Sets a custom spawn condition.
customCondition Ownership is transferred. Reference to this config for chaining.
References SchedulerConfig.
SchedulerConfig & helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::fixedAmount(const size_t count)
Sets a fixed spawn amount.
count Number of entities to spawn per trigger. Reference to this config for chaining.
References SchedulerConfig.
SchedulerConfig & helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::amount(std::unique_ptr< const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider > customProvider)
Sets a custom amount provider.
customProvider Ownership is transferred. Reference to this config for chaining.
References SchedulerConfig.
helios::engine::core::data::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::profileId() const noexcept
Returns the profile ID for this rule.
The spawn profile ID.
Referenced by SchedulerConfig.
std::unique_ptr< helios::engine::runtime::spawn::policy::SpawnRule > helios::engine::builder::spawnSystem::builders::configs::SchedulerConfig::build()
Builds and returns the configured SpawnRule.
The assembled SpawnRule. Ownership is transferred to the caller.