helios::engine::modules::rendering::renderable::components::RenderableComponent
std::shared_ptr<helios::rendering::Renderable> helios::engine::modules::rendering::renderable::components::RenderableComponent::renderable_
Shared pointer to the renderable resource.
helios::math::aabbf helios::engine::modules::rendering::renderable::components::RenderableComponent::aabb_
The initial AABB of the model associated with the renderable.
bool helios::engine::modules::rendering::renderable::components::RenderableComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::rendering::renderable::components::RenderableComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::rendering::renderable::components::RenderableComponent::enable() noexcept
Enables this component.
void helios::engine::modules::rendering::renderable::components::RenderableComponent::disable() noexcept
Disables this component.
helios::engine::modules::rendering::renderable::components::RenderableComponent::RenderableComponent(std::shared_ptr< helios::rendering::Renderable > renderable)
Constructs a RenderableComponent.
renderable Shared pointer to the Renderable. Must not be nullptr.
References renderable.
Referenced by operator=, operator=, RenderableComponent, RenderableComponent.
helios::engine::modules::rendering::renderable::components::RenderableComponent::RenderableComponent(const RenderableComponent &other)
Copy constructor.
Copies the shared pointer to the Renderable. Both components will reference the same Renderable resource (shared ownership). other The component to copy from.
References RenderableComponent.
RenderableComponent & helios::engine::modules::rendering::renderable::components::RenderableComponent::operator=(const RenderableComponent &)=default
Copy assignment operator.
References RenderableComponent.
helios::engine::modules::rendering::renderable::components::RenderableComponent::RenderableComponent(RenderableComponent &&) noexcept=default
Move constructor.
References RenderableComponent.
RenderableComponent & helios::engine::modules::rendering::renderable::components::RenderableComponent::operator=(RenderableComponent &&) noexcept=default
Move assignment operator.
References RenderableComponent.
std::shared_ptr< helios::rendering::Renderable > helios::engine::modules::rendering::renderable::components::RenderableComponent::shareRenderable() const noexcept
Retrieves a shared pointer to the stored Renderable.
Shared pointer to the Renderable.
References shareRenderable.
Referenced by helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent, shareRenderable.
const helios::rendering::Renderable & helios::engine::modules::rendering::renderable::components::RenderableComponent::renderable() const noexcept
Retrieves a const ref to the stored Renderable.
Const ref to the Renderable (never null after construction).
Referenced by RenderableComponent.