helios::engine::modules::spatial::transform::components::TranslationStateComponent
helios::math::vec3f helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation_
The current translation vector.
bool helios::engine::modules::spatial::transform::components::TranslationStateComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::spatial::transform::components::TranslationStateComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::enable() noexcept
Enables this component.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::disable() noexcept
Disables this component.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent()=default
Default constructor.
Referenced by operator=, operator=, TranslationStateComponent, TranslationStateComponent, TranslationStateComponent.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent(const TranslationStateComponent &other)
Copy constructor.
other The component to copy from.
References TranslationStateComponent.
TranslationStateComponent & helios::engine::modules::spatial::transform::components::TranslationStateComponent::operator=(const TranslationStateComponent &)=default
Copy assignment operator.
References TranslationStateComponent.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent(TranslationStateComponent &&) noexcept=default
Move constructor.
References TranslationStateComponent.
TranslationStateComponent & helios::engine::modules::spatial::transform::components::TranslationStateComponent::operator=(TranslationStateComponent &&) noexcept=default
Move assignment operator.
References TranslationStateComponent.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent(const helios::math::vec3f translation)
Creates a new TranslationStateComponent with the specified translation vector.
translation The translation vector this component should be initialized with.
References translation, TranslationStateComponent.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::onAcquire() noexcept
Resets the translation vector to 0-vector when acquired.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::onRelease() noexcept
Resets the translation vector to 0-vector when released.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::setTranslation(helios::math::vec3f translation)
Sets the absolute translation.
translation The new position vector.
References translation.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::translateBy(helios::math::vec3f translation)
Translates the current position by a delta vector.
translation The vector to add to the current position.
References translation.
helios::math::vec3f helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation() const noexcept
Returns the current translation vector.
The current position.
Referenced by setTranslation, translateBy, TranslationStateComponent, helios::engine::modules::ai::systems::ChaseSystem::update.