helios::engine::mechanics::timing::GameTimer
TimerRevision helios::engine::mechanics::timing::GameTimer::timerRevision_
Monotonically increasing revision counter, incremented on each update.
GameTimerId helios::engine::mechanics::timing::GameTimer::gameTimerId_
Unique identifier for this timer.
float helios::engine::mechanics::timing::GameTimer::elapsed_
Accumulated elapsed time in seconds.
TimerState helios::engine::mechanics::timing::GameTimer::timerState_
Current state of the timer.
float helios::engine::mechanics::timing::GameTimer::duration_
Optional duration limit in seconds.
helios::engine::mechanics::timing::GameTimer::GameTimer(const helios::engine::mechanics::timing::types::GameTimerId gameTimerId)
Constructs a GameTimer with the given identifier.
gameTimerId The unique identifier for this timer.
References gameTimerId.
helios::engine::mechanics::timing::types::GameTimerId helios::engine::mechanics::timing::GameTimer::gameTimerId() const noexcept
Returns the timer identifier.
The GameTimerId assigned to this timer.
Referenced by GameTimer.
void helios::engine::mechanics::timing::GameTimer::reset(const TimerState state=TimerState::Undefined) noexcept
Resets the elapsed time to zero and sets timer state to Undefined.
state The new TimerState the timer should be resetted to.
References setState, state, helios::engine::mechanics::timing::types::Undefined.
Referenced by cancel, restart.
void helios::engine::mechanics::timing::GameTimer::restart() noexcept
Resets timer by resetting its internal counter and setting its state to TimerState::Running.
reset
References reset, helios::engine::mechanics::timing::types::Running.
void helios::engine::mechanics::timing::GameTimer::cancel() noexcept
Cancels this timer by setting its state to TimerState::Cancelled.
reset
References helios::engine::mechanics::timing::types::Cancelled, reset.
void helios::engine::mechanics::timing::GameTimer::setDuration(float duration)
Sets the duration limit.
duration Duration in seconds.
References duration.
float helios::engine::mechanics::timing::GameTimer::duration() const noexcept
Returns the duration limit.
The duration in seconds.
Referenced by setDuration.
float helios::engine::mechanics::timing::GameTimer::elapsed() const noexcept
Returns the accumulated elapsed time.
Elapsed time in seconds.
TimerState helios::engine::mechanics::timing::GameTimer::state() const noexcept
Returns the current timer state.
The current TimerState.
Referenced by reset, setState.
void helios::engine::mechanics::timing::GameTimer::setState(const TimerState state) noexcept
Sets the timer state.
state The new TimerState.
References state.
Referenced by reset.
bool helios::engine::mechanics::timing::GameTimer::shouldUpdate() const noexcept
Returns whether this timer should accumulate time.
True if the timer is in the Running state.
References helios::engine::mechanics::timing::types::Running.
Referenced by update.
bool helios::engine::mechanics::timing::GameTimer::isFinished() const noexcept
Returns whether this timer's internal state represents the Finished-state.
True if the timer is finished.
References helios::engine::mechanics::timing::types::Finished.
TimerRevision helios::engine::mechanics::timing::GameTimer::timerRevision() const noexcept
Returns the current revision counter.
The TimerRevision value.
void helios::engine::mechanics::timing::GameTimer::update(const float ft)
Advances the timer by the given frame time.
Only accumulates time when the timer is in the Running state. Increments the revision counter on each successful update. ft Frame time in seconds.
References shouldUpdate.