helios::scene::Camera
helios::math::mat4f helios::scene::Camera::perspectiveMatrix_
The projection matrix of this camera.
Referenced by Camera, projectionMatrix, update.
helios::math::mat4f helios::scene::Camera::orthographicMatrix_
The orthographic projection matrix of this camera.
Used when the camera is in orthographic mode (`usePerspective_ == false`).
Referenced by Camera, projectionMatrix, update.
helios::math::mat4f helios::scene::Camera::viewMatrix_
The view matrix of this camera.
Referenced by Camera, setViewMatrix, viewMatrix.
float helios::scene::Camera::aspectRatio_
The aspect ratio of the camera (width/height).
Defaults to 1.0.
Referenced by aspectRatio, setAspectRatio, setOrtho, setPerspective, update.
float helios::scene::Camera::zNear_
The near clipping plane distance.
Defaults to 0.1.
Referenced by setOrtho, setPerspective, setZNear, update, zNear.
float helios::scene::Camera::zFar_
The far clipping plane distance.
Defaults to 1000.0.
Referenced by setOrtho, setPerspective, setZFar, update, zFar.
float helios::scene::Camera::fovY_
The vertical field of view in radians.
Defaults to 90 degrees (converted to radians).
Referenced by fovY, setFovY, setPerspective, update.
bool helios::scene::Camera::needsUpdate_
Flag indicating whether the matrices need to be updated.
Referenced by onResize, setAspectRatio, setFovY, setOrtho, setPerspective, setZFar, setZNear, update.
float helios::scene::Camera::left_
Left boundary of the orthographic frustum.
Referenced by onResize, setOrtho, update.
float helios::scene::Camera::right_
Right boundary of the orthographic frustum.
Referenced by onResize, setOrtho, update.
float helios::scene::Camera::bottom_
Bottom boundary of the orthographic frustum.
Referenced by onResize, setOrtho, update.
float helios::scene::Camera::top_
Top boundary of the orthographic frustum.
Referenced by onResize, setOrtho, update.
bool helios::scene::Camera::usePerspective_
Flag indicating the projection mode.
When `true`, perspective projection is used. When `false`, orthographic projection is used. Defaults to `true`.
Referenced by onResize, projectionMatrix, setOrtho, setPerspective, update.
void helios::scene::Camera::update() const
Updates the view and projection matrices if needed.
This function recalculates the view and projection matrices based on the current camera parameters.
References aspectRatio_, bottom_, fovY_, left_, needsUpdate_, helios::math::ortho, orthographicMatrix_, helios::math::perspective, perspectiveMatrix_, right_, top_, usePerspective_, zFar_, zNear_.
Referenced by projectionMatrix.
helios::scene::Camera::Camera() noexcept
Constructs a camera with identity projection and view matrices.
References orthographicMatrix_, perspectiveMatrix_, viewMatrix_.
Referenced by setAspectRatio, setFovY, setOrtho, setPerspective, setViewMatrix, setZFar, setZNear.
const helios::math::mat4f & helios::scene::Camera::projectionMatrix() const noexcept
Gets the current projection matrix.
Typically set to a perspective or orthographic projection. A const reference to this camera's projection matrix.
References orthographicMatrix_, perspectiveMatrix_, update, usePerspective_.
const helios::math::mat4f & helios::scene::Camera::viewMatrix() const noexcept
Gets the current view matrix.
The view matrix represents the inverse of the camera's world transform. A const reference to this camera's view matrix.
References viewMatrix_.
Referenced by setViewMatrix.
Camera & helios::scene::Camera::setViewMatrix(const helios::math::mat4f &viewMatrix) noexcept
Sets the view matrix for this camera.
This method is typically called by `CameraSceneNode::worldTransform()` to update the view matrix based on the camera node's position and orientation in the scene graph. viewMatrix The new view matrix to assign. A const reference to this camera instance. helios::scene::CameraSceneNode::worldTransform()
References Camera, viewMatrix, viewMatrix_.
Camera & helios::scene::Camera::setAspectRatio(float aspectRatio) noexcept
Sets the aspect ratio used by the camera.
aspectRatio The new aspect ratio (width/height). A reference to this camera instance.
References aspectRatio, aspectRatio_, Camera, needsUpdate_.
Referenced by onResize.
void helios::scene::Camera::onResize(const float width, const float height) noexcept
Handles viewport resize events.
Adjusts the camera projection parameters when the viewport dimensions change. For perspective projection: Updates the aspect ratio. For orthographic projection: Adjusts the right and top boundaries to maintain the correct projection volume. width The new viewport width in pixels. height The new viewport height in pixels.
References bottom_, left_, needsUpdate_, right_, setAspectRatio, top_, usePerspective_.
Camera & helios::scene::Camera::setPerspective(float fovY, float aspectRatio, float zNear, float zFar) noexcept
Sets the perspective projection parameters.
fovY The vertical field of view in radians. aspectRatio The aspect ratio (width/height). zNear The near clipping plane distance. zFar The far clipping plane distance. A reference to this camera instance.
References aspectRatio, aspectRatio_, Camera, fovY, fovY_, needsUpdate_, usePerspective_, zFar, zFar_, zNear, zNear_.
Camera & helios::scene::Camera::setOrtho(const float left, const float right, const float bottom, const float top, const float zNear=-1.0f, const float zFar=100.0f) noexcept
Sets the orthographic projection parameters.
Configures the camera for orthographic projection, which is useful for 2D rendering, UI overlays, or scenes where parallel lines should remain parallel (no perspective distortion). left The left boundary of the view volume. right The right boundary of the view volume. bottom The bottom boundary of the view volume. top The top boundary of the view volume. zNear The near clipping plane distance. Defaults to -1.0. zFar The far clipping plane distance. Defaults to 100.0. A reference to this camera instance. Calling this method switches the camera to orthographic projection mode.
References aspectRatio_, bottom_, Camera, left_, needsUpdate_, right_, top_, usePerspective_, zFar, zFar_, zNear, zNear_.
Camera & helios::scene::Camera::setZNear(float zNear) noexcept
Sets the near clipping plane distance.
zNear The new near clipping plane distance. A reference to this camera instance.
References Camera, needsUpdate_, zNear, zNear_.
Camera & helios::scene::Camera::setZFar(float zFar) noexcept
Sets the far clipping plane distance.
zFar The new far clipping plane distance. A reference to this camera instance.
References Camera, needsUpdate_, zFar, zFar_.
Camera & helios::scene::Camera::setFovY(float fovY) noexcept
Sets the vertical field of view.
fovY The new vertical field of view in radians. A reference to this camera instance.
References Camera, fovY, fovY_, needsUpdate_.
float helios::scene::Camera::fovY() const noexcept
Gets the current vertical field of view.
The vertical field of view in radians.
References fovY_.
Referenced by setFovY, setPerspective.
float helios::scene::Camera::aspectRatio() const noexcept
Gets the current aspect ratio.
The aspect ratio (width/height).
References aspectRatio_.
Referenced by setAspectRatio, setPerspective.
float helios::scene::Camera::zNear() const noexcept
Gets the current near clipping plane distance.
The near clipping plane distance.
References zNear_.
Referenced by setOrtho, setPerspective, setZNear.
float helios::scene::Camera::zFar() const noexcept
Gets the current far clipping plane distance.
The far clipping plane distance.
References zFar_.
Referenced by setOrtho, setPerspective, setZFar.