helios::engine::mechanics::scoring::components::ScoreObserverComponent
friend class helios::engine::mechanics::scoring::systems::ScoreObserverClearSystem
References helios::core::types::no_init.
helios::engine::mechanics::scoring::types::ScorePoolId helios::engine::mechanics::scoring::components::ScoreObserverComponent::scorePoolId_
ID of the score pool to observe.
bool helios::engine::mechanics::scoring::components::ScoreObserverComponent::hasUpdate_
Flag indicating whether the value changed this frame.
Cleared by ScoreObserverClearSystem at frame end.
helios::engine::mechanics::scoring::ScorePoolSnapshot helios::engine::mechanics::scoring::components::ScoreObserverComponent::snapshot_
the current snapshot saved by this observer component.
bool helios::engine::mechanics::scoring::components::ScoreObserverComponent::isEnabled_
Whether this component is enabled.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::clearUpdate()
Clears the update flag.
Called by ScoreObserverClearSystem.
bool helios::engine::mechanics::scoring::components::ScoreObserverComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::scoring::components::ScoreObserverComponent::ScoreObserverComponent()=default
Referenced by operator=, operator=, ScoreObserverComponent, ScoreObserverComponent.
helios::engine::mechanics::scoring::components::ScoreObserverComponent::ScoreObserverComponent(const ScoreObserverComponent &other)
Copy constructor.
other The component to copy from.
References ScoreObserverComponent.
ScoreObserverComponent & helios::engine::mechanics::scoring::components::ScoreObserverComponent::operator=(const ScoreObserverComponent &)=default
References ScoreObserverComponent.
helios::engine::mechanics::scoring::components::ScoreObserverComponent::ScoreObserverComponent(ScoreObserverComponent &&) noexcept=default
References ScoreObserverComponent.
ScoreObserverComponent & helios::engine::mechanics::scoring::components::ScoreObserverComponent::operator=(ScoreObserverComponent &&) noexcept=default
References ScoreObserverComponent.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::setScorePoolId(const helios::engine::mechanics::scoring::types::ScorePoolId scorePoolId) noexcept
Sets the score pool to observe.
scorePoolId The ID of the pool to observe.
References scorePoolId, setScorePoolId.
Referenced by setScorePoolId.
helios::engine::mechanics::scoring::types::ScorePoolId helios::engine::mechanics::scoring::components::ScoreObserverComponent::scorePoolId() const noexcept
Returns the observed score pool ID.
The ScorePoolId.
Referenced by setScorePoolId.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::setScorePoolSnapshot(const helios::engine::mechanics::scoring::ScorePoolSnapshot &snapshot) noexcept
Sets the cached snapshot value.
Sets hasUpdate to true if the value changes. snapshot The snapshot to use for the next update.
ScorePoolRevision helios::engine::mechanics::scoring::components::ScoreObserverComponent::scorePoolRevision() const noexcept
Returns the cached score pool revision.
The revision of the last observed snapshot.
double helios::engine::mechanics::scoring::components::ScoreObserverComponent::totalScore() const noexcept
Returns the cached total score.
The current score value.
bool helios::engine::mechanics::scoring::components::ScoreObserverComponent::hasUpdate() const noexcept
Checks if the value changed since last clear.
True if the value was updated this frame.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Clears the update flag and resets the cached snapshot.
void helios::engine::mechanics::scoring::components::ScoreObserverComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Clears the update flag and resets the cached snapshot.