helios::engine::runtime::world::Manager
std::unique_ptr<Concept> helios::engine::runtime::world::Manager::pimpl_
helios::engine::runtime::world::Manager::Manager()=default
Default constructor creating an empty Manager.
Referenced by Manager, Manager, operator=, operator=.
helios::engine::runtime::world::Manager::Manager(T manager)
Wraps a concrete manager in a type-erased Manager.
T The concrete manager type, must satisfy `IsManagerLike<T>`. manager The concrete manager instance to wrap (moved into internal storage).
helios::engine::runtime::world::Manager::Manager(const Manager &)=delete
References Manager.
Manager & helios::engine::runtime::world::Manager::operator=(const Manager &)=delete
References Manager.
Manager & helios::engine::runtime::world::Manager::operator=(Manager &&)=default
References Manager.
helios::engine::runtime::world::Manager::Manager(Manager &&) noexcept=default
References Manager.
void helios::engine::runtime::world::Manager::flush(UpdateContext &updateContext) noexcept
Delegates to the wrapped manager's `flush()` method.
Called by the GameLoop at each commit point after CommandBuffers have been flushed. Managers process their accumulated requests in batch. updateContext The current frame's update context. Manager must be initialized (pimpl_ != nullptr).
References flush.
Referenced by flush.
void helios::engine::runtime::world::Manager::init(GameWorld &gameWorld) noexcept
Delegates to the wrapped manager's `init()` method, if present.
If the concrete type satisfies `HasInit<T>`, its `init()` is called. Otherwise this is a no-op. Typically used by managers to register their TypedCommandHandlers with the GameWorld. gameWorld The GameWorld for one-time initialization. Manager must be initialized (pimpl_ != nullptr).
void helios::engine::runtime::world::Manager::reset() noexcept
Delegates to the wrapped manager's `reset()` method, if present.
If the concrete type satisfies `HasReset<T>`, its `reset()` is called. Otherwise this is a no-op. Used during level transitions or game restarts to clear accumulated state. Manager must be initialized (pimpl_ != nullptr).
void * helios::engine::runtime::world::Manager::underlying() noexcept
Returns a type-erased pointer to the wrapped manager instance.
Pointer to the underlying concrete manager. Manager must be initialized (pimpl_ != nullptr).
const void * helios::engine::runtime::world::Manager::underlying() const noexcept
Returns a type-erased pointer to the wrapped manager instance.
Pointer to the underlying concrete manager. Manager must be initialized (pimpl_ != nullptr).