helios::engine::builder::gameObject::builders::configs::UiTransformConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::UiTransformConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig(helios::engine::ecs::GameObject gameObject)
Constructs a UiTransformConfig and adds ComposeTransformComponent.
gameObject Target GameObject to configure.
Referenced by anchor, offsets, pivot, viewport.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor(const helios::engine::modules::ui::layout::Anchor anchor)
Sets the anchor point for UI positioning.
anchor The anchor position (e.g., TopLeft, Center). Reference to this config for chaining.
References anchor, UiTransformConfig.
Referenced by anchor, pivot.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::viewport(const helios::engine::core::data::ViewportId viewportId)
Sets the viewport for this UI element.
viewportId The ID of the viewport to attach to. Reference to this config for chaining.
References UiTransformConfig.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::pivot(const helios::engine::modules::ui::layout::Anchor anchor)
Sets the pivot point for transformations.
anchor The pivot position. Reference to this config for chaining.
References anchor, UiTransformConfig.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::offsets(const helios::math::vec4f offsets)
Sets the offsets for UI positioning.
offsets The offsets as vec4f (top, right, bottom, left). Reference to this config for chaining.
References offsets, UiTransformConfig.
Referenced by offsets.