helios::engine::mechanics::combat::components::ShootComponent
float helios::engine::mechanics::combat::components::ShootComponent::intensity_
Current fire intensity (0.0 to 1.0).
Set by shoot() and cleared when intensity is zero. Controls whether projectiles are spawned during update().
Referenced by intensity, shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta_
Cooldown interval between shots, in seconds.
Derived from fireRate (1.0 / fireRate). Determines the minimum time that must pass between consecutive projectile spawns.
Referenced by cooldownDelta, setFireRate.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer_
Accumulated time since last shot, in seconds.
Accumulates delta time multiplied by intensity. When this value exceeds cooldownDelta, projectiles are spawned and the timer is reduced.
Referenced by cooldownTimer, setCooldownTimer, updateCooldownTimerBy.
float helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed_
The projectile speed, in meters per second.
Referenced by projectileSpeed, setProjectileSpeed.
helios::math::vec3f helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity_
Velocity of the source object in three-dimensional space.
Used to adjust the trajectory of projectiles emitted by the source's movement.
Referenced by shoot, sourceVelocity.
float helios::engine::mechanics::combat::components::ShootComponent::fireRate_
Fire rate per second, i.e. projectiles than can be shot per second.
Referenced by fireRate, setFireRate.
bool helios::engine::mechanics::combat::components::ShootComponent::isEnabled_
Whether this component is enabled.
Referenced by disable, enable, isEnabled.
bool helios::engine::mechanics::combat::components::ShootComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References isEnabled_.
void helios::engine::mechanics::combat::components::ShootComponent::enable() noexcept
Enables this component.
References isEnabled_.
void helios::engine::mechanics::combat::components::ShootComponent::disable() noexcept
Disables this component.
References isEnabled_.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent()=default
Constructs a new ShootComponent with default settings.
Referenced by operator=, operator=, ShootComponent, ShootComponent.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent(const ShootComponent &)=default
References ShootComponent.
ShootComponent & helios::engine::mechanics::combat::components::ShootComponent::operator=(const ShootComponent &)=default
References ShootComponent.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent(ShootComponent &&) noexcept=default
References ShootComponent.
ShootComponent & helios::engine::mechanics::combat::components::ShootComponent::operator=(ShootComponent &&) noexcept=default
References ShootComponent.
void helios::engine::mechanics::combat::components::ShootComponent::shoot(const float intensity, const helios::math::vec3f sourceVelocity)
Sets the shooting intensity.
Call with a non-zero value to start shooting, or zero to stop. The intensity affects whether projectiles are spawned during update(). intensity Fire intensity (0.0 to 1.0). Zero stops firing. sourceVelocity The velocity of the object emitting the projectile.
References helios::math::EPSILON_LENGTH, intensity, intensity_, shoot, sourceVelocity, sourceVelocity_.
Referenced by shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta() const noexcept
Returns the cooldown interval between shots.
Cooldown interval in seconds (derived from 1.0 / fireRate).
References cooldownDelta_.
float helios::engine::mechanics::combat::components::ShootComponent::intensity() const noexcept
Returns the current fire intensity.
The intensity value (0.0 to 1.0).
References intensity_.
Referenced by shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer() const noexcept
Returns the accumulated time since last shot.
Accumulated cooldown timer in seconds.
References cooldownTimer_.
void helios::engine::mechanics::combat::components::ShootComponent::setCooldownTimer(float cooldown) noexcept
Sets the accumulated cooldown timer.
cooldown New timer value in seconds.
References cooldownTimer_.
void helios::engine::mechanics::combat::components::ShootComponent::updateCooldownTimerBy(float delta) noexcept
Adds delta time to the cooldown timer.
delta Time to add in seconds.
References cooldownTimer_.
float helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed() const noexcept
Returns the projectile speed.
Projectile speed in meters per second.
References projectileSpeed_.
void helios::engine::mechanics::combat::components::ShootComponent::setProjectileSpeed(float speed) noexcept
Sets the projectile speed.
speed New projectile speed in meters per second.
References projectileSpeed_.
helios::math::vec3f helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity() const noexcept
Returns the source object's velocity.
Velocity vector used for projectile trajectory adjustment.
References sourceVelocity_.
Referenced by shoot.
float helios::engine::mechanics::combat::components::ShootComponent::fireRate() const noexcept
Returns the fire rate in projectiles per second.
Fire rate (projectiles/second).
References fireRate_.
Referenced by setFireRate.
void helios::engine::mechanics::combat::components::ShootComponent::setFireRate(const float fireRate) noexcept
Sets the fire rate.
Updates the cooldown delta based on the new fire rate. fireRate The number of projectiles per second. Must be greater than zero.
References cooldownDelta_, helios::math::EPSILON_LENGTH, fireRate, fireRate_.