helios::engine::builder::gameObject::builders::configs::ObserverConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::ObserverConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig(helios::engine::ecs::GameObject gameObject)
Constructs an ObserverConfig.
gameObject Target GameObject to configure.
Referenced by lives, maxScore, runningScore, scorePool, time.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::scorePool(const helios::engine::core::data::ScorePoolId scorePoolId)
Adds a ScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining. Deprecateduse runningScore()
References ObserverConfig, runningScore.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::runningScore(const helios::engine::core::data::ScorePoolId scorePoolId)
Adds a ScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining.
References ObserverConfig.
Referenced by scorePool.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::lives(const helios::engine::ecs::GameObject gameObject)
Adds a LivesBindingComponent observing the given entity's lives.
gameObject The entity whose LivesComponent is observed. Reference to this config for chaining.
References ObserverConfig.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::maxScore(const helios::engine::core::data::ScorePoolId scorePoolId)
Adds a MaxScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining.
References ObserverConfig.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::time(const helios::engine::core::data::GameTimerId gameTimerId)
Adds a GameTimerBindingComponent bound to the specified timer.
gameTimerId The ID of the game timer to observe. Reference to this config for chaining.
References ObserverConfig.