helios::engine::mechanics::match::types::MatchStateTransitionContext
MatchState helios::engine::mechanics::match::types::MatchStateTransitionContext::from_
MatchStateTransitionId helios::engine::mechanics::match::types::MatchStateTransitionContext::transitionId_
MatchState helios::engine::mechanics::match::types::MatchStateTransitionContext::to_
helios::engine::mechanics::match::types::MatchStateTransitionContext::MatchStateTransitionContext(const MatchState from, const MatchState to, const MatchStateTransitionId transitionId)
Constructs a transition context.
from The state being exited. to The state being entered. transitionId The identifier of the transition.
References from, to, transitionId.
MatchState helios::engine::mechanics::match::types::MatchStateTransitionContext::to() const noexcept
Returns the target state.
Referenced by MatchStateTransitionContext.
MatchState helios::engine::mechanics::match::types::MatchStateTransitionContext::from() const noexcept
Returns the source state.
Referenced by MatchStateTransitionContext.
MatchStateTransitionId helios::engine::mechanics::match::types::MatchStateTransitionContext::transitionId() const noexcept
Returns the transition identifier.
Referenced by MatchStateTransitionContext.