helios::engine::builder::gameObject::builders::configs::TextRenderableConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::gameObject_
The GameObject being configured.
helios::rendering::text::FontResourceProvider* helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontResourceProvider_
Pointer to the font resource provider.
std::shared_ptr<helios::ext::opengl::rendering::shader::OpenGLShader> helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader_
The shader used for text rendering.
helios::math::vec4f helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color_
The text color.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text_
The text content to display.
float helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale_
The font scale factor.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::numberFormat_
Format string for number display (std::vformat syntax).
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::isUiText_
Whether this text should be configured as UI text.
helios::engine::modules::ui::widgets::types::FontId helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId_
The font identifier.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::timestampFormat_
Format string for timestamp display (std::vformat syntax).
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::usesTimeFormatter_
Whether a TimeFormatterComponent should be attached.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::usesNumberFormatter_
Whether a NumberFormatterComponent should be attached.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::displayRemaining_
Whether the timer should display remaining instead of elapsed time.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::elapsedLabel_
Label displayed instead of "00:00" when remaining time reaches zero.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::showElapsedLabel_
True if an elapsed label has been configured.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::hideWhenZero_
True if the output should be empty when remaining time reaches zero.
helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig(helios::engine::ecs::GameObject gameObject)
Constructs a TextRenderableConfig for the given GameObject.
gameObject The GameObject to configure.
Referenced by asUiText, build, color, displayRemaining, fontId, fontResourceProvider, fontScale, formattedAsNumber, formattedAsTimestamp, hideWhenZero, shader, text, useElapsedLabel.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader(const std::shared_ptr< helios::ext::opengl::rendering::shader::OpenGLShader > &shader)
Sets the shader for text rendering.
shader The shader to use. Reference to this config for method chaining.
References shader, TextRenderableConfig.
Referenced by shader.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color(const helios::math::vec4f color)
Sets the text color.
color The RGBA color. Reference to this config for method chaining.
References color, TextRenderableConfig.
Referenced by color.
SceneNodeConfig helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo(helios::engine::ecs::GameObject parent)
Builds the text renderable and attaches to a parent GameObject.
parent The parent GameObject to attach to. A SceneNodeConfig for further configuration.
References build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
SceneNodeConfig helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo(helios::scene::SceneNode *parent)
Builds the text renderable and attaches to a parent SceneNode.
parent The parent SceneNode to attach to. A SceneNodeConfig for further configuration.
References build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontResourceProvider(helios::rendering::text::FontResourceProvider &provider)
Sets the font resource provider.
provider The font resource provider. Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::asUiText()
Configures this text as a UI text component.
Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsNumber(std::string numberFormat="{:.0f}")
Attaches a NumberFormatterComponent with the given format.
Implicitly enables UI text mode. numberFormat A std::vformat-compatible string. Defaults to "{:.0f}". Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsTimestamp(std::string timestampFormat)
Attaches a TimeFormatterComponent with the given format.
Implicitly enables UI text mode. timestampFormat A std::vformat-compatible string expecting minutes and seconds. Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::useElapsedLabel(std::string label)
Sets the label shown instead of "00:00" when remaining time reaches zero.
Only effective in Remaining mode. Once the remaining time drops to one second or below, format() returns this label instead of the numeric output. label The label string to display (e.g. "TIME UP"). Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::hideWhenZero()
Hides the time output when remaining time reaches zero.
Only effective in Remaining mode. When enabled, format() returns an empty string once the remaining time is exhausted. Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::displayRemaining()
Switches the time formatter to display remaining time.
Only effective when formattedAsTimestamp() has been called. Reference to this config for method chaining.
References TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text(std::string text)
Sets the text content.
text The text to display. Reference to this config for method chaining.
References text, TextRenderableConfig.
Referenced by text.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId(helios::engine::modules::ui::widgets::types::FontId fontId)
Sets the font identifier.
fontId The font ID to use. Reference to this config for method chaining.
References fontId, TextRenderableConfig.
Referenced by fontId.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale(const float fontScale)
Sets the font scale factor.
fontScale The scale factor. Reference to this config for method chaining.
References fontScale, TextRenderableConfig.
Referenced by fontScale.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build()
Builds the text renderable and adds components to the GameObject.
Creates a TextRenderable with the configured properties and adds RenderableComponent and ModelAabbComponent. If configured as UI text, also adds UiTextComponent. Reference to this config for method chaining.
References helios::engine::modules::ui::layout::types::Elapsed, helios::engine::modules::ui::layout::types::Remaining, helios::engine::modules::ui::layout::components::TimeFormatterComponent::setFormat, TextRenderableConfig.
Referenced by attachTo, attachTo.