helios::engine::modules::physics::collision::events::SolidCollisionEvent
const helios::util::Guid helios::engine::modules::physics::collision::events::SolidCollisionEvent::source_
GUID of the GameObject that initiated or detected the collision.
const helios::util::Guid helios::engine::modules::physics::collision::events::SolidCollisionEvent::match_
GUID of the GameObject that was collided with.
const helios::math::vec3f helios::engine::modules::physics::collision::events::SolidCollisionEvent::contact_
The world-space contact point of the collision.
helios::engine::modules::physics::collision::events::SolidCollisionEvent::SolidCollisionEvent(const helios::util::Guid source, const helios::util::Guid match, const helios::math::vec3f contact)
Constructs a SolidCollisionEvent.
source GUID of the GameObject that detected or initiated the collision. match GUID of the GameObject that was collided with. contact The world-space position where the collision occurred.
References contact, match, source.
helios::math::vec3f helios::engine::modules::physics::collision::events::SolidCollisionEvent::contact() const noexcept
Returns the contact point in world space.
The 3D position where the collision occurred.
Referenced by SolidCollisionEvent.
helios::util::Guid helios::engine::modules::physics::collision::events::SolidCollisionEvent::source() const noexcept
Returns the GUID of the source GameObject.
The source is the entity that detected/reported the collision. Use `GameWorld::find()` to retrieve the actual GameObject. GUID of the collision reporter.
Referenced by SolidCollisionEvent.
helios::util::Guid helios::engine::modules::physics::collision::events::SolidCollisionEvent::match() const noexcept
Returns the GUID of the matched GameObject.
The match is the entity that was collided with. Use `GameWorld::find()` to retrieve the actual GameObject. GUID of the collided entity.
Referenced by SolidCollisionEvent.