helios::engine::modules::rendering::model::components::ModelAabbComponent
helios::math::aabbf helios::engine::modules::rendering::model::components::ModelAabbComponent::aabb_
The stored AABB.
helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent()=default
Default constructor.
Referenced by ModelAabbComponent.
helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent(const ModelAabbComponent &other)
References ModelAabbComponent.
void helios::engine::modules::rendering::model::components::ModelAabbComponent::setAabb(const helios::math::aabbf &aabb)
Sets the AABB for this component.
aabb The new AABB to store.
References aabb.
Referenced by helios::engine::modules::rendering::renderable::components::RenderableComponent::onAttach.
const helios::math::aabbf & helios::engine::modules::rendering::model::components::ModelAabbComponent::aabb() const noexcept
Retrieves the stored AABB.
Constant reference to the AABB.
Referenced by setAabb.