helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent
float helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::restitution_
Coefficient of restitution (bounciness).
A value of 1.0 means a perfectly elastic collision (no energy lost). A value of 0.0 means a perfectly inelastic collision (no bounce). Default is 0.5.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::collisionBehavior_
The behavior type for boundary collisions.
Defines how the entity reacts when hitting level bounds (e.g., Bounce, Reflect, Clamp, Despawn).
helios::engine::modules::physics::collision::types::CollisionResponse helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::collisionResponse_
bool helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::LevelBoundsBehaviorComponent(const float restitution)
Constructs a LevelBoundsBehaviorComponent with a specified restitution.
restitution The coefficient of restitution (0.0 to 1.0).
References restitution.
Referenced by LevelBoundsBehaviorComponent, LevelBoundsBehaviorComponent, operator=, operator=.
helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::LevelBoundsBehaviorComponent(const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior=helios::engine::modules::physics::collision::types::CollisionBehavior::Reflect, const helios::engine::modules::physics::collision::types::CollisionResponse collisionResponse=helios::engine::modules::physics::collision::types::CollisionResponse::None)
Constructs a LevelBoundsBehaviorComponent with a specified collision behavior.
collisionBehavior The collision behavior type (default: Reflect).
References collisionBehavior, collisionResponse, helios::engine::modules::physics::collision::types::None, helios::engine::modules::physics::collision::types::Reflect.
helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::LevelBoundsBehaviorComponent(const LevelBoundsBehaviorComponent &other)
Copy constructor.
other The component to copy from.
References LevelBoundsBehaviorComponent.
LevelBoundsBehaviorComponent & helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::operator=(const LevelBoundsBehaviorComponent &)=default
References LevelBoundsBehaviorComponent.
helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::LevelBoundsBehaviorComponent(LevelBoundsBehaviorComponent &&) noexcept=default
References LevelBoundsBehaviorComponent.
LevelBoundsBehaviorComponent & helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::operator=(LevelBoundsBehaviorComponent &&) noexcept=default
References LevelBoundsBehaviorComponent.
float helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::restitution() const noexcept
Retrieves the restitution coefficient.
The restitution value.
References restitution.
Referenced by LevelBoundsBehaviorComponent, restitution, setRestitution.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::collisionBehavior() const noexcept
Retrieves the collision behavior type.
The collision behavior (e.g., Bounce, Reflect, Clamp, Despawn).
Referenced by LevelBoundsBehaviorComponent, setCollisionBehavior.
helios::engine::modules::physics::collision::types::CollisionResponse helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::collisionResponse() const noexcept
Retrieves the collision response type.
The collision response type (e.g., None, Event).
Referenced by LevelBoundsBehaviorComponent, setCollisionResponse.
void helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::setCollisionResponse(const helios::engine::modules::physics::collision::types::CollisionResponse collisionResponse) noexcept
Sets the collision response type.
collisionResponse The new collision response to set.
References collisionResponse.
void helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::setCollisionBehavior(const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior) noexcept
Sets the collision behavior type.
collisionBehavior The new collision behavior to set.
References collisionBehavior.
void helios::engine::mechanics::bounds::components::LevelBoundsBehaviorComponent::setRestitution(const float restitution) noexcept
Sets the coefficient of restitution (bounciness).
restitution The new restitution value to set. Must be within the range [0.0, 1.0]. Values outside this range will be clamped.
References restitution.