helios::engine::mechanics::scoring::components::ScorePoolComponent
helios::engine::core::data::ScorePoolId helios::engine::mechanics::scoring::components::ScorePoolComponent::scorePoolId_
ID of the associated score pool.
bool helios::engine::mechanics::scoring::components::ScorePoolComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::scoring::components::ScorePoolComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::scoring::components::ScorePoolComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::scoring::components::ScorePoolComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::scoring::components::ScorePoolComponent::ScorePoolComponent()=default
Referenced by operator=, operator=, ScorePoolComponent, ScorePoolComponent.
helios::engine::mechanics::scoring::components::ScorePoolComponent::ScorePoolComponent(const ScorePoolComponent &other)
Copy constructor.
other The component to copy from.
References ScorePoolComponent.
ScorePoolComponent & helios::engine::mechanics::scoring::components::ScorePoolComponent::operator=(const ScorePoolComponent &)=default
References ScorePoolComponent.
helios::engine::mechanics::scoring::components::ScorePoolComponent::ScorePoolComponent(ScorePoolComponent &&) noexcept=default
References ScorePoolComponent.
ScorePoolComponent & helios::engine::mechanics::scoring::components::ScorePoolComponent::operator=(ScorePoolComponent &&) noexcept=default
References ScorePoolComponent.
void helios::engine::mechanics::scoring::components::ScorePoolComponent::setScorePoolId(const helios::engine::core::data::ScorePoolId scorePoolId) noexcept
Sets the associated score pool.
scorePoolId The ID of the score pool.
References scorePoolId, setScorePoolId.
Referenced by setScorePoolId.
helios::engine::core::data::ScorePoolId helios::engine::mechanics::scoring::components::ScorePoolComponent::scorePoolId() const noexcept
Returns the associated score pool ID.
The ScorePoolId.
Referenced by setScorePoolId.