helios::engine::runtime::messaging::command::CommandBuffer
std::unique_ptr<Concept> helios::engine::runtime::messaging::command::CommandBuffer::pimpl_
Owning pointer to the type-erased command buffer.
helios::engine::runtime::messaging::command::CommandBuffer::CommandBuffer()=default
Referenced by CommandBuffer, CommandBuffer, operator=, operator=.
helios::engine::runtime::messaging::command::CommandBuffer::CommandBuffer(T cmdBuffer)
Constructs a CommandBuffer wrapping the given concrete buffer.
Ownership of the buffer is transferred into a heap-allocated Model<T>. The concrete type is erased after construction. T The concrete buffer type. Must satisfy IsCommandBufferLike. cmdBuffer The buffer instance to wrap. Moved into the wrapper.
helios::engine::runtime::messaging::command::CommandBuffer::CommandBuffer(const CommandBuffer &)=delete
References CommandBuffer.
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::operator=(const CommandBuffer &)=delete
References CommandBuffer.
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::operator=(CommandBuffer &&)=default
References CommandBuffer.
helios::engine::runtime::messaging::command::CommandBuffer::CommandBuffer(CommandBuffer &&) noexcept=default
References CommandBuffer.
void helios::engine::runtime::messaging::command::CommandBuffer::flush(GameWorld &gameWorld, UpdateContext &updateContext) noexcept
Executes all queued commands and clears the buffer.
Delegates to the wrapped buffer's `flush()`. Commands are routed to their registered handler if available, otherwise executed directly. gameWorld The game world providing the CommandHandlerRegistry. updateContext The current frame's update context. The CommandBuffer must be initialized (not default-constructed).
References flush.
Referenced by flush.
void helios::engine::runtime::messaging::command::CommandBuffer::clear() noexcept
Discards all queued commands without executing them.
The CommandBuffer must be initialized.
void * helios::engine::runtime::messaging::command::CommandBuffer::underlying() noexcept
Returns a type-erased pointer to the owned buffer instance.
Non-null void pointer to the underlying concrete buffer. The CommandBuffer must be initialized.
const void * helios::engine::runtime::messaging::command::CommandBuffer::underlying() const noexcept
Returns a type-erased pointer to the owned buffer instance.
Non-null void pointer to the underlying concrete buffer. The CommandBuffer must be initialized.