helios::engine::builder::gameObject::builders::configs::CollisionConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::CollisionConfig::gameObject_
Non-owning pointer to the target GameObject.
void helios::engine::builder::gameObject::builders::configs::CollisionConfig::ensureCollisionComponent(const bool isAvailable) const noexcept
Validates CollisionComponent presence.
isAvailable Whether the component should exist.
helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a CollisionConfig and adds CollisionStateComponent.
gameObject Target GameObject to configure.
Referenced by dealDamage, hitPolicy, layerId, onSolidCollision, reportCollisions, solidCollisionMask, useBoundingBox.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::useBoundingBox()
Adds AABB collider for bounding box collision.
Reference to this config for chaining.
References CollisionConfig.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::layerId(const uint32_t layerId)
Sets the collision layer ID.
layerId The layer this entity belongs to. Reference to this config for chaining.
References CollisionConfig, layerId.
Referenced by layerId.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::hitPolicy(const helios::engine::modules::physics::collision::types::HitPolicy hitPolicy)
Sets the hit policy for collision detection.
Controls how many collision events this entity receives per frame: `OneHit`: Only the first collision is reported (default) `All`: All collisions with overlapping entities are reported hitPolicy The hit policy to apply. Reference to this config for chaining. HitPolicy
References CollisionConfig, hitPolicy.
Referenced by hitPolicy.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::reportCollisions(bool isCollisionReporter)
Sets whether this entity reports collisions.
isCollisionReporter True to generate collision events. Reference to this config for chaining.
References CollisionConfig.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::solidCollisionMask(const uint32_t solidCollisionMask)
Sets the solid collision mask.
solidCollisionMask Bitmask of layers to collide with. Reference to this config for chaining.
References CollisionConfig, solidCollisionMask.
Referenced by solidCollisionMask.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::onSolidCollision(const uint32_t otherLayerId, const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior)
Adds a collision behavior for a specific layer.
otherLayerId The layer to respond to. collisionBehavior The behavior when colliding. Reference to this config for chaining.
References CollisionConfig.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::dealDamage(const float damageAmount, const uint32_t otherLayerId)
Configures damage dealing on collision with a specific layer.
Adds or updates a DamageDealerComponent to deal the specified damage when colliding with entities on the given layer. damageAmount The amount of damage to deal. otherLayerId The layer to deal damage to. Reference to this config for chaining.
References CollisionConfig.