helios::core::ecs::ComponentOpsRegistry
using helios::core::ecs::ComponentOpsRegistry< THandle >::ComponentTypeId_type = ComponentTypeId<THandle>
std::vector<ComponentOps> helios::core::ecs::ComponentOpsRegistry< THandle >::operations_
Type-indexed storage for ComponentOps.
ComponentOps helios::core::ecs::ComponentOpsRegistry< THandle >::emptyOps_
Empty ops returned for unregistered types.
static void helios::core::ecs::ComponentOpsRegistry< THandle >::setOps(const ComponentTypeId_type typeId, const ComponentOps &ops)
Registers ComponentOps for a component type.
Auto-resizes the internal vector if necessary. typeId The unique identifier for the component type. ops The lifecycle function pointers to register.
Referenced by helios::core::ecs::ComponentReflector< THandle, TEntityManager >::registerType.
static const ComponentOps & helios::core::ecs::ComponentOpsRegistry< THandle >::ops(const ComponentTypeId_type typeId)
Retrieves ComponentOps for a component type.
typeId The unique identifier for the component type. Reference to the registered ComponentOps, or empty ops if not registered.
Referenced by helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::add, helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::onAcquire, helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::onRelease, helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::setActive.