helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig
SpawnPoolConfig& helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::parent_
Parent pool this profile belongs to.
helios::engine::runtime::spawn::SpawnManager& helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::spawnManager_
The spawn manager to register with.
helios::engine::runtime::spawn::types::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::profileId_
Profile identifier.
helios::engine::runtime::pooling::types::GameObjectPoolId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::poolId_
Pool to acquire entities from.
std::unique_ptr<helios::engine::runtime::spawn::behavior::SpawnPlacer> helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::placer_
Placement strategy for spawned entities.
std::unique_ptr<helios::engine::runtime::spawn::behavior::SpawnInitializer> helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::initializer_
Initialization strategy for spawned entities.
std::vector<std::unique_ptr<SpawnRuleConfig> > helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::rules_
Scheduled rules for this profile.
helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig(SpawnPoolConfig &parent, helios::engine::runtime::spawn::SpawnManager &spawnManager, helios::engine::runtime::spawn::types::SpawnProfileId profileId, helios::engine::runtime::pooling::types::GameObjectPoolId poolId)
Constructs a SpawnProfileConfig.
parent The parent pool config. spawnManager The spawn manager to register profiles with. profileId Unique identifier for the profile. poolId Pool from which entities are acquired.
References profileId.
Referenced by axisPlacement, emitterPlacement, initializer, moveInitializer, placer, randomDirectionInitializer, randomPlacement.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::emitterPlacement()
Configures emitter-relative placement and initialization.
Reference to this config for chaining.
References SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomPlacement()
Configures random placement within level bounds.
Reference to this config for chaining.
References SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::axisPlacement(const helios::math::vec3f &axis, const helios::math::vec3f &origin)
Configures axis-aligned placement.
axis Direction axis for spawn distribution. origin Starting point of the axis. Reference to this config for chaining.
References SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::placer(std::unique_ptr< helios::engine::runtime::spawn::behavior::SpawnPlacer > customPlacer)
Sets a custom spawn placer.
customPlacer Ownership is transferred. Reference to this config for chaining.
References SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomDirectionInitializer()
Configures a move initializer with random direction.
Reference to this config for chaining.
References helios::engine::runtime::spawn::behavior::initializers::Random, SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::moveInitializer(const helios::math::vec3f &direction)
Configures a move initializer with a fixed direction.
direction The movement direction. Reference to this config for chaining.
References SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::initializer(std::unique_ptr< helios::engine::runtime::spawn::behavior::SpawnInitializer > customInitializer)
Sets a custom spawn initializer.
customInitializer Ownership is transferred. Reference to this config for chaining.
References SpawnProfileConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::scheduledBy(helios::engine::runtime::spawn::types::SpawnRuleId ruleId)
Begins configuration of a scheduled spawn rule for this profile.
ruleId Unique identifier for the rule. Reference to the new rule config for chaining.
helios::engine::runtime::spawn::types::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::profileId() const noexcept
Returns the profile ID.
The spawn profile ID.
Referenced by SpawnProfileConfig.
std::vector< std::pair< helios::engine::runtime::spawn::types::SpawnProfileId, std::unique_ptr< helios::engine::runtime::spawn::policy::SpawnRule > > > helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::commit()
Commits the profile and builds any associated rules.
Vector of built spawn rules (may be empty).
SpawnPoolConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::done()
Finalizes the profile and returns to the parent pool config.
Reference to the parent SpawnPoolConfig.