helios::engine::modules::physics::collision::components::AabbColliderComponent
helios::math::aabbf helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds_
The local bounds of the collider.
bool helios::engine::modules::physics::collision::components::AabbColliderComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::physics::collision::components::AabbColliderComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::enable() noexcept
Enables this component.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::disable() noexcept
Disables this component.
helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent()=default
Default constructor.
Referenced by AabbColliderComponent, AabbColliderComponent, operator=, operator=.
helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent(const AabbColliderComponent &other)
Copy constructor.
Preserves the bounds of this component.
References AabbColliderComponent.
AabbColliderComponent & helios::engine::modules::physics::collision::components::AabbColliderComponent::operator=(const AabbColliderComponent &)=default
References AabbColliderComponent.
helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent(AabbColliderComponent &&) noexcept=default
References AabbColliderComponent.
AabbColliderComponent & helios::engine::modules::physics::collision::components::AabbColliderComponent::operator=(AabbColliderComponent &&) noexcept=default
References AabbColliderComponent.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::onAcquire() noexcept
Resets the bounds to invalidate state when this Component is acquired.
References onAcquire.
Referenced by onAcquire.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::onRelease() noexcept
Resets the bounds to invalidate state when this Component is released.
const helios::math::aabbf & helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds()
Retrieves the bounds of the collider.
A const reference to the AABB.
Referenced by setBounds, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::setBounds(const helios::math::aabbf &bounds)
Sets the bounds of the collider.
bounds The new AABB to set.
References bounds.
bool helios::engine::modules::physics::collision::components::AabbColliderComponent::boundsInitialized() const noexcept
Checks whether the bounds of the collider have been initialized.
Bounds of the collider component are considered to be initialized if the minimum X coordinate is less or equal to the maximum X coordinate. true if the bounds are considered to be initialized; otherwise, false.