helios::rendering::mesh::MeshRenderable
std::shared_ptr<const helios::rendering::RenderPrototype> helios::rendering::mesh::MeshRenderable::renderPrototype_
Shared pointer to the immutable RenderPrototype definition.
Referenced by emit, localAABB, MeshRenderable, renderPrototype, shareRenderPrototype, writeUniformValues.
std::optional<helios::rendering::material::MaterialShaderPropertiesOverride> helios::rendering::mesh::MeshRenderable::materialOverride_
The MaterialShaderPropertiesOverride owned by this class. This will be std::nullopt if not available.
Referenced by hasMaterialOverride, materialOverride, materialOverride, MeshRenderable, writeUniformValues.
const helios::util::log::Logger& helios::rendering::mesh::MeshRenderable::logger_
Shared logger instance for all MeshRenderable objects.
Referenced by MeshRenderable.
helios::rendering::mesh::MeshRenderable::MeshRenderable()=delete
Deleted default constructor.
Referenced by MeshRenderable, MeshRenderable, MeshRenderable, operator=, operator=.
helios::rendering::mesh::MeshRenderable::MeshRenderable(const MeshRenderable &)=delete
Deleted copy constructor.
References MeshRenderable.
MeshRenderable & helios::rendering::mesh::MeshRenderable::operator=(const MeshRenderable &)=delete
Deleted copy assignment operator.
References MeshRenderable.
helios::rendering::mesh::MeshRenderable::MeshRenderable(MeshRenderable &&) noexcept=default
Defaulted move constructor.
References MeshRenderable.
MeshRenderable & helios::rendering::mesh::MeshRenderable::operator=(MeshRenderable &&) noexcept=default
Defaulted move assignment operator.
References MeshRenderable.
helios::rendering::mesh::MeshRenderable::MeshRenderable(std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype, const std::optional< helios::rendering::material::MaterialShaderPropertiesOverride > &materialOverride=std::nullopt)
Creates a new MeshRenderable instance.
renderPrototype A shared pointer to the immutable RenderPrototype definition. Must not be nullptr. materialOverride An optional set of instance-specific material property overrides. If std::nullopt, the MeshRenderable uses only the default properties from the RenderPrototype's Material. std::invalid_argument if `renderPrototype` is a nullptr.
References logger_, materialOverride, materialOverride_, MeshRenderable, renderPrototype, renderPrototype_.
std::shared_ptr< const helios::rendering::RenderPrototype > helios::rendering::mesh::MeshRenderable::shareRenderPrototype() const noexcept
Returns a shared pointer to the RenderPrototype used by this MeshRenderable.
A shared pointer to the RenderPrototype.
References renderPrototype_.
const helios::rendering::RenderPrototype * helios::rendering::mesh::MeshRenderable::renderPrototype() const noexcept
Returns a raw pointer to the RenderPrototype used by this MeshRenderable.
This method provides direct access to the prototype without incrementing the reference count, making it suitable for use in hot rendering paths. A raw pointer to the RenderPrototype (never null after construction).
References renderPrototype_.
Referenced by MeshRenderable.
const std::optional< helios::rendering::material::MaterialShaderPropertiesOverride > & helios::rendering::mesh::MeshRenderable::materialOverride() const noexcept
Returns a const reference to the optional instance-specific MaterialShaderPropertiesOverride.
This allows read-only access to the overrides. Use `.has_value()` to check for existence and `.value()` or `->` to safely access the override data. A const reference to the std::optional<MaterialShaderPropertiesOverride>.
References materialOverride_.
Referenced by MeshRenderable.
std::optional< helios::rendering::material::MaterialShaderPropertiesOverride > & helios::rendering::mesh::MeshRenderable::materialOverride() noexcept
Returns a non-const reference to the optional instance-specific MaterialShaderPropertiesOverride.
This allows modification of the overrides. If the optional currently has no value, it can be assigned to or `.emplace()` can be used to create a new MaterialShaderPropertiesOverride. A non-const reference to the std::optional<MaterialShaderPropertiesOverride>.
References materialOverride_.
bool helios::rendering::mesh::MeshRenderable::hasMaterialOverride() const noexcept
Returns true if this MeshRenderable was configured with a MaterialShaderPropertiesOverride.
True if this MeshRenderable was configured with a MaterialShaderPropertiesOverride instance, otherwise false.
References materialOverride_.
const helios::math::aabbf & helios::rendering::mesh::MeshRenderable::localAABB() const noexcept override
Returns the local-space axis-aligned bounding box.
Delegates to the underlying mesh's AABB from the render prototype. A const reference to the local-space AABB.
References renderPrototype_.
void helios::rendering::mesh::MeshRenderable::writeUniformValues(helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept override
Writes uniform values into the given map.
This method first applies the default uniform values from the base Material definition and then overlays any specific overrides provided by this instance's MaterialShaderPropertiesOverride. uniformValueMap Target map receiving the uniform values.
References materialOverride_, renderPrototype_.
Referenced by emit.
void helios::rendering::mesh::MeshRenderable::emit(helios::rendering::RenderQueue &renderQueue, helios::rendering::shader::UniformValueMap &objectUniformValues, helios::rendering::shader::UniformValueMap &materialUniformValues) const override
Emits a mesh render command to the render queue.
Creates a `MeshRenderCommand` with the render prototype and uniform values, then adds it to the render queue for processing by the rendering device. renderQueue The render queue to emit the command to. objectUniformValues Object-specific uniform values (e.g., model matrix). materialUniformValues Material uniform values (will be merged with material properties).
References helios::rendering::RenderQueue::add, renderPrototype_, writeUniformValues.