helios::engine::runtime::gameloop::Pass
helios::engine::runtime::world::SystemRegistry helios::engine::runtime::gameloop::Pass::systemRegistry_
Registry holding all systems for this pass.
Referenced by addSystem, helios::engine::runtime::gameloop::TypedPass< StateType >::helios::engine::runtime::gameloop::Phase.
virtual helios::engine::runtime::gameloop::Pass::~Pass()=default
virtual void helios::engine::runtime::gameloop::Pass::update(helios::engine::runtime::world::UpdateContext &updateContext)=0
Updates all systems in this pass.
updateContext The current update context.
virtual void helios::engine::runtime::gameloop::Pass::init(helios::engine::runtime::world::GameWorld &gameWorld)=0
Initializes all systems in this pass.
gameWorld Reference to the game world.
virtual Phase & helios::engine::runtime::gameloop::Pass::addCommitPoint(const CommitPoint commitPoint=CommitPoint::PassEvents)=0
Adds a commit point and returns the owning Phase.
commitPoint The synchronization flags. Reference to the owning Phase.
References commitPoint, helios::engine::runtime::gameloop::PassEvents.
virtual CommitPoint helios::engine::runtime::gameloop::Pass::commitPoint() const noexcept=0
Returns the configured commit point.
The commit point flags for this pass.
Referenced by addCommitPoint.
virtual bool helios::engine::runtime::gameloop::Pass::shouldRun(helios::engine::runtime::world::UpdateContext &updateContext) const noexcept=0
Determines if this pass should execute.
updateContext The current update context. True if the pass should run.
References shouldRun.
Referenced by shouldRun.
Pass & helios::engine::runtime::gameloop::Pass::addSystem(Args &&... args)
Adds a system of type T to this pass.
T The system type to add. Must derive from System. Args Constructor argument types for the system. args Arguments forwarded to the system constructor. Reference to this Pass for method chaining.
References addSystem, systemRegistry_.
Referenced by addSystem.