helios::core::data::TypeIndexer
std::atomic<size_t> helios::core::data::TypeIndexer< Group >::counter_
A static atomic counter used for generating unique type indices.
static size_t helios::core::data::TypeIndexer< Group >::typeIndex()
Generates and returns a unique type index for a specific type.
This method assigns a unique index to each type within the scope of the associated TypeIndexer. T The type for which to retrieve the unique index. A unique index representing the specific type T within this Group.
References helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::ecs::types::ComponentTypeId::id, helios::engine::mechanics::scoring::types::ScoreTypeId::id, helios::engine::runtime::messaging::command::types::CommandBufferTypeId::id, helios::engine::runtime::messaging::command::types::CommandTypeId::id, helios::engine::runtime::world::types::ManagerTypeId::id, helios::engine::runtime::world::types::ResourceTypeId::id, helios::engine::runtime::world::types::SystemTypeId::id, helios::engine::state::types::StateTypeId::id, helios::core::data::TypeIndexer< Group >::typeIndex.