helios::engine::mechanics::timing::components::GameTimerBindingComponent
GameTimerId helios::engine::mechanics::timing::components::GameTimerBindingComponent::gameTimerId_
The id of the observed game timer.
TimerRevision helios::engine::mechanics::timing::components::GameTimerBindingComponent::timerRevision_
Last known revision of the observed timer.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent()=default
Referenced by GameTimerBindingComponent, GameTimerBindingComponent, operator=, operator=.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent(const GameTimerBindingComponent &other)
Copy constructor.
other The component to copy from.
References GameTimerBindingComponent.
GameTimerBindingComponent & helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=(const GameTimerBindingComponent &)=default
References GameTimerBindingComponent.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent(GameTimerBindingComponent &&) noexcept=default
References GameTimerBindingComponent.
GameTimerBindingComponent & helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=(GameTimerBindingComponent &&) noexcept=default
References GameTimerBindingComponent.
void helios::engine::mechanics::timing::components::GameTimerBindingComponent::setGameTimerId(const helios::engine::core::data::GameTimerId gameTimerId) noexcept
Sets the id of the game timer to observe.
gameTimerId The timer id.
References gameTimerId, setGameTimerId.
Referenced by setGameTimerId.
helios::engine::core::data::GameTimerId helios::engine::mechanics::timing::components::GameTimerBindingComponent::gameTimerId() const noexcept
Returns the observed game timer id.
The GameTimerId.
Referenced by setGameTimerId.
void helios::engine::mechanics::timing::components::GameTimerBindingComponent::setTimerRevision(const TimerRevision timerRevision) noexcept
Sets the last known timer revision.
If the new revision differs from the stored one, the update flag is set so that consuming systems can detect the change. timerRevision The revision value.
References timerRevision.
TimerRevision helios::engine::mechanics::timing::components::GameTimerBindingComponent::timerRevision() const noexcept
Returns the last known timer revision.
The stored TimerRevision.
Referenced by setTimerRevision.