helios::engine::ecs::ComponentOpsRegistry
std::vector<ComponentOps> helios::engine::ecs::ComponentOpsRegistry::operations_
Type-indexed storage for ComponentOps.
ComponentOps helios::engine::ecs::ComponentOpsRegistry::emptyOps_
Empty ops returned for unregistered types.
static void helios::engine::ecs::ComponentOpsRegistry::setOps(const helios::engine::core::data::ComponentTypeId typeId, const ComponentOps &ops)
Registers ComponentOps for a component type.
Auto-resizes the internal vector if necessary. typeId The unique identifier for the component type. ops The lifecycle function pointers to register.
References ops, helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::ComponentReflector::registerType.
static const ComponentOps & helios::engine::ecs::ComponentOpsRegistry::ops(const helios::engine::core::data::ComponentTypeId typeId)
Retrieves ComponentOps for a component type.
typeId The unique identifier for the component type. Reference to the registered ComponentOps, or empty ops if not registered.
References helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::GameObject::add, helios::engine::ecs::EntityManager::clone, helios::engine::ecs::EntityManager::destroy, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::GameObject::onAcquire, helios::engine::ecs::GameObject::onRelease, helios::engine::ecs::EntityManager::remove, helios::engine::ecs::GameObject::setActive, setOps, helios::engine::mechanics::lifecycle::systems::DelayedComponentEnablerSystem::update.