helios::engine::builder::gameObject::builders::configs::HealthConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::HealthConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::HealthConfig::HealthConfig(helios::engine::ecs::GameObject gameObject)
Constructs a HealthConfig and adds HealthComponent.
gameObject Target GameObject to configure.
Referenced by healthDepletedTriggers, lives, maxHealth.
HealthConfig & helios::engine::builder::gameObject::builders::configs::HealthConfig::maxHealth(const float maxHealth)
Sets the maximum health value.
maxHealth The maximum health value. Reference to this config for chaining.
References HealthConfig, maxHealth.
Referenced by maxHealth.
HealthConfig & helios::engine::builder::gameObject::builders::configs::HealthConfig::lives(const size_t lives)
Sets the initial number of lives.
Adds or retrieves a LivesComponent with the given count. lives Initial life count. Reference to this config for chaining.
References HealthConfig, lives.
Referenced by lives.
HealthConfig & helios::engine::builder::gameObject::builders::configs::HealthConfig::healthDepletedTriggers(const HealthDepletedBehavior behavior)
Configures the response when health reaches zero.
behavior Bitmask of HealthDepletedBehavior flags. Reference to this config for chaining.
References HealthConfig.