helios.engine.runtime.messaging.command.CommandBuffer
std::type_index helios::engine::runtime::messaging::command::CommandBuffer::TargetedCommandProxy::typeIdx
helios::engine::ecs::EntityHandle helios::engine::runtime::messaging::command::CommandBuffer::TargetedCommandProxy::entityHandle
std::unique_ptr<helios::engine::runtime::messaging::command::TargetedCommand> helios::engine::runtime::messaging::command::CommandBuffer::TargetedCommandProxy::targetedCommand
std::type_index helios::engine::runtime::messaging::command::CommandBuffer::WorldCommandProxy::typeIdx
std::unique_ptr<helios::engine::runtime::messaging::command::WorldCommand> helios::engine::runtime::messaging::command::CommandBuffer::WorldCommandProxy::worldCommand
std::deque<TargetedCommandProxy> helios::engine::runtime::messaging::command::CommandBuffer::targetedCommandBuffer_
Internal queue storing buffered commands.
Uses std::deque for efficient push_back and iteration.
std::deque<WorldCommandProxy> helios::engine::runtime::messaging::command::CommandBuffer::worldCommandBuffer_
Internal queue storing buffered world commands.
Uses std::deque for efficient push_back and iteration.
const helios::util::log::Logger& helios::engine::runtime::messaging::command::CommandBuffer::logger_
The logger used with this CommandBuffer instance.
Defaults to HELIOS_LOG_SCOPE.
std::unordered_map<std::type_index, std::unique_ptr<helios::engine::runtime::messaging::command::TargetedCommandDispatcher> > helios::engine::runtime::messaging::command::CommandBuffer::targetedCommandDispatchers_
Registry of dispatchers for TargetedCommand types.
Maps command type indices to their corresponding dispatchers. When a command is flushed and a dispatcher is registered for its type, the command is routed through the dispatcher instead of executing directly.
std::unordered_map<std::type_index, std::unique_ptr<helios::engine::runtime::messaging::command::WorldCommandDispatcher> > helios::engine::runtime::messaging::command::CommandBuffer::worldCommandDispatchers_
Registry of dispatchers for WorldCommand types.
Maps command type indices to their corresponding dispatchers. When a command is flushed and a dispatcher is registered for its type, the command is routed through the dispatcher instead of executing directly.
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::addDispatcher(std::unique_ptr< helios::engine::runtime::messaging::command::TypedTargetedCommandDispatcher< T > > d)
Registers a dispatcher for a specific TargetedCommand type.
When flush() processes a command of type T, it will route the command through this dispatcher instead of calling execute() directly. T The concrete TargetedCommand type to dispatch. d The dispatcher instance to register. Ownership is transferred. No dispatcher for type T must already be registered. A reference to **this** CommandBuffer.
References helios::engine::runtime::messaging::command::CommandBuffer::hasDispatcher.
bool helios::engine::runtime::messaging::command::CommandBuffer::hasDispatcher() const
Checks if a dispatcher is registered for a specific TargetedCommand type.
T The concrete TargetedCommand type to check. true if a dispatcher is registered for type T, false otherwise.
Referenced by helios::engine::runtime::messaging::command::CommandBuffer::addDispatcher, helios::engine::runtime::messaging::command::CommandBuffer::addDispatcher.
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::addDispatcher(std::unique_ptr< helios::engine::runtime::messaging::command::TypedWorldCommandDispatcher< T > > d)
Registers a dispatcher for a specific WorldCommand type.
When flush() processes a command of type T, it will route the command through this dispatcher instead of calling execute() directly. T The concrete WorldCommand type to dispatch. d The dispatcher instance to register. Ownership is transferred. No dispatcher for type T must already be registered. A reference to **this** CommandBuffer.
References helios::engine::runtime::messaging::command::CommandBuffer::hasDispatcher.
bool helios::engine::runtime::messaging::command::CommandBuffer::hasDispatcher() const
Checks if a dispatcher is registered for a specific WorldCommand type.
T The concrete WorldCommand type to check. true if a dispatcher is registered for type T, false otherwise.
void helios::engine::runtime::messaging::command::CommandBuffer::add(const helios::engine::ecs::EntityHandle &entityHandle, Args &&...args)
Adds a command targeting a GameObject identified by Guid.
guid The unique identifier of the target GameObject. command The command to execute. Ownership is transferred to the buffer. command must not be nullptr. If command is nullptr, the call is silently ignored (will be logged in future). This overload is useful when the GameObject instance is not directly available, such as in networked scenarios or when processing serialized commands.
Referenced by helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
void helios::engine::runtime::messaging::command::CommandBuffer::add(Args &&...args)
Adds a world command to the buffer.
T The concrete WorldCommand type to create. Args Constructor argument types for T. args Arguments forwarded to the T constructor. WorldCommands operate on the entire GameWorld rather than a specific GameObject. They are executed before TargetedCommands during flush().
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::flush(helios::engine::runtime::world::GameWorld &gameWorld)
Executes all buffered commands against the GameWorld and clears the buffer.
gameWorld The world containing target GameObjects. Reference to this CommandBuffer for method chaining. Execution proceeds in two phases: 1. **WorldCommands** are processed first. For each command, if a dispatcher is registered for its type, the command is routed via accept(). Otherwise, execute() is called directly. 2. **TargetedCommands** are processed second. Each command's target GameObject is resolved by Guid. If found and a dispatcher exists, the command is routed via accept(). Otherwise, execute() is called directly. Commands targeting non-existent GameObjects (i.e., find() returns nullptr) are skipped and a warning is logged. All commands are cleared after execution, regardless of success or failure. Command execution should be noexcept. If execute() throws, the flush operation aborts and remaining commands are not executed.
References helios::engine::runtime::messaging::command::CommandBuffer::clear, helios::engine::runtime::world::GameWorld::find.
CommandBuffer & helios::engine::runtime::messaging::command::CommandBuffer::clear()
Clears all buffered commands without executing them.
Reference to this CommandBuffer for method chaining. This destroys all buffered commands. Use this to discard commands without executing them (e.g., when reverting to a previous game state).
References helios::engine::runtime::messaging::command::CommandBuffer::clear.
Referenced by helios::engine::runtime::messaging::command::CommandBuffer::clear, helios::engine::runtime::messaging::command::CommandBuffer::flush.