helios.engine.game.event.SolidCollisionEvent
const helios::engine::game::GameObject* helios::engine::game::event::SolidCollisionEvent::source_
The primary GameObject that initiated or detected the collision.
const helios::engine::game::GameObject* helios::engine::game::event::SolidCollisionEvent::match_
The secondary GameObject that was collided with.
const helios::math::vec3f helios::engine::game::event::SolidCollisionEvent::contact_
The world-space contact point of the collision.
helios::engine::game::event::SolidCollisionEvent::SolidCollisionEvent(const helios::engine::game::GameObject *source, const helios::engine::game::GameObject *match, const helios::math::vec3f contact)
Constructs a SolidCollisionEvent.
source The GameObject that detected or initiated the collision. match The GameObject that was collided with. contact The world-space position where the collision occurred.
References helios::engine::game::event::SolidCollisionEvent::contact, helios::engine::game::event::SolidCollisionEvent::match, helios::engine::game::event::SolidCollisionEvent::source.
helios::math::vec3f helios::engine::game::event::SolidCollisionEvent::contact() const noexcept
Returns the contact point in world space.
The 3D position where the collision occurred.
Referenced by helios::engine::game::event::SolidCollisionEvent::SolidCollisionEvent.
const helios::engine::game::GameObject * helios::engine::game::event::SolidCollisionEvent::source() const noexcept
Returns the source GameObject.
Non-owning pointer to the GameObject that detected the collision.
Referenced by helios::engine::game::event::SolidCollisionEvent::SolidCollisionEvent.
const helios::engine::game::GameObject * helios::engine::game::event::SolidCollisionEvent::match() const noexcept
Returns the matched GameObject.
Non-owning pointer to the GameObject that was collided with.
Referenced by helios::engine::game::event::SolidCollisionEvent::SolidCollisionEvent.