helios.engine.builder.gameObject.builders.configs.TransformConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::TransformConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::TransformConfig::TransformConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a TransformConfig and adds ComposeTransformComponent.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::TransformConfig::scale, helios::engine::builder::gameObject::builders::configs::TransformConfig::translate.
TransformConfig & helios::engine::builder::gameObject::builders::configs::TransformConfig::scale(const helios::math::vec3f scale, const helios::core::units::Unit unit=helios::core::units::Unit::Meter)
Sets the scale of the entity.
scale Scale factors for x, y, z axes. unit The unit of measurement (default: Meter). Reference to this config for chaining.
References helios::core::units::Meter, helios::engine::builder::gameObject::builders::configs::TransformConfig::scale, helios::engine::builder::gameObject::builders::configs::TransformConfig::TransformConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TransformConfig::scale.
TransformConfig & helios::engine::builder::gameObject::builders::configs::TransformConfig::translate(const helios::math::vec3f translation)
Sets the translation (position) of the entity.
translation Position in world space. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::TransformConfig::TransformConfig.