helios.rendering.mesh.MeshRenderCommand
const helios::rendering::RenderPrototype* helios::rendering::mesh::MeshRenderCommand::renderPrototype_
A non-owning raw pointer to the RenderPrototype to be used.
The caller must ensure the `RenderPrototype` outlives this command.
helios::rendering::shader::UniformValueMap helios::rendering::mesh::MeshRenderCommand::objectUniformValues_
An owning, unique pointer to the uniform values specific for the object to be rendered. This map contains uniforms that change per object instance, such as the world transformation matrix.
helios::rendering::shader::UniformValueMap helios::rendering::mesh::MeshRenderCommand::materialUniformValues_
An owning, unique pointer to the uniform values specific to the material of the object to be rendered. This map contains uniforms related to the surface properties of a material.
helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand(const MeshRenderCommand &)=delete
Prevent copying. A MeshRenderCommand is not intended to be copied.
References helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
Referenced by helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand, helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand, helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand, helios::rendering::mesh::MeshRenderCommand::operator=, helios::rendering::mesh::MeshRenderCommand::operator=, helios::rendering::mesh::MeshRenderCommand::~MeshRenderCommand.
MeshRenderCommand & helios::rendering::mesh::MeshRenderCommand::operator=(const MeshRenderCommand &)=delete
Prevent copy assignment. A MeshRenderCommand is not intended to be copied.
References helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand(MeshRenderCommand &&) noexcept=default
Default move constructor.
References helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
MeshRenderCommand & helios::rendering::mesh::MeshRenderCommand::operator=(MeshRenderCommand &&) noexcept=default
Default move assignment.
References helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
helios::rendering::mesh::MeshRenderCommand::~MeshRenderCommand()=default
Default destructor.
References helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand(const helios::rendering::RenderPrototype *renderPrototype, const helios::rendering::shader::UniformValueMap &objectUniformValues, const helios::rendering::shader::UniformValueMap &materialUniformValues) noexcept
Constructs a new `MeshRenderCommand`.
Initializes this command with a non-owning pointer to the render prototype and takes ownership of the provided `UniformValueMaps`. renderPrototype A raw pointer to the `RenderPrototype` to be associated with this command. Must remain valid for the lifetime of this command. objectUniformValues A `UniformValueMap` containing all uniform values for the rendered object. materialUniformValues A `UniformValueMap` containing all uniform values for the material.
References helios::rendering::mesh::MeshRenderCommand::materialUniformValues, helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand, helios::rendering::mesh::MeshRenderCommand::objectUniformValues, helios::rendering::mesh::MeshRenderCommand::renderPrototype.
const helios::rendering::RenderPrototype * helios::rendering::mesh::MeshRenderCommand::renderPrototype() const noexcept
Returns the RenderPrototype associated with this command.
A raw pointer to this command's RenderPrototype. May be `nullptr` if no prototype was provided.
Referenced by helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
const helios::rendering::shader::UniformValueMap & helios::rendering::mesh::MeshRenderCommand::objectUniformValues() const noexcept
Returns a const ref to this command's UniformValueMap for the object.
A const ref to this command's UniformValueMap for the object.
Referenced by helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.
const helios::rendering::shader::UniformValueMap & helios::rendering::mesh::MeshRenderCommand::materialUniformValues() const noexcept
Returns a const ref to this command's UniformValueMap for the material.
A const ref to this command's UniformValueMap for the material.
Referenced by helios::rendering::mesh::MeshRenderCommand::MeshRenderCommand.