helios.engine.modules.physics.motion.components.SteeringComponent
float helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_SPEED
Default maximum rotation speed in degrees per second.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults.
float helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_SPEED_THRESHOLD
Default minimum rotation speed before rotation stops completely.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults.
float helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_DAMPENING
Default exponential decay factor for rotation when input stops.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed_
Maximum rotation speed in degrees per second.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed, helios::engine::modules::physics::motion::components::SteeringComponent::setRotationSpeed, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold_
Minimum rotation speed before rotation stops completely.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold, helios::engine::modules::physics::motion::components::SteeringComponent::setRotationSpeedThreshold, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening_
Exponential decay factor for rotation when input stops.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults, helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening, helios::engine::modules::physics::motion::components::SteeringComponent::setRotationDampening, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
float helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationAngle_
Current rotation angle in degrees.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationAngle, helios::engine::modules::physics::motion::components::SteeringComponent::setCurrentRotationAngle.
float helios::engine::modules::physics::motion::components::SteeringComponent::targetRotationAngle_
Target rotation angle derived from input direction.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setTargetRotationAngle, helios::engine::modules::physics::motion::components::SteeringComponent::targetRotationAngle.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationAngleDelta_
Shortest angular distance to target rotation.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::rotationAngleDelta, helios::engine::modules::physics::motion::components::SteeringComponent::setRotationAngleDelta.
float helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationSpeed_
Current rotation speed after applying input and dampening.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationSpeed, helios::engine::modules::physics::motion::components::SteeringComponent::setCurrentRotationSpeed.
bool helios::engine::modules::physics::motion::components::SteeringComponent::stateChanged_
Indicates whether input is currently being received.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent, helios::engine::modules::physics::motion::components::SteeringComponent::stateChanged.
float helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity_
Intensity of the turn input, typically from 0.0 to 1.0.
Derived from the magnitude of the input direction vector. Used to modulate rotation speed based on stick deflection.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent, helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity.
helios::math::vec3f helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput_
Current steering input as 2D direction vector.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent, helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput, helios::engine::modules::physics::motion::components::SteeringComponent::steeringIntent.
helios::math::vec3f helios::engine::modules::physics::motion::components::SteeringComponent::rotationAxis_
The axis around which rotation occurs.
Defaults to Z-axis for 2D top-down rotation.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::rotationAxis, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
bool helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation_
Flag for instant rotation mode.
When true, the entity snaps to the target rotation instantly rather than smoothly interpolating.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setUseInstantRotation, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent, helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation.
bool helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering_
Flag indicating if the direction component should be updated from steering.
If true, the DirectionComponent of the entity will be synchronized with the steering input direction.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering, helios::engine::modules::physics::motion::components::SteeringComponent::setDirectionFromSteering, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent()=default
Default constructor.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent(bool useInstantRotation, bool directionFromSteering=false)
Constructs a SteeringComponent with specified settings.
useInstantRotation If true, rotation snaps instantly to target. directionFromSteering If true, synchronizes DirectionComponent with steering.
References helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering, helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering_, helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation, helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation_.
helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent(const SteeringComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationAxis_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold_, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent, helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setHeading(helios::math::vec3f direction, float turnIntensity)
DeprecatedUse setSteeringIntent instead.
References helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent, helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity.
void helios::engine::modules::physics::motion::components::SteeringComponent::setDirectionFromSteering(const bool directionFromSteering) noexcept
Sets whether the direction component should be updated from steering.
directionFromSteering True to enable synchronization, false to disable.
References helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering, helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering_.
bool helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering() const noexcept
Checks if direction synchronization is enabled.
True if DirectionComponent is updated from steering, false otherwise.
References helios::engine::modules::physics::motion::components::SteeringComponent::directionFromSteering_.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setDirectionFromSteering, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
bool helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation() const noexcept
Returns whether instant rotation mode is enabled.
True if rotation snaps instantly, false for smooth interpolation.
References helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation_.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setUseInstantRotation, helios::engine::modules::physics::motion::components::SteeringComponent::SteeringComponent.
void helios::engine::modules::physics::motion::components::SteeringComponent::setUseInstantRotation(const bool useInstantRotation) noexcept
Sets the instant rotation mode.
useInstantRotation True to snap instantly to target rotation, false for interpolation.
References helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation, helios::engine::modules::physics::motion::components::SteeringComponent::useInstantRotation_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent(helios::math::vec3f direction, float turnIntensity)
Sets the heading direction and turn intensity from input.
Updates the heading input vector and turn intensity. If the turn intensity is below the epsilon threshold, input is deactivated and the heading is reset to zero. direction Normalized direction vector representing the desired heading. turnIntensity Magnitude of the input (0.0 to 1.0). direction must be a normalized vector (length ~= 1.0).
References helios::math::EPSILON_LENGTH, helios::math::vec3< T >::isNormalized, helios::engine::modules::physics::motion::components::SteeringComponent::stateChanged_, helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput_, helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity, helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity_.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setHeading.
helios::math::vec3f helios::engine::modules::physics::motion::components::SteeringComponent::rotationAxis() const noexcept
Returns the axis around which rotation occurs.
For 2D gameplay on the XY plane, this is typically the Z-axis. The rotation axis as a unit vector.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationAxis_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setCurrentRotationSpeed(float speed) noexcept
Sets the current rotation speed.
speed The new rotation speed.
References helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationSpeed_.
float helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationSpeed() const noexcept
Returns the current rotation speed.
The current rotation speed.
References helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationSpeed_.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationAngleDelta() const noexcept
Returns the angular distance to the target rotation.
The angle delta in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationAngleDelta_.
float helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationAngle() const noexcept
Returns the current rotation angle.
The current rotation angle in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationAngle_.
float helios::engine::modules::physics::motion::components::SteeringComponent::targetRotationAngle() const noexcept
Returns the target rotation angle.
The target rotation angle in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::targetRotationAngle_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setTargetRotationAngle(float angle) noexcept
Sets the target rotation angle.
angle The new target rotation angle in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::targetRotationAngle_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setCurrentRotationAngle(float angle) noexcept
Sets the current rotation angle.
angle The new rotation angle in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::currentRotationAngle_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setRotationAngleDelta(float delta) noexcept
Sets the angular distance to the target rotation.
delta The new angle delta in degrees.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationAngleDelta_.
bool helios::engine::modules::physics::motion::components::SteeringComponent::stateChanged() const noexcept
Checks if input is currently active.
True if input is active, false otherwise.
References helios::engine::modules::physics::motion::components::SteeringComponent::stateChanged_.
const helios::math::vec3f & helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput() const noexcept
Returns the current steering input direction.
Const reference to the 2D steering input vector.
References helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput_.
const helios::math::vec3f & helios::engine::modules::physics::motion::components::SteeringComponent::steeringIntent() const noexcept
Returns the current steering intent (alias for steeringInput).
Const reference to the steering input vector.
References helios::engine::modules::physics::motion::components::SteeringComponent::steeringInput_.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed() const noexcept
Returns the maximum rotation speed in degrees per second.
Maximum rotation speed value.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed_.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold() const noexcept
Returns the minimum rotation speed threshold.
Rotation speed threshold below which rotation stops.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold_.
float helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening() const noexcept
Returns the rotation dampening factor.
Exponential decay factor for rotation.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setRotationSpeed(float value) noexcept
Sets the maximum rotation speed in degrees per second.
value New rotation speed value.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setRotationSpeedThreshold(float value) noexcept
Sets the minimum rotation speed threshold.
value New threshold value.
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold_.
void helios::engine::modules::physics::motion::components::SteeringComponent::setRotationDampening(float value) noexcept
Sets the rotation dampening factor.
value New dampening factor (exponential decay).
References helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening_.
float helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity() const noexcept
Returns the current turn intensity.
Turn intensity value, typically from 0.0 to 1.0.
References helios::engine::modules::physics::motion::components::SteeringComponent::turnIntensity_.
Referenced by helios::engine::modules::physics::motion::components::SteeringComponent::setHeading, helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent.
void helios::engine::modules::physics::motion::components::SteeringComponent::resetToDefaults() noexcept
Resets all physics parameters to their default values.
References helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_DAMPENING, helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_SPEED, helios::engine::modules::physics::motion::components::SteeringComponent::DEFAULT_ROTATION_SPEED_THRESHOLD, helios::engine::modules::physics::motion::components::SteeringComponent::rotationDampening_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeed_, helios::engine::modules::physics::motion::components::SteeringComponent::rotationSpeedThreshold_.