helios.engine.core.data.GameObjectPoolId
uint32_t helios::engine::core::data::GameObjectPoolId::id_
The underlying numeric identifier.
helios::engine::core::data::GameObjectPoolId::GameObjectPoolId(uint32_t id) noexcept
Constructs a GameObjectPoolId with the specified value.
id The numeric identifier for this pool.
Referenced by helios::engine::core::data::GameObjectPoolId::operator<, helios::engine::core::data::GameObjectPoolId::operator==, helios::engine::core::data::GameObjectPoolId::operator>.
uint32_t helios::engine::core::data::GameObjectPoolId::value() const noexcept
Returns the underlying numeric value.
The pool ID as an unsigned 32-bit integer.
bool helios::engine::core::data::GameObjectPoolId::operator<(const GameObjectPoolId &other) const noexcept
Less-than comparison operator for ordered containers.
other The GameObjectPoolId to compare against. True if this ID is less than other.
References helios::engine::core::data::GameObjectPoolId::GameObjectPoolId.
bool helios::engine::core::data::GameObjectPoolId::operator>(const GameObjectPoolId &other) const noexcept
Greater-than comparison operator for ordered containers.
other The GameObjectPoolId to compare against. True if this ID is greater than other.
References helios::engine::core::data::GameObjectPoolId::GameObjectPoolId.
std::size_t std::hash< helios::engine::core::data::GameObjectPoolId >::operator()(const helios::engine::core::data::GameObjectPoolId &id) const noexcept