helios.engine.core.data.ComponentTypeId
using helios::engine::core::data::ComponentTypeId::ComponentType = helios_engine_core_data_ComponentTypes
size_t helios::engine::core::data::ComponentTypeId::id_
The underlying ID value.
helios::engine::core::data::ComponentTypeId::ComponentTypeId(const size_t id)
Constructs a ComponentTypeId with a specific ID value.
This constructor initializes a ComponentTypeId object with a given ID, representing a unique identifier for a component type. The ID is used internally for indexing and retrieving components from the storage system. id The unique identifier assigned to the component type. This ID must be a valid non-negative value.
References helios::engine::core::data::ComponentTypeId::id.
Referenced by helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::operator==.
helios::engine::core::data::ComponentTypeId::ComponentTypeId(helios::core::types::no_init_t)
Constructs an uninitialized ComponentTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::core::data::ComponentTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
Referenced by helios::engine::ecs::EntityManager::emplace, helios::engine::ecs::EntityManager::get, helios::engine::ecs::EntityManager::getSparseSet, helios::engine::ecs::EntityManager::getSparseSet, helios::engine::ecs::EntityManager::has, helios::engine::ecs::EntityManager::has, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::EntityManager::raw, helios::engine::ecs::ComponentOpsRegistry::setOps.
static ComponentTypeId helios::engine::core::data::ComponentTypeId::id()
Gets the ComponentTypeId for a specific component type.
Uses TypeIndexer to generate a unique, monotonically increasing ID for each component type. The ID is generated once per type and cached. T The component type. Must be a concrete type (not abstract). The unique ComponentTypeId for type T.
References helios::engine::core::data::ComponentTypeId::ComponentTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::ecs::GameObject::add, helios::engine::core::data::ComponentTypeId::ComponentTypeId, helios::engine::ecs::EntityManager::emplace, helios::engine::ecs::EntityManager::get, helios::engine::ecs::EntityManager::getSparseSet, helios::engine::ecs::EntityManager::getSparseSet, helios::engine::ecs::EntityManager::has, helios::engine::ecs::ComponentReflector::registerType, helios::engine::ecs::EntityManager::remove.
std::size_t std::hash< helios::engine::core::data::ComponentTypeId >::operator()(const helios::engine::core::data::ComponentTypeId &id) const noexcept