helios.engine.modules.physics.motion.components.DirectionComponent
helios::math::vec3f helios::engine::modules::physics::motion::components::DirectionComponent::direction_
The stored normalized direction vector.
bool helios::engine::modules::physics::motion::components::DirectionComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::physics::motion::components::DirectionComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::physics::motion::components::DirectionComponent::enable() noexcept
Enables this component.
void helios::engine::modules::physics::motion::components::DirectionComponent::disable() noexcept
Disables this component.
helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent()=default
Default constructor.
Referenced by helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent, helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent, helios::engine::modules::physics::motion::components::DirectionComponent::operator=, helios::engine::modules::physics::motion::components::DirectionComponent::operator=.
helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent(const DirectionComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::physics::motion::components::DirectionComponent::direction, helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent.
DirectionComponent & helios::engine::modules::physics::motion::components::DirectionComponent::operator=(const DirectionComponent &)=default
References helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent.
helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent(DirectionComponent &&) noexcept=default
References helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent.
DirectionComponent & helios::engine::modules::physics::motion::components::DirectionComponent::operator=(DirectionComponent &&) noexcept=default
References helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent.
void helios::engine::modules::physics::motion::components::DirectionComponent::setDirection(const helios::math::vec3f direction) noexcept
Sets the direction vector.
The provided vector must be normalized. An assertion checks this in debug builds. direction The new normalized direction vector.
References helios::engine::modules::physics::motion::components::DirectionComponent::direction, helios::math::EPSILON_LENGTH, helios::engine::modules::physics::motion::components::DirectionComponent::setDirection.
Referenced by helios::engine::modules::physics::motion::components::DirectionComponent::setDirection.
helios::math::vec3f helios::engine::modules::physics::motion::components::DirectionComponent::direction() const noexcept
Retrieves the stored direction vector.
The current normalized direction vector.
Referenced by helios::engine::modules::physics::motion::components::DirectionComponent::DirectionComponent, helios::engine::modules::physics::motion::components::DirectionComponent::setDirection.