helios.engine.builder.gameObject.builders.configs.MeshRenderableConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::gameObject_
Non-owning pointer to the target GameObject.
std::shared_ptr<helios::rendering::asset::shape::Shape> helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shape_
The shape geometry to render.
std::shared_ptr<helios::ext::opengl::rendering::shader::OpenGLShader> helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shader_
The shader for rendering.
helios::rendering::mesh::PrimitiveType helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::primitiveType_
The primitive type for mesh rendering.
helios::math::vec4f helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::color_
The base color for the material.
std::unordered_map< helios::rendering::mesh::PrimitiveType, std::shared_ptr<helios::rendering::mesh::MeshConfig> > helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::meshConfigs_
static std::shared_ptr< helios::rendering::mesh::MeshConfig > helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::meshConfig(helios::rendering::mesh::PrimitiveType primitiveType)
helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig(helios::engine::ecs::GameObject gameObject)
Constructs a MeshRenderableConfig for the given GameObject.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::build, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::color, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::primitiveType, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shader, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shape.
MeshRenderableConfig & helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shape(std::shared_ptr< helios::rendering::asset::shape::Shape > shape)
Sets the shape geometry.
shape Shared pointer to the shape. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shape.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shape.
MeshRenderableConfig & helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shader(std::shared_ptr< helios::ext::opengl::rendering::shader::OpenGLShader > shader)
Sets the shader program.
shader Shared pointer to the OpenGL shader. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shader.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::shader.
MeshRenderableConfig & helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::primitiveType(helios::rendering::mesh::PrimitiveType primitiveType)
Sets the primitive type for rendering.
primitiveType The OpenGL primitive type. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::primitiveType.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::primitiveType.
MeshRenderableConfig & helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::color(const helios::math::vec4f color)
Sets the base color for the material.
color RGBA color vector. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::color, helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::color.
void helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::attachTo(helios::scene::SceneNode *parent)
Builds the renderable and attaches it to a scene node.
parent Parent SceneNode for the new node.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
MeshRenderableConfig & helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::build()
Builds and attaches the RenderableComponent.
Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::MeshRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::MeshRenderableConfig::attachTo.