helios.engine.runtime.pooling.GameObjectPool
std::vector<size_t> helios::engine::runtime::pooling::GameObjectPool::activeIndex_
Maps active GameObject EntityIds to their index in activeGameObjects_.
Enables O(1) lookup for release operations.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::lock, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
std::vector<size_t> helios::engine::runtime::pooling::GameObjectPool::versionIndex_
Tracks version numbers for active EntityHandles.
Used to validate that a release operation targets the correct entity version.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::lock, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
std::vector<helios::engine::ecs::EntityHandle> helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_
List of EntityHandles for currently active (in-use) GameObjects.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::activeCount, helios::engine::runtime::pooling::GameObjectPool::activeGameObjects, helios::engine::runtime::pooling::GameObjectPool::GameObjectPool, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
std::vector<helios::engine::ecs::EntityHandle> helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_
List of EntityHandles for currently inactive (available) GameObjects.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::runtime::pooling::GameObjectPool::GameObjectPool, helios::engine::runtime::pooling::GameObjectPool::inactiveCount, helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects, helios::engine::runtime::pooling::GameObjectPool::release.
size_t helios::engine::runtime::pooling::GameObjectPool::poolSize_
The maximum number of objects this pool manages.
Referenced by helios::engine::runtime::pooling::GameObjectPool::GameObjectPool, helios::engine::runtime::pooling::GameObjectPool::size.
helios::engine::ecs::types::EntityId helios::engine::runtime::pooling::GameObjectPool::minEntityId_
Minimum EntityId in the pool (used for sparse array offset).
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::runtime::pooling::GameObjectPool::lock.
helios::engine::ecs::types::EntityId helios::engine::runtime::pooling::GameObjectPool::maxEntityId_
Maximum EntityId in the pool (used for sparse array sizing).
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::runtime::pooling::GameObjectPool::lock.
size_t helios::engine::runtime::pooling::GameObjectPool::delta_
Offset for sparse array indexing (equals minEntityId_ after lock).
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::lock, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
const helios::util::Guid helios::engine::runtime::pooling::GameObjectPool::guid_
Unique identifier for this pool instance.
Referenced by helios::engine::runtime::pooling::GameObjectPool::GameObjectPool, helios::engine::runtime::pooling::GameObjectPool::guid.
bool helios::engine::runtime::pooling::GameObjectPool::locked_
True if the pool is locked and ready for acquire/release operations.
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::runtime::pooling::GameObjectPool::isLocked, helios::engine::runtime::pooling::GameObjectPool::lock.
helios::engine::runtime::pooling::GameObjectPool::GameObjectPool(size_t poolSize)
Constructs a GameObjectPool with the specified capacity.
Pre-allocates internal storage for the given pool size. The pool starts empty; use `addInactive()` or a factory to populate it. poolSize The maximum number of GameObjects this pool can manage.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_, helios::engine::runtime::pooling::GameObjectPool::guid_, helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_, helios::engine::runtime::pooling::GameObjectPool::poolSize_.
helios::util::Guid helios::engine::runtime::pooling::GameObjectPool::guid() const noexcept
Returns the unique identifier of this pool.
The Guid assigned to this pool instance.
References helios::engine::runtime::pooling::GameObjectPool::guid_.
size_t helios::engine::runtime::pooling::GameObjectPool::size() const noexcept
Returns the maximum capacity of this pool.
The pool size specified at construction.
References helios::engine::runtime::pooling::GameObjectPool::poolSize_.
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive.
bool helios::engine::runtime::pooling::GameObjectPool::acquire(helios::engine::ecs::EntityHandle &entityHandle)
Acquires an inactive GameObject from the pool.
Removes a EntityHandle from the inactive list and adds it to the active tracking structures. The caller is responsible for activating the actual GameObject in the GameWorld. entityHandle Receives the EntityHandle of the acquired object on success. True if an object was acquired, false if the pool is exhausted.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_, helios::engine::runtime::pooling::GameObjectPool::activeIndex_, helios::engine::runtime::pooling::GameObjectPool::delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::ecs::types::EntityTombstone, helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_, helios::engine::ecs::EntityHandle::versionId, helios::engine::runtime::pooling::GameObjectPool::versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::isLocked() const noexcept
Checks if the pool is locked.
True if the pool is locked and ready for acquire/release operations.
References helios::engine::runtime::pooling::GameObjectPool::locked_.
void helios::engine::runtime::pooling::GameObjectPool::lock() noexcept
Locks the pool for acquire/release operations.
After locking, no more EntityHandles can be added via `addInactive()`. The sparse arrays are sized based on the min/max EntityIds added.
References helios::engine::runtime::pooling::GameObjectPool::activeIndex_, helios::engine::runtime::pooling::GameObjectPool::delta_, helios::engine::ecs::types::EntityTombstone, helios::engine::runtime::pooling::GameObjectPool::locked_, helios::engine::runtime::pooling::GameObjectPool::maxEntityId_, helios::engine::runtime::pooling::GameObjectPool::minEntityId_, helios::engine::runtime::pooling::GameObjectPool::versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::addInactive(const helios::engine::ecs::EntityHandle entityHandle)
Adds a EntityHandle to the inactive list without acquiring it.
Used during pool initialization to register pre-created GameObjects. Fails if the pool is already at capacity. entityHandle The EntityHandle of the GameObject to add. True if added successfully, false if pool is full.
References helios::engine::runtime::pooling::GameObjectPool::activeCount, helios::engine::ecs::EntityHandle::entityId, helios::engine::runtime::pooling::GameObjectPool::inactiveCount, helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_, helios::engine::ecs::EntityHandle::isValid, helios::engine::runtime::pooling::GameObjectPool::locked_, helios::engine::runtime::pooling::GameObjectPool::maxEntityId_, helios::engine::runtime::pooling::GameObjectPool::minEntityId_, helios::engine::runtime::pooling::GameObjectPool::size.
bool helios::engine::runtime::pooling::GameObjectPool::release(const helios::engine::ecs::EntityHandle entityHandle)
Releases a GameObject back to the pool by its EntityHandle.
Validates the EntityHandle against both the GameWorld and the active tracking list. Uses swap-and-pop for O(1) removal from the active list. The object is marked inactive and added to the inactive list for future acquisition. entityHandle The unique identifier of the GameObject to release. True if the object was successfully released, false if the EntityHandle was not found in the GameWorld or not tracked as active.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_, helios::engine::runtime::pooling::GameObjectPool::activeIndex_, helios::engine::runtime::pooling::GameObjectPool::delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::ecs::types::EntityTombstone, helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_, helios::engine::ecs::EntityHandle::isValid, helios::engine::ecs::EntityHandle::versionId, helios::engine::runtime::pooling::GameObjectPool::versionIndex_.
bool helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove(const helios::engine::ecs::EntityHandle entityHandle)
Releases and permanently removes a GameObject from the pool.
Unlike `release()`, this method does not add the EntityHandle back to the inactive list. Use this when a pooled object is being destroyed rather than recycled. entityHandle The unique identifier of the GameObject to remove. True if removed successfully, false if EntityHandle was not active.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_, helios::engine::runtime::pooling::GameObjectPool::activeIndex_, helios::engine::runtime::pooling::GameObjectPool::delta_, helios::engine::ecs::EntityHandle::entityId, helios::engine::ecs::types::EntityTombstone, helios::engine::ecs::EntityHandle::isValid, helios::engine::ecs::EntityHandle::versionId, helios::engine::runtime::pooling::GameObjectPool::versionIndex_.
size_t helios::engine::runtime::pooling::GameObjectPool::activeCount() const noexcept
Returns the number of active game objects.
The number of active game objects.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_.
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive.
size_t helios::engine::runtime::pooling::GameObjectPool::inactiveCount() const noexcept
Returns the number of inactive game objects.
The number of inactive game objects.
References helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_.
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive.
std::span< helios::engine::ecs::EntityHandle > helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects()
Returns a span of all inactive EntityHandles.
Span of inactive EntityHandles.
References helios::engine::runtime::pooling::GameObjectPool::inactiveGameObjects_.
std::span< helios::engine::ecs::EntityHandle > helios::engine::runtime::pooling::GameObjectPool::activeGameObjects()
Returns a span of all active EntityHandles.
Span of active EntityHandles.
References helios::engine::runtime::pooling::GameObjectPool::activeGameObjects_.