helios.engine.game.GameObject
helios::util::Guid helios::engine::game::GameObject::guid_
Unique identifier for this GameObject.
Generated during construction and remains constant for the lifetime of the object. Used for lookups in GameWorld and command targeting.
Referenced by helios::engine::game::GameObject::GameObject, helios::engine::game::GameObject::guid.
std::vector<std::unique_ptr<Component> > helios::engine::game::GameObject::components_
List of components attached to this GameObject.
Components are owned by the GameObject via std::unique_ptr.
Referenced by helios::engine::game::GameObject::add, helios::engine::game::GameObject::setActive.
std::unordered_map<std::type_index, helios::engine::game::Component*> helios::engine::game::GameObject::componentIndex_
Type-indexed map for O(1) component lookups.
Referenced by helios::engine::game::GameObject::add, helios::engine::game::GameObject::get, helios::engine::game::GameObject::has.
std::vector<Updatable*> helios::engine::game::GameObject::updatables_
Cached list of components that implement the Updatable interface.
This list is maintained for efficient iteration during the update phase. The pointers are non-owning references to elements within components_.
Referenced by helios::engine::game::GameObject::add, helios::engine::game::GameObject::update.
bool helios::engine::game::GameObject::isActive_
Active state flag for this GameObject.
Inactive GameObjects are skipped during iteration and updates. When the state changes, onActivate() or onDeactivate() is called on all components.
Referenced by helios::engine::game::GameObject::isActive, helios::engine::game::GameObject::setActive.
helios::engine::game::GameObject::GameObject()
Constructs a new GameObject with a unique Guid.
The Guid is automatically generated and remains constant for the lifetime of this object.
References helios::engine::game::GameObject::guid_.
virtual helios::engine::game::GameObject::~GameObject()=default
Virtual destructor for proper polymorphic cleanup.
T & helios::engine::game::GameObject::add(Args &&... args)
Adds a new component of type T to the GameObject.
The component is created, attached to this GameObject (onAttach is called), and if it implements Updatable, it is added to the update list. Normalizes T and uses the type-indexed componentIndex_ for O(1) lookup complexity. T The type of component to add. Must derive from Component. Args Argument types for the component's constructor. args Arguments forwarded to the component's constructor. Reference to the newly created component.
References helios::engine::game::GameObject::componentIndex_, helios::engine::game::GameObject::components_, helios::engine::game::GameObject::has, helios::engine::game::GameObject::updatables_.
Referenced by helios::engine::game::GameObject::getOrAdd.
std::remove_cvref_t< T > & helios::engine::game::GameObject::getOrAdd(Args &&... args)
Retrieves an existing component of type T, or creates and adds it if not present.
Normalizes T and uses the type-indexed componentIndex_ for O(1) lookup complexity. This is a convenience method that combines get() and add(). If the component already exists, the arguments are ignored. T The type of component to retrieve or add. Must derive from Component. Args Argument types for the component's constructor. args Arguments forwarded to the component's constructor if it needs to be created. Reference to the existing or newly created component.
References helios::engine::game::GameObject::add, helios::engine::game::GameObject::get.
std::remove_cvref_t< T > * helios::engine::game::GameObject::get() const
Retrieves a component of type T.
Normalizes T and uses the type-indexed componentIndex_ for O(1) lookup complexity. T The type of component to retrieve. Pointer to the component if found, nullptr otherwise.
References helios::engine::game::GameObject::componentIndex_.
Referenced by helios::engine::game::commands::Aim2DCommand::execute, helios::engine::game::commands::HeadingCommand::execute, helios::engine::game::commands::Move2DCommand::execute, helios::engine::game::commands::ShootCommand::execute, helios::engine::game::GameObject::getOrAdd.
bool helios::engine::game::GameObject::has() const
Checks if the GameObject has a component of type T.
Normalizes T and uses the type-indexed componentIndex_ for O(1) lookup complexity. T The type of component to check for. true if the component exists, false otherwise.
References helios::engine::game::GameObject::componentIndex_.
Referenced by helios::engine::game::GameObject::add.
void helios::engine::game::GameObject::update(helios::engine::game::UpdateContext &updateContext)
Updates all updatable components attached to this GameObject.
updateContext Context containing frame delta time and other update data.
References helios::engine::game::GameObject::updatables_.
const helios::util::Guid & helios::engine::game::GameObject::guid() const noexcept
Returns the unique identifier for this GameObject.
Const reference to the Guid, valid for the lifetime of this object.
References helios::engine::game::GameObject::guid_.
Referenced by helios::engine::game::GameObjectPool::release.
bool helios::engine::game::GameObject::isActive() const noexcept
Checks if this GameObject is currently active.
True if the GameObject is active, false otherwise. Inactive GameObjects are typically skipped during updates and rendering.
References helios::engine::game::GameObject::isActive_.
void helios::engine::game::GameObject::setActive(bool active) noexcept
Sets the active state of this GameObject.
When the active state changes, this method notifies all attached components by calling onActivate() or onDeactivate() accordingly. If the new state equals the current state, no action is taken. active The new active state.
References helios::engine::game::GameObject::components_, helios::engine::game::GameObject::isActive_.