helios.engine.mechanics.gamestate.types.GameStateTransitionRule
using helios::engine::mechanics::gamestate::types::GuardCallback = bool(*)( helios::engine::runtime::world::UpdateContext&, GameStateTransitionRequest )
Function pointer type for transition guard callbacks.
updateContext The current update context. request The transition request being evaluated. True if the transition should proceed.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::from_
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionId_
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::to_
GameStateTransitionType helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionType_
GuardCallback helios::engine::mechanics::gamestate::types::GameStateTransitionRule::guard_
helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule(const GameState from, const GameStateTransitionId transitionId, const GameState to, const GameStateTransitionType transitionType, GuardCallback guard=nullptr)
Constructs a transition rule.
from The source state. transitionId The transition identifier. to The target state. transitionType The type of transition. guard Optional guard callback.
References helios::engine::mechanics::gamestate::types::GameStateTransitionRule::from, helios::engine::mechanics::gamestate::types::GameStateTransitionRule::guard, helios::engine::mechanics::gamestate::types::GameStateTransitionRule::to, helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionId, helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionType.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::from() const noexcept
Returns the source state.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionRule::to() const noexcept
Returns the target state.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule.
GameStateTransitionType helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionType() const noexcept
Returns the transition type.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule.
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionRule::transitionId() const noexcept
Returns the transition identifier.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule.
GuardCallback helios::engine::mechanics::gamestate::types::GameStateTransitionRule::guard() const noexcept
Returns the guard callback, or nullptr if none.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionRule::GameStateTransitionRule.