helios.rendering.text.TextMesh
helios::engine::core::data::FontId helios::rendering::text::TextMesh::fontId_
Font identifier for glyph lookup.
std::string helios::rendering::text::TextMesh::text_
The text string to render.
bool helios::rendering::text::TextMesh::needsUpdate_
Flag indicating whether the cached layout needs recomputation.
TextLayout helios::rendering::text::TextMesh::textLayout_
Cached layout data (AABB and vertices).
TypeSetter helios::rendering::text::TextMesh::typeSetter_
TypeSetter instance for computing text layout.
float helios::rendering::text::TextMesh::fontScale_
The scale factor for the font.
void helios::rendering::text::TextMesh::updateCache(FontResourceProvider &fontResourceProvider) const
Updates the cached layout if needed.
fontResourceProvider Provider for glyph data.
helios::rendering::text::TextMesh::TextMesh(std::string text, const float fontScale, const helios::engine::core::data::FontId fontId) noexcept
Constructs a TextMesh with the given text and font.
text The text string to render. fontScale The scale of the font, relative to the pixelHeight it was loaded with. fontId The font identifier for glyph lookup.
References helios::rendering::text::TextMesh::fontId, helios::rendering::text::TextMesh::fontScale, helios::rendering::text::TextMesh::text.
const helios::math::aabbf & helios::rendering::text::TextMesh::localAABB(FontResourceProvider &fontResourceProvider) const noexcept
Returns the local-space axis-aligned bounding box.
Triggers layout computation if the cache is invalid. fontResourceProvider Provider for glyph data. Reference to the cached AABB.
std::span< helios::math::vec4f > helios::rendering::text::TextMesh::vertices(FontResourceProvider &fontResourceProvider) const noexcept
Returns the vertex data for rendering.
Each glyph is represented as 6 vertices (2 triangles). Triggers layout computation if the cache is invalid. fontResourceProvider Provider for glyph data. A span of vertex data (x, y, texU, texV per vertex).
void helios::rendering::text::TextMesh::setText(std::string text) noexcept
Updates the text string.
Invalidates the cached layout, which will be recomputed on the next call to `vertices()` or `localAABB()`. text The new text to render.
References helios::rendering::text::TextMesh::text.
std::string_view helios::rendering::text::TextMesh::text() const noexcept
Returns the current text string.
View of the text string.
Referenced by helios::rendering::text::TextMesh::setText, helios::rendering::text::TextMesh::TextMesh.
void helios::rendering::text::TextMesh::setFontScale(const float scale) noexcept
Sets the font scale factor.
Invalidates the cached layout, which will be recomputed on the next call to `vertices()` or `localAABB()`. scale The new scale factor relative to the font's pixel height.
float helios::rendering::text::TextMesh::fontScale() const noexcept
Returns the current font scale factor.
The scale factor relative to the font's pixel height.
Referenced by helios::rendering::text::TextMesh::TextMesh.
bool helios::rendering::text::TextMesh::needsUpdate() const noexcept
Checks if the cached layout needs recomputation.
True if the layout is invalid and needs to be recomputed.
helios::engine::core::data::FontId helios::rendering::text::TextMesh::fontId() const noexcept
Returns the font identifier.
The font ID used for glyph lookup.
Referenced by helios::rendering::text::TextMesh::TextMesh.