helios.engine.game.GameWorld
std::unordered_map<helios::util::Guid, std::unique_ptr<GameObject> > helios::engine::game::GameWorld::gameObjects_
Hash map storing all active GameObjects, indexed by their Guid.
Uses std::unordered_map for O(1) average-case lookup performance. The map owns all GameObjects via std::unique_ptr.
const helios::util::log::Logger& helios::engine::game::GameWorld::logger_
The logger used with this GameWorld instance.
Defaults to HELIOS_LOG_SCOPE.
helios::scene::Scene* helios::engine::game::GameWorld::scene_
Pointer to the Scene for scene graph integration.
Non-owning pointer; may be nullptr if scene integration is not required.
std::vector<std::unique_ptr<System> > helios::engine::game::GameWorld::systems_
Vector storing all registered Systems.
Systems are updated in order of registration after all GameObjects have been updated.
Referenced by helios::engine::game::GameWorld::add, helios::engine::game::GameWorld::get.
helios::engine::game::GameWorld::GameWorld(helios::scene::Scene *scene) noexcept
Constructs a GameWorld with a reference to the scene graph.
scene Pointer to the Scene used for scene graph integration. May be nullptr if scene graph integration is not required.
References helios::engine::game::GameWorld::scene.
const helios::scene::Scene * helios::engine::game::GameWorld::scene() const noexcept
Returns the scene graph associated with this GameWorld.
Const pointer to the Scene, or nullptr if not set.
Referenced by helios::engine::game::GameWorld::GameWorld.
T & helios::engine::game::GameWorld::add(Args &&... args)
Adds a System to the GameWorld.
Creates a System of the specified type with the given constructor arguments, invokes its `onAdd()` callback, and registers it with this GameWorld. Systems are updated each frame after GameObjects. T The System type to add. Must derive from System. Args Constructor argument types. args Arguments forwarded to the System constructor. Reference to the newly added System. The GameWorld takes ownership of the System.
References helios::engine::game::GameWorld::add, helios::engine::game::GameWorld::systems_.
Referenced by helios::engine::game::GameWorld::add.
T * helios::engine::game::GameWorld::get() const
Retrieves a System of the specified type.
Searches through all registered Systems using dynamic_cast to find a matching type. T The System type to retrieve. Must derive from System. Pointer to the System if found, nullptr otherwise. Uses dynamic_cast internally; consider type-based registry for performance-critical paths.
References helios::engine::game::GameWorld::systems_.
Referenced by helios::engine::game::GameWorld::has.
bool helios::engine::game::GameWorld::has() const
Checks if a System of the specified type is registered.
T The System type to check for. Must derive from System. True if a System of type T exists, false otherwise.
References helios::engine::game::GameWorld::get.
void helios::engine::game::GameWorld::update(helios::engine::game::UpdateContext &updateContext) const noexcept
Updates all GameObjects in the world for the current frame.
updateContext Context containing deltaTime, input snapshot, game world and command buffer. Iterates through all registered GameObjects and invokes their update() method. The order of updates is not guaranteed due to the underlying unordered_map storage. This method is noexcept; individual GameObject::update() implementations should handle their own exceptions to prevent propagation.
helios::engine::game::GameObject * helios::engine::game::GameWorld::addGameObject(std::unique_ptr< GameObject > gameObject)
Adds a GameObject to the world and transfers ownership.
gameObject The GameObject to add. Ownership is transferred to the GameWorld. Pointer to the added GameObject, or nullptr if addition failed. GameObject* Non-owning pointer to the added object (valid until removed) nullptr If gameObject was null or a GameObject with the same Guid already exists The GameWorld takes ownership of the GameObject. The returned pointer remains valid until the GameObject is removed from the world. Attempting to add a nullptr or a GameObject with a duplicate Guid will fail, return nullptr, and log a warning.
helios::engine::game::GameObject * helios::engine::game::GameWorld::find(const helios::util::Guid &guid)
Finds a GameObject by its unique identifier.
guid The unique identifier of the GameObject to find. Pointer to the GameObject if found, nullptr otherwise. GameObject* Non-owning pointer to the found object nullptr If no GameObject with the specified Guid exists This is the non-const overload. Use the const overload for read-only access.
const helios::engine::game::GameObject * helios::engine::game::GameWorld::find(const helios::util::Guid &guid) const
Finds a GameObject by its unique identifier (const overload).
guid The unique identifier of the GameObject to find. Const pointer to the GameObject if found, nullptr otherwise. const GameObject* Non-owning const pointer to the found object nullptr If no GameObject with the specified Guid exists This overload is used when the GameWorld is accessed via const reference.
std::unique_ptr< helios::engine::game::GameObject > helios::engine::game::GameWorld::removeGameObject(const GameObject &gameObject)
Removes a GameObject from the world and transfers ownership to the caller.
gameObject Reference to the GameObject to remove. Unique pointer to the removed GameObject, or nullptr if not found. std::unique_ptr<GameObject> Ownership of the removed object nullptr If the GameObject was not found in the world After successful removal, all non-owning pointers to the GameObject become invalid unless the caller maintains the returned unique_ptr. Attempting to remove a GameObject that doesn't exist returns nullptr and logs a warning.