helios.engine.game.Component
GameObject* helios::engine::game::Component::gameObject_
Non-owning pointer to the owning GameObject.
Set by onAttach() when the component is added to a GameObject. nullptr until attached.
Referenced by helios::engine::game::Component::gameObject, helios::engine::game::Component::onAttach.
bool helios::engine::game::Component::isEnabled_
Boolean flag indicating whether this component is enabled.
Referenced by helios::engine::game::Component::disable, helios::engine::game::Component::enable, helios::engine::game::Component::isDisabled, helios::engine::game::Component::isEnabled.
virtual helios::engine::game::Component::~Component()=default
Virtual destructor for proper polymorphic cleanup.
helios::engine::game::Component::Component()=default
Default constructor.
Referenced by helios::engine::game::components::physics::LevelBoundsBehaviorComponent::LevelBoundsBehaviorComponent, helios::engine::game::components::rendering::RenderableComponent::RenderableComponent.
virtual void helios::engine::game::Component::onAttach(GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
gameObject Pointer to the owning GameObject. Derived classes that override this method should call the base implementation to ensure gameObject_ is set correctly.
References helios::engine::game::Component::gameObject, helios::engine::game::Component::gameObject_.
Referenced by helios::engine::game::components::gameplay::ShootComponent::onAttach, helios::engine::game::components::physics::ScaleComponent::onAttach, helios::engine::game::components::rendering::RenderableComponent::onAttach, helios::engine::game::components::scene::SceneNodeComponent::onAttach.
bool helios::engine::game::Component::isEnabled() const noexcept
Checks whether the component is enabled.
An enabled component is expected to actively participate in the GameObject's lifecycle, such as rendering, updating, or responding to events. A disabled component is effectively ignored in these processes. true if the component is enabled, false otherwise.
References helios::engine::game::Component::isEnabled_.
Referenced by helios::engine::game::systems::physics::GridCollisionDetectionSystem::update.
bool helios::engine::game::Component::isDisabled() const noexcept
Checks whether the component is disabled.
Inverse of isEnabled() true if the component is disabled, false otherwise.
References helios::engine::game::Component::isEnabled_.
void helios::engine::game::Component::enable() noexcept
Enables this component.
References helios::engine::game::Component::isEnabled_.
void helios::engine::game::Component::disable() noexcept
Disables this component.
References helios::engine::game::Component::isEnabled_.
virtual void helios::engine::game::Component::onActivate() noexcept
Called when the owning GameObject becomes active.
Override this method to perform initialization or state restoration when the GameObject is activated. The default implementation does nothing.
virtual void helios::engine::game::Component::onDeactivate() noexcept
Called when the owning GameObject becomes inactive.
Override this method to perform cleanup or state preservation when the GameObject is deactivated. The default implementation does nothing.
GameObject * helios::engine::game::Component::gameObject() const noexcept
Returns the owning GameObject.
Non-owning pointer to the GameObject, or nullptr if not attached.
References helios::engine::game::Component::gameObject_.
Referenced by helios::engine::game::Component::onAttach, helios::engine::game::components::gameplay::ShootComponent::onAttach, helios::engine::game::components::physics::ScaleComponent::onAttach, helios::engine::game::components::rendering::RenderableComponent::onAttach, helios::engine::game::components::scene::SceneNodeComponent::onAttach, helios::engine::game::components::input::TwinStickInputComponent::update.