helios.input.gamepad.GamepadState
const helios::util::log::Logger& helios::input::gamepad::GamepadState::logger_
Shared logger instance for all GamepadState objects.
bool helios::input::gamepad::GamepadState::buttonA_
State of the A button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonB_
State of the B button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonX_
State of the X button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonY_
State of the Y button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonStart_
State of the Start button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonBack_
State of the Back button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonGuide_
State of the Guide button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonLeftBumper_
State of the left bumper button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonRightBumper_
State of the right bumper button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonLeftThumb_
State of the left thumbstick button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonRightThumb_
State of the right thumbstick button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonDpadUp_
State of the D-pad up button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonDpadRight_
State of the D-pad right button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonDpadDown_
State of the D-pad down button (true if pressed).
bool helios::input::gamepad::GamepadState::buttonDpadLeft_
State of the D-pad left button (true if pressed).
bool helios::input::gamepad::GamepadState::needsUpdate_
Flag to indicate if the cached vec2f members need to be recalculated.
float helios::input::gamepad::GamepadState::axisLeftX_
Raw float value of the left stick's x-axis.
float helios::input::gamepad::GamepadState::axisLeftY_
Raw float value of the left stick's y-axis.
float helios::input::gamepad::GamepadState::axisRightX_
Raw float value of the right stick's x-axis.
float helios::input::gamepad::GamepadState::axisRightY_
Raw float value of the right stick's y-axis.
float helios::input::gamepad::GamepadState::triggerLeft_
Raw float value of the left trigger.
float helios::input::gamepad::GamepadState::triggerRight_
Raw float value of the right trigger.
helios::math::vec2f helios::input::gamepad::GamepadState::left_
Cached vec2f representation of the left stick (x, y).
helios::math::vec2f helios::input::gamepad::GamepadState::right_
Cached vec2f representation of the right stick (x, y).
helios::math::vec2f helios::input::gamepad::GamepadState::trigger_
Cached vec2f representation of the triggers (left, right).
void helios::input::gamepad::GamepadState::update() const noexcept
Internal method to update the cached vec2f representations. This method should be called when the current values of the axes are queried in vec2f form and `needsUpdate_` evaluates to `true`.
helios::input::gamepad::GamepadState::~GamepadState()=default
helios::input::gamepad::GamepadState::GamepadState()=default
Default constructor.
Initializes all the values with 0.0f.
helios::input::gamepad::GamepadState::GamepadState(float axisLeftX, float axisLeftY, float axisRightX, float axisRightY, float triggerLeft, float triggerRight, bool buttonA, bool buttonB, bool buttonX, bool buttonY, bool buttonStart, bool buttonBack, bool buttonGuide, bool buttonLeftBumper, bool buttonRightBumper, bool buttonLeftThumb, bool buttonRightThumb, bool buttonDpadUp, bool buttonDpadRight, bool buttonDpadDown, bool buttonDpadLeft) noexcept
Creates a new GamepadState object.
Delegates to `updateAxes` for value initialization. updateAxes
References helios::input::gamepad::GamepadState::buttonA, helios::input::gamepad::GamepadState::buttonB, helios::input::gamepad::GamepadState::buttonBack, helios::input::gamepad::GamepadState::buttonDpadDown, helios::input::gamepad::GamepadState::buttonDpadLeft, helios::input::gamepad::GamepadState::buttonDpadRight, helios::input::gamepad::GamepadState::buttonDpadUp, helios::input::gamepad::GamepadState::buttonGuide, helios::input::gamepad::GamepadState::buttonLeftBumper, helios::input::gamepad::GamepadState::buttonLeftThumb, helios::input::gamepad::GamepadState::buttonRightBumper, helios::input::gamepad::GamepadState::buttonRightThumb, helios::input::gamepad::GamepadState::buttonStart, helios::input::gamepad::GamepadState::buttonX, helios::input::gamepad::GamepadState::buttonY, helios::input::gamepad::GamepadState::triggerLeft, helios::input::gamepad::GamepadState::triggerRight, helios::input::gamepad::GamepadState::updateAxes.
void helios::input::gamepad::GamepadState::updateAxes(float axisLeftX, float axisLeftY, float axisRightX, float axisRightY, float triggerLeft, float triggerRight, bool buttonA, bool buttonB, bool buttonX, bool buttonY, bool buttonStart, bool buttonBack, bool buttonGuide, bool buttonLeftBumper, bool buttonRightBumper, bool buttonLeftThumb, bool buttonRightThumb, bool buttonDpadUp, bool buttonDpadRight, bool buttonDpadDown, bool buttonDpadLeft) noexcept
Updates the axes and button states of this GamepadState object.
This method updates raw axis and trigger values and stores the boolean state of all standard gamepad buttons. Float parameters are asserted to be in their expected ranges and then clamped. For the sticks' range [-1, 1] the following holds: -1 means moved all the way left/down, 0 means not moved at all, 1 means moved all the way right/up. For the triggers' range of [0, 1] the following holds: 0 means not pressed, 1 means fully pressed. axisLeftX The x-axis of the left stick, expected in [-1, 1]. axisLeftY The y-axis of the left stick, expected in [-1, 1]. axisRightX The x-axis of the right stick, expected in [-1, 1]. axisRightY The y-axis of the right stick, expected in [-1, 1]. triggerLeft The left trigger value, expected in [0, 1]. triggerRight The right trigger value, expected in [0, 1]. buttonA True if the A button is pressed. buttonB True if the B button is pressed. buttonX True if the X button is pressed. buttonY True if the Y button is pressed. buttonStart True if the Start button is pressed. buttonBack True if the Back button is pressed. buttonGuide True if the Guide (platform) button is pressed. buttonLeftBumper True if the left bumper is pressed. buttonRightBumper True if the right bumper is pressed. buttonLeftThumb True if the left thumbstick button is pressed. buttonRightThumb True if the right thumbstick button is pressed. buttonDpadUp True if the D-pad Up button is pressed. buttonDpadRight True if the D-pad Right button is pressed. buttonDpadDown True if the D-pad Down button is pressed. buttonDpadLeft True if the D-pad Left button is pressed.
References helios::input::gamepad::GamepadState::buttonA, helios::input::gamepad::GamepadState::buttonB, helios::input::gamepad::GamepadState::buttonBack, helios::input::gamepad::GamepadState::buttonDpadDown, helios::input::gamepad::GamepadState::buttonDpadLeft, helios::input::gamepad::GamepadState::buttonDpadRight, helios::input::gamepad::GamepadState::buttonDpadUp, helios::input::gamepad::GamepadState::buttonGuide, helios::input::gamepad::GamepadState::buttonLeftBumper, helios::input::gamepad::GamepadState::buttonLeftThumb, helios::input::gamepad::GamepadState::buttonRightBumper, helios::input::gamepad::GamepadState::buttonRightThumb, helios::input::gamepad::GamepadState::buttonStart, helios::input::gamepad::GamepadState::buttonX, helios::input::gamepad::GamepadState::buttonY, helios::input::gamepad::GamepadState::triggerLeft, helios::input::gamepad::GamepadState::triggerRight.
Referenced by helios::input::gamepad::GamepadState::GamepadState.
float helios::input::gamepad::GamepadState::leftX() const noexcept
Returns the current value of the left stick's x-axis.
float value in the range [-1, 1]
float helios::input::gamepad::GamepadState::leftY() const noexcept
Returns the current value of the left stick's y-axis.
float value in the range [-1, 1]
float helios::input::gamepad::GamepadState::rightX() const noexcept
Returns the current value of the right stick's x-axis.
float value in the range [-1, 1]
float helios::input::gamepad::GamepadState::rightY() const noexcept
Returns the current value of the right stick's y-axis.
float value in the range [-1, 1]
float helios::input::gamepad::GamepadState::triggerLeft() const noexcept
Returns the current value of the left trigger.
float value in the range [0, 1]
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
float helios::input::gamepad::GamepadState::triggerRight() const noexcept
Returns the current value of the right trigger.
float value in the range [0, 1]
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
helios::math::vec2f helios::input::gamepad::GamepadState::left() const noexcept
Returns the state of the left stick as a helios::math::vec2f.
A helios::math::vec2f, with the first component being the x-axis, the second component the y-axis.
helios::math::vec2f helios::input::gamepad::GamepadState::right() const noexcept
Returns the state of the right stick as a helios::math::vec2f.
A helios::math::vec2f, with the first component being the x-axis, the second component the y-axis.
helios::math::vec2f helios::input::gamepad::GamepadState::trigger() const noexcept
Returns the state of the triggers as a helios::math::vec2f.
A helios::math::vec2f, with the first component being the left trigger-axis, the second component the right trigger-axis.
bool helios::input::gamepad::GamepadState::buttonA() const noexcept
Returns true when the A button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonB() const noexcept
Returns true when the B button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonX() const noexcept
Returns true when the X button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonY() const noexcept
Returns true when the Y button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonStart() const noexcept
Returns true when the Start button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonBack() const noexcept
Returns true when the Back button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonGuide() const noexcept
Returns true when the Guide button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonLeftBumper() const noexcept
Returns true when the left bumper is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonRightBumper() const noexcept
Returns true when the right bumper is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonLeftThumb() const noexcept
Returns true when the left thumbstick button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonRightThumb() const noexcept
Returns true when the right thumbstick button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonDpadUp() const noexcept
Returns true when the D-pad Up button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonDpadRight() const noexcept
Returns true when the D-pad Right button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonDpadDown() const noexcept
Returns true when the D-pad Down button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.
bool helios::input::gamepad::GamepadState::buttonDpadLeft() const noexcept
Returns true when the D-pad Left button is pressed.
true if pressed, false otherwise.
Referenced by helios::input::gamepad::GamepadState::GamepadState, helios::input::gamepad::GamepadState::updateAxes.