helios.engine.modules.spatial.transform.components.ScaleStateComponent
float helios::engine::modules::spatial::transform::components::ScaleStateComponent::width_
Width of the entity.
float helios::engine::modules::spatial::transform::components::ScaleStateComponent::height_
Height of the entity.
float helios::engine::modules::spatial::transform::components::ScaleStateComponent::depth_
Depth of the entity.
helios::core::units::Unit helios::engine::modules::spatial::transform::components::ScaleStateComponent::unit_
Unit of measurement for the dimensions.
bool helios::engine::modules::spatial::transform::components::ScaleStateComponent::isDirty_
Flag indicating if the scale has changed.
bool helios::engine::modules::spatial::transform::components::ScaleStateComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::spatial::transform::components::ScaleStateComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::enable() noexcept
Enables this component.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::disable() noexcept
Disables this component.
helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent(const float width, const float height, const float depth, const helios::core::units::Unit unit)
Constructs a ScaleStateComponent with specified dimensions and unit.
width Width of the entity. height Height of the entity. depth Depth of the entity. unit Unit of measurement (default: Meter).
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::unit.
Referenced by helios::engine::modules::spatial::transform::components::ScaleStateComponent::operator=, helios::engine::modules::spatial::transform::components::ScaleStateComponent::operator=, helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent, helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent.
helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent(const helios::math::vec3f scale, const helios::core::units::Unit unit=helios::core::units::Unit::Meter)
References helios::core::units::Meter, helios::engine::modules::spatial::transform::components::ScaleStateComponent::unit.
helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent(const ScaleStateComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent.
ScaleStateComponent & helios::engine::modules::spatial::transform::components::ScaleStateComponent::operator=(const ScaleStateComponent &)=default
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent.
helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent(ScaleStateComponent &&) noexcept=default
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent.
ScaleStateComponent & helios::engine::modules::spatial::transform::components::ScaleStateComponent::operator=(ScaleStateComponent &&) noexcept=default
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::onAcquire() noexcept
Resets the dirty flag to true when acquired.
Makes sure scaling is considered once the component was acquired.
References helios::engine::modules::spatial::transform::components::ScaleStateComponent::onAcquire.
Referenced by helios::engine::modules::spatial::transform::components::ScaleStateComponent::onAcquire.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::onRelease() noexcept
Resets the dirty flag to true when released.
Makes sure the entities dirty-state is reset to the default state.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::clearDirty() noexcept
Clears the dirty flag.
bool helios::engine::modules::spatial::transform::components::ScaleStateComponent::isDirty() const noexcept
Checks if the scale has changed.
True if dirty, false otherwise.
helios::core::units::Unit helios::engine::modules::spatial::transform::components::ScaleStateComponent::unit() const noexcept
Retrieves the unit of measurement.
The unit enum value.
Referenced by helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent, helios::engine::modules::spatial::transform::components::ScaleStateComponent::ScaleStateComponent, helios::engine::modules::spatial::transform::components::ScaleStateComponent::setScale.
helios::math::vec3f helios::engine::modules::spatial::transform::components::ScaleStateComponent::scaling() const noexcept
Retrieves the scaling vector (width, height, depth).
A vec3f containing the dimensions.
void helios::engine::modules::spatial::transform::components::ScaleStateComponent::setScale(const float width, const float height, const float depth, const helios::core::units::Unit unit=helios::core::units::Unit::Meter) noexcept
Sets the dimensions and unit of the entity.
width New width. height New height. depth New depth. unit New unit of measurement (default: Meter).
References helios::core::units::Meter, helios::engine::modules::spatial::transform::components::ScaleStateComponent::unit.