helios.engine.game.event.TriggerCollisionEvent
const helios::engine::game::GameObject* helios::engine::game::event::TriggerCollisionEvent::source_
The GameObject that entered the trigger volume.
const helios::engine::game::GameObject* helios::engine::game::event::TriggerCollisionEvent::match_
The trigger volume GameObject that was entered.
const helios::math::vec3f helios::engine::game::event::TriggerCollisionEvent::contact_
The world-space contact point where the trigger was activated.
helios::engine::game::event::TriggerCollisionEvent::TriggerCollisionEvent(const helios::engine::game::GameObject *source, const helios::engine::game::GameObject *match, const helios::math::vec3f contact)
Constructs a TriggerCollisionEvent.
source The GameObject that entered the trigger. match The trigger volume GameObject. contact The world-space position where the trigger was activated.
References helios::engine::game::event::TriggerCollisionEvent::contact, helios::engine::game::event::TriggerCollisionEvent::match, helios::engine::game::event::TriggerCollisionEvent::source.
helios::math::vec3f helios::engine::game::event::TriggerCollisionEvent::contact() const noexcept
Returns the contact point in world space.
The 3D position where the trigger was activated.
Referenced by helios::engine::game::event::TriggerCollisionEvent::TriggerCollisionEvent.
const helios::engine::game::GameObject * helios::engine::game::event::TriggerCollisionEvent::source() const noexcept
Returns the source GameObject.
Non-owning pointer to the GameObject that entered the trigger.
Referenced by helios::engine::game::event::TriggerCollisionEvent::TriggerCollisionEvent.
const helios::engine::game::GameObject * helios::engine::game::event::TriggerCollisionEvent::match() const noexcept
Returns the trigger volume GameObject.
Non-owning pointer to the trigger volume that was entered.
Referenced by helios::engine::game::event::TriggerCollisionEvent::TriggerCollisionEvent.