helios.rendering.RenderQueue
std::vector<std::unique_ptr<const helios::rendering::RenderCommand> > helios::rendering::RenderQueue::renderCommands_
Stores the unique ptrs to the RenderCommand objects of this queue.
Referenced by helios::rendering::RenderQueue::add, helios::rendering::RenderQueue::clear, helios::rendering::RenderQueue::renderCommands, helios::rendering::RenderQueue::renderCommandsSize.
std::vector<helios::rendering::text::TextRenderCommand> helios::rendering::RenderQueue::textRenderCommands_
Stores text render commands for glyph-based text rendering.
Referenced by helios::rendering::RenderQueue::add, helios::rendering::RenderQueue::clear, helios::rendering::RenderQueue::textRenderCommands, helios::rendering::RenderQueue::textRenderCommandsSize.
const helios::util::log::Logger& helios::rendering::RenderQueue::logger_
Shared logger instance for all RenderQueue objects.
Referenced by helios::rendering::RenderQueue::add.
helios::rendering::RenderQueue::~RenderQueue()=default
helios::rendering::RenderQueue::RenderQueue(const RenderQueue &)=delete
Delete copy constructor.
References helios::rendering::RenderQueue::RenderQueue.
Referenced by helios::rendering::RenderQueue::operator=, helios::rendering::RenderQueue::operator=, helios::rendering::RenderQueue::RenderQueue, helios::rendering::RenderQueue::RenderQueue, helios::rendering::RenderQueue::RenderQueue.
RenderQueue & helios::rendering::RenderQueue::operator=(const RenderQueue &)=delete
Delete copy assignment operator.
References helios::rendering::RenderQueue::RenderQueue.
helios::rendering::RenderQueue::RenderQueue(RenderQueue &&) noexcept=delete
Delete move constructor.
References helios::rendering::RenderQueue::RenderQueue.
RenderQueue & helios::rendering::RenderQueue::operator=(RenderQueue &&) noexcept=delete
Delete move assignment operator.
References helios::rendering::RenderQueue::RenderQueue.
helios::rendering::RenderQueue::RenderQueue()=default
Constructs a new empty RenderQueue.
References helios::rendering::RenderQueue::RenderQueue.
void helios::rendering::RenderQueue::add(std::unique_ptr< const helios::rendering::RenderCommand > renderCommand)
Adds a `RenderCommand` to this `RenderQueue`. Ownership of the `RenderCommand` is transferred to this `RenderQueue`.
renderCommand A unique_ptr to the RenderCommand. This instance takes ownership of the RenderCommand. Todoprevent adding renderables while rendering
References helios::rendering::RenderQueue::add, helios::rendering::RenderQueue::logger_, helios::rendering::RenderQueue::renderCommands_.
Referenced by helios::rendering::RenderQueue::add, helios::rendering::RenderPassFactory::populateRenderQueue.
void helios::rendering::RenderQueue::add(helios::rendering::text::TextRenderCommand renderCommand)
Adds a `TextRenderCommand` to this `RenderQueue`.
The command is moved into the queue. Text commands are processed separately from geometry commands during rendering. renderCommand The text render command to add (moved).
References helios::rendering::RenderQueue::textRenderCommands_.
const std::vector< std::unique_ptr< const helios::rendering::RenderCommand > > & helios::rendering::RenderQueue::renderCommands() const noexcept
Returns a const ref to the internal vector of `RenderCommand`.
A const ref to the list of `RenderCommand`s of this queue.
References helios::rendering::RenderQueue::renderCommands_.
const std::vector< helios::rendering::text::TextRenderCommand > & helios::rendering::RenderQueue::textRenderCommands() const noexcept
Returns a const ref to the internal vector of `TextRenderCommand`.
A const ref to the list of text render commands in this queue.
References helios::rendering::RenderQueue::textRenderCommands_.
void helios::rendering::RenderQueue::clear()
Clears all `RenderCommand` objects from the queue.
This prepares this queue to be reused in a new rendering pass.
References helios::rendering::RenderQueue::renderCommands_, helios::rendering::RenderQueue::textRenderCommands_.
Referenced by helios::rendering::RenderPassFactory::populateRenderQueue.
size_t helios::rendering::RenderQueue::renderCommandsSize() const noexcept
Returns the number of `RenderCommand`s this queue contains.
The number of RenderCommands in this queue.
References helios::rendering::RenderQueue::renderCommands_.
size_t helios::rendering::RenderQueue::textRenderCommandsSize() const noexcept
Returns the number of `TextRenderCommand`s this queue contains.
The number of text render commands in this queue.
References helios::rendering::RenderQueue::textRenderCommands_.