helios.engine.game.components.scene.SceneNodeComponent
const helios::math::vec3f helios::engine::game::components::scene::SceneNodeComponent::canonicalSize_
Original mesh dimensions from the SceneNode's AABB.
Used as reference for setSize() calculations. Defaults to (1,1,1) if no renderable or mesh is available.
Referenced by helios::engine::game::components::scene::SceneNodeComponent::SceneNodeComponent, helios::engine::game::components::scene::SceneNodeComponent::setSize.
helios::scene::SceneNode* helios::engine::game::components::scene::SceneNodeComponent::sceneNode_
Non-owning pointer to the associated SceneNode.
Referenced by helios::engine::game::components::scene::SceneNodeComponent::rotation, helios::engine::game::components::scene::SceneNodeComponent::scaling, helios::engine::game::components::scene::SceneNodeComponent::sceneNode, helios::engine::game::components::scene::SceneNodeComponent::SceneNodeComponent, helios::engine::game::components::scene::SceneNodeComponent::setRotation, helios::engine::game::components::scene::SceneNodeComponent::setScale, helios::engine::game::components::scene::SceneNodeComponent::setTranslation, helios::engine::game::components::scene::SceneNodeComponent::translation.
helios::engine::game::components::scene::SceneNodeComponent::SceneNodeComponent(helios::scene::SceneNode *sceneNode)
Constructs a SceneNodeComponent linked to a SceneNode.
sceneNode Pointer to the SceneNode to control. Must not be nullptr.
References helios::engine::game::components::scene::SceneNodeComponent::canonicalSize_, helios::engine::game::components::scene::SceneNodeComponent::sceneNode, helios::engine::game::components::scene::SceneNodeComponent::sceneNode_.
Referenced by helios::engine::game::components::scene::SceneNodeComponent::setRotation, helios::engine::game::components::scene::SceneNodeComponent::setScale, helios::engine::game::components::scene::SceneNodeComponent::setSize, helios::engine::game::components::scene::SceneNodeComponent::setTranslation.