helios.engine.modules.physics.collision.systems.GridCollisionDetectionSystem
bool helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::isSolidCollision
bool helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::isTriggerCollision
bool helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::aIsCollisionReporter
bool helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::bIsCollisionReporter
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::aCollisionBehavior
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::bCollisionBehavior
helios::engine::ecs::GameObject* helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionCandidate::gameObject
Pointer to the GameObject entity.
AabbColliderComponent* helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionCandidate::aabbColliderComponent
Pointer to the AABB collider component providing world-space bounds.
CollisionComponent* helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionCandidate::collisionComponent
Pointer to the collision component defining layer masks and collision behavior.
CollisionStateComponent* helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionCandidate::collisionStateComponent
Pointer to the collision state component for storing collision results.
std::vector<CollisionCandidate> helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::GridCell::collisionCandidates
List of collision candidates currently occupying this cell.
const auto& helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::logger_
Scoped logger instance for structured logging within the current context.
std::unordered_set<std::pair<helios::util::Guid, helios::util::Guid>, GuidPairHash> helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solvedCollisions_
Set of already-processed collision pairs to avoid duplicate events.
Stores pairs of GUIDs in canonical order (smaller GUID first) to ensure each collision pair is processed only once per frame, even when entities span multiple cells.
float helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellSize_
Size of each grid cell in world units.
helios::math::aabbf helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::gridBounds_
World-space bounds defining the spatial region covered by the grid.
std::vector<GridCell> helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cells_
Flat storage for all grid cells, indexed as x + y * cellsX + z * (cellsX * cellsY).
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsX_
Number of cells along the X axis.
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsY_
Number of cells along the Y axis.
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsZ_
Number of cells along the Z axis.
std::vector<size_t> helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::trackedCells_
Helper to keep track of updated cells (with potential collisions candidates) in one pass.
bool helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::CollisionStruct::hasAnyInteraction() const noexcept
std::size_t helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::GuidPairHash::operator()(const std::pair< helios::util::Guid, helios::util::Guid > &pair) const
Computes a hash value for a GUID pair.
pair The pair of GUIDs to hash. A combined hash value for both GUIDs.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::GridCell::clear()
Clears all candidates from this cell.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::initGrid()
Initializes the grid based on world bounds and cell size.
Computes the number of cells needed in each dimension and allocates the cell storage.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::prepareCollisionDetection()
Prepares the grid for a new collision detection pass.
Clears all collision candidates from every cell and resets the set of already-solved collision pairs.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::postEvent(const helios::engine::ecs::GameObject *candidate, const helios::engine::ecs::GameObject *match, const helios::math::vec3f contact, const CollisionStruct collisionStruct, const helios::engine::runtime::world::UpdateContext &updateContext, CollisionStateComponent *csc_a, CollisionStateComponent *csc_b) const noexcept
Posts collision events to the UpdateContext's event sink.
Updates the CollisionStateComponent of both entities with collision information including contact point, collision type, behavior, and reporter status. An entity marked as collision reporter receives the event as the "source" entity. candidate First collision candidate (potential event source). match Second collision candidate (collision partner). contact The contact point between the two AABBs. collisionStruct Struct containing collision type and behavior information. updateContext Context for pushing events to the event queue. csc_a Collision state component of the first entity. csc_b Collision state component of the second entity.
CollisionStruct helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::findCollisionType(const CollisionComponent *cc, const CollisionComponent *matchCC) const noexcept
Determines the collision type between two entities based on their layer masks.
Evaluates both solid and trigger collision masks to determine if and how two entities can collide. Solid collisions are symmetric (both entities must accept collision with each other), while trigger collisions are asymmetric (either entity can trigger). cc Collision component of the first entity. matchCC Collision component of the second entity. CollisionStruct a struct with the requested collision information.
helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::GridCollisionDetectionSystem(const helios::math::aabbf &bounds, const float cellSize)
Constructs a GridCollisionDetectionSystem with specified bounds and cell size.
The grid is initialized to cover the given world bounds. Cell size determines the granularity of spatial partitioning; smaller cells reduce false positives but increase memory and insertion overhead. bounds World-space AABB defining the region where collision detection is active. cellSize Size of each grid cell in world units. Must be greater than zero. Given n objects, the 1/3 rule should be applied for determining the number of cells for partitioning, i.e. with n objects, the cube should consist of k x k x k cells, with k = n^{1/3} - that is, on average, one cell fits one object that should be tested for collision. Dimensions of said cells are derived by taking the reference space into account, e.g. WorldBounds.size/k (see [HS99]).
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update(helios::engine::runtime::world::UpdateContext &updateContext) noexcept override
Performs collision detection for all active entities.
Executes the complete collision detection pipeline each frame: 1. Clears all grid cells and resets solved collision pairs. 2. Iterates all active GameObjects with CollisionComponent and AabbColliderComponent. 3. Inserts each entity into all grid cells its AABB overlaps. 4. For each cell with multiple candidates, runs narrow-phase AABB intersection tests. 5. Publishes collision events (TriggerCollisionEvent, SolidCollisionEvent) to the event queue. updateContext The update context providing access to GameWorld and event queue.
References helios::engine::ecs::query::Active, helios::engine::ecs::query::ComponentEnabled, helios::engine::ecs::System::gameWorld_, helios::engine::ecs::Component::isEnabled, helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionMask, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell, helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionMask, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::worldBoundsToGridBounds.
helios::math::aabbi helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::worldBoundsToGridBounds(const helios::math::aabbf &aabbf) const noexcept
Converts world-space AABB bounds to grid cell indices.
Transforms a floating-point AABB in world space to integer cell coordinates, clamped to the valid grid range. Used to determine which cells an entity occupies. aabbf The world-space AABB to convert. An integer AABB representing the range of grid cell indices the entity spans.
References helios::math::aabb< T >::max, helios::math::aabb< T >::min.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate(helios::engine::ecs::GameObject *go, const helios::math::aabbi &bounds, AabbColliderComponent *aabbColliderComponent, CollisionComponent *collisionComponent, CollisionStateComponent *collisionStateComponent)
Inserts a collision candidate into all grid cells it overlaps.
Iterates through all cells within the given bounds and adds the candidate to each cell's collision candidate list for subsequent narrow-phase testing. go Pointer to the GameObject entity. bounds Grid cell index bounds (integer AABB) the entity spans. aabbColliderComponent Pointer to the entity's AABB collider component. collisionComponent Pointer to the entity's collision component.
References helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cell, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellIndex, helios::math::aabb< T >::max, helios::math::aabb< T >::min.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
void helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell(GridCell &cell, helios::engine::runtime::world::UpdateContext &updateContext)
Performs narrow-phase collision detection for all candidates in a cell.
Tests all unique pairs of collision candidates within the cell using AABB intersection. For each collision detected, determines collision type (solid/trigger) based on layer masks and publishes appropriate events. Uses a solved-set to avoid duplicate events when entities span multiple cells. cell The grid cell containing collision candidates to test. updateContext Context for pushing collision events to the event queue.
References helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cell, helios::engine::ecs::GameObject::guid, helios::engine::modules::physics::collision::components::CollisionStateComponent::hasCollision, helios::engine::modules::physics::collision::components::CollisionComponent::hitPolicy, helios::math::aabb< T >::intersects, helios::engine::modules::physics::collision::types::OneHit, helios::math::overlapCenter.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
GridCell & helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cell(const unsigned int x, const unsigned int y, const unsigned int z) noexcept
Accesses a grid cell by its 3D coordinates.
x X-coordinate of the cell (0 to cellsX - 1). y Y-coordinate of the cell (0 to cellsY - 1). z Z-coordinate of the cell (0 to cellsZ - 1). Reference to the GridCell at the specified coordinates.
References helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellIndex.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate.
size_t helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellIndex(const unsigned int x, const unsigned int y, const unsigned int z) const noexcept
Computes the 1D index of a cell in a 3D grid based on its x, y, and z coordinates.
x The x-coordinate of the cell (must be less than the grid's x-dimension). y The y-coordinate of the cell (must be less than the grid's y-dimension). z The z-coordinate of the cell (must be less than the grid's z-dimension). The 1D index of the cell in the grid.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cell, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate.
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsX() const noexcept
Returns the number of cells along the X axis.
Number of grid cells in the X dimension.
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsY() const noexcept
Returns the number of cells along the Y axis.
Number of grid cells in the Y dimension.
unsigned int helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::cellsZ() const noexcept
Returns the number of cells along the Z axis.
Number of grid cells in the Z dimension.