helios.engine.builder.spawnSystem.builders.configs.SpawnPoolConfig
helios::engine::runtime::pooling::GameObjectPoolManager& helios::engine::builder::spawnSystem::builders::configs::SpawnSystemConfigurator::poolManager_
The pool manager for pool registration.
helios::engine::runtime::spawn::SpawnManager& helios::engine::builder::spawnSystem::builders::configs::SpawnSystemConfigurator::spawnManager_
The spawn manager for profile and scheduler registration.
SpawnProfileConfig& helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::parent_
Parent profile this rule belongs to.
helios::engine::core::data::SpawnRuleId helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::ruleId_
Unique identifier for this rule.
std::unique_ptr<const helios::engine::runtime::spawn::policy::SpawnCondition> helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::condition_
Condition determining when to spawn.
std::unique_ptr<const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider> helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::amountProvider_
Provider determining how many to spawn.
SpawnPoolConfig& helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::parent_
Parent pool this profile belongs to.
helios::engine::runtime::spawn::SpawnManager& helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::spawnManager_
The spawn manager to register with.
helios::engine::core::data::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::profileId_
Profile identifier.
helios::engine::core::data::GameObjectPoolId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::poolId_
Pool to acquire entities from.
std::unique_ptr<helios::engine::runtime::spawn::behavior::SpawnPlacer> helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::placer_
Placement strategy for spawned entities.
std::unique_ptr<helios::engine::runtime::spawn::behavior::SpawnInitializer> helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::initializer_
Initialization strategy for spawned entities.
std::vector<std::unique_ptr<SpawnRuleConfig> > helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::rules_
Scheduled rules for this profile.
helios::engine::runtime::pooling::GameObjectPoolManager& helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::poolManager_
The pool manager to register with.
helios::engine::runtime::spawn::SpawnManager& helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::spawnManager_
The spawn manager to register profiles with.
helios::engine::core::data::GameObjectPoolId helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::poolId_
Pool identifier.
helios::engine::core::data::PrefabId helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::prefabId_
Identifier of the prefab template for cloning.
size_t helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::size_
Number of instances to pre-allocate.
std::vector<std::unique_ptr<SpawnProfileConfig> > helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::profiles_
Profile configurations attached to this pool.
helios::engine::builder::spawnSystem::builders::configs::SpawnSystemConfigurator::SpawnSystemConfigurator(helios::engine::runtime::pooling::GameObjectPoolManager &poolManager, helios::engine::runtime::spawn::SpawnManager &spawnManager) noexcept
Constructs a configurator with the given managers.
poolManager The pool manager for pool registration. spawnManager The spawn manager for profile and scheduler registration.
SpawnPoolConfig helios::engine::builder::spawnSystem::builders::configs::SpawnSystemConfigurator::pool(helios::engine::core::data::GameObjectPoolId poolId, helios::engine::core::data::PrefabId prefabId, size_t poolSize)
Begins ID-centric configuration of a spawn pool.
poolId Unique pool identifier. prefab Template GameObject for cloning. poolSize Number of instances to pre-allocate. SpawnPoolConfig for fluent configuration.
helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig(SpawnProfileConfig &parent, helios::engine::core::data::SpawnRuleId ruleId)
Constructs a SpawnRuleConfig.
parent The parent profile config. ruleId Unique identifier for this rule.
Referenced by helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::amount, helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::condition, helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::fixedAmount, helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerCondition, helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerWithAvailabilityCondition.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerCondition(const float intervalSeconds)
Sets a timer-based spawn condition.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::timerWithAvailabilityCondition(const float intervalSeconds)
Sets a combined condition: timer + pool availability.
intervalSeconds Seconds between spawn evaluations. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::condition(std::unique_ptr< const helios::engine::runtime::spawn::policy::SpawnCondition > customCondition)
Sets a custom spawn condition.
customCondition Ownership is transferred. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::fixedAmount(const size_t count)
Sets a fixed spawn amount.
count Number of entities to spawn per trigger. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::amount(std::unique_ptr< const helios::engine::runtime::spawn::policy::amount::SpawnAmountProvider > customProvider)
Sets a custom amount provider.
customProvider Ownership is transferred. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::SpawnRuleConfig.
std::unique_ptr< helios::engine::runtime::spawn::policy::SpawnRule > helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::build()
Builds the SpawnRule from this configuration.
The assembled SpawnRule.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnRuleConfig::done()
Finalizes the rule and returns to the parent profile config.
Reference to the parent SpawnProfileConfig.
helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig(SpawnPoolConfig &parent, helios::engine::runtime::spawn::SpawnManager &spawnManager, helios::engine::core::data::SpawnProfileId profileId, helios::engine::core::data::GameObjectPoolId poolId)
Constructs a SpawnProfileConfig.
parent The parent pool config. spawnManager The spawn manager to register profiles with. profileId Unique identifier for the profile. poolId Pool from which entities are acquired.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::profileId.
Referenced by helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::axisPlacement, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::emitterPlacement, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::initializer, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::moveInitializer, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::placer, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomDirectionInitializer, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomPlacement.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::emitterPlacement()
Configures emitter-relative placement and initialization.
Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomPlacement()
Configures random placement within level bounds.
Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::axisPlacement(const helios::math::vec3f &axis, const helios::math::vec3f &origin)
Configures axis-aligned placement.
axis Direction axis for spawn distribution. origin Starting point of the axis. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::placer(std::unique_ptr< helios::engine::runtime::spawn::behavior::SpawnPlacer > customPlacer)
Sets a custom spawn placer.
customPlacer Ownership is transferred. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::randomDirectionInitializer()
Configures a move initializer with random direction.
Reference to this config for chaining.
References helios::engine::runtime::spawn::behavior::initializers::Random, helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::moveInitializer(const helios::math::vec3f &direction)
Configures a move initializer with a fixed direction.
direction The movement direction. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::initializer(std::unique_ptr< helios::engine::runtime::spawn::behavior::SpawnInitializer > customInitializer)
Sets a custom spawn initializer.
customInitializer Ownership is transferred. Reference to this config for chaining.
References helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
SpawnRuleConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::scheduledBy(helios::engine::core::data::SpawnRuleId ruleId)
Begins configuration of a scheduled spawn rule for this profile.
ruleId Unique identifier for the rule. Reference to the new rule config for chaining.
helios::engine::core::data::SpawnProfileId helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::profileId() const noexcept
Returns the profile ID.
The spawn profile ID.
Referenced by helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::SpawnProfileConfig.
std::vector< std::pair< helios::engine::core::data::SpawnProfileId, std::unique_ptr< helios::engine::runtime::spawn::policy::SpawnRule > > > helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::commit()
Commits the profile and builds any associated rules.
Vector of built spawn rules (may be empty).
SpawnPoolConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnProfileConfig::done()
Finalizes the profile and returns to the parent pool config.
Reference to the parent SpawnPoolConfig.
helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::SpawnPoolConfig(helios::engine::runtime::pooling::GameObjectPoolManager &poolManager, helios::engine::runtime::spawn::SpawnManager &spawnManager, helios::engine::core::data::GameObjectPoolId poolId, helios::engine::core::data::PrefabId prefabId, size_t poolSize)
Constructs a SpawnPoolConfig.
poolManager The pool manager to register pools with. spawnManager The spawn manager to register profiles with. poolId Unique identifier for the pool. prefabId Identifier of the prefab template for cloning. poolSize Number of instances to pre-allocate.
SpawnProfileConfig & helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::profile(helios::engine::core::data::SpawnProfileId profileId)
Begins configuration of a spawn profile for this pool.
profileId Unique identifier for the profile. Reference to the new profile config for chaining.
SpawnSystemConfigurator helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::commit()
Commits pool, all profiles, and registers scheduled rules.
Profiles with scheduled rules are automatically registered with a DefaultSpawnScheduler per profile. Configurator for chaining the next pool() call.
SpawnSystemConfigurator helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::commitProfilesOnly()
Commits pool and profiles without creating any schedulers.
Use this when profiles should be registered but scheduling is handled separately (e.g., via SchedulerBuilder). Rules attached via scheduledBy() are silently discarded. This enables reuse of the same profile configuration under different scheduling strategies: ```cpp // Register pool + profiles (no schedulers) spawns.pool(PoolId, PrefabId, 100) .profile(LeftId).axisPlacement(...).moveInitializer(...).done() .profile(RightId).axisPlacement(...).moveInitializer(...).done() .commitProfilesOnly(); // Attach scheduling separately SchedulerBuilder sb(spawnManager); sb.cyclicScheduler( SchedulerConfig(LeftId, Rule1).timerCondition(5.0f).fixedAmount(10), SchedulerConfig(RightId, Rule2).timerCondition(5.0f).fixedAmount(10) ); ``` Configurator for chaining the next pool() call.
SpawnSystemConfigurator helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::commitCyclic()
Commits with all scheduled rules in a single CyclicSpawnScheduler.
Use this when multiple profiles share a cyclic spawn pattern (e.g., wave-based edge spawning). All rules across all profiles are bundled into one CyclicSpawnScheduler. N Number of rules in the cyclic scheduler. Configurator for chaining the next pool() call.
void helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::commitPool()
Registers the pool with the pool manager.
void helios::engine::builder::spawnSystem::builders::configs::SpawnPoolConfig::commitProfiles(bool skipSchedulers)
Commits all profiles and optionally creates per-profile schedulers.
skipSchedulers If true, profiles are committed without scheduler creation.