helios.engine.runtime.messaging.command.types.CommandBufferTypeId
using helios::engine::runtime::messaging::command::types::CommandBufferTypeId::ComponentType = helios_engine_core_data_CommandTypes
size_t helios::engine::runtime::messaging::command::types::CommandBufferTypeId::id_
The underlying ID value.
helios::engine::runtime::messaging::command::types::CommandBufferTypeId::CommandBufferTypeId(const size_t id)
Constructs a CommandBufferTypeId with a specific value.
id The type ID value.
References helios::engine::runtime::messaging::command::types::CommandBufferTypeId::id.
Referenced by helios::engine::runtime::messaging::command::types::CommandBufferTypeId::id, helios::engine::runtime::messaging::command::types::CommandBufferTypeId::operator==.
helios::engine::runtime::messaging::command::types::CommandBufferTypeId::CommandBufferTypeId(helios::core::types::no_init_t)
Constructs an uninitialized CommandBufferTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::runtime::messaging::command::types::CommandBufferTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID.
static CommandBufferTypeId helios::engine::runtime::messaging::command::types::CommandBufferTypeId::id()
Returns the CommandBufferTypeId for a specific command type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The command type. The unique CommandBufferTypeId for type T.
References helios::engine::runtime::messaging::command::types::CommandBufferTypeId::CommandBufferTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::runtime::messaging::command::types::CommandBufferTypeId::CommandBufferTypeId.
std::size_t std::hash< helios::engine::runtime::messaging::command::types::CommandBufferTypeId >::operator()(const helios::engine::runtime::messaging::command::types::CommandBufferTypeId &id) const noexcept