helios.engine.modules.ui.transform.components.UiTransformComponent
helios::engine::modules::ui::layout::Anchor helios::engine::modules::ui::transform::components::UiTransformComponent::anchor_
Anchor point relative to the viewport.
helios::engine::modules::ui::layout::Anchor helios::engine::modules::ui::transform::components::UiTransformComponent::pivot_
Pivot point of this element for positioning calculations.
helios::engine::core::data::ViewportId helios::engine::modules::ui::transform::components::UiTransformComponent::viewportId_
ID of the viewport this element is positioned relative to.
helios::math::vec4f helios::engine::modules::ui::transform::components::UiTransformComponent::margins_
Margins from anchor point (top, right, bottom, left).
bool helios::engine::modules::ui::transform::components::UiTransformComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::ui::transform::components::UiTransformComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::ui::transform::components::UiTransformComponent::enable() noexcept
Enables this component.
void helios::engine::modules::ui::transform::components::UiTransformComponent::disable() noexcept
Disables this component.
helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent()=default
Default constructor.
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::operator=, helios::engine::modules::ui::transform::components::UiTransformComponent::operator=, helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent, helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent.
helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent(const UiTransformComponent &)=default
Copy constructor.
References helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent.
UiTransformComponent & helios::engine::modules::ui::transform::components::UiTransformComponent::operator=(const UiTransformComponent &)=default
Copy assignment operator.
References helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent.
helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent(UiTransformComponent &&) noexcept=default
Move constructor.
References helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent.
UiTransformComponent & helios::engine::modules::ui::transform::components::UiTransformComponent::operator=(UiTransformComponent &&) noexcept=default
Move assignment operator.
References helios::engine::modules::ui::transform::components::UiTransformComponent::UiTransformComponent.
void helios::engine::modules::ui::transform::components::UiTransformComponent::setAnchor(const helios::engine::modules::ui::layout::Anchor anchor) noexcept
Sets the anchor point.
anchor The anchor point relative to the viewport.
References helios::engine::modules::ui::transform::components::UiTransformComponent::anchor, helios::engine::modules::ui::transform::components::UiTransformComponent::setAnchor.
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::setAnchor.
helios::engine::modules::ui::layout::Anchor helios::engine::modules::ui::transform::components::UiTransformComponent::anchor() const noexcept
Returns the current anchor point.
The anchor point relative to the viewport.
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::setAnchor.
void helios::engine::modules::ui::transform::components::UiTransformComponent::setViewportId(const helios::engine::core::data::ViewportId viewportId) noexcept
Sets the viewport ID.
viewportId The ID of the viewport for positioning.
References helios::engine::modules::ui::transform::components::UiTransformComponent::viewportId.
void helios::engine::modules::ui::transform::components::UiTransformComponent::setMargins(const helios::math::vec4f margins) noexcept
Sets the margins from the anchor point.
margins Margins as vec4f (top, right, bottom, left).
References helios::engine::modules::ui::transform::components::UiTransformComponent::margins.
helios::math::vec4f helios::engine::modules::ui::transform::components::UiTransformComponent::margins() const noexcept
Returns the current margins.
Margins as vec4f (top, right, bottom, left).
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::setMargins.
void helios::engine::modules::ui::transform::components::UiTransformComponent::setPivot(const helios::engine::modules::ui::layout::Anchor pivot) noexcept
Sets the pivot point.
pivot The pivot point of this element.
References helios::engine::modules::ui::transform::components::UiTransformComponent::pivot.
helios::engine::modules::ui::layout::Anchor helios::engine::modules::ui::transform::components::UiTransformComponent::pivot() const noexcept
Returns the current pivot point.
The pivot point of this element.
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::setPivot.
helios::engine::core::data::ViewportId helios::engine::modules::ui::transform::components::UiTransformComponent::viewportId() const noexcept
Returns the viewport ID.
The ID of the viewport this element is positioned relative to.
Referenced by helios::engine::modules::ui::transform::components::UiTransformComponent::setViewportId.