helios.engine.builder.gameObject.builders.configs.TextRenderableConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::gameObject_
The GameObject being configured.
helios::rendering::text::FontResourceProvider* helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontResourceProvider_
Pointer to the font resource provider.
std::shared_ptr<helios::ext::opengl::rendering::shader::OpenGLShader> helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader_
The shader used for text rendering.
helios::math::vec4f helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color_
The text color.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text_
The text content to display.
float helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale_
The font scale factor.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::numberFormat_
Format string for number display (std::vformat syntax).
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::isUiText_
Whether this text should be configured as UI text.
helios::engine::core::data::FontId helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId_
The font identifier.
std::string helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::timestampFormat_
Format string for timestamp display (std::vformat syntax).
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::usesTimeFormatter_
Whether a TimeFormatterComponent should be attached.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::usesNumberFormatter_
Whether a NumberFormatterComponent should be attached.
bool helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::displayRemaining_
Whether the timer should display remaining instead of elapsed time.
helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig(helios::engine::ecs::GameObject gameObject)
Constructs a TextRenderableConfig for the given GameObject.
gameObject The GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::asUiText, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::displayRemaining, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontResourceProvider, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsNumber, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsTimestamp, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader(const std::shared_ptr< helios::ext::opengl::rendering::shader::OpenGLShader > &shader)
Sets the shader for text rendering.
shader The shader to use. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::shader.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color(const helios::math::vec4f color)
Sets the text color.
color The RGBA color. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::color.
SceneNodeConfig helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo(helios::engine::ecs::GameObject parent)
Builds the text renderable and attaches to a parent GameObject.
parent The parent GameObject to attach to. A SceneNodeConfig for further configuration.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
SceneNodeConfig helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo(helios::scene::SceneNode *parent)
Builds the text renderable and attaches to a parent SceneNode.
parent The parent SceneNode to attach to. A SceneNodeConfig for further configuration.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontResourceProvider(helios::rendering::text::FontResourceProvider &provider)
Sets the font resource provider.
provider The font resource provider. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::asUiText()
Configures this text as a UI text component.
Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsNumber(std::string numberFormat="{:.0f}")
Attaches a NumberFormatterComponent with the given format.
Implicitly enables UI text mode. numberFormat A std::vformat-compatible string. Defaults to "{:.0f}". Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::formattedAsTimestamp(std::string timestampFormat)
Attaches a TimeFormatterComponent with the given format.
Implicitly enables UI text mode. timestampFormat A std::vformat-compatible string expecting minutes and seconds. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::displayRemaining()
Switches the time formatter to display remaining time.
Only effective when formattedAsTimestamp() has been called. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text(std::string text)
Sets the text content.
text The text to display. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::text.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId(helios::engine::core::data::FontId fontId)
Sets the font identifier.
fontId The font ID to use. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontId.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale(const float fontScale)
Sets the font scale factor.
fontScale The scale factor. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::fontScale.
TextRenderableConfig & helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build()
Builds the text renderable and adds components to the GameObject.
Creates a TextRenderable with the configured properties and adds RenderableComponent and ModelAabbComponent. If configured as UI text, also adds UiTextComponent. Reference to this config for method chaining.
References helios::engine::modules::ui::layout::types::Elapsed, helios::engine::modules::ui::layout::types::Remaining, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::TextRenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo, helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::attachTo.