helios.engine.core.data.CommandTypeId
using helios::engine::core::data::CommandTypeId::ComponentType = helios_engine_core_data_CommandTypes
size_t helios::engine::core::data::CommandTypeId::id_
The underlying ID value.
helios::engine::core::data::CommandTypeId::CommandTypeId(const size_t id)
Constructs a CommandTypeId with a specific value.
id The type ID value.
References helios::engine::core::data::CommandTypeId::id.
Referenced by helios::engine::core::data::CommandTypeId::id, helios::engine::core::data::CommandTypeId::operator==.
helios::engine::core::data::CommandTypeId::CommandTypeId(helios::core::types::no_init_t)
Constructs an uninitialized CommandTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::core::data::CommandTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID.
static CommandTypeId helios::engine::core::data::CommandTypeId::id()
Returns the CommandTypeId for a specific command type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The command type. The unique CommandTypeId for type T.
References helios::engine::core::data::CommandTypeId::CommandTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::core::data::CommandTypeId::CommandTypeId.
std::size_t std::hash< helios::engine::core::data::CommandTypeId >::operator()(const helios::engine::core::data::CommandTypeId &id) const noexcept