helios.core.data.TypeIndexedDoubleBuffer
ReadBuffer<T> helios::core::data::ReadWriteDoubleBuffer< T >::readBuffer_
Buffer containing messages available for reading.
WriteBuffer<T> helios::core::data::ReadWriteDoubleBuffer< T >::writeBuffer_
Buffer where new messages are pushed.
std::vector<std::unique_ptr<BufferBase> > helios::core::data::TypeIndexedDoubleBuffer< Indexer >::buffers_
TypeIndexedDoubleBuffer* helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::db_
Non-owning pointer to the parent buffer.
void helios::core::data::ReadWriteDoubleBuffer< T >::reserve(size_t size)
Pre-allocates memory for both buffers.
size The number of messages to reserve capacity for.
void helios::core::data::ReadWriteDoubleBuffer< T >::push(Args &&... args)
Constructs and pushes a message to the write buffer.
Args Constructor argument types for T. args Arguments forwarded to T's constructor.
std::span< const T > helios::core::data::ReadWriteDoubleBuffer< T >::read() const noexcept
Returns a read-only view of messages in the read buffer.
A span over all messages written in the previous frame.
Referenced by helios::core::data::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::read.
void helios::core::data::ReadWriteDoubleBuffer< T >::swap() override
Swaps read with write buffer.
Swaps the read- with the write-buffer. The write buffer is empty after this operation, while the read buffer contains the contents of the write buffer.
void helios::core::data::ReadWriteDoubleBuffer< T >::clearReadBuffer() override
Clears the read buffer.
void helios::core::data::ReadWriteDoubleBuffer< T >::clearWriteBuffer() override
Clears the write buffer.
static size_t helios::core::data::TypeIndexedDoubleBuffer< Indexer >::index()
helios::core::data::TypeIndexedDoubleBuffer< Indexer >::~TypeIndexedDoubleBuffer()=default
helios::core::data::TypeIndexedDoubleBuffer< Indexer >::TypeIndexedDoubleBuffer()=default
Referenced by helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::WriteSink.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::push(Args &&... args)
Pushes a message of type T to the write buffer.
T The message type. Args Constructor argument types for T. args Arguments forwarded to T's constructor.
std::span< const T > helios::core::data::TypeIndexedDoubleBuffer< Indexer >::read() const noexcept
Returns a read-only view of all messages of type T.
Returns messages that were written before the last `swapBuffers()` call. If no messages of type T exist, returns an empty span. T The message type to read. A span over all messages of type T in the read buffer.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::reserve(size_t size)
Pre-allocates capacity for messages of type T.
Call during initialization to avoid allocations during gameplay. T The message type. size The number of messages to reserve capacity for.
ReadWriteDoubleBuffer< T > & helios::core::data::TypeIndexedDoubleBuffer< Indexer >::getOrCreateBuffer()
Gets or creates the buffer for message type T.
T The message type. Reference to the ReadWriteDoubleBuffer for type T.
Referenced by helios::core::data::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::push, helios::core::data::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::reserve.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::swapBuffers()
Swaps read and write buffers for all message types.
Call once per frame at a consistent point (e.g., end of update phase). After this call, messages pushed in the current frame become readable.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::clearReadBuffers()
Clears all read buffers.
Typically not needed as `swapBuffers()` clears read buffers automatically.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::clearWriteBuffers()
Clears all write buffers without swapping.
Use to discard messages that were pushed but should not be processed.
helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::WriteSink(TypeIndexedDoubleBuffer &db) noexcept
Constructs a WriteSink from a TypeIndexedDoubleBuffer reference.
db The buffer to write to. Must remain valid for the lifetime of this sink.
References helios::core::data::TypeIndexedDoubleBuffer< Indexer >::TypeIndexedDoubleBuffer.
void helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push(Args &&... args) noexcept
Constructs and pushes a message of type E to the buffer.
E The message type. Args Constructor argument types for E. args Arguments forwarded to E's constructor.
References helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push.
Referenced by helios::core::data::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push.
WriteSink helios::core::data::TypeIndexedDoubleBuffer< Indexer >::writeSink() noexcept
Creates a WriteSink handle for this buffer.
A WriteSink that can push messages to this buffer.