helios.ext.opengl.rendering.OpenGLDevice
std::unique_ptr<helios::ext::opengl::rendering::OpenGLGlyphTextRenderer> helios::ext::opengl::rendering::OpenGLDevice::textRenderer_
Text renderer for FreeType-based glyph rendering.
std::unique_ptr<helios::rendering::text::FontResourceProvider> helios::ext::opengl::rendering::OpenGLDevice::fontResourceProvider_
Font resource provider for loading fonts and retrieving glyph data.
const helios::ext::opengl::rendering::shader::OpenGLShader* helios::ext::opengl::rendering::OpenGLDevice::lastShader_
Cached pointer to the last used shader for state optimization.
unsigned int helios::ext::opengl::rendering::OpenGLDevice::lastVao_
Cached VAO ID for state optimization.
GLenum helios::ext::opengl::rendering::OpenGLDevice::toOpenGL(helios::rendering::model::config::PrimitiveType primitiveType) const noexcept
Translates helios abstract PrimitiveType enum to its corresponding OpenGL GLenum value.
This is a utility function used exclusively by the OpenGLDevice to interpret the API-agnostic primitive type requested by the helios configuration. primitiveType The API-agnostic PrimitiveType value. The corresponding OpenGL primitive type as a GLenum. If mapping does not succeed, the function falls back to GL_TRIANGLES.
helios::ext::opengl::rendering::OpenGLDevice::~OpenGLDevice() override=default
helios::ext::opengl::rendering::OpenGLDevice::OpenGLDevice(std::unique_ptr< helios::ext::opengl::rendering::OpenGLGlyphTextRenderer > textRenderer, std::unique_ptr< helios::rendering::text::FontResourceProvider > fontResourceProvider)
Constructs an OpenGLDevice with the given text renderer and font provider.
textRenderer The text renderer to use for glyph-based text rendering. Ownership is transferred to this device. fontResourceProvider The font resource provider for loading fonts. Ownership is transferred to this device.
References helios::ext::opengl::rendering::OpenGLDevice::fontResourceProvider, helios::ext::opengl::rendering::OpenGLDevice::textRenderer.
void helios::ext::opengl::rendering::OpenGLDevice::init() override
Initializes the OpenGL device to access modern OpenGL.
This method must be called **after** the helios application's `setCurrent()` was called for creating a current context. This OpenGL device will then load from this context. This method uses the `gladLoadGL` method in conjunction with `glfwGetProcAddress`, which returns the address of the specific OpenGL core. https://www.glfw.org/docs/latest/group__context.html#ga35f1837e6f666781842483937612f163 TodoProvide abstraction for glfwGetProcAddress.
References helios::rendering::RenderingDevice::initialized_, helios::rendering::RenderingDevice::logger_.
void helios::ext::opengl::rendering::OpenGLDevice::beginRenderPass(helios::rendering::RenderPass &renderPass) const noexcept override
Begins a new render pass.
This implementation makes sure that the rendering surface is cleared with the current clear color, which can be configured via `clearColor()`. renderPass The render pass to begin. clear() clearColor()
References helios::rendering::Color, helios::rendering::Depth, helios::rendering::RenderTarget::height, helios::rendering::Stencil, helios::rendering::RenderTarget::width.
void helios::ext::opengl::rendering::OpenGLDevice::doRender(helios::rendering::RenderPass &renderPass) const noexcept override
Processes render commands and draws geometry and text.
Iterates through all render commands in the render queue, binds the appropriate shaders and VAOs, applies uniform values, and issues draw calls. After processing geometry, delegates any text render commands to `renderTextCommands()`. renderPass The render pass containing the render queue to be processed. renderTextCommands()
References helios::ext::opengl::rendering::OpenGLDevice::renderTextCommands.
void helios::ext::opengl::rendering::OpenGLDevice::renderTextCommands(const helios::rendering::RenderPass &renderPass) const noexcept
Renders all text commands in the render pass.
Iterates through the text render commands in the render queue and delegates each command to the `OpenGLGlyphTextRenderer` for rendering. renderPass The render pass containing text render commands.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::doRender.
void helios::ext::opengl::rendering::OpenGLDevice::endRenderPass(helios::rendering::RenderPass &renderPass) const noexcept override
Ends the specified render pass.
The current implementation does nothing. renderPass The render pass to end.
helios::rendering::text::TextRenderer & helios::ext::opengl::rendering::OpenGLDevice::textRenderer() const noexcept
Returns a reference to the text renderer.
Use this to register font families before rendering text. Reference to the `TextRenderer` interface. OpenGLGlyphTextRenderer::addFontFamily()
Referenced by helios::ext::opengl::rendering::OpenGLDevice::OpenGLDevice.
helios::rendering::text::FontResourceProvider & helios::ext::opengl::rendering::OpenGLDevice::fontResourceProvider() const noexcept override
Returns a reference to the font resource provider.
Use this to load fonts before creating `TextRenderPrototype` instances. Reference to the `FontResourceProvider` implementation.
Referenced by helios::ext::opengl::rendering::OpenGLDevice::OpenGLDevice.