helios.engine.mechanics.timing.components.GameTimerBindingComponent
GameTimerId helios::engine::mechanics::timing::components::GameTimerBindingComponent::gameTimerId_
The id of the observed game timer.
TimerRevision helios::engine::mechanics::timing::components::GameTimerBindingComponent::timerRevision_
Last known revision of the observed timer.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent()=default
Referenced by helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent, helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent, helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=, helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent(const GameTimerBindingComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent.
GameTimerBindingComponent & helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=(const GameTimerBindingComponent &)=default
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent.
helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent(GameTimerBindingComponent &&) noexcept=default
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent.
GameTimerBindingComponent & helios::engine::mechanics::timing::components::GameTimerBindingComponent::operator=(GameTimerBindingComponent &&) noexcept=default
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::GameTimerBindingComponent.
void helios::engine::mechanics::timing::components::GameTimerBindingComponent::setGameTimerId(const helios::engine::mechanics::timing::types::GameTimerId gameTimerId) noexcept
Sets the id of the game timer to observe.
gameTimerId The timer id.
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::gameTimerId, helios::engine::mechanics::timing::components::GameTimerBindingComponent::setGameTimerId.
Referenced by helios::engine::mechanics::timing::components::GameTimerBindingComponent::setGameTimerId.
helios::engine::mechanics::timing::types::GameTimerId helios::engine::mechanics::timing::components::GameTimerBindingComponent::gameTimerId() const noexcept
Returns the observed game timer id.
The GameTimerId.
Referenced by helios::engine::mechanics::timing::components::GameTimerBindingComponent::setGameTimerId.
void helios::engine::mechanics::timing::components::GameTimerBindingComponent::setTimerRevision(const TimerRevision timerRevision) noexcept
Sets the last known timer revision.
If the new revision differs from the stored one, the update flag is set so that consuming systems can detect the change. timerRevision The revision value.
References helios::engine::mechanics::timing::components::GameTimerBindingComponent::timerRevision.
TimerRevision helios::engine::mechanics::timing::components::GameTimerBindingComponent::timerRevision() const noexcept
Returns the last known timer revision.
The stored TimerRevision.
Referenced by helios::engine::mechanics::timing::components::GameTimerBindingComponent::setTimerRevision.