helios.engine.mechanics.scoring.ScorePool
helios::engine::mechanics::scoring::types::ScorePoolId helios::engine::mechanics::scoring::ScorePool::scorePoolId_
Unique identifier for this score pool.
std::vector<double> helios::engine::mechanics::scoring::ScorePool::scores_
Per-type score values indexed by ScoreTypeId.
double helios::engine::mechanics::scoring::ScorePool::totalScore_
Running total of all scores in this pool.
double helios::engine::mechanics::scoring::ScorePool::maxScore_
The highest total score observed so far.
helios::engine::mechanics::scoring::types::ScorePoolRevision helios::engine::mechanics::scoring::ScorePool::maxScoreRevision_
Revision counter for maxScore changes.
helios::engine::mechanics::scoring::types::ScorePoolRevision helios::engine::mechanics::scoring::ScorePool::revision_
The current revision of this ScorePool.
void helios::engine::mechanics::scoring::ScorePool::addTotal(const double total) noexcept
Adds to the running total.
total Value to add.
void helios::engine::mechanics::scoring::ScorePool::setTotal(const double total) noexcept
Sets the running total directly.
total New total value.
helios::engine::mechanics::scoring::ScorePool::ScorePool(const helios::engine::mechanics::scoring::types::ScorePoolId scorePoolId)
Constructs a ScorePool with the given ID.
scorePoolId Unique identifier for this pool.
References helios::engine::mechanics::scoring::ScorePool::scorePoolId.
helios::engine::mechanics::scoring::types::ScorePoolId helios::engine::mechanics::scoring::ScorePool::id() const noexcept
Returns the pool's unique identifier.
The ScorePoolId.
Referenced by helios::engine::mechanics::scoring::ScorePool::addScore.
void helios::engine::mechanics::scoring::ScorePool::addScore(const helios::engine::mechanics::scoring::types::ScoreValueContext &scoreContext)
Adds a score from the given context.
Updates both the per-type score and the running total. scoreContext Context containing type ID and value.
References helios::engine::mechanics::scoring::ScorePool::id, helios::engine::mechanics::scoring::types::ScoreValueContext::scoreTypeId, helios::engine::mechanics::scoring::ScorePool::updateMaxScore, helios::engine::mechanics::scoring::types::ScoreTypeId::value, helios::engine::mechanics::scoring::types::ScoreValueContext::value.
void helios::engine::mechanics::scoring::ScorePool::reset() noexcept
Resets all scores to zero.
double helios::engine::mechanics::scoring::ScorePool::totalScore() const noexcept
Returns the running total of all scores.
The total score value.
helios::engine::mechanics::scoring::types::ScorePoolId helios::engine::mechanics::scoring::ScorePool::scorePoolId() const noexcept
Returns the pool's unique identifier.
The ScorePoolId.
Referenced by helios::engine::mechanics::scoring::ScorePool::ScorePool.
helios::engine::mechanics::scoring::types::ScorePoolRevision helios::engine::mechanics::scoring::ScorePool::revision() const noexcept
Returns the current revision number.
The revision is incremented whenever a score value changes. Used by observers to detect changes without polling values. The current ScorePoolRevision.
helios::engine::mechanics::scoring::ScorePoolSnapshot helios::engine::mechanics::scoring::ScorePool::snapshot() const noexcept
Returns a snapshot of the current pool state.
The snapshot contains the pool ID, total score, and current revision. Useful for observers and UI binding. A ScorePoolSnapshot with current values.
void helios::engine::mechanics::scoring::ScorePool::updateMaxScore() noexcept
Recalculates the high score from the current total.
Increments maxScoreRevision if the high score changes. Called automatically by addScore().
Referenced by helios::engine::mechanics::scoring::ScorePool::addScore.
double helios::engine::mechanics::scoring::ScorePool::maxScore() const noexcept
Returns the highest total score observed.
The maximum score value.
helios::engine::mechanics::scoring::types::ScorePoolRevision helios::engine::mechanics::scoring::ScorePool::maxScoreRevision() const noexcept
Returns the revision counter for maxScore changes.
The current max score revision.
helios::engine::mechanics::scoring::MaxScorePoolSnapshot helios::engine::mechanics::scoring::ScorePool::maxScoreSnapshot() const noexcept
Returns a snapshot of the current high score state.
A MaxScorePoolSnapshot with current values. MaxScorePoolSnapshot