helios.engine.builder.gameObject.builders.configs.RenderableConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::RenderableConfig::gameObject_
Non-owning pointer to the target GameObject.
std::shared_ptr<helios::rendering::asset::shape::Shape> helios::engine::builder::gameObject::builders::configs::RenderableConfig::shape_
The shape geometry to render.
std::shared_ptr<helios::ext::opengl::rendering::shader::OpenGLShader> helios::engine::builder::gameObject::builders::configs::RenderableConfig::shader_
The shader for rendering.
helios::rendering::model::config::PrimitiveType helios::engine::builder::gameObject::builders::configs::RenderableConfig::primitiveType_
The primitive type for mesh rendering.
helios::math::vec4f helios::engine::builder::gameObject::builders::configs::RenderableConfig::color_
The base color for the material.
std::unordered_map< helios::rendering::model::config::PrimitiveType, std::shared_ptr<helios::rendering::model::config::MeshConfig> > helios::engine::builder::gameObject::builders::configs::RenderableConfig::meshConfigs_
static std::shared_ptr< helios::rendering::model::config::MeshConfig > helios::engine::builder::gameObject::builders::configs::RenderableConfig::meshConfig(helios::rendering::model::config::PrimitiveType primitiveType)
helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a RenderableConfig for the given GameObject.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::build, helios::engine::builder::gameObject::builders::configs::RenderableConfig::color, helios::engine::builder::gameObject::builders::configs::RenderableConfig::primitiveType, helios::engine::builder::gameObject::builders::configs::RenderableConfig::shader, helios::engine::builder::gameObject::builders::configs::RenderableConfig::shape.
RenderableConfig & helios::engine::builder::gameObject::builders::configs::RenderableConfig::shape(std::shared_ptr< helios::rendering::asset::shape::Shape > shape)
Sets the shape geometry.
shape Shared pointer to the shape. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig, helios::engine::builder::gameObject::builders::configs::RenderableConfig::shape.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::shape.
RenderableConfig & helios::engine::builder::gameObject::builders::configs::RenderableConfig::shader(std::shared_ptr< helios::ext::opengl::rendering::shader::OpenGLShader > shader)
Sets the shader program.
shader Shared pointer to the OpenGL shader. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig, helios::engine::builder::gameObject::builders::configs::RenderableConfig::shader.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::shader.
RenderableConfig & helios::engine::builder::gameObject::builders::configs::RenderableConfig::primitiveType(helios::rendering::model::config::PrimitiveType primitiveType)
Sets the primitive type for rendering.
primitiveType The OpenGL primitive type. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::primitiveType, helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::primitiveType.
RenderableConfig & helios::engine::builder::gameObject::builders::configs::RenderableConfig::color(const helios::math::vec4f color)
Sets the base color for the material.
color RGBA color vector. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::color, helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::color.
void helios::engine::builder::gameObject::builders::configs::RenderableConfig::attachTo(helios::scene::SceneNode *parent)
Builds the renderable and attaches it to a scene node.
parent Parent SceneNode for the new node.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::build, helios::engine::builder::gameObject::builders::configs::SceneNodeConfig::parent.
RenderableConfig & helios::engine::builder::gameObject::builders::configs::RenderableConfig::build()
Builds and attaches the RenderableComponent.
Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::RenderableConfig::RenderableConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::RenderableConfig::attachTo.