helios.engine.modules.physics.collision.components.CollisionComponent
size_t helios::engine::modules::physics::collision::components::CollisionComponent::CollisionBehaviorSize
uint32_t helios::engine::modules::physics::collision::components::CollisionComponent::layerId_
The collision layer this component belongs to.
uint32_t helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionMask_
Bitmask specifying layers that generate trigger collisions.
Trigger collision masks may be asymmetric, i.e. a component B must not know about the existence of another layerId.
uint32_t helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionMask_
Bitmask specifying layers that generate solid collisions.
Solid collision should be symmetric and in the calling API treated as such: `(maskB & thisLayerId) != 0 && (thisMask & layerBId) != 0`
bool helios::engine::modules::physics::collision::components::CollisionComponent::isCollisionReporter_
Flag indicating whether this component can report collision events.
std::array< uint32_t, helios::engine::modules::physics::collision::types::CollisionBehaviorItemSize > helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionBehavior_
Per-behavior layer masks for solid collisions.
Each array index corresponds to a CollisionBehavior enum value. The bitmask at each index indicates which layers trigger that behavior for solid collisions.
std::array< uint32_t, helios::engine::modules::physics::collision::types::CollisionBehaviorItemSize > helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionBehavior_
Per-behavior layer masks for trigger collisions.
Each array index corresponds to a CollisionBehavior enum value. The bitmask at each index indicates which layers trigger that behavior for trigger collisions.
helios::engine::modules::physics::collision::types::HitPolicy helios::engine::modules::physics::collision::components::CollisionComponent::hitPolicy_
Controls how many collisions are reported per frame.
Defaults to `OneHit`, reporting only the first collision. Set to `All` for multi-target collision detection. HitPolicy
bool helios::engine::modules::physics::collision::components::CollisionComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::physics::collision::components::CollisionComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
void helios::engine::modules::physics::collision::components::CollisionComponent::enable() noexcept
Enables this component.
void helios::engine::modules::physics::collision::components::CollisionComponent::disable() noexcept
Disables this component.
helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent(uint32_t layerId, bool isCollisionReporter=true, uint32_t solidCollisionMask=0, uint32_t triggerCollisionMask=0)
Constructs a CollisionComponent with a layer ID.
layerId The collision layer this entity belongs to. isCollisionReporter Whether this entity can emit collision events. solidCollisionMask Initial bitmask for solid collisions. triggerCollisionMask Initial bitmask for trigger collisions.
References helios::engine::modules::physics::collision::components::CollisionComponent::isCollisionReporter, helios::engine::modules::physics::collision::components::CollisionComponent::layerId, helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionMask, helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionMask.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::addSolidCollisionBehavior, helios::engine::modules::physics::collision::components::CollisionComponent::addTriggerCollisionBehavior, helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::operator=, helios::engine::modules::physics::collision::components::CollisionComponent::operator=, helios::engine::modules::physics::collision::components::CollisionComponent::setSolidCollisionMask, helios::engine::modules::physics::collision::components::CollisionComponent::setTriggerCollisionMask.
helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent(const CollisionComponent &other)
Copy constructor.
Creates a deep copy of the collision component, preserving layer ID, masks, and all behavior configurations. other The component to copy from.
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::operator=(const CollisionComponent &)=default
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent(CollisionComponent &&) noexcept=default
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::operator=(CollisionComponent &&) noexcept=default
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
void helios::engine::modules::physics::collision::components::CollisionComponent::setIsCollisionReporter(bool isCollisionReporter)
Sets whether this component should report collision events.
isCollisionReporter True to enable event reporting, false to disable.
References helios::engine::modules::physics::collision::components::CollisionComponent::isCollisionReporter, helios::engine::modules::physics::collision::components::CollisionComponent::setIsCollisionReporter.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::setIsCollisionReporter.
void helios::engine::modules::physics::collision::components::CollisionComponent::setHitPolicy(const helios::engine::modules::physics::collision::types::HitPolicy hitPolicy)
Sets the hit policy for collision detection.
Controls how many collision events this entity can receive per frame: `OneHit`: Only the first collision is reported (default) `All`: All collisions are reported hitPolicy The hit policy to apply. HitPolicy
References helios::engine::modules::physics::collision::components::CollisionComponent::hitPolicy.
helios::engine::modules::physics::collision::types::HitPolicy helios::engine::modules::physics::collision::components::CollisionComponent::hitPolicy() const noexcept
Returns the current hit policy.
The configured HitPolicy for this component. HitPolicy
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::setHitPolicy, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
bool helios::engine::modules::physics::collision::components::CollisionComponent::isCollisionReporter() const noexcept
Returns whether this component can emit collision events.
True if collision events can be generated, false otherwise.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::setIsCollisionReporter.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::setSolidCollisionMask(const uint32_t solidCollisionMask) noexcept
Sets the solid collision mask.
solidCollisionMask Bitmask of layers to generate solid collisions with. Reference to this component for method chaining.
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionMask.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::setTriggerCollisionMask(const uint32_t triggerCollisionMask) noexcept
Sets the trigger collision mask.
triggerCollisionMask Bitmask of layers to generate trigger collisions with. Reference to this component for method chaining.
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionMask.
uint32_t helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionMask() const noexcept
Returns the solid collision mask.
Bitmask of layers this entity generates solid collisions with.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::setSolidCollisionMask, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
uint32_t helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionMask() const noexcept
Returns the trigger collision mask.
Bitmask of layers this entity generates trigger collisions with.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent, helios::engine::modules::physics::collision::components::CollisionComponent::setTriggerCollisionMask, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
unsigned int helios::engine::modules::physics::collision::components::CollisionComponent::layerId() const noexcept
Returns the collision layer ID.
The layer this entity belongs to.
Referenced by helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::addSolidCollisionBehavior(const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior, const uint32_t otherLayerId) noexcept
Adds a solid collision behavior for a specific layer.
Associates a collision behavior with a target layer for solid collisions. If a behavior was previously set for the same layer, it is replaced. collisionBehavior The behavior to apply on collision. otherLayerId The layer ID to associate the behavior with. Reference to this component for method chaining.
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::components::CollisionComponent::solidCollisionBehavior(uint32_t otherLayerId) const noexcept
Returns the solid collision behavior for a specific layer.
Looks up the configured behavior for collisions with the specified layer. Returns `CollisionBehavior::None` if no solid collision mask is set for the layer. otherLayerId The layer ID to query. The collision behavior for the specified layer.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::components::CollisionComponent::triggerCollisionBehavior(uint32_t otherLayerId) const noexcept
Returns the trigger collision behavior for a specific layer.
Looks up the configured behavior for trigger collisions with the specified layer. Returns `CollisionBehavior::None` if no trigger collision mask is set for the layer. otherLayerId The layer ID to query. The collision behavior for the specified layer.
CollisionComponent & helios::engine::modules::physics::collision::components::CollisionComponent::addTriggerCollisionBehavior(const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior, const uint32_t otherLayerId) noexcept
Adds a trigger collision behavior for a specific layer.
Associates a collision behavior with a target layer for trigger collisions. If a behavior was previously set for the same layer, it is replaced. collisionBehavior The behavior to apply on collision. otherLayerId The layer ID to associate the behavior with. Reference to this component for method chaining.
References helios::engine::modules::physics::collision::components::CollisionComponent::CollisionComponent.