helios.engine.mechanics.scoring.components.MaxScoreObserverComponent
helios::engine::core::data::ScorePoolId helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::scorePoolId_
ID of the score pool to observe.
bool helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::hasUpdate_
Flag indicating whether the value changed this frame.
Cleared by MaxScoreObserverClearSystem at frame end.
helios::engine::mechanics::scoring::MaxScorePoolSnapshot helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::snapshot_
the current snapshot saved by this observer component.
bool helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::isEnabled_
Whether this component is enabled.
void helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::clearUpdate()
Clears the update flag.
Called by MaxScoreObserverClearSystem.
bool helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent()=default
Referenced by helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent, helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent, helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::operator=, helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::operator=.
helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent(const MaxScoreObserverComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent.
MaxScoreObserverComponent & helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::operator=(const MaxScoreObserverComponent &)=default
References helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent.
helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent(MaxScoreObserverComponent &&) noexcept=default
References helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent.
MaxScoreObserverComponent & helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::operator=(MaxScoreObserverComponent &&) noexcept=default
References helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::MaxScoreObserverComponent.
void helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::setScorePoolId(const helios::engine::core::data::ScorePoolId scorePoolId) noexcept
Sets the score pool to observe.
scorePoolId The ID of the pool to observe.
References helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::scorePoolId, helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::setScorePoolId.
Referenced by helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::setScorePoolId.
helios::engine::core::data::ScorePoolId helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::scorePoolId() const noexcept
Returns the observed score pool ID.
The ScorePoolId.
Referenced by helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::setScorePoolId.
void helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::setMaxScorePoolSnapshot(const helios::engine::mechanics::scoring::MaxScorePoolSnapshot &snapshot) noexcept
Sets the cached snapshot value.
Sets hasUpdate to true if the value changes. snapshot The snapshot to use for the next update.
ScorePoolRevision helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::scorePoolRevision() const noexcept
Returns the cached score pool revision.
The revision of the last observed snapshot.
double helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::maxScore() const noexcept
Returns the cached max score.
The current high score value.
bool helios::engine::mechanics::scoring::components::MaxScoreObserverComponent::hasUpdate() const noexcept
Checks if the value changed since last clear.
True if the value was updated this frame.