helios.engine.runtime.world.types.ManagerTypeId
using helios::engine::runtime::world::types::ManagerTypeId::ResourceType = helios_engine_core_data_ResourceTypes
size_t helios::engine::runtime::world::types::ManagerTypeId::id_
The underlying ID value.
helios::engine::runtime::world::types::ManagerTypeId::ManagerTypeId(const size_t id)
Constructs a ManagerTypeId with a specific value.
id The type ID value.
References helios::engine::runtime::world::types::ManagerTypeId::id.
Referenced by helios::engine::runtime::world::types::ManagerTypeId::id, helios::engine::runtime::world::types::ManagerTypeId::operator==.
helios::engine::runtime::world::types::ManagerTypeId::ManagerTypeId(helios::core::types::no_init_t)
Constructs an uninitialized ManagerTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::runtime::world::types::ManagerTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
static ManagerTypeId helios::engine::runtime::world::types::ManagerTypeId::id()
Returns the ManagerTypeId for a specific type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The resource type. The unique ManagerTypeId for type T.
References helios::engine::runtime::world::types::ManagerTypeId::ManagerTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::runtime::world::types::ManagerTypeId::ManagerTypeId.
std::size_t std::hash< helios::engine::runtime::world::types::ManagerTypeId >::operator()(const helios::engine::runtime::world::types::ManagerTypeId &id) const noexcept