helios.scene.CameraSceneNode
std::unique_ptr<helios::scene::Camera> helios::scene::CameraSceneNode::camera_
Unique pointer to the camera instance owned by this scene node.
helios::scene::CameraSceneNode::CameraSceneNode(std::unique_ptr< helios::scene::Camera > camera)
Constructs a CameraSceneNode that takes ownership of the given camera.
The CameraSceneNode becomes the sole owner of the Camera instance. The camera's view matrix is automatically updated when `worldTransform()` is called. camera A unique pointer to the camera to be owned by this scene node. std::invalid_argument if camera is a nullptr.
References helios::scene::CameraSceneNode::camera.
SceneNode * helios::scene::CameraSceneNode::addChild(std::unique_ptr< SceneNode > sceneNode) override
Prevents adding child nodes to a camera scene node.
This method does nothing and returns `nullptr`, indicating that a `CameraSceneNode` must not have child nodes. sceneNode The attempted child node to add (ignored). Always returns `nullptr`. https://stackoverflow.com/questions/24609872/delete-virtual-function-from-a-derived-class
References helios::scene::SceneNode::SceneNode.
const helios::scene::Camera & helios::scene::CameraSceneNode::camera() const noexcept
Gets the camera associated with this scene node.
A const ref to the associated camera instance.
Referenced by helios::scene::CameraSceneNode::camera, helios::scene::CameraSceneNode::CameraSceneNode.
helios::scene::Camera & helios::scene::CameraSceneNode::camera() noexcept
Gets the camera associated with this scene node.
A ref to the associated camera instance.
References helios::scene::CameraSceneNode::camera.
void helios::scene::CameraSceneNode::lookAt(helios::math::vec3f target, helios::math::vec3f up)
Orients this camera node to look at a target position in world space.
Computes the rotation matrix required to align this scene node's forward direction with the specified target position. The rotation is computed in world space and then converted to local space by factoring out the parent's rotation. target The world-space coordinates of the target to look at. up The up vector defining the camera's vertical orientation in world space. The camera node must have a valid parent (i.e., must be added to a scene graph). The up vector should typically be `(0, 1, 0)` for standard upright orientation. TodoImplement `lookAtLocal()` for observing nodes in local space. helios::scene::SceneNode::rotate()
References helios::scene::CameraSceneNode::lookAt.
Referenced by helios::scene::CameraSceneNode::lookAt.
const helios::math::mat4f & helios::scene::CameraSceneNode::worldTransform() noexcept override
Computes the world transform and updates the associated camera's view matrix.
This override extends `SceneNode::worldTransform()` by additionally computing the view matrix from the camera's world transform. The view matrix is the inverse of the world transform, with the Z-axis negated to convert from helios' Left-Handed System to OpenGL's Right-Handed clip space. The computed view matrix is automatically assigned to the underlying `Camera` instance. A const reference to this node's world transform matrix. helios::scene::Camera::setViewMatrix() helios::scene::SceneNode::worldTransform()
References helios::scene::CameraSceneNode::worldTransform.
Referenced by helios::scene::CameraSceneNode::worldTransform.