helios.engine.runtime.world.UpdateContext
float helios::engine::runtime::world::UpdateContext::deltaTime_
Time elapsed since the last frame, in seconds.
float helios::engine::runtime::world::UpdateContext::totalTime_
Time elapsed since the first frame, in seconds.
const helios::input::InputSnapshot& helios::engine::runtime::world::UpdateContext::inputSnapshot_
Immutable snapshot of input state for the current frame.
helios::engine::runtime::world::Session& helios::engine::runtime::world::UpdateContext::session_
Reference to the current game session for state tracking.
helios::engine::runtime::messaging::event::GameLoopEventBus::WriteSink helios::engine::runtime::world::UpdateContext::phaseEventSink_
Sink for pushing phase-level events during update.
Used by systems and components to publish events (e.g., collision, spawn requests) that will be processed in the next phase of the game loop.
const helios::engine::runtime::messaging::event::GameLoopEventBus::ReadSource helios::engine::runtime::world::UpdateContext::phaseEventSource_
Source for reading phase-level events from the previous phase.
helios::engine::runtime::messaging::event::GameLoopEventBus::WriteSink helios::engine::runtime::world::UpdateContext::passEventSink_
Sink for pushing pass-level events during update.
Used by systems and components to publish events that will be processed in subsequent passes within the same phase, after a commit point.
const helios::engine::runtime::messaging::event::GameLoopEventBus::ReadSource helios::engine::runtime::world::UpdateContext::passEventSource_
Source for reading pass-level events from previous passes.
helios::engine::runtime::messaging::event::GameLoopEventBus::WriteSink helios::engine::runtime::world::UpdateContext::frameEventSink_
Sink for pushing frame-level events during update.
Used by systems and components to publish events that will be processed in the next frame. Frame-level events persist across all phases and are swapped at the end of the Post phase.
const helios::engine::runtime::messaging::event::GameLoopEventBus::ReadSource helios::engine::runtime::world::UpdateContext::frameEventSource_
Source for reading frame-level events from the previous frame.
std::span<const helios::rendering::ViewportSnapshot> helios::engine::runtime::world::UpdateContext::viewportSnapshots_
Immutable snapshot of all viewport states for this frame.
helios::engine::runtime::world::ResourceRegistry& helios::engine::runtime::world::UpdateContext::resourceRegistry_
Reference to the ResourceRegistry for O(1) resource lookup.
helios::engine::ecs::EntityResolver helios::engine::runtime::world::UpdateContext::entityResolver_
Callable for resolving EntityHandles to GameObjects.
const Level* helios::engine::runtime::world::UpdateContext::level_
Pointer to the active Level, or nullptr if no level is loaded.
helios::engine::runtime::world::UpdateContext::UpdateContext(helios::engine::runtime::world::ResourceRegistry &resourceRegistry, helios::engine::ecs::EntityResolver entityResolver, helios::engine::runtime::world::Session &session, const float deltaTime, const float totalTime, helios::engine::runtime::messaging::event::GameLoopEventBus &phaseEventBus, helios::engine::runtime::messaging::event::GameLoopEventBus &passEventBus, helios::engine::runtime::messaging::event::GameLoopEventBus &frameEventBus, const helios::input::InputSnapshot &inputSnapshot, std::span< const helios::rendering::ViewportSnapshot > viewportSnapshots, const Level *level)
Constructs an UpdateContext with all per-frame dependencies.
resourceRegistry Reference to the ResourceRegistry for resource lookup. entityResolver Callable for resolving EntityHandles to GameObjects. session Reference to the current game session. deltaTime Time since last frame in seconds. totalTime Accumulated time since the first frame in seconds. phaseEventBus Reference to the phase-level event bus. passEventBus Reference to the pass-level event bus. frameEventBus Reference to the frame-level event bus. inputSnapshot Immutable input state for this frame. viewportSnapshots Immutable snapshot of viewport states. level Pointer to the active Level, or nullptr.
References helios::engine::runtime::world::UpdateContext::deltaTime, helios::engine::runtime::world::UpdateContext::entityResolver, helios::engine::runtime::world::UpdateContext::inputSnapshot, helios::engine::runtime::world::UpdateContext::level, helios::engine::runtime::world::UpdateContext::resourceRegistry, helios::engine::runtime::world::UpdateContext::session, helios::engine::runtime::world::UpdateContext::totalTime, helios::engine::runtime::world::UpdateContext::viewportSnapshots.
std::span< const helios::rendering::ViewportSnapshot > helios::engine::runtime::world::UpdateContext::viewportSnapshots() const noexcept
Returns the viewport snapshots for this frame.
A span of const ViewportSnapshot objects.
Referenced by helios::engine::runtime::world::UpdateContext::UpdateContext.
float helios::engine::runtime::world::UpdateContext::deltaTime() const noexcept
Returns the time elapsed since the last frame, in seconds.
Delta time in seconds.
Referenced by helios::engine::runtime::world::UpdateContext::UpdateContext.
float helios::engine::runtime::world::UpdateContext::totalTime() const noexcept
Returns the time elapsed since the first frame, in seconds.
Total time in seconds.
Referenced by helios::engine::runtime::world::UpdateContext::UpdateContext.
const helios::input::InputSnapshot & helios::engine::runtime::world::UpdateContext::inputSnapshot() const noexcept
Returns the immutable input snapshot for this frame.
Const ref to the current InputSnapshot.
Referenced by helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update, helios::engine::runtime::world::UpdateContext::UpdateContext.
helios::engine::runtime::world::ResourceRegistry & helios::engine::runtime::world::UpdateContext::resourceRegistry() noexcept
Returns the ResourceRegistry for resource lookup.
Reference to the ResourceRegistry.
Referenced by helios::engine::runtime::spawn::policy::amount::SpawnAll::getAmount, helios::engine::runtime::gameloop::GameLoop::phaseCommit, helios::engine::runtime::world::UpdateContext::UpdateContext.
const helios::engine::runtime::world::ResourceRegistry & helios::engine::runtime::world::UpdateContext::resourceRegistry() const noexcept
Returns the ResourceRegistry for resource lookup.
Reference to the ResourceRegistry.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::world::UpdateContext::find(helios::engine::ecs::EntityHandle handle) const noexcept
Resolves an EntityHandle to a GameObject.
Validates the handle via the EntityResolver and returns a lightweight GameObject wrapper if the entity is still alive. handle The entity handle to resolve. A GameObject if the handle is valid, std::nullopt otherwise.
Referenced by helios::engine::modules::ui::widgets::systems::MenuDisplaySystem< StateLft, StateRgt >::focusMenu, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerActive, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerInactive, helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
helios::engine::ecs::EntityResolver & helios::engine::runtime::world::UpdateContext::entityResolver() noexcept
Returns the EntityResolver for direct handle validation.
Reference to the EntityResolver.
Referenced by helios::engine::runtime::world::UpdateContext::UpdateContext.
const Level * helios::engine::runtime::world::UpdateContext::level() noexcept
Returns the active Level.
Pointer to the Level, or nullptr if no level is loaded.
Referenced by helios::engine::runtime::world::UpdateContext::UpdateContext.
EngineCommandBuffer & helios::engine::runtime::world::UpdateContext::commandBuffer() const noexcept
Returns the EngineCommandBuffer for submitting commands.
Shortcut for `resourceRegistry().resource<EngineCommandBuffer>()`. Only accepts engine-defined command types. For custom commands, look up the appropriate handler or buffer via `resourceRegistry()` directly. Reference to the EngineCommandBuffer.
Referenced by helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
helios::engine::runtime::world::Session & helios::engine::runtime::world::UpdateContext::session() const noexcept
Returns the session for game/match state access.
Ref to the Session used with this UpdateContext.
Referenced by helios::engine::state::StateManager< types::GameState >::flush, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerActive, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerInactive, helios::engine::runtime::gameloop::TypedPass< StateType >::shouldRun, helios::engine::runtime::world::UpdateContext::UpdateContext.
void helios::engine::runtime::world::UpdateContext::pushPass(Args &&... args)
Pushes an event to the pass-level event bus.
Events pushed here become readable in subsequent passes within the same phase, after a commit point is reached. E The event type to push. Args Constructor argument types for the event. args Arguments forwarded to the event constructor. readPass() Pass::addCommitPoint()
void helios::engine::runtime::world::UpdateContext::pushPhase(Args &&... args)
Pushes an event to the phase-level event bus.
Events pushed here become readable in subsequent phases, after the current phase commits. E The event type to push. Args Constructor argument types for the event. args Arguments forwarded to the event constructor. readPhase() GameLoop
std::span< const E > helios::engine::runtime::world::UpdateContext::readPhase()
Reads events from the phase-level event bus.
Returns events that were pushed during the previous phase via `pushPhase()`. The phase event bus is swapped at phase boundaries, configured in GameLoop::phaseCommit(). E The event type to read. A span of const events of type E. pushPhase() GameLoop
std::span< const E > helios::engine::runtime::world::UpdateContext::readPass()
Reads events from the pass-level event bus.
Returns events that were pushed during previous passes within the current phase via `pushPass()`. The pass event bus is swapped at commit points, configured via Pass::addCommitPoint(). E The event type to read. A span of const events of type E. pushPass() Pass::addCommitPoint()
std::span< const E > helios::engine::runtime::world::UpdateContext::readFrame()
Reads events from the frame-level event bus.
Returns events that were pushed during the previous frame via `pushFrame()`. The frame event bus is swapped at the end of the Post phase, making events readable in the subsequent frame. Frame-level events are useful for cross-frame communication, such as: Collision events that trigger effects in the next frame Spawn confirmations for UI updates Audio/VFX triggers E The event type to read. A span of const events of type E. pushFrame() GameLoop
void helios::engine::runtime::world::UpdateContext::pushFrame(Args &&... args)
Pushes an event to the frame-level event bus.
Events pushed here become readable in the next frame via `readFrame()`. The frame event bus is swapped at the end of the Post phase in GameLoop. Use frame-level events for cross-frame communication where events should persist beyond the current phase. E The event type to push. Args Constructor argument types for the event. args Arguments forwarded to the event constructor. readFrame() GameLoop
auto helios::engine::runtime::world::UpdateContext::view()
Creates a View for querying entities with the given component types.
Convenience shortcut that avoids accessing the GameWorld directly. Delegates to the EntityManager owned by the EntityResolver. Components The component types to query. A View over all entities possessing every requested component. helios::engine::ecs::View
Referenced by helios::engine::ecs::systems::HierarchyPropagationSystem::update, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update, helios::engine::modules::ui::widgets::systems::MenuNavigationSystem::update.
auto helios::engine::runtime::world::UpdateContext::view() const
Creates a View for querying entities with the given component types.
Convenience shortcut that avoids accessing the GameWorld directly. Delegates to the EntityManager owned by the EntityResolver. Components The component types to query. A View over all entities possessing every requested component. helios::engine::ecs::View