helios.ecs.Entity
using helios::ecs::Entity< TEntityManager >::Handle_type = TEntityManager::Handle_type
using helios::ecs::Entity< TEntityManager >::ComponentTypeId_type = ComponentTypeId<Handle_type>
using helios::ecs::Entity< TEntityManager >::ComponentOpsRegistry_type = ComponentOpsRegistry<Handle_type>
using helios::ecs::Entity< TEntityManager >::HierarchyComponent_type = components::HierarchyComponent<Handle_type>
using helios::ecs::Entity< TEntityManager >::InactiveComponent_type = components::Inactive<Handle_type>
using helios::ecs::Entity< TEntityManager >::ActiveComponent_type = components::Active<Handle_type>
TEntityManager::Handle_type helios::ecs::Entity< TEntityManager >::entityHandle_
The underlying entity identifier.
TEntityManager* helios::ecs::Entity< TEntityManager >::entityManager_
Non-owning pointer to the EntityManager.
helios::ecs::Entity< TEntityManager >::Entity(const Handle_type entityHandle, TEntityManager *entityManager) noexcept
Constructs a Entity wrapper.
entityHandle The entity handle to wrap. entityManager Pointer to the EntityManager. Must not be null.
std::generator< ComponentTypeId_type > helios::ecs::Entity< TEntityManager >::componentTypeIds() const
Returns a generator over all component type IDs attached to this entity.
Generator yielding ComponentTypeId for each attached component.
Referenced by helios::ecs::Entity< TEntityManager >::onAcquire, helios::ecs::Entity< TEntityManager >::onRelease, helios::ecs::Entity< TEntityManager >::setActive.
Handle_type helios::ecs::Entity< TEntityManager >::handle() noexcept
Returns the underlying entity handle.
The EntityHandle for this Entity.
Handle_type helios::ecs::Entity< TEntityManager >::handle() const noexcept
Returns the underlying entity handle (const).
The EntityHandle for this Entity.
T & helios::ecs::Entity< TEntityManager >::add(Args &&...args)
Constructs and attaches a component to this entity.
If the entity is active, calls `onActivate()` on the new component. If inactive, calls `onDeactivate()`. T The component type to add. Args Constructor argument types. args Arguments forwarded to the component constructor. Reference to the newly created component.
References helios::ecs::Entity< TEntityManager >::has, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::Entity< TEntityManager >::raw.
Referenced by helios::ecs::Entity< TEntityManager >::getOrAdd.
T & helios::ecs::Entity< TEntityManager >::getOrAdd(Args &&...args)
Returns existing component or creates a new one.
T The component type. Args Constructor argument types. args Arguments forwarded to the constructor if creating. Reference to the existing or newly created component.
References helios::ecs::Entity< TEntityManager >::add, helios::ecs::Entity< TEntityManager >::get, helios::ecs::Entity< TEntityManager >::has.
bool helios::ecs::Entity< TEntityManager >::remove()
Removes a component from this entity.
T The component type to remove. True if the component was removed, false if not present.
References helios::ecs::Entity< TEntityManager >::remove.
Referenced by helios::ecs::Entity< TEntityManager >::remove, helios::ecs::Entity< TEntityManager >::setActive.
void * helios::ecs::Entity< TEntityManager >::raw(const ComponentTypeId_type typeId)
Returns raw pointer to component by type ID.
typeId The component type identifier. Raw void pointer to the component, or nullptr if not found.
References helios::ecs::Entity< TEntityManager >::raw.
Referenced by helios::ecs::Entity< TEntityManager >::add, helios::ecs::Entity< TEntityManager >::onAcquire, helios::ecs::Entity< TEntityManager >::onRelease, helios::ecs::Entity< TEntityManager >::raw, helios::ecs::Entity< TEntityManager >::setActive.
T * helios::ecs::Entity< TEntityManager >::get()
Returns pointer to a component.
T The component type. Pointer to the component, or nullptr if not attached.
References helios::ecs::Entity< TEntityManager >::get.
Referenced by helios::ecs::Entity< TEntityManager >::get, helios::ecs::Entity< TEntityManager >::get, helios::ecs::Entity< TEntityManager >::getOrAdd, helios::ecs::Entity< TEntityManager >::setActive.
const T * helios::ecs::Entity< TEntityManager >::get() const
Returns const pointer to a component.
T The component type. Const pointer to the component, or nullptr if not attached.
References helios::ecs::Entity< TEntityManager >::get.
bool helios::ecs::Entity< TEntityManager >::has() const noexcept
Checks if this entity has a specific component type.
T The component type to check. True if the component is attached, false otherwise.
References helios::ecs::Entity< TEntityManager >::has.
Referenced by helios::ecs::Entity< TEntityManager >::add, helios::ecs::Entity< TEntityManager >::getOrAdd, helios::ecs::Entity< TEntityManager >::has, helios::ecs::Entity< TEntityManager >::has, helios::ecs::Entity< TEntityManager >::isActive, helios::ecs::Entity< TEntityManager >::setActive.
bool helios::ecs::Entity< TEntityManager >::has(ComponentTypeId_type typeId) const noexcept
Checks if this entity has a component by type ID.
typeId The component type identifier. True if the component is attached, false otherwise.
References helios::ecs::Entity< TEntityManager >::has.
void helios::ecs::Entity< TEntityManager >::enableComponent(const ComponentTypeId_type typeId)
Enables a specific component by type ID.
typeId The component type identifier.
void helios::ecs::Entity< TEntityManager >::disableComponent(const ComponentTypeId_type typeId)
Disables a specific component by type ID.
typeId The component type identifier.
void helios::ecs::Entity< TEntityManager >::setActive(const bool active)
Sets the activation state of this Entity.
When deactivated: An `Inactive` tag component is added The `Active` tag component is removed `onDeactivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation When activated: The `Inactive` tag component is removed An `Active` tag component is added `onActivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation Does **not** call `enable()`/`disable()` on components. active True to activate, false to deactivate. HierarchyComponent_type HierarchyPropagationSystem
References helios::ecs::Entity< TEntityManager >::componentTypeIds, helios::ecs::Entity< TEntityManager >::get, helios::ecs::Entity< TEntityManager >::has, helios::ecs::Entity< TEntityManager >::isActive, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::Entity< TEntityManager >::raw, helios::ecs::Entity< TEntityManager >::remove.
bool helios::ecs::Entity< TEntityManager >::isActive() const
Returns whether this Entity is active.
True if the entity has the Active tag component.
References helios::ecs::Entity< TEntityManager >::has.
Referenced by helios::ecs::Entity< TEntityManager >::setActive.
void helios::ecs::Entity< TEntityManager >::onRelease()
Notifies all components that the entity is being released to a pool.
Iterates through all attached components and calls `onRelease()` on those that implement it.
References helios::ecs::Entity< TEntityManager >::componentTypeIds, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::Entity< TEntityManager >::raw.
void helios::ecs::Entity< TEntityManager >::onAcquire()
Notifies all components that the entity is being acquired from a pool.
Iterates through all attached components and calls `onAcquire()` on those that implement it.
References helios::ecs::Entity< TEntityManager >::componentTypeIds, helios::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::ecs::Entity< TEntityManager >::raw.