helios.engine.modules.physics.collision.components.AabbColliderComponent
helios::math::aabbf helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds_
The local bounds of the collider.
helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent()=default
Default constructor.
Referenced by helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent.
helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent(const AabbColliderComponent &other)
Copy constructor.
Preserves the bounds of this component.
References helios::engine::modules::physics::collision::components::AabbColliderComponent::AabbColliderComponent.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::onAcquire() noexcept override
Resets the bounds to invalidate state when this Component is acquired.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::onRelease() noexcept override
Resets the bounds to invalidate state when this Component is released.
const helios::math::aabbf & helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds()
Retrieves the bounds of the collider.
A const reference to the AABB.
Referenced by helios::engine::modules::physics::collision::components::AabbColliderComponent::setBounds, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
void helios::engine::modules::physics::collision::components::AabbColliderComponent::setBounds(const helios::math::aabbf &bounds)
Sets the bounds of the collider.
bounds The new AABB to set.
References helios::engine::modules::physics::collision::components::AabbColliderComponent::bounds.
bool helios::engine::modules::physics::collision::components::AabbColliderComponent::boundsInitialized() const noexcept
Checks whether the bounds of the collider have been initialized.
Bounds of the collider component are considered to be initialized if the minimum X coordinate is less or equal to the maximum X coordinate. true if the bounds are considered to be initialized; otherwise, false.