helios.engine.mechanics.combat.components.Aim2DComponent
helios::math::vec2f helios::engine::mechanics::combat::components::Aim2DComponent::direction_
Current aim direction as normalized 2D vector.
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::aim, helios::engine::mechanics::combat::components::Aim2DComponent::direction.
float helios::engine::mechanics::combat::components::Aim2DComponent::frequency_
Current frequency factor (0.0 to 1.0) for additional fire rate control.
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::aim, helios::engine::mechanics::combat::components::Aim2DComponent::frequency.
bool helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled_
Whether this component is enabled.
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::disable, helios::engine::mechanics::combat::components::Aim2DComponent::enable, helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled.
bool helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled_.
void helios::engine::mechanics::combat::components::Aim2DComponent::enable() noexcept
Enables this component.
References helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled_.
void helios::engine::mechanics::combat::components::Aim2DComponent::disable() noexcept
Disables this component.
References helios::engine::mechanics::combat::components::Aim2DComponent::isEnabled_.
helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent()=default
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent, helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent, helios::engine::mechanics::combat::components::Aim2DComponent::operator=, helios::engine::mechanics::combat::components::Aim2DComponent::operator=.
helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent(const Aim2DComponent &)=default
References helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent.
Aim2DComponent & helios::engine::mechanics::combat::components::Aim2DComponent::operator=(const Aim2DComponent &)=default
References helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent.
helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent(Aim2DComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent.
Aim2DComponent & helios::engine::mechanics::combat::components::Aim2DComponent::operator=(Aim2DComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::Aim2DComponent::Aim2DComponent.
void helios::engine::mechanics::combat::components::Aim2DComponent::aim(helios::math::vec2f direction, float freq)
Sets the aim direction and fire frequency.
direction Normalized 2D direction vector. freq Fire frequency factor (0.0 to 1.0).
References helios::engine::mechanics::combat::components::Aim2DComponent::aim, helios::engine::mechanics::combat::components::Aim2DComponent::direction, helios::engine::mechanics::combat::components::Aim2DComponent::direction_, helios::math::EPSILON_LENGTH, helios::engine::mechanics::combat::components::Aim2DComponent::frequency_.
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::aim.
const helios::math::vec2f & helios::engine::mechanics::combat::components::Aim2DComponent::direction() const noexcept
Returns the current aim direction.
Const reference to the normalized 2D direction vector.
References helios::engine::mechanics::combat::components::Aim2DComponent::direction_.
Referenced by helios::engine::mechanics::combat::components::Aim2DComponent::aim.
float helios::engine::mechanics::combat::components::Aim2DComponent::frequency() const noexcept
Returns the current frequency factor.
Fire frequency factor in range [0.0, 1.0].
References helios::engine::mechanics::combat::components::Aim2DComponent::frequency_.