helios.engine.game.components.physics.CollisionComponent
const uint32_t helios::engine::game::components::physics::CollisionComponent::layerId_
The collision layer this component belongs to.
uint32_t helios::engine::game::components::physics::CollisionComponent::triggerCollisionMask_
Bitmask specifying layers that generate trigger collisions.
Trigger collision masks may be asymmetric, i.e. a component B must not know about the existence of another layerId.
uint32_t helios::engine::game::components::physics::CollisionComponent::solidCollisionMask_
Bitmask specifying layers that generate solid collisions.
Solid collision should be symmetric and in the calling API treated as such: `(maskB & thisLayerId) != 0 && (thisMask & layerBId) != 0`
bool helios::engine::game::components::physics::CollisionComponent::isCollisionReporter_
Flag indicating whether this component can report collision events.
helios::engine::game::components::physics::CollisionComponent::CollisionComponent(uint32_t layerId, bool isCollisionReporter=true)
Constructs a CollisionComponent with a layer ID.
layerId The collision layer this entity belongs to. isCollisionReporter Whether this entity can emit collision events.
References helios::engine::game::components::physics::CollisionComponent::isCollisionReporter, helios::engine::game::components::physics::CollisionComponent::layerId.
Referenced by helios::engine::game::components::physics::CollisionComponent::setSolidCollisionMask, helios::engine::game::components::physics::CollisionComponent::setTriggerCollisionMask.
bool helios::engine::game::components::physics::CollisionComponent::isCollisionReporter() const noexcept
Returns whether this component can emit collision events.
True if collision events can be generated, false otherwise.
Referenced by helios::engine::game::components::physics::CollisionComponent::CollisionComponent.
CollisionComponent & helios::engine::game::components::physics::CollisionComponent::setSolidCollisionMask(const uint32_t solidCollisionMask) noexcept
Sets the solid collision mask.
solidCollisionMask Bitmask of layers to generate solid collisions with. Reference to this component for method chaining.
References helios::engine::game::components::physics::CollisionComponent::CollisionComponent, helios::engine::game::components::physics::CollisionComponent::solidCollisionMask.
CollisionComponent & helios::engine::game::components::physics::CollisionComponent::setTriggerCollisionMask(const uint32_t triggerCollisionMask) noexcept
Sets the trigger collision mask.
triggerCollisionMask Bitmask of layers to generate trigger collisions with. Reference to this component for method chaining.
References helios::engine::game::components::physics::CollisionComponent::CollisionComponent, helios::engine::game::components::physics::CollisionComponent::triggerCollisionMask.
uint32_t helios::engine::game::components::physics::CollisionComponent::solidCollisionMask() const noexcept
Returns the solid collision mask.
Bitmask of layers this entity generates solid collisions with.
Referenced by helios::engine::game::components::physics::CollisionComponent::setSolidCollisionMask, helios::engine::game::systems::physics::GridCollisionDetectionSystem::update.
uint32_t helios::engine::game::components::physics::CollisionComponent::triggerCollisionMask() const noexcept
Returns the trigger collision mask.
Bitmask of layers this entity generates trigger collisions with.
Referenced by helios::engine::game::components::physics::CollisionComponent::setTriggerCollisionMask, helios::engine::game::systems::physics::GridCollisionDetectionSystem::update.
unsigned int helios::engine::game::components::physics::CollisionComponent::layerId() const noexcept
Returns the collision layer ID.
The layer this entity belongs to.
Referenced by helios::engine::game::components::physics::CollisionComponent::CollisionComponent.