helios.engine.mechanics.timing.GameTimer
TimerRevision helios::engine::mechanics::timing::GameTimer::timerRevision_
Monotonically increasing revision counter, incremented on each update.
GameTimerId helios::engine::mechanics::timing::GameTimer::gameTimerId_
Unique identifier for this timer.
float helios::engine::mechanics::timing::GameTimer::elapsed_
Accumulated elapsed time in seconds.
TimerState helios::engine::mechanics::timing::GameTimer::timerState_
Current state of the timer.
float helios::engine::mechanics::timing::GameTimer::duration_
Optional duration limit in seconds.
helios::engine::mechanics::timing::GameTimer::GameTimer(const helios::engine::mechanics::timing::types::GameTimerId gameTimerId)
Constructs a GameTimer with the given identifier.
gameTimerId The unique identifier for this timer.
References helios::engine::mechanics::timing::GameTimer::gameTimerId.
helios::engine::mechanics::timing::types::GameTimerId helios::engine::mechanics::timing::GameTimer::gameTimerId() const noexcept
Returns the timer identifier.
The GameTimerId assigned to this timer.
Referenced by helios::engine::mechanics::timing::GameTimer::GameTimer.
void helios::engine::mechanics::timing::GameTimer::reset(const TimerState state=TimerState::Undefined) noexcept
Resets the elapsed time to zero and sets timer state to Undefined.
state The new TimerState the timer should be resetted to.
References helios::engine::mechanics::timing::GameTimer::setState, helios::engine::mechanics::timing::GameTimer::state, helios::engine::mechanics::timing::types::Undefined.
void helios::engine::mechanics::timing::GameTimer::setDuration(float duration)
Sets the duration limit.
duration Duration in seconds.
References helios::engine::mechanics::timing::GameTimer::duration.
float helios::engine::mechanics::timing::GameTimer::duration() const noexcept
Returns the duration limit.
The duration in seconds.
Referenced by helios::engine::mechanics::timing::GameTimer::setDuration.
float helios::engine::mechanics::timing::GameTimer::elapsed() const noexcept
Returns the accumulated elapsed time.
Elapsed time in seconds.
TimerState helios::engine::mechanics::timing::GameTimer::state() const noexcept
Returns the current timer state.
The current TimerState.
Referenced by helios::engine::mechanics::timing::GameTimer::reset, helios::engine::mechanics::timing::GameTimer::setState.
void helios::engine::mechanics::timing::GameTimer::setState(const TimerState state) noexcept
Sets the timer state.
state The new TimerState.
References helios::engine::mechanics::timing::GameTimer::state.
Referenced by helios::engine::mechanics::timing::GameTimer::reset.
bool helios::engine::mechanics::timing::GameTimer::shouldUpdate() const noexcept
Returns whether this timer should accumulate time.
True if the timer is in the Started state.
References helios::engine::mechanics::timing::types::Started.
Referenced by helios::engine::mechanics::timing::GameTimer::update.
TimerRevision helios::engine::mechanics::timing::GameTimer::timerRevision() const noexcept
Returns the current revision counter.
The TimerRevision value.
void helios::engine::mechanics::timing::GameTimer::update(const float ft)
Advances the timer by the given frame time.
Only accumulates time when the timer is in the Started state. Increments the revision counter on each successful update. ft Frame time in seconds.
References helios::engine::mechanics::timing::GameTimer::shouldUpdate.