helios.engine.mechanics.combat.components.ShootComponent
float helios::engine::mechanics::combat::components::ShootComponent::intensity_
Current fire intensity (0.0 to 1.0).
Set by shoot() and cleared when intensity is zero. Controls whether projectiles are spawned during update().
Referenced by helios::engine::mechanics::combat::components::ShootComponent::intensity, helios::engine::mechanics::combat::components::ShootComponent::shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta_
Cooldown interval between shots, in seconds.
Derived from fireRate (1.0 / fireRate). Determines the minimum time that must pass between consecutive projectile spawns.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta, helios::engine::mechanics::combat::components::ShootComponent::setFireRate.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer_
Accumulated time since last shot, in seconds.
Accumulates delta time multiplied by intensity. When this value exceeds cooldownDelta, projectiles are spawned and the timer is reduced.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer, helios::engine::mechanics::combat::components::ShootComponent::setCooldownTimer, helios::engine::mechanics::combat::components::ShootComponent::updateCooldownTimerBy.
float helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed_
The projectile speed, in meters per second.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed, helios::engine::mechanics::combat::components::ShootComponent::setProjectileSpeed.
helios::math::vec3f helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity_
Velocity of the source object in three-dimensional space.
Used to adjust the trajectory of projectiles emitted by the source's movement.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::shoot, helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity.
float helios::engine::mechanics::combat::components::ShootComponent::fireRate_
Fire rate per second, i.e. projectiles than can be shot per second.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::fireRate, helios::engine::mechanics::combat::components::ShootComponent::setFireRate.
bool helios::engine::mechanics::combat::components::ShootComponent::isEnabled_
Whether this component is enabled.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::disable, helios::engine::mechanics::combat::components::ShootComponent::enable, helios::engine::mechanics::combat::components::ShootComponent::isEnabled.
bool helios::engine::mechanics::combat::components::ShootComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References helios::engine::mechanics::combat::components::ShootComponent::isEnabled_.
void helios::engine::mechanics::combat::components::ShootComponent::enable() noexcept
Enables this component.
References helios::engine::mechanics::combat::components::ShootComponent::isEnabled_.
void helios::engine::mechanics::combat::components::ShootComponent::disable() noexcept
Disables this component.
References helios::engine::mechanics::combat::components::ShootComponent::isEnabled_.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent()=default
Constructs a new ShootComponent with default settings.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::operator=, helios::engine::mechanics::combat::components::ShootComponent::operator=, helios::engine::mechanics::combat::components::ShootComponent::ShootComponent, helios::engine::mechanics::combat::components::ShootComponent::ShootComponent.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent(const ShootComponent &)=default
References helios::engine::mechanics::combat::components::ShootComponent::ShootComponent.
ShootComponent & helios::engine::mechanics::combat::components::ShootComponent::operator=(const ShootComponent &)=default
References helios::engine::mechanics::combat::components::ShootComponent::ShootComponent.
helios::engine::mechanics::combat::components::ShootComponent::ShootComponent(ShootComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::ShootComponent::ShootComponent.
ShootComponent & helios::engine::mechanics::combat::components::ShootComponent::operator=(ShootComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::ShootComponent::ShootComponent.
void helios::engine::mechanics::combat::components::ShootComponent::shoot(const float intensity, const helios::math::vec3f sourceVelocity)
Sets the shooting intensity.
Call with a non-zero value to start shooting, or zero to stop. The intensity affects whether projectiles are spawned during update(). intensity Fire intensity (0.0 to 1.0). Zero stops firing. sourceVelocity The velocity of the object emitting the projectile.
References helios::math::EPSILON_LENGTH, helios::engine::mechanics::combat::components::ShootComponent::intensity, helios::engine::mechanics::combat::components::ShootComponent::intensity_, helios::engine::mechanics::combat::components::ShootComponent::shoot, helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity, helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity_.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta() const noexcept
Returns the cooldown interval between shots.
Cooldown interval in seconds (derived from 1.0 / fireRate).
References helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta_.
float helios::engine::mechanics::combat::components::ShootComponent::intensity() const noexcept
Returns the current fire intensity.
The intensity value (0.0 to 1.0).
References helios::engine::mechanics::combat::components::ShootComponent::intensity_.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::shoot.
float helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer() const noexcept
Returns the accumulated time since last shot.
Accumulated cooldown timer in seconds.
References helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer_.
void helios::engine::mechanics::combat::components::ShootComponent::setCooldownTimer(float cooldown) noexcept
Sets the accumulated cooldown timer.
cooldown New timer value in seconds.
References helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer_.
void helios::engine::mechanics::combat::components::ShootComponent::updateCooldownTimerBy(float delta) noexcept
Adds delta time to the cooldown timer.
delta Time to add in seconds.
References helios::engine::mechanics::combat::components::ShootComponent::cooldownTimer_.
float helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed() const noexcept
Returns the projectile speed.
Projectile speed in meters per second.
References helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed_.
void helios::engine::mechanics::combat::components::ShootComponent::setProjectileSpeed(float speed) noexcept
Sets the projectile speed.
speed New projectile speed in meters per second.
References helios::engine::mechanics::combat::components::ShootComponent::projectileSpeed_.
helios::math::vec3f helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity() const noexcept
Returns the source object's velocity.
Velocity vector used for projectile trajectory adjustment.
References helios::engine::mechanics::combat::components::ShootComponent::sourceVelocity_.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::shoot.
float helios::engine::mechanics::combat::components::ShootComponent::fireRate() const noexcept
Returns the fire rate in projectiles per second.
Fire rate (projectiles/second).
References helios::engine::mechanics::combat::components::ShootComponent::fireRate_.
Referenced by helios::engine::mechanics::combat::components::ShootComponent::setFireRate.
void helios::engine::mechanics::combat::components::ShootComponent::setFireRate(const float fireRate) noexcept
Sets the fire rate.
Updates the cooldown delta based on the new fire rate. fireRate The number of projectiles per second. Must be greater than zero.
References helios::engine::mechanics::combat::components::ShootComponent::cooldownDelta_, helios::math::EPSILON_LENGTH, helios::engine::mechanics::combat::components::ShootComponent::fireRate, helios::engine::mechanics::combat::components::ShootComponent::fireRate_.