helios.engine.game.GameObjectPool
using helios::engine::game::GameObjectPool::Factory = std::function<std::unique_ptr<helios::engine::game::GameObject>()>
Factory function type for creating new GameObjects.
The factory is invoked during pool warmup to create all pooled objects. It should return a fully configured GameObject ready for use.
std::unordered_map<helios::util::Guid, size_t> helios::engine::game::GameObjectPool::activeIndex_
Maps active GameObject Guids to their index in activeGameObjects_.
Enables O(1) lookup for release operations.
Referenced by helios::engine::game::GameObjectPool::acquire, helios::engine::game::GameObjectPool::release.
std::vector<helios::util::Guid> helios::engine::game::GameObjectPool::activeGameObjects_
List of Guids for currently active (in-use) GameObjects.
Referenced by helios::engine::game::GameObjectPool::acquire, helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::release.
std::vector<helios::util::Guid> helios::engine::game::GameObjectPool::inactiveGameObjects_
List of Guids for currently inactive (available) GameObjects.
Referenced by helios::engine::game::GameObjectPool::acquire, helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::inactiveGameObjects, helios::engine::game::GameObjectPool::release, helios::engine::game::GameObjectPool::warmup.
size_t helios::engine::game::GameObjectPool::poolSize_
The maximum number of objects this pool manages.
Referenced by helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::warmup.
helios::engine::game::GameWorld& helios::engine::game::GameObjectPool::gameWorld_
Reference to the GameWorld that owns the pooled GameObjects.
Referenced by helios::engine::game::GameObjectPool::acquire, helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::inactiveGameObjects, helios::engine::game::GameObjectPool::release, helios::engine::game::GameObjectPool::warmup.
Factory helios::engine::game::GameObjectPool::gameObjectFactory_
Factory function used to create new GameObjects during warmup.
Referenced by helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::warmup.
const helios::util::Guid helios::engine::game::GameObjectPool::guid_
Unique identifier for this pool instance.
Referenced by helios::engine::game::GameObjectPool::GameObjectPool, helios::engine::game::GameObjectPool::guid.
void helios::engine::game::GameObjectPool::warmup()
Pre-allocates all pooled objects and adds them to the GameWorld.
Creates poolSize_ GameObjects using the factory, sets them inactive, adds them to the GameWorld, and tracks their Guids for later acquisition. Called automatically during construction.
References helios::engine::game::GameObjectPool::gameObjectFactory_, helios::engine::game::GameObjectPool::gameWorld_, helios::engine::game::GameObjectPool::guid, helios::engine::game::GameObjectPool::inactiveGameObjects_, helios::engine::game::GameObjectPool::poolSize_.
Referenced by helios::engine::game::GameObjectPool::GameObjectPool.
helios::engine::game::GameObjectPool::GameObjectPool(helios::engine::game::GameWorld &gameWorld, Factory gameObjectFactory, size_t poolSize)
Constructs a new GameObjectPool.
gameWorld Reference to the GameWorld that will own the pooled objects. gameObjectFactory Factory function to create new GameObjects. poolSize Number of objects to pre-allocate in the pool. The pool immediately calls warmup() to pre-allocate all objects.
References helios::engine::game::GameObjectPool::activeGameObjects_, helios::engine::game::GameObjectPool::gameObjectFactory_, helios::engine::game::GameObjectPool::gameWorld_, helios::engine::game::GameObjectPool::guid_, helios::engine::game::GameObjectPool::inactiveGameObjects_, helios::engine::game::GameObjectPool::poolSize_, helios::engine::game::GameObjectPool::warmup.
helios::util::Guid helios::engine::game::GameObjectPool::guid() const noexcept
Returns the unique identifier of this pool.
The Guid assigned to this pool instance.
References helios::engine::game::GameObjectPool::guid_.
Referenced by helios::engine::game::GameObjectPool::acquire, helios::engine::game::GameObjectPool::inactiveGameObjects, helios::engine::game::GameObjectPool::release, helios::engine::game::GameObjectPool::warmup.
helios::engine::game::GameObject * helios::engine::game::GameObjectPool::acquire()
Acquires the next available GameObject from the pool.
Retrieves an inactive GameObject, validates it against the GameWorld, marks it as active, and returns it. If a Guid references an object that no longer exists in the GameWorld (e.g., externally removed), it is silently discarded and the next available object is tried. Pointer to an activated GameObject, or nullptr if the pool is exhausted. The returned object is marked as active and tracked internally. Call release() to return it to the pool when done.
References helios::engine::game::GameObjectPool::activeGameObjects_, helios::engine::game::GameObjectPool::activeIndex_, helios::engine::game::GameObjectPool::gameWorld_, helios::engine::game::GameObjectPool::guid, helios::engine::game::GameObjectPool::inactiveGameObjects_.
bool helios::engine::game::GameObjectPool::release(const helios::engine::game::GameObject *gameObject)
Releases a GameObject back to the pool.
gameObject Pointer to the GameObject to release. May be nullptr. True if the object was successfully released, false if gameObject was nullptr or not tracked by this pool.
References helios::engine::game::GameObject::guid, helios::engine::game::GameObjectPool::release.
Referenced by helios::engine::game::GameObjectPool::release.
bool helios::engine::game::GameObjectPool::release(const helios::util::Guid &guid)
Releases a GameObject back to the pool by its Guid.
Validates the Guid against both the GameWorld and the active tracking list. Uses swap-and-pop for O(1) removal from the active list. The object is marked inactive and added to the inactive list for future acquisition. guid The unique identifier of the GameObject to release. True if the object was successfully released, false if the Guid was not found in the GameWorld or not tracked as active.
References helios::engine::game::GameObjectPool::activeGameObjects_, helios::engine::game::GameObjectPool::activeIndex_, helios::engine::game::GameObjectPool::gameWorld_, helios::engine::game::GameObjectPool::guid, helios::engine::game::GameObjectPool::inactiveGameObjects_.
std::vector< helios::engine::game::GameObject * > helios::engine::game::GameObjectPool::inactiveGameObjects()
Retrieves all currently inactive GameObjects.
Iterates the inactive Guid list and resolves each to a GameObject pointer. Objects that no longer exist in the GameWorld are silently skipped. Vector of pointers to inactive GameObjects. The vector may be smaller than the inactive count if some objects were externally removed. This operation has O(n) complexity where n is the number of inactive objects.
References helios::engine::game::GameObjectPool::gameWorld_, helios::engine::game::GameObjectPool::guid, helios::engine::game::GameObjectPool::inactiveGameObjects_.