helios.engine.core.data.SystemTypeId
using helios::engine::core::data::SystemTypeId::SystemType = helios_engine_core_data_SystemTypes
size_t helios::engine::core::data::SystemTypeId::id_
The underlying ID value.
helios::engine::core::data::SystemTypeId::SystemTypeId(const size_t id)
Constructs a SystemTypeId with a specific value.
id The type ID value.
References helios::engine::core::data::SystemTypeId::id.
Referenced by helios::engine::core::data::SystemTypeId::id, helios::engine::core::data::SystemTypeId::operator==.
helios::engine::core::data::SystemTypeId::SystemTypeId(helios::core::types::no_init_t)
Constructs an uninitialized SystemTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::core::data::SystemTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
Referenced by helios::engine::runtime::world::SystemRegistry::add, helios::engine::runtime::world::SystemRegistry::getSystem.
static SystemTypeId helios::engine::core::data::SystemTypeId::id()
Returns the SystemTypeId for a specific type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The resource type. The unique SystemTypeId for type T.
References helios::engine::core::data::SystemTypeId::SystemTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::runtime::world::SystemRegistry::add, helios::engine::runtime::world::SystemRegistry::getSystem, helios::engine::core::data::SystemTypeId::SystemTypeId.
std::size_t std::hash< helios::engine::core::data::SystemTypeId >::operator()(const helios::engine::core::data::SystemTypeId &id) const noexcept