helios.engine.builder.gameObject.builders.configs.CollisionConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::CollisionConfig::gameObject_
Non-owning pointer to the target GameObject.
void helios::engine::builder::gameObject::builders::configs::CollisionConfig::ensureCollisionComponent(const bool isAvailable) const noexcept
Validates CollisionComponent presence.
isAvailable Whether the component should exist.
helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a CollisionConfig and adds CollisionStateComponent.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::CollisionConfig::hitPolicy, helios::engine::builder::gameObject::builders::configs::CollisionConfig::layerId, helios::engine::builder::gameObject::builders::configs::CollisionConfig::onSolidCollision, helios::engine::builder::gameObject::builders::configs::CollisionConfig::reportCollisions, helios::engine::builder::gameObject::builders::configs::CollisionConfig::solidCollisionMask, helios::engine::builder::gameObject::builders::configs::CollisionConfig::useBoundingBox.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::useBoundingBox()
Adds AABB collider for bounding box collision.
Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::layerId(const uint32_t layerId)
Sets the collision layer ID.
layerId The layer this entity belongs to. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig, helios::engine::builder::gameObject::builders::configs::CollisionConfig::layerId.
Referenced by helios::engine::builder::gameObject::builders::configs::CollisionConfig::layerId.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::hitPolicy(const helios::engine::modules::physics::collision::types::HitPolicy hitPolicy)
Sets the hit policy for collision detection.
Controls how many collision events this entity receives per frame: `OneHit`: Only the first collision is reported (default) `All`: All collisions with overlapping entities are reported hitPolicy The hit policy to apply. Reference to this config for chaining. HitPolicy
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig, helios::engine::builder::gameObject::builders::configs::CollisionConfig::hitPolicy.
Referenced by helios::engine::builder::gameObject::builders::configs::CollisionConfig::hitPolicy.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::reportCollisions(bool isCollisionReporter)
Sets whether this entity reports collisions.
isCollisionReporter True to generate collision events. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::solidCollisionMask(const uint32_t solidCollisionMask)
Sets the solid collision mask.
solidCollisionMask Bitmask of layers to collide with. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig, helios::engine::builder::gameObject::builders::configs::CollisionConfig::solidCollisionMask.
Referenced by helios::engine::builder::gameObject::builders::configs::CollisionConfig::solidCollisionMask.
CollisionConfig & helios::engine::builder::gameObject::builders::configs::CollisionConfig::onSolidCollision(const uint32_t otherLayerId, const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior)
Adds a collision behavior for a specific layer.
otherLayerId The layer to respond to. collisionBehavior The behavior when colliding. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::CollisionConfig::CollisionConfig.