helios.engine.modules.scene.components.SceneNodeComponent
helios::scene::SceneNode* helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_
Non-owning pointer to the associated SceneNode.
Referenced by helios::engine::modules::scene::components::SceneNodeComponent::onActivate, helios::engine::modules::scene::components::SceneNodeComponent::onClone, helios::engine::modules::scene::components::SceneNodeComponent::onDeactivate, helios::engine::modules::scene::components::SceneNodeComponent::sceneNode, helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
bool helios::engine::modules::scene::components::SceneNodeComponent::isEnabled_
Whether this component is enabled.
Referenced by helios::engine::modules::scene::components::SceneNodeComponent::disable, helios::engine::modules::scene::components::SceneNodeComponent::enable, helios::engine::modules::scene::components::SceneNodeComponent::isEnabled.
bool helios::engine::modules::scene::components::SceneNodeComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References helios::engine::modules::scene::components::SceneNodeComponent::isEnabled_.
void helios::engine::modules::scene::components::SceneNodeComponent::enable() noexcept
Enables this component.
References helios::engine::modules::scene::components::SceneNodeComponent::isEnabled_.
void helios::engine::modules::scene::components::SceneNodeComponent::disable() noexcept
Disables this component.
References helios::engine::modules::scene::components::SceneNodeComponent::isEnabled_.
void helios::engine::modules::scene::components::SceneNodeComponent::onActivate() noexcept
Called when the owning GameObject is activated.
Activates the SceneNode, making it visible in the scene graph.
References helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_.
void helios::engine::modules::scene::components::SceneNodeComponent::onDeactivate() noexcept
Called when the owning GameObject is deactivated.
Deactivates the SceneNode, hiding it from the scene graph.
References helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_.
helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent(helios::scene::SceneNode *sceneNode)
Constructs a SceneNodeComponent linked to a SceneNode.
sceneNode Pointer to the SceneNode to control. Must not be nullptr.
References helios::engine::modules::scene::components::SceneNodeComponent::sceneNode, helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_.
Referenced by helios::engine::modules::scene::components::SceneNodeComponent::onClone, helios::engine::modules::scene::components::SceneNodeComponent::operator=, helios::engine::modules::scene::components::SceneNodeComponent::operator=, helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent, helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent(const SceneNodeComponent &other)=default
Copy constructor.
Copies the SceneNode pointer. The actual SceneNode cloning is handled by onClone() during entity cloning.
References helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
SceneNodeComponent & helios::engine::modules::scene::components::SceneNodeComponent::operator=(const SceneNodeComponent &)=default
Copy assignment operator.
References helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent(SceneNodeComponent &&) noexcept=default
Move constructor.
References helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
SceneNodeComponent & helios::engine::modules::scene::components::SceneNodeComponent::operator=(SceneNodeComponent &&) noexcept=default
Move assignment operator.
References helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
void helios::engine::modules::scene::components::SceneNodeComponent::onClone(const SceneNodeComponent &other)
Called after copy construction during entity cloning.
Creates a new SceneNode for this entity by cloning the source's renderable and adding it to the same parent node. This ensures each cloned entity has its own SceneNode in the scene graph. other The source component to clone from.
References helios::engine::modules::scene::components::SceneNodeComponent::onClone, helios::engine::modules::scene::components::SceneNodeComponent::sceneNode, helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_, helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.
Referenced by helios::engine::modules::scene::components::SceneNodeComponent::onClone.
helios::scene::SceneNode * helios::engine::modules::scene::components::SceneNodeComponent::sceneNode() const noexcept
Returns the underlying SceneNode.
Non-owning pointer to the associated SceneNode.
References helios::engine::modules::scene::components::SceneNodeComponent::sceneNode_.
Referenced by helios::engine::modules::scene::components::SceneNodeComponent::onClone, helios::engine::modules::scene::components::SceneNodeComponent::SceneNodeComponent.