helios.engine.mechanics.health.components.HealthComponent
float helios::engine::mechanics::health::components::HealthComponent::maxHealth_
Maximum health value.
float helios::engine::mechanics::health::components::HealthComponent::health_
Current health value.
bool helios::engine::mechanics::health::components::HealthComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::health::components::HealthComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::health::components::HealthComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::health::components::HealthComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent()=default
Referenced by helios::engine::mechanics::health::components::HealthComponent::HealthComponent, helios::engine::mechanics::health::components::HealthComponent::HealthComponent, helios::engine::mechanics::health::components::HealthComponent::operator=, helios::engine::mechanics::health::components::HealthComponent::operator=.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(const float maxHealth)
Constructs a HealthComponent with the given maximum health.
maxHealth The maximum health value.
References helios::engine::mechanics::health::components::HealthComponent::maxHealth.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(const HealthComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::mechanics::health::components::HealthComponent::HealthComponent.
HealthComponent & helios::engine::mechanics::health::components::HealthComponent::operator=(const HealthComponent &)=default
References helios::engine::mechanics::health::components::HealthComponent::HealthComponent.
helios::engine::mechanics::health::components::HealthComponent::HealthComponent(HealthComponent &&) noexcept=default
References helios::engine::mechanics::health::components::HealthComponent::HealthComponent.
HealthComponent & helios::engine::mechanics::health::components::HealthComponent::operator=(HealthComponent &&) noexcept=default
References helios::engine::mechanics::health::components::HealthComponent::HealthComponent.
void helios::engine::mechanics::health::components::HealthComponent::takeDamage(const float damage) noexcept
Applies damage to this entity.
Health is clamped to a minimum of 0. damage The amount of damage to apply.
References helios::engine::mechanics::health::components::HealthComponent::takeDamage.
Referenced by helios::engine::mechanics::health::components::HealthComponent::takeDamage, helios::engine::mechanics::damage::systems::DamageOnCollisionSystem::update.
void helios::engine::mechanics::health::components::HealthComponent::heal(const float amount) noexcept
Heals this entity.
Health is clamped to the maximum health value. amount The amount to heal.
void helios::engine::mechanics::health::components::HealthComponent::setMaxHealth(const float maxHealth) noexcept
Sets the maximum health value.
maxHealth The new maximum health.
References helios::engine::mechanics::health::components::HealthComponent::maxHealth.
bool helios::engine::mechanics::health::components::HealthComponent::isAlive() const noexcept
Checks if the entity is alive.
True if health is greater than 0.
float helios::engine::mechanics::health::components::HealthComponent::health() const noexcept
Returns the current health value.
The current health.
float helios::engine::mechanics::health::components::HealthComponent::maxHealth() const noexcept
Returns the maximum health value.
The maximum health.
Referenced by helios::engine::mechanics::health::components::HealthComponent::HealthComponent, helios::engine::mechanics::health::components::HealthComponent::setMaxHealth.
void helios::engine::mechanics::health::components::HealthComponent::reset()
Resets health to maximum.
Referenced by helios::engine::mechanics::health::components::HealthComponent::onAcquire, helios::engine::mechanics::health::components::HealthComponent::onRelease.
void helios::engine::mechanics::health::components::HealthComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Resets health to maximum value.
References helios::engine::mechanics::health::components::HealthComponent::reset.
void helios::engine::mechanics::health::components::HealthComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Resets health to maximum value.
References helios::engine::mechanics::health::components::HealthComponent::reset.