helios.engine.core.data.SpawnProfileId
uint32_t helios::engine::core::data::SpawnProfileId::id_
The underlying numeric identifier.
helios::engine::core::data::SpawnProfileId::SpawnProfileId(uint32_t id) noexcept
Constructs a SpawnProfileId with the given numeric value.
id The numeric identifier value.
Referenced by helios::engine::core::data::SpawnProfileId::operator<, helios::engine::core::data::SpawnProfileId::operator==, helios::engine::core::data::SpawnProfileId::operator>.
uint32_t helios::engine::core::data::SpawnProfileId::value() const noexcept
Returns the underlying numeric value.
The raw identifier value.
bool helios::engine::core::data::SpawnProfileId::operator<(const SpawnProfileId &other) const noexcept
Less-than comparison for ordered containers.
other The SpawnProfileId to compare against. True if this ID is less than the other.
References helios::engine::core::data::SpawnProfileId::SpawnProfileId.
bool helios::engine::core::data::SpawnProfileId::operator>(const SpawnProfileId &other) const noexcept
Greater-than comparison for ordered containers.
other The SpawnProfileId to compare against. True if this ID is greater than the other.
References helios::engine::core::data::SpawnProfileId::SpawnProfileId.
std::size_t std::hash< helios::engine::core::data::SpawnProfileId >::operator()(const helios::engine::core::data::SpawnProfileId &id) const noexcept
Computes the hash value for a SpawnProfileId.
id The SpawnProfileId to hash. The hash value based on the underlying numeric identifier.