helios.scene.Camera
helios::math::mat4f helios::scene::Camera::perspectiveMatrix_
The projection matrix of this camera.
Referenced by helios::scene::Camera::Camera, helios::scene::Camera::projectionMatrix, helios::scene::Camera::update.
helios::math::mat4f helios::scene::Camera::orthographicMatrix_
The orthographic projection matrix of this camera.
Used when the camera is in orthographic mode (`usePerspective_ == false`).
Referenced by helios::scene::Camera::Camera, helios::scene::Camera::projectionMatrix, helios::scene::Camera::update.
helios::math::mat4f helios::scene::Camera::viewMatrix_
The view matrix of this camera.
Referenced by helios::scene::Camera::Camera, helios::scene::Camera::setViewMatrix, helios::scene::Camera::viewMatrix.
float helios::scene::Camera::aspectRatio_
The aspect ratio of the camera (width/height).
Defaults to 1.0.
Referenced by helios::scene::Camera::aspectRatio, helios::scene::Camera::setAspectRatio, helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::update.
float helios::scene::Camera::zNear_
The near clipping plane distance.
Defaults to 0.1.
Referenced by helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setZNear, helios::scene::Camera::update, helios::scene::Camera::zNear.
float helios::scene::Camera::zFar_
The far clipping plane distance.
Defaults to 1000.0.
Referenced by helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setZFar, helios::scene::Camera::update, helios::scene::Camera::zFar.
float helios::scene::Camera::fovY_
The vertical field of view in radians.
Defaults to 90 degrees (converted to radians).
Referenced by helios::scene::Camera::fovY, helios::scene::Camera::setFovY, helios::scene::Camera::setPerspective, helios::scene::Camera::update.
bool helios::scene::Camera::needsUpdate_
Flag indicating whether the matrices need to be updated.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::setAspectRatio, helios::scene::Camera::setFovY, helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setZFar, helios::scene::Camera::setZNear, helios::scene::Camera::update.
float helios::scene::Camera::left_
Left boundary of the orthographic frustum.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::setOrtho, helios::scene::Camera::update.
float helios::scene::Camera::right_
Right boundary of the orthographic frustum.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::setOrtho, helios::scene::Camera::update.
float helios::scene::Camera::bottom_
Bottom boundary of the orthographic frustum.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::setOrtho, helios::scene::Camera::update.
float helios::scene::Camera::top_
Top boundary of the orthographic frustum.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::setOrtho, helios::scene::Camera::update.
bool helios::scene::Camera::usePerspective_
Flag indicating the projection mode.
When `true`, perspective projection is used. When `false`, orthographic projection is used. Defaults to `true`.
Referenced by helios::scene::Camera::onResize, helios::scene::Camera::projectionMatrix, helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::update.
void helios::scene::Camera::update() const
Updates the view and projection matrices if needed.
This function recalculates the view and projection matrices based on the current camera parameters.
References helios::scene::Camera::aspectRatio_, helios::scene::Camera::bottom_, helios::scene::Camera::fovY_, helios::scene::Camera::left_, helios::scene::Camera::needsUpdate_, helios::math::ortho, helios::scene::Camera::orthographicMatrix_, helios::math::perspective, helios::scene::Camera::perspectiveMatrix_, helios::scene::Camera::right_, helios::scene::Camera::top_, helios::scene::Camera::usePerspective_, helios::scene::Camera::zFar_, helios::scene::Camera::zNear_.
Referenced by helios::scene::Camera::projectionMatrix.
helios::scene::Camera::Camera() noexcept
Constructs a camera with identity projection and view matrices.
References helios::scene::Camera::orthographicMatrix_, helios::scene::Camera::perspectiveMatrix_, helios::scene::Camera::viewMatrix_.
Referenced by helios::scene::Camera::setAspectRatio, helios::scene::Camera::setFovY, helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setViewMatrix, helios::scene::Camera::setZFar, helios::scene::Camera::setZNear.
const helios::math::mat4f & helios::scene::Camera::projectionMatrix() const noexcept
Gets the current projection matrix.
Typically set to a perspective or orthographic projection. A const reference to this camera's projection matrix.
References helios::scene::Camera::orthographicMatrix_, helios::scene::Camera::perspectiveMatrix_, helios::scene::Camera::update, helios::scene::Camera::usePerspective_.
const helios::math::mat4f & helios::scene::Camera::viewMatrix() const noexcept
Gets the current view matrix.
The view matrix represents the inverse of the camera's world transform. A const reference to this camera's view matrix.
References helios::scene::Camera::viewMatrix_.
Referenced by helios::scene::Camera::setViewMatrix.
Camera & helios::scene::Camera::setViewMatrix(const helios::math::mat4f &viewMatrix) noexcept
Sets the view matrix for this camera.
This method is typically called by `CameraSceneNode::worldTransform()` to update the view matrix based on the camera node's position and orientation in the scene graph. viewMatrix The new view matrix to assign. A const reference to this camera instance. helios::scene::CameraSceneNode::worldTransform()
References helios::scene::Camera::Camera, helios::scene::Camera::viewMatrix, helios::scene::Camera::viewMatrix_.
Camera & helios::scene::Camera::setAspectRatio(float aspectRatio) noexcept
Sets the aspect ratio used by the camera.
aspectRatio The new aspect ratio (width/height). A reference to this camera instance.
References helios::scene::Camera::aspectRatio, helios::scene::Camera::aspectRatio_, helios::scene::Camera::Camera, helios::scene::Camera::needsUpdate_.
Referenced by helios::scene::Camera::onResize.
void helios::scene::Camera::onResize(const float width, const float height) noexcept
Handles viewport resize events.
Adjusts the camera projection parameters when the viewport dimensions change. For perspective projection: Updates the aspect ratio. For orthographic projection: Adjusts the right and top boundaries to maintain the correct projection volume. width The new viewport width in pixels. height The new viewport height in pixels.
References helios::scene::Camera::bottom_, helios::scene::Camera::left_, helios::scene::Camera::needsUpdate_, helios::scene::Camera::right_, helios::scene::Camera::setAspectRatio, helios::scene::Camera::top_, helios::scene::Camera::usePerspective_.
Camera & helios::scene::Camera::setPerspective(float fovY, float aspectRatio, float zNear, float zFar) noexcept
Sets the perspective projection parameters.
fovY The vertical field of view in radians. aspectRatio The aspect ratio (width/height). zNear The near clipping plane distance. zFar The far clipping plane distance. A reference to this camera instance.
References helios::scene::Camera::aspectRatio, helios::scene::Camera::aspectRatio_, helios::scene::Camera::Camera, helios::scene::Camera::fovY, helios::scene::Camera::fovY_, helios::scene::Camera::needsUpdate_, helios::scene::Camera::usePerspective_, helios::scene::Camera::zFar, helios::scene::Camera::zFar_, helios::scene::Camera::zNear, helios::scene::Camera::zNear_.
Camera & helios::scene::Camera::setOrtho(const float left, const float right, const float bottom, const float top, const float zNear=-1.0f, const float zFar=100.0f) noexcept
Sets the orthographic projection parameters.
Configures the camera for orthographic projection, which is useful for 2D rendering, UI overlays, or scenes where parallel lines should remain parallel (no perspective distortion). left The left boundary of the view volume. right The right boundary of the view volume. bottom The bottom boundary of the view volume. top The top boundary of the view volume. zNear The near clipping plane distance. Defaults to -1.0. zFar The far clipping plane distance. Defaults to 100.0. A reference to this camera instance. Calling this method switches the camera to orthographic projection mode.
References helios::scene::Camera::aspectRatio_, helios::scene::Camera::bottom_, helios::scene::Camera::Camera, helios::scene::Camera::left_, helios::scene::Camera::needsUpdate_, helios::scene::Camera::right_, helios::scene::Camera::top_, helios::scene::Camera::usePerspective_, helios::scene::Camera::zFar, helios::scene::Camera::zFar_, helios::scene::Camera::zNear, helios::scene::Camera::zNear_.
Camera & helios::scene::Camera::setZNear(float zNear) noexcept
Sets the near clipping plane distance.
zNear The new near clipping plane distance. A reference to this camera instance.
References helios::scene::Camera::Camera, helios::scene::Camera::needsUpdate_, helios::scene::Camera::zNear, helios::scene::Camera::zNear_.
Camera & helios::scene::Camera::setZFar(float zFar) noexcept
Sets the far clipping plane distance.
zFar The new far clipping plane distance. A reference to this camera instance.
References helios::scene::Camera::Camera, helios::scene::Camera::needsUpdate_, helios::scene::Camera::zFar, helios::scene::Camera::zFar_.
Camera & helios::scene::Camera::setFovY(float fovY) noexcept
Sets the vertical field of view.
fovY The new vertical field of view in radians. A reference to this camera instance.
References helios::scene::Camera::Camera, helios::scene::Camera::fovY, helios::scene::Camera::fovY_, helios::scene::Camera::needsUpdate_.
float helios::scene::Camera::fovY() const noexcept
Gets the current vertical field of view.
The vertical field of view in radians.
References helios::scene::Camera::fovY_.
Referenced by helios::scene::Camera::setFovY, helios::scene::Camera::setPerspective.
float helios::scene::Camera::aspectRatio() const noexcept
Gets the current aspect ratio.
The aspect ratio (width/height).
References helios::scene::Camera::aspectRatio_.
Referenced by helios::scene::Camera::setAspectRatio, helios::scene::Camera::setPerspective.
float helios::scene::Camera::zNear() const noexcept
Gets the current near clipping plane distance.
The near clipping plane distance.
References helios::scene::Camera::zNear_.
Referenced by helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setZNear.
float helios::scene::Camera::zFar() const noexcept
Gets the current far clipping plane distance.
The far clipping plane distance.
References helios::scene::Camera::zFar_.
Referenced by helios::scene::Camera::setOrtho, helios::scene::Camera::setPerspective, helios::scene::Camera::setZFar.