helios.rendering.text.TextRenderable
std::shared_ptr<const helios::rendering::text::TextRenderPrototype> helios::rendering::text::TextRenderable::textRenderPrototype_
Shared prototype containing shader and text properties.
Referenced by helios::rendering::text::TextRenderable::TextRenderable, helios::rendering::text::TextRenderable::textRenderPrototype, helios::rendering::text::TextRenderable::writeUniformValues.
std::string helios::rendering::text::TextRenderable::text_
The text string to render.
Referenced by helios::rendering::text::TextRenderable::setText, helios::rendering::text::TextRenderable::text, helios::rendering::text::TextRenderable::TextRenderable.
std::optional<helios::rendering::text::config::TextShaderPropertiesOverride> helios::rendering::text::TextRenderable::textPropertiesOverride_
Optional overrides for text shader properties.
Referenced by helios::rendering::text::TextRenderable::TextRenderable, helios::rendering::text::TextRenderable::writeUniformValues.
helios::rendering::text::DrawProperties helios::rendering::text::TextRenderable::drawProperties_
Positioning and styling data (font, position, scale).
Referenced by helios::rendering::text::TextRenderable::drawProperties, helios::rendering::text::TextRenderable::TextRenderable.
helios::rendering::text::TextRenderable::TextRenderable(std::string text, std::shared_ptr< const helios::rendering::text::TextRenderPrototype > renderPrototype, const helios::rendering::text::DrawProperties drawProperties, const std::optional< helios::rendering::text::config::TextShaderPropertiesOverride > &textPropertiesOverride=std::nullopt)
Constructs a TextRenderable with the given text and configuration.
text The text string to render. renderPrototype Shared prototype with shader and font configuration. drawProperties Position, scale, and font selection. textPropertiesOverride Optional overrides for shader properties. std::invalid_argument If `renderPrototype` is null.
References helios::rendering::text::TextRenderable::drawProperties, helios::rendering::text::TextRenderable::drawProperties_, helios::rendering::text::TextRenderable::text, helios::rendering::text::TextRenderable::text_, helios::rendering::text::TextRenderable::textPropertiesOverride_, helios::rendering::text::TextRenderable::textRenderPrototype_.
void helios::rendering::text::TextRenderable::setText(std::string text) noexcept
Updates the text string.
text The new text to render.
References helios::rendering::text::TextRenderable::text, helios::rendering::text::TextRenderable::text_.
std::string_view helios::rendering::text::TextRenderable::text() const noexcept
Returns the current text string.
View of the text string.
References helios::rendering::text::TextRenderable::text_.
Referenced by helios::rendering::text::TextRenderable::setText, helios::rendering::text::TextRenderable::TextRenderable.
std::shared_ptr< const helios::rendering::text::TextRenderPrototype > helios::rendering::text::TextRenderable::textRenderPrototype() const noexcept
Returns the text render prototype.
Shared pointer to the prototype.
References helios::rendering::text::TextRenderable::textRenderPrototype_.
const helios::rendering::text::DrawProperties & helios::rendering::text::TextRenderable::drawProperties() const noexcept
Returns the draw properties.
Reference to the positioning and styling data.
References helios::rendering::text::TextRenderable::drawProperties_.
Referenced by helios::rendering::text::TextRenderable::TextRenderable.
void helios::rendering::text::TextRenderable::writeUniformValues(helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept
Writes uniform values to the given map.
Applies the prototype's text properties first, then any instance-specific overrides. Used by the render pipeline to configure the text shader. uniformValueMap The map to write uniform values to.
References helios::rendering::text::TextRenderable::textPropertiesOverride_, helios::rendering::text::TextRenderable::textRenderPrototype_.