helios.ecs.TypedHandleWorld
std::tuple<TEntityManagers...> helios::ecs::TypedHandleWorld< TEntityManagers >::entityManagers_
auto & helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager()
Returns a reference to the EntityManager that owns handles of type `THandle`.
Uses `HandleToManager` to resolve the tuple index at compile time. A `static_assert` fires if no manager matches. THandle The handle type identifying the target domain. Mutable reference to the matching EntityManager.
Referenced by helios::ecs::TypedHandleWorld< TEntityManagers >::addEntity, helios::ecs::TypedHandleWorld< TEntityManagers >::addEntity, helios::ecs::TypedHandleWorld< TEntityManagers >::cloneEntity, helios::ecs::TypedHandleWorld< TEntityManagers >::destroy, helios::ecs::TypedHandleWorld< TEntityManagers >::findEntity, helios::ecs::TypedHandleWorld< TEntityManagers >::view.
const auto & helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager() const
Returns a const reference to the EntityManager that owns handles of type `THandle`.
THandle The handle type identifying the target domain. Const reference to the matching EntityManager.
auto helios::ecs::TypedHandleWorld< TEntityManagers >::addEntity(THandle::StrongId_type strongId)
Creates a new entity in the domain identified by `THandle`.
Delegates to the matching `EntityManager::create()` and wraps the result in an `Entity` facade. THandle The handle type identifying the target domain. An `Entity` wrapping the newly created handle.
References helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::ecs::TypedHandleWorld< TEntityManagers >::addEntity()
Creates a new entity with an auto-generated id.
THandle The handle type identifying the target domain. An `Entity` wrapping the newly created handle.
References helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
Referenced by helios::ecs::TypedHandleWorld< TEntityManagers >::cloneEntity.
bool helios::ecs::TypedHandleWorld< TEntityManagers >::destroy(THandle handle)
Destroys an entity identified by its handle.
Delegates to the owning `EntityManager::destroy()`. The handle's version is incremented, making all existing copies stale. THandle The handle type identifying the target domain. handle The handle of the entity to destroy. True if the entity was valid and successfully destroyed.
References helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::ecs::TypedHandleWorld< TEntityManagers >::findEntity(THandle handle)
Looks up an existing entity by its handle.
Validates the handle via the owning `EntityManager`. If valid, returns an `Entity` facade; otherwise returns `std::nullopt`. THandle The handle type (and thus the domain) to search. handle The entity handle to resolve. `std::optional<Entity>` — engaged if the handle is valid.
References helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::ecs::TypedHandleWorld< TEntityManagers >::cloneEntity(THandle source) noexcept
Clones all components from a source entity into a new entity.
Creates a new entity in the same domain and copies every component attached to `source` into it via `EntityManager::clone()`. THandle The handle type identifying the target domain. source The handle of the entity to clone. An `Entity` wrapping the newly created clone.
References helios::ecs::TypedHandleWorld< TEntityManagers >::addEntity, helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.
auto helios::ecs::TypedHandleWorld< TEntityManagers >::view()
Creates a `View` for iterating entities with specific components.
The view operates on the `EntityManager` identified by `THandle`. The first component type in `TComponents` serves as the lead set for iteration. THandle The handle type selecting the domain. TComponents The component types to include in the view. A `View` over the matching EntityManager. View
References helios::ecs::TypedHandleWorld< TEntityManagers >::entityManager.