helios.core.ecs.View
using helios::core::ecs::View< TEntityManager, Components >::Iterator::Entity_type = Entity<typename TEntityManager::Handle_type, TEntityManager>
using helios::core::ecs::View< TEntityManager, Components >::Iterator::LeadComponent = std::tuple_element_t<0, std::tuple<Components...>>
The first component type determines iteration order.
using helios::core::ecs::View< TEntityManager, Components >::Iterator::LeadIterator = typename SparseSet<LeadComponent>::Iterator
Iterator type from the lead component's SparseSet.
TEntityManager* helios::core::ecs::View< TEntityManager, Components >::em_
std::tuple<SparseSet<Components>*... > helios::core::ecs::View< TEntityManager, Components >::includeSets_
Pointers to the SparseSets of the included components.
std::vector<std::function<bool(EntityId)> > helios::core::ecs::View< TEntityManager, Components >::excludeChecks_
List of exclusion predicates. Stores functions that return true if an entity should be EXCLUDED. Operates on EntityId (index) because the SparseSet uses it internally.
bool helios::core::ecs::View< TEntityManager, Components >::filterEnabledOnly_
Flag to filter only enabled components.
bool helios::core::ecs::View< TEntityManager, Components >::filterActiveOnly_
LeadIterator helios::core::ecs::View< TEntityManager, Components >::Iterator::current_
Referenced by helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator!=, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator*, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator==.
LeadIterator helios::core::ecs::View< TEntityManager, Components >::Iterator::end_
Referenced by helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.
const View* helios::core::ecs::View< TEntityManager, Components >::Iterator::view_
Referenced by helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator*.
helios::core::ecs::View< TEntityManager, Components >::View(TEntityManager *em)
Constructs the view and retrieves the necessary component sets.
em Pointer to the EntityManager to retrieve sets and construct Entities.
Referenced by helios::core::ecs::View< TEntityManager, Components >::exclude, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator, helios::core::ecs::View< TEntityManager, Components >::whereEnabled.
View & helios::core::ecs::View< TEntityManager, Components >::exclude()
Excludes entities that have a specific component.
Entities possessing the specified component type will be skipped during iteration. Multiple exclusions can be chained. ```cpp // Skip entities with Shield or Invincible for (auto [e, health] : world->view<HealthComponent>() .exclude<ShieldComponent>() .exclude<InvincibleComponent>()) { // Only vulnerable entities } ``` T The component type to exclude. Reference to this View for method chaining.
References helios::core::ecs::View< TEntityManager, Components >::View.
bool helios::core::ecs::View< TEntityManager, Components >::empty()
References helios::core::ecs::View< TEntityManager, Components >::begin, helios::core::ecs::View< TEntityManager, Components >::end.
View & helios::core::ecs::View< TEntityManager, Components >::whereEnabled()
Filters to only include entities with enabled components.
Components must implement `isEnabled()` returning bool. Components without this method are assumed to be enabled. Reference to this View for method chaining.
References helios::core::ecs::View< TEntityManager, Components >::View.
helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator()=default
Default constructor creating an invalid iterator.
Referenced by helios::core::ecs::View< TEntityManager, Components >::Iterator::operator!=, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator++, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator==.
helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator(LeadIterator current, LeadIterator end, const View *view)
Constructs an iterator with the given range and view.
current Iterator to the current position. end Iterator to the end position. view Pointer to the owning View for filter access.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::end, helios::core::ecs::View< TEntityManager, Components >::Iterator::end_, helios::core::ecs::View< TEntityManager, Components >::View, helios::core::ecs::View< TEntityManager, Components >::Iterator::view_.
bool helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid() const
Validates if the current entity matches all filter criteria.
Performs the following checks in order: 1. Entity validity in the registry 2. Include check - entity has all required components 3. Exclude check - entity has none of the excluded components 4. Enabled check - all components pass isEnabled() (if filtered) True if the entity passes all checks, false otherwise.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::Iterator::end_, helios::core::ecs::View< TEntityManager, Components >::Iterator::view_.
Referenced by helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::begin.
void helios::core::ecs::View< TEntityManager, Components >::Iterator::advance()
Advances to the next valid entity.
Increments the underlying iterator and skips invalid entities until a valid one is found or end is reached.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::Iterator::end_, helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid.
Referenced by helios::core::ecs::View< TEntityManager, Components >::begin, helios::core::ecs::View< TEntityManager, Components >::Iterator::operator++.
Iterator & helios::core::ecs::View< TEntityManager, Components >::Iterator::operator++() noexcept
Pre-increment operator.
Reference to this iterator after advancing.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.
bool helios::core::ecs::View< TEntityManager, Components >::Iterator::operator!=(const Iterator &other) const noexcept
Inequality comparison.
other The iterator to compare against. True if iterators point to different positions.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.
auto helios::core::ecs::View< TEntityManager, Components >::Iterator::operator*() const
Dereference operator.
A tuple containing {GameObject, Component*...}. Returns by value to support C++17 Structured Binding (auto [go, comp] : view).
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::Iterator::view_.
bool helios::core::ecs::View< TEntityManager, Components >::Iterator::operator==(const Iterator &other) const noexcept
References helios::core::ecs::View< TEntityManager, Components >::Iterator::current_, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.
Iterator helios::core::ecs::View< TEntityManager, Components >::begin()
Returns an iterator to the first valid entity.
Uses the first component type's SparseSet as the lead. If the first entity is invalid, advances to the next valid one. Iterator to the first valid entity, or end() if none found.
References helios::core::ecs::View< TEntityManager, Components >::Iterator::advance, helios::core::ecs::View< TEntityManager, Components >::Iterator::isValid.
Referenced by helios::core::ecs::View< TEntityManager, Components >::empty.
Iterator helios::core::ecs::View< TEntityManager, Components >::end()
Returns an iterator to the end (past the last entity).
End iterator for comparison.
Referenced by helios::core::ecs::View< TEntityManager, Components >::empty, helios::core::ecs::View< TEntityManager, Components >::Iterator::Iterator.