helios.rendering.Renderable
std::shared_ptr<const helios::rendering::RenderPrototype> helios::rendering::Renderable::renderPrototype_
Shared pointer to the immutable RenderPrototype definition.
Referenced by helios::rendering::Renderable::Renderable, helios::rendering::Renderable::renderPrototype, helios::rendering::Renderable::writeUniformValues.
std::optional<helios::rendering::model::config::MaterialPropertiesOverride> helios::rendering::Renderable::materialOverride_
The MaterialPropertiesOverride owned by this class. This will be std::nullopt if not available.
Referenced by helios::rendering::Renderable::hasMaterialOverride, helios::rendering::Renderable::materialOverride, helios::rendering::Renderable::materialOverride, helios::rendering::Renderable::Renderable, helios::rendering::Renderable::writeUniformValues.
const helios::util::log::Logger& helios::rendering::Renderable::logger_
Shared logger instance for all Renderable objects.
Referenced by helios::rendering::Renderable::Renderable.
helios::rendering::Renderable::Renderable()=delete
Deleted default constructor.
Referenced by helios::rendering::Renderable::operator=, helios::rendering::Renderable::operator=, helios::rendering::Renderable::Renderable, helios::rendering::Renderable::Renderable, helios::rendering::Renderable::Renderable.
helios::rendering::Renderable::Renderable(const Renderable &)=delete
Deleted copy constructor.
References helios::rendering::Renderable::Renderable.
Renderable & helios::rendering::Renderable::operator=(const Renderable &)=delete
Deleted copy assignment operator.
References helios::rendering::Renderable::Renderable.
helios::rendering::Renderable::Renderable(Renderable &&) noexcept=default
Defaulted move constructor.
References helios::rendering::Renderable::Renderable.
Renderable & helios::rendering::Renderable::operator=(Renderable &&) noexcept=default
Defaulted move assignment operator.
References helios::rendering::Renderable::Renderable.
helios::rendering::Renderable::Renderable(std::shared_ptr< const helios::rendering::RenderPrototype > renderPrototype, const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > &materialOverride=std::nullopt)
Creates a new Renderable instance.
renderPrototype A shared pointer to the immutable RenderPrototype definition. Must not be nullptr. materialOverride An optional set of instance-specific material property overrides. If std::nullopt, the Renderable uses only the default properties from the RenderPrototype's Material. std::invalid_argument if `renderPrototype` is a nullptr.
References helios::rendering::Renderable::logger_, helios::rendering::Renderable::materialOverride, helios::rendering::Renderable::materialOverride_, helios::rendering::Renderable::Renderable, helios::rendering::Renderable::renderPrototype, helios::rendering::Renderable::renderPrototype_.
std::shared_ptr< const helios::rendering::RenderPrototype > helios::rendering::Renderable::renderPrototype() const noexcept
Returns a shared pointer to the RenderPrototype used by this Renderable.
A shared pointer to the RenderPrototype.
References helios::rendering::Renderable::renderPrototype_.
Referenced by helios::rendering::Renderable::Renderable.
const std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & helios::rendering::Renderable::materialOverride() const noexcept
Returns a const reference to the optional instance-specific MaterialPropertiesOverride.
This allows read-only access to the overrides. Use `.has_value()` to check for existence and `.value()` or `->` to safely access the override data. A const reference to the std::optional<MaterialPropertiesOverride>.
References helios::rendering::Renderable::materialOverride_.
Referenced by helios::rendering::Renderable::Renderable.
std::optional< helios::rendering::model::config::MaterialPropertiesOverride > & helios::rendering::Renderable::materialOverride() noexcept
Returns a non-const reference to the optional instance-specific MaterialPropertiesOverride.
This allows modification of the overrides. If the optional currently has no value, it can be assigned to or `.emplace()` can be used to create a new MaterialPropertiesOverride. A non-const reference to the std::optional<MaterialPropertiesOverride>.
References helios::rendering::Renderable::materialOverride_.
bool helios::rendering::Renderable::hasMaterialOverride() const noexcept
Returns true if this Renderable was configured with a MaterialPropertiesOverride.
True if this Renderable was configured with a MaterialPropertiesOverride instance, otherwise false.
References helios::rendering::Renderable::materialOverride_.
void helios::rendering::Renderable::writeUniformValues(helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept
Writes uniform values into the given map.
This method first applies the default uniform values from the base Material definition and then overlays any specific overrides provided by this instance's MaterialPropertiesOverride. uniformValueMap Target map receiving the uniform values.
References helios::rendering::Renderable::materialOverride_, helios::rendering::Renderable::renderPrototype_.