helios.engine.modules.rendering.model.components.ModelAabbComponent
helios::math::aabbf helios::engine::modules::rendering::model::components::ModelAabbComponent::aabb_
The stored AABB.
bool helios::engine::modules::rendering::model::components::ModelAabbComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::rendering::model::components::ModelAabbComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::rendering::model::components::ModelAabbComponent::enable() noexcept
Enables this component.
void helios::engine::modules::rendering::model::components::ModelAabbComponent::disable() noexcept
Disables this component.
helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent()=default
Default constructor.
Referenced by helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent, helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent, helios::engine::modules::rendering::model::components::ModelAabbComponent::operator=, helios::engine::modules::rendering::model::components::ModelAabbComponent::operator=.
helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent(const ModelAabbComponent &other)
References helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent.
ModelAabbComponent & helios::engine::modules::rendering::model::components::ModelAabbComponent::operator=(const ModelAabbComponent &)=default
References helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent.
helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent(ModelAabbComponent &&) noexcept=default
References helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent.
ModelAabbComponent & helios::engine::modules::rendering::model::components::ModelAabbComponent::operator=(ModelAabbComponent &&) noexcept=default
References helios::engine::modules::rendering::model::components::ModelAabbComponent::ModelAabbComponent.
void helios::engine::modules::rendering::model::components::ModelAabbComponent::setAabb(const helios::math::aabbf &aabb)
Sets the AABB for this component.
aabb The new AABB to store.
References helios::engine::modules::rendering::model::components::ModelAabbComponent::aabb, helios::engine::modules::rendering::model::components::ModelAabbComponent::setAabb.
Referenced by helios::engine::modules::rendering::model::components::ModelAabbComponent::setAabb.
const helios::math::aabbf & helios::engine::modules::rendering::model::components::ModelAabbComponent::aabb() const noexcept
Retrieves the stored AABB.
Constant reference to the AABB.
Referenced by helios::engine::modules::rendering::model::components::ModelAabbComponent::setAabb.