helios.engine.mechanics.combat.components.LastAttackerComponent
helios::engine::mechanics::combat::types::AttackContext helios::engine::mechanics::combat::components::LastAttackerComponent::lastAttackContext_
Context of the most recent attack received.
bool helios::engine::mechanics::combat::components::LastAttackerComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::combat::components::LastAttackerComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::combat::components::LastAttackerComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::combat::components::LastAttackerComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent()=default
Referenced by helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent, helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent, helios::engine::mechanics::combat::components::LastAttackerComponent::operator=, helios::engine::mechanics::combat::components::LastAttackerComponent::operator=.
helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent(const LastAttackerComponent &other)
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent.
LastAttackerComponent & helios::engine::mechanics::combat::components::LastAttackerComponent::operator=(const LastAttackerComponent &)=default
References helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent.
helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent(LastAttackerComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent.
LastAttackerComponent & helios::engine::mechanics::combat::components::LastAttackerComponent::operator=(LastAttackerComponent &&) noexcept=default
References helios::engine::mechanics::combat::components::LastAttackerComponent::LastAttackerComponent.
void helios::engine::mechanics::combat::components::LastAttackerComponent::setLastAttackContext(const helios::engine::mechanics::combat::types::AttackContext lastAttackContext) noexcept
Sets the last attack context.
lastAttackContext The attack context to store.
References helios::engine::mechanics::combat::components::LastAttackerComponent::lastAttackContext, helios::engine::mechanics::combat::components::LastAttackerComponent::setLastAttackContext.
Referenced by helios::engine::mechanics::combat::components::LastAttackerComponent::setLastAttackContext.
helios::engine::mechanics::combat::types::AttackContext helios::engine::mechanics::combat::components::LastAttackerComponent::lastAttackContext() const noexcept
Returns the last attack context.
The stored AttackContext.
Referenced by helios::engine::mechanics::combat::components::LastAttackerComponent::setLastAttackContext.
void helios::engine::mechanics::combat::components::LastAttackerComponent::reset()
Resets the component to its initial state.
Referenced by helios::engine::mechanics::combat::components::LastAttackerComponent::onAcquire, helios::engine::mechanics::combat::components::LastAttackerComponent::onRelease.
void helios::engine::mechanics::combat::components::LastAttackerComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Resets the attack context to ensure no stale data.
References helios::engine::mechanics::combat::components::LastAttackerComponent::reset.
void helios::engine::mechanics::combat::components::LastAttackerComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Resets the attack context to ensure no stale data.
References helios::engine::mechanics::combat::components::LastAttackerComponent::reset.