helios.ext.opengl.rendering.shader.LegacyOpenGLShader
std::string helios::ext::opengl::rendering::shader::LegacyOpenGLShader::vertexShaderSource_
Source of the shader. Not guaranteed to be persisted once compilation was successful.
std::string helios::ext::opengl::rendering::shader::LegacyOpenGLShader::fragmentShaderSource_
Source of the shader. Not guaranteed to be persisted once compilation was successful.
unsigned int helios::ext::opengl::rendering::shader::LegacyOpenGLShader::progId_
The program id as assigned by the underlying rendering backend.
Referenced by helios::ext::opengl::rendering::shader::LegacyOpenGLShader::use, helios::ext::opengl::rendering::shader::LegacyOpenGLShader::~LegacyOpenGLShader.
std::unique_ptr<const OpenGLUniformLocationMap> helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocationMap_
A unique pointer to the OpenGLUniformLocationMap this shader uses.
Referenced by helios::ext::opengl::rendering::shader::LegacyOpenGLShader::setUniformLocationMap, helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocation.
void helios::ext::opengl::rendering::shader::LegacyOpenGLShader::load(const std::string &vertexShaderPath, const std::string &fragmentShaderPath, const helios::util::io::StringFileReader &stringFileReader)
Loads the specified vertex and fragment shader.
true if loading succeeded, otherwise false. if loading the specified files failed.
void helios::ext::opengl::rendering::shader::LegacyOpenGLShader::compile()
Compiles the vertex and fragment shader represented by this instance.
true if compilation succeeded, otherwise false. if compilation failed.
helios::ext::opengl::rendering::shader::LegacyOpenGLShader::LegacyOpenGLShader(const LegacyOpenGLShader &)=delete
Rule of three.
https://wikis.khronos.org/opengl/Common_Mistakes#RAII_and_hidden_destructor_calls https://en.cppreference.com/w/cpp/language/rule_of_three.html Prevent copying.
References helios::ext::opengl::rendering::shader::LegacyOpenGLShader::LegacyOpenGLShader.
Referenced by helios::ext::opengl::rendering::shader::LegacyOpenGLShader::LegacyOpenGLShader, helios::ext::opengl::rendering::shader::LegacyOpenGLShader::operator=.
LegacyOpenGLShader & helios::ext::opengl::rendering::shader::LegacyOpenGLShader::operator=(const LegacyOpenGLShader &)=delete
References helios::ext::opengl::rendering::shader::LegacyOpenGLShader::LegacyOpenGLShader.
helios::ext::opengl::rendering::shader::LegacyOpenGLShader::LegacyOpenGLShader(const std::string &vertexShaderPath, const std::string &fragmentShaderPath, const helios::util::io::StringFileReader &stringFileReader)
Creates and initializes this LegacyOpenGLShader. An instance of this class is guaranteed to have a progId_ != 0, hence shader-files where successfully loaded and compiled, ready to be used.
vertexShaderPath The path to the vertex shader. fragmentShaderPath The path to the fragment shader. stringFileReader The StringFileReader used for loading the shader source files. if creating this shader failed.
References helios::rendering::shader::Shader::logger_.
void helios::ext::opengl::rendering::shader::LegacyOpenGLShader::use() const noexcept override
Activates this LegacyOpenGLShader for subsequent draw calls. This implementation calls `glUseProgram` with the `progId_` received after compilation.
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glUseProgram.xhtml
References helios::rendering::shader::Shader::logger_, helios::ext::opengl::rendering::shader::LegacyOpenGLShader::progId_.
helios::ext::opengl::rendering::shader::LegacyOpenGLShader::~LegacyOpenGLShader() override
Deletes the program object upon destruction of this instance.
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteProgram.xhtml
References helios::ext::opengl::rendering::shader::LegacyOpenGLShader::progId_.
void helios::ext::opengl::rendering::shader::LegacyOpenGLShader::setUniformLocationMap(std::unique_ptr< const OpenGLUniformLocationMap > uniformLocationMap) noexcept
Sets the OpenGLUniformLocationMap for this LegacyOpenGLShader. Ownership is transferred to this instance.
uniformLocationMap The OpenGLUniformMap providing the mappings for the uniforms of the underlying GLSL shader.
References helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocationMap_.
int helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocation(helios::rendering::shader::UniformSemantics uniformSemantics) const noexcept
Returns the uniform location for the uniform represented by the specified UniformSemantics.
uniformSemantics The `UniformSemantics` identifier. The integer representing the uniform variable location in the shader, or -1 if no location map was registered with this shader or if the uniform with the specified semantics was not found.
References helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocationMap_.
Referenced by helios::ext::opengl::rendering::shader::LegacyOpenGLShader::applyUniformValues.
void helios::ext::opengl::rendering::shader::LegacyOpenGLShader::applyUniformValues(const helios::rendering::shader::UniformValueMap &uniformValueMap) const noexcept override
Applies the specified UniformValueMap to the uniforms defined by the shader. This method does not change the binding state of the shader, but it passes the uniform values to the underlying rendering backend. Implementations should ensure that the shader is properly bound before this method is called.
uniformValueMap A const ref to the `UniformValueMap` containing the values for the uniforms in this shader.
References helios::rendering::shader::MaterialBaseColor, helios::rendering::shader::ModelMatrix, helios::rendering::shader::ProjectionMatrix, helios::rendering::shader::TextColor, helios::rendering::shader::TextTexture, helios::ext::opengl::rendering::shader::LegacyOpenGLShader::uniformLocation, helios::rendering::shader::ViewMatrix.