helios.core.ecs.ComponentTypeId
size_t helios::core::ecs::ComponentTypeId< THandle >::id_
The underlying ID value.
helios::core::ecs::ComponentTypeId< THandle >::ComponentTypeId(const size_t id)
Constructs a ComponentTypeId with a specific ID value.
This constructor initializes a ComponentTypeId object with a given ID, representing a unique identifier for a component type. The ID is used internally for indexing and retrieving components from the storage system. id The unique identifier assigned to the component type. This ID must be a valid non-negative value.
Referenced by helios::core::ecs::ComponentTypeId< Handle_type >::id.
helios::core::ecs::ComponentTypeId< THandle >::ComponentTypeId(helios::core::types::no_init_t)
Constructs an uninitialized ComponentTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::core::ecs::ComponentTypeId< THandle >::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
Referenced by helios::core::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::has, helios::core::ecs::ComponentOpsRegistry< Handle_type >::ops, helios::core::ecs::EntityManager< THandle, TEntityRegistry, TCapacity >::raw, helios::core::ecs::ComponentOpsRegistry< Handle_type >::setOps.
static ComponentTypeId< THandle > helios::core::ecs::ComponentTypeId< THandle >::id()
Gets the ComponentTypeId for a specific component type.
Uses TypeIndexer to generate a unique, monotonically increasing ID for each component type. The ID is generated once per type and cached. T The component type. Must be a concrete type (not abstract). The unique ComponentTypeId for type T.
std::size_t std::hash< helios::core::ecs::ComponentTypeId< THandle > >::operator()(const helios::core::ecs::ComponentTypeId< THandle > &id) const noexcept