helios.engine.core.data.ResourceTypeId
using helios::engine::core::data::ResourceTypeId::ResourceType = helios_engine_core_data_ResourceTypes
size_t helios::engine::core::data::ResourceTypeId::id_
The underlying ID value.
helios::engine::core::data::ResourceTypeId::ResourceTypeId(const size_t id)
Constructs a ResourceTypeId with a specific value.
id The type ID value.
References helios::engine::core::data::ResourceTypeId::id.
Referenced by helios::engine::core::data::ResourceTypeId::id, helios::engine::core::data::ResourceTypeId::operator==.
helios::engine::core::data::ResourceTypeId::ResourceTypeId(helios::core::types::no_init_t)
Constructs an uninitialized ResourceTypeId.
no_init_t Tag to indicate no initialization.
size_t helios::engine::core::data::ResourceTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
Referenced by helios::engine::runtime::world::ResourceRegistry::has, helios::engine::runtime::world::ResourceRegistry::registerResource, helios::engine::runtime::world::ResourceRegistry::registerResource, helios::engine::runtime::world::ResourceRegistry::resource, helios::engine::runtime::world::ResourceRegistry::resource, helios::engine::runtime::world::ResourceRegistry::tryResource, helios::engine::runtime::world::ResourceRegistry::tryResource.
static ResourceTypeId helios::engine::core::data::ResourceTypeId::id()
Returns the ResourceTypeId for a specific type.
Uses TypeIndexer to generate a unique ID per type. The ID is generated once and cached. T The resource type. The unique ResourceTypeId for type T.
References helios::engine::core::data::ResourceTypeId::ResourceTypeId, helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::runtime::world::ResourceRegistry::has, helios::engine::runtime::world::ResourceRegistry::registerResource, helios::engine::runtime::world::ResourceRegistry::registerResource, helios::engine::runtime::world::ResourceRegistry::resource, helios::engine::runtime::world::ResourceRegistry::resource, helios::engine::core::data::ResourceTypeId::ResourceTypeId, helios::engine::runtime::world::ResourceRegistry::tryResource, helios::engine::runtime::world::ResourceRegistry::tryResource.
std::size_t std::hash< helios::engine::core::data::ResourceTypeId >::operator()(const helios::engine::core::data::ResourceTypeId &id) const noexcept