helios.rendering.asset.shape.Shape
std::shared_ptr<const std::vector<Vertex> > helios::rendering::asset::shape::Shape::vertices
Shared pointer to an immutable vector of vertices for this shape.
Referenced by helios::rendering::asset::shape::Shape::Shape.
std::shared_ptr<const std::vector<unsigned int> > helios::rendering::asset::shape::Shape::indices
Shared pointer to an immutable vector of indices for this shape.
Referenced by helios::rendering::asset::shape::Shape::Shape.
virtual helios::rendering::asset::shape::Shape::~Shape()=default
helios::rendering::asset::shape::Shape::Shape(std::vector< Vertex > vertices, std::vector< unsigned int > indices)
Creates a new shape from the given vertices and indices. The data is copied into immutable shared vectors.
vertices A vector of vertices representing the shape's geometry indices A vector of unsigned integers representing the shape's indices.
References helios::rendering::asset::shape::Shape::indices, helios::rendering::asset::shape::Shape::vertices.
Referenced by helios::rendering::asset::shape::basic::Circle::Circle, helios::rendering::asset::shape::basic::Cube::Cube, helios::rendering::asset::shape::basic::Ellipse::Ellipse, helios::rendering::asset::shape::basic::Line::Line, helios::rendering::asset::shape::basic::Rectangle::Rectangle, helios::rendering::asset::shape::basic::Rhombus::Rhombus, helios::rendering::asset::shape::basic::Triangle::Triangle.
virtual helios::rendering::mesh::PrimitiveType helios::rendering::asset::shape::Shape::primitiveType() const noexcept=0
Returns the intended PrimitiveType for this Shape.
This method returns the intended PrimitiveType for the Shape represented by this instance. This information can be used to properly set up the MeshConfig wrapping this Shape. The intended PrimitiveType of this Shape.