helios.engine.core.data.ScoreTypeId
using helios::engine::core::data::ScoreTypeId::ScoreType = helios_engine_core_data_ScoreTypes
size_t helios::engine::core::data::ScoreTypeId::id_
The underlying ID value.
helios::engine::core::data::ScoreTypeId::ScoreTypeId(const size_t id)
Private constructor for internal use.
id The type ID value.
helios::engine::core::data::ScoreTypeId::ScoreTypeId(helios::core::types::no_init_t)
Constructs an uninitialized ScoreTypeId.
helios::core::types::no_init_t Tag to indicate no initialization.
size_t helios::engine::core::data::ScoreTypeId::value() const noexcept
Returns the underlying ID value.
The numeric type ID, suitable for use as an array index.
Referenced by helios::engine::mechanics::scoring::ScorePool::addScore, helios::engine::mechanics::scoring::systems::CombatScoringSystem::update.
static ScoreTypeId helios::engine::core::data::ScoreTypeId::id()
Gets the ScoreTypeId for a specific component type.
Uses TypeIndexer to generate a unique, monotonically increasing ID for each component type. The ID is generated once per type and cached. T The component type. Must be a concrete type (not abstract). The unique ScoreTypeId for type T.
References helios::core::data::TypeIndexer< Group >::typeIndex.
Referenced by helios::engine::mechanics::scoring::types::KillReward::typeId, helios::engine::mechanics::scoring::systems::CombatScoringSystem::update.
std::size_t std::hash< helios::engine::core::data::ScoreTypeId >::operator()(const helios::engine::core::data::ScoreTypeId &id) const noexcept