helios.game.GameObject
helios::util::Guid helios::game::GameObject::guid_
Unique identifier for this GameObject.
Generated during construction and remains constant for the lifetime of the object. Used for lookups in GameWorld and command targeting.
Referenced by helios::game::GameObject::GameObject, helios::game::GameObject::guid.
helios::scene::Transform* helios::game::GameObject::transform_
Pointer to the SceneNode's transform component.
This is a non-owning pointer. The GameObject does not manage the lifetime of the SceneNode or its Transform. The pointer remains valid only as long as the associated SceneNode exists. This pointer can become dangling if the SceneNode is destroyed before this GameObject. Accessing a dangling pointer results in undefined behavior. TodoImplement notification mechanism to invalidate this pointer when the SceneNode is destroyed. Consider using observer pattern or std::weak_ptr to safely detect SceneNode destruction.
Referenced by helios::game::GameObject::GameObject, helios::game::GameObject::rotate, helios::game::GameObject::scale, helios::game::GameObject::translate.
helios::game::GameObject::GameObject(helios::scene::SceneNode *sceneNode)
Constructs a GameObject associated with a SceneNode.
sceneNode Pointer to the SceneNode this GameObject wraps. Must not be null. sceneNode != nullptr The GameObject does NOT take ownership of the SceneNode. The caller is responsible for ensuring the SceneNode outlives this GameObject. A unique Guid is automatically generated during construction. Passing a null sceneNode will result in undefined behavior when accessing transform methods. In debug builds, this should trigger an assertion.
References helios::game::GameObject::guid_, helios::game::GameObject::transform_.
Referenced by helios::game::GameObject::rotate, helios::game::GameObject::scale, helios::game::GameObject::translate.
virtual helios::game::GameObject::~GameObject()=default
Virtual destructor to ensure proper cleanup of derived classes.
virtual void helios::game::GameObject::update(float deltaTime)=0
Updates the GameObject state for the current frame.
deltaTime Time elapsed since the last frame, in seconds. Derived classes must implement this method to define frame-by-frame behavior such as physics updates, animation, AI logic, or other time-dependent state changes. Called once per frame by the GameWorld during its update cycle.
const helios::util::Guid & helios::game::GameObject::guid() const noexcept
Returns the unique identifier of this GameObject.
Const reference to the GameObject's Guid. The Guid is generated during construction and never changes.
References helios::game::GameObject::guid_.
Referenced by helios::game::GameWorld::removeGameObject.
GameObject & helios::game::GameObject::scale(const helios::math::vec3f &scale) noexcept
Applies a scaling transformation to the GameObject.
scale The scale vector to apply (x, y, z components). Reference to this GameObject for method chaining. This modifies the underlying SceneNode's local transform. If the SceneNode has been destroyed, this will cause undefined behavior.
References helios::game::GameObject::GameObject, helios::game::GameObject::scale, helios::game::GameObject::transform_.
Referenced by helios::game::GameObject::scale.
GameObject & helios::game::GameObject::rotate(const helios::math::mat4f &rotation) noexcept
Applies a rotation transformation to the GameObject.
rotation The rotation matrix to apply. Reference to this GameObject for method chaining. This modifies the underlying SceneNode's local transform. If the SceneNode has been destroyed, this will cause undefined behavior.
References helios::game::GameObject::GameObject, helios::game::GameObject::transform_.
GameObject & helios::game::GameObject::translate(const helios::math::vec3f &translation) noexcept
Applies a translation transformation to the GameObject.
translation The translation vector to apply (x, y, z components). Reference to this GameObject for method chaining. This modifies the underlying SceneNode's local transform. If the SceneNode has been destroyed, this will cause undefined behavior.
References helios::game::GameObject::GameObject, helios::game::GameObject::transform_.