helios.scene.Snapshot
const helios::math::mat4f helios::scene::Snapshot::projectionMatrix_
The projection matrix that should be used with this Snapshot.
The projection matrix transforms camera space into clip space.
Referenced by helios::scene::Snapshot::projectionMatrix, helios::scene::Snapshot::Snapshot.
const helios::math::mat4f helios::scene::Snapshot::viewMatrix_
The view matrix that should be used with this Snapshot.
The view matrix transforms world space coordinates into camera space.
Referenced by helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::viewMatrix.
const std::vector<SnapshotItem> helios::scene::Snapshot::snapshotItems_
A const collection of `SnapshotItem`s representing all renderable objects visible in this Snapshot.
Each item contains the world transformation along with the renderable object.
Referenced by helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::snapshotItems.
const helios::rendering::Viewport& helios::scene::Snapshot::viewport_
The viewport associated with this Snapshot.
Referenced by helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::viewport.
helios::scene::Snapshot::~Snapshot()=default
helios::scene::Snapshot::Snapshot(const Snapshot &)=delete
Delete copy constructor.
Snapshots are not intended to be copied.
References helios::scene::Snapshot::Snapshot.
Referenced by helios::scene::Snapshot::operator=, helios::scene::Snapshot::operator=, helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::Snapshot.
Snapshot & helios::scene::Snapshot::operator=(const Snapshot &)=delete
Delete copy assignment operator.
Snapshots are not intended to be copied.
References helios::scene::Snapshot::Snapshot.
helios::scene::Snapshot::Snapshot(Snapshot &&) noexcept=delete
Delete move constructor.
References helios::scene::Snapshot::Snapshot.
Snapshot & helios::scene::Snapshot::operator=(Snapshot &&) noexcept=delete
Delete move assignment.
References helios::scene::Snapshot::Snapshot.
helios::scene::Snapshot::Snapshot(const helios::rendering::Viewport &viewport, const math::mat4f &projectionMatrix, const math::mat4f &viewMatrix, std::vector< SnapshotItem > snapshotItems) noexcept
Constructs a new immutable Snapshot from the given data.
viewport The viewport associated with this snapshot. projectionMatrix The projection matrix of the camera for this snapshot. viewMatrix The view matrix of the camera for this snapshot. snapshotItems A vector of snapshot items. The vector is moved into the Snapshot, transferring ownership to this instance.
References helios::scene::Snapshot::projectionMatrix, helios::scene::Snapshot::projectionMatrix_, helios::scene::Snapshot::Snapshot, helios::scene::Snapshot::snapshotItems, helios::scene::Snapshot::snapshotItems_, helios::scene::Snapshot::viewMatrix, helios::scene::Snapshot::viewMatrix_, helios::scene::Snapshot::viewport, helios::scene::Snapshot::viewport_.
std::span< const SnapshotItem > helios::scene::Snapshot::snapshotItems() const noexcept
Returns a const reference to this Snapshot's SnapshotItems.
The vector contains all renderable items in the scene. A const reference to this Snapshot's collection of SnapshotItems.
References helios::scene::Snapshot::snapshotItems_.
Referenced by helios::rendering::RenderPassFactory::populateRenderQueue, helios::scene::Snapshot::Snapshot.
const helios::rendering::Viewport & helios::scene::Snapshot::viewport() const noexcept
Returns the viewport associated with this Snapshot.
A shared pointer to the const Viewport.
References helios::scene::Snapshot::viewport_.
Referenced by helios::rendering::RenderPassFactory::buildRenderPass, helios::scene::Snapshot::Snapshot.
const helios::math::mat4f & helios::scene::Snapshot::projectionMatrix() const noexcept
Returns a const reference to the projection matrix for this Snapshot.
The matrix represents the projection matrix of the camera that was used to capture this scene. A const reference to the projection matrix used for creating this Snapshot.
References helios::scene::Snapshot::projectionMatrix_.
Referenced by helios::rendering::RenderPassFactory::buildRenderPass, helios::scene::Snapshot::Snapshot.
const helios::math::mat4f & helios::scene::Snapshot::viewMatrix() const noexcept
Returns a const reference to the view matrix for this Snapshot.
The matrix represents the view matrix of the camera that was used to capture this scene. A const reference to the view matrix used for creating this Snapshot.
References helios::scene::Snapshot::viewMatrix_.
Referenced by helios::rendering::RenderPassFactory::buildRenderPass, helios::scene::Snapshot::Snapshot.