helios.engine.builder.gameObject.builders.configs.UiTransformConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::UiTransformConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig(helios::engine::ecs::GameObject gameObject)
Constructs a UiTransformConfig and adds ComposeTransformComponent.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::offsets, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::pivot, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::viewport.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor(const helios::engine::modules::ui::layout::Anchor anchor)
Sets the anchor point for UI positioning.
anchor The anchor position (e.g., TopLeft, Center). Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::pivot.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::viewport(const helios::engine::common::types::ViewportId viewportId)
Sets the viewport for this UI element.
viewportId The ID of the viewport to attach to. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::pivot(const helios::engine::modules::ui::layout::Anchor anchor)
Sets the pivot point for transformations.
anchor The pivot position. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::UiTransformConfig::anchor, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig.
UiTransformConfig & helios::engine::builder::gameObject::builders::configs::UiTransformConfig::offsets(const helios::math::vec4f offsets)
Sets the offsets for UI positioning.
offsets The offsets as vec4f (top, right, bottom, left). Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::UiTransformConfig::offsets, helios::engine::builder::gameObject::builders::configs::UiTransformConfig::UiTransformConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::UiTransformConfig::offsets.