helios.engine.runtime.spawn.policy.SpawnRuleState
float helios::engine::runtime::spawn::policy::SpawnRuleState::sinceLastSpawn_
Time elapsed since the last spawn in seconds.
void helios::engine::runtime::spawn::policy::SpawnRuleState::setSinceLastSpawn(float sinceLastSpawn) noexcept
Sets the time since last spawn.
sinceLastSpawn Time in seconds.
References helios::engine::runtime::spawn::policy::SpawnRuleState::sinceLastSpawn.
Referenced by helios::engine::runtime::spawn::policy::conditions::RequestedAmountIsAvailableCondition::onCommit, helios::engine::runtime::spawn::policy::conditions::TimerSpawnCondition::onCommit.
float helios::engine::runtime::spawn::policy::SpawnRuleState::sinceLastSpawn() const noexcept
Returns the time since last spawn.
Time in seconds since the last spawn.
Referenced by helios::engine::runtime::spawn::policy::SpawnRuleState::setSinceLastSpawn.
void helios::engine::runtime::spawn::policy::SpawnRuleState::update(const float deltaTime) noexcept
Updates the state with the frame delta time.
deltaTime Time elapsed since last frame in seconds.