helios.core.algorithms
uint32_t helios::core::algorithms::fnv1a_hash(const std::string_view str) noexcept
Computes a 32-bit FNV-1a hash from a string.
Implements the Fowler–Noll–Vo hash function (FNV-1a variant), a fast, non-cryptographic hash suitable for hash tables and identifier generation. The function is `constexpr`, enabling compile-time hashing of string literals. ## Algorithm 1. Initialize hash with FNV offset basis (2166136261) 2. For each byte: XOR with hash, then multiply by FNV prime (16777619) ## Usage ```cpp // Compile-time hash for type-safe IDs constexpr uint32_t id = fnv1a_hash("enemy_spawn"); // Used internally by strongly-typed ID constructors constexpr GameObjectPoolId POOL{"bullets"}; // calls fnv1a_hash ``` str The string view to hash. 32-bit hash value. This is not a cryptographic hash. Do not use for security purposes. https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function GameObjectPoolId SpawnProfileId SpawnRuleId
Referenced by helios::engine::core::data::ActionId::ActionId, helios::engine::core::data::FontId::FontId, helios::engine::core::data::GameObjectPoolId::GameObjectPoolId, helios::engine::core::data::MenuId::MenuId, helios::engine::core::data::SceneId::SceneId, helios::engine::core::data::ScorePoolId::ScorePoolId, helios::engine::core::data::SpawnProfileId::SpawnProfileId, helios::engine::core::data::SpawnRuleId::SpawnRuleId, helios::engine::core::data::ViewportId::ViewportId.