helios.engine.modules.ui.widgets.components.UiTextComponent
std::string helios::engine::modules::ui::widgets::components::UiTextComponent::template_
Format template using std::format syntax.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::setTemplate, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent, helios::engine::modules::ui::widgets::components::UiTextComponent::update.
helios::rendering::text::TextRenderable* helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_
Pointer to the underlying text renderable. Not owned.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::renderable, helios::engine::modules::ui::widgets::components::UiTextComponent::renderable, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent, helios::engine::modules::ui::widgets::components::UiTextComponent::update.
double helios::engine::modules::ui::widgets::components::UiTextComponent::doubleValue_
Current numeric value to display.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::reset, helios::engine::modules::ui::widgets::components::UiTextComponent::setDouble, helios::engine::modules::ui::widgets::components::UiTextComponent::update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isDirty_
True if the text content needs to be updated.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::reset, helios::engine::modules::ui::widgets::components::UiTextComponent::setDouble, helios::engine::modules::ui::widgets::components::UiTextComponent::update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize_
True if the AABB bounds need to be recalculated.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize, helios::engine::modules::ui::widgets::components::UiTextComponent::resizeComplete, helios::engine::modules::ui::widgets::components::UiTextComponent::update.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled_
Whether this component is enabled.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::disable, helios::engine::modules::ui::widgets::components::UiTextComponent::enable, helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
References helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::enable() noexcept
Enables this component.
References helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::disable() noexcept
Disables this component.
References helios::engine::modules::ui::widgets::components::UiTextComponent::isEnabled_.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(helios::rendering::text::TextRenderable *renderable)
Constructs a UiTextComponent with the given renderable.
renderable Pointer to the TextRenderable. Must not be nullptr.
References helios::engine::modules::ui::widgets::components::UiTextComponent::renderable, helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::operator=, helios::engine::modules::ui::widgets::components::UiTextComponent::operator=, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(const UiTextComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_, helios::engine::modules::ui::widgets::components::UiTextComponent::template_, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
UiTextComponent & helios::engine::modules::ui::widgets::components::UiTextComponent::operator=(const UiTextComponent &)=default
References helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent(UiTextComponent &&) noexcept=default
References helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
UiTextComponent & helios::engine::modules::ui::widgets::components::UiTextComponent::operator=(UiTextComponent &&) noexcept=default
References helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
const helios::rendering::text::TextRenderable * helios::engine::modules::ui::widgets::components::UiTextComponent::renderable() const noexcept
Returns the underlying text renderable as const pointer.
Const pointer to the TextRenderable. Never nullptr.
References helios::engine::modules::ui::widgets::components::UiTextComponent::renderable, helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::renderable, helios::engine::modules::ui::widgets::components::UiTextComponent::UiTextComponent.
helios::rendering::text::TextRenderable * helios::engine::modules::ui::widgets::components::UiTextComponent::renderable() noexcept
Returns the underlying text renderable as a pointer.
Pointer to the TextRenderable. Never nullptr.
References helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::setTemplate(std::string templateTxt)
Sets the format template.
Uses std::format syntax. The value is inserted at `{0}`. templateTxt The format template string.
References helios::engine::modules::ui::widgets::components::UiTextComponent::template_.
Referenced by helios::engine::builder::gameObject::builders::configs::TextRenderableConfig::build.
void helios::engine::modules::ui::widgets::components::UiTextComponent::reset() noexcept
Resets the component to its initial state.
References helios::engine::modules::ui::widgets::components::UiTextComponent::doubleValue_, helios::engine::modules::ui::widgets::components::UiTextComponent::isDirty_.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::onAcquire, helios::engine::modules::ui::widgets::components::UiTextComponent::onRelease.
void helios::engine::modules::ui::widgets::components::UiTextComponent::onAcquire() noexcept
References helios::engine::modules::ui::widgets::components::UiTextComponent::reset.
void helios::engine::modules::ui::widgets::components::UiTextComponent::onRelease() noexcept
References helios::engine::modules::ui::widgets::components::UiTextComponent::reset.
void helios::engine::modules::ui::widgets::components::UiTextComponent::update()
Updates the text content if dirty.
Applies the template to the current value and updates the renderable.
References helios::engine::modules::ui::widgets::components::UiTextComponent::doubleValue_, helios::engine::modules::ui::widgets::components::UiTextComponent::isDirty_, helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize_, helios::engine::modules::ui::widgets::components::UiTextComponent::renderable_, helios::engine::modules::ui::widgets::components::UiTextComponent::template_.
Referenced by helios::engine::modules::ui::widgets::components::UiTextComponent::setDouble.
bool helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize() const noexcept
Checks if the AABB bounds need recalculation.
True if a resize is needed, false otherwise.
References helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::resizeComplete() noexcept
Marks the resize as complete.
References helios::engine::modules::ui::widgets::components::UiTextComponent::needsResize_.
void helios::engine::modules::ui::widgets::components::UiTextComponent::setDouble(const double value)
Sets the numeric value to display.
Triggers an update if the value has changed. value The value to display.
References helios::engine::modules::ui::widgets::components::UiTextComponent::doubleValue_, helios::engine::modules::ui::widgets::components::UiTextComponent::isDirty_, helios::engine::modules::ui::widgets::components::UiTextComponent::update.