helios.engine.builder.gameObject.builders.configs.MenuItemConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::MenuItemConfig::gameObject_
The GameObject being configured.
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::MenuItemConfig::parentMenu_
Pointer to the parent menu GameObject.
std::optional<size_t> helios::engine::builder::gameObject::builders::configs::MenuItemConfig::index_
Optional index position in the menu.
bool helios::engine::builder::gameObject::builders::configs::MenuItemConfig::isSelected_
Whether this item is selected.
void helios::engine::builder::gameObject::builders::configs::MenuItemConfig::attach()
Attaches this item to the parent menu.
helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig(helios::engine::ecs::GameObject gameObject, helios::engine::ecs::GameObject &parentMenu)
Constructs a MenuItemConfig for the given GameObject.
Automatically adds UiStyleComponent and UiStateComponent, and attaches the item to the parent menu. gameObject The GameObject to configure. parentMenu The parent menu GameObject (must have MenuComponent).
Referenced by helios::engine::builder::gameObject::builders::configs::MenuItemConfig::actionId, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::index, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::normalColor, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::normalScale, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selected, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selectedColor, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selectedScale.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selected(const bool isSelected)
Sets the selected state.
isSelected True if this item should be selected. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::normalColor(const helios::math::vec4f color)
Sets the normal state color.
color The RGBA color. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::normalScale(const float scale)
Sets the normal state scale.
scale The scale factor. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selectedColor(helios::math::vec4f color)
Sets the selected state color.
color The RGBA color. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::selectedScale(const float scale)
Sets the selected state scale.
scale The scale factor. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::actionId(const helios::engine::core::data::ActionId actionId)
Sets the action ID for this menu item.
actionId The action to trigger when activated. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::actionId, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::MenuItemConfig::actionId.
MenuItemConfig & helios::engine::builder::gameObject::builders::configs::MenuItemConfig::index(const size_t index)
Sets the index position in the parent menu.
index The index position. Reference to this config for method chaining.
References helios::engine::builder::gameObject::builders::configs::MenuItemConfig::index, helios::engine::builder::gameObject::builders::configs::MenuItemConfig::MenuItemConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::MenuItemConfig::index.