helios.engine.runtime.world.Session
ecs::GameObject helios::engine::runtime::world::Session::gameObject_
The underlying GameObject storing session components.
ecs::EntityHandle helios::engine::runtime::world::Session::playerEntity_
Handle to the player entity.
helios::engine::runtime::world::Session::Session(const ecs::GameObject go)
Constructs a session with the given GameObject.
Automatically adds ActiveViewportIdsStateComponent. State types must be registered separately via trackState<T>(). go The GameObject to use as the session entity.
void helios::engine::runtime::world::Session::setPlayerEntityHandle(const ecs::EntityHandle go) noexcept
Sets the player entity handle.
go The player's entity handle.
ecs::EntityHandle helios::engine::runtime::world::Session::playerEntityHandle() const noexcept
Returns the player entity handle.
The player's entity handle.
Referenced by helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerActive, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerInactive.
void helios::engine::runtime::world::Session::reset()
Resets the session state.
void helios::engine::runtime::world::Session::setStateFrom(const StateTransitionContext< StateType > stateTransitionContext) noexcept
Updates state from a transition context.
Called by StateManager after a successful transition. StateType The state enum type. stateTransitionContext The completed transition context.
StateType helios::engine::runtime::world::Session::state() const noexcept
Returns the current state for a given state type.
StateType The state enum type. The current state, or StateType::Undefined if not found.
References helios::engine::state::components::StateComponent< StateType >::state.
Referenced by helios::engine::runtime::gameloop::TypedPass< StateType >::shouldRun.
StateTransitionIdType< StateType > helios::engine::runtime::world::Session::stateTransitionId() const noexcept
Returns the last transition ID for a given state type.
StateType The state enum type. The transition ID, or Undefined if not found.
References helios::engine::state::components::StateComponent< StateType >::transitionId.
void helios::engine::runtime::world::Session::trackState()
Lets this session track the specified StateType.
StateType The state enum type.
void helios::engine::runtime::world::Session::setViewportIds(std::span< const helios::engine::core::data::ViewportId > &viewportIds) noexcept
Replaces the active viewport IDs with the provided list.
viewportIds The new list of active viewport IDs.
References helios::engine::runtime::world::Session::setViewportIds, helios::engine::runtime::world::Session::viewportIds.
Referenced by helios::engine::runtime::world::Session::setViewportIds.
std::span< const helios::engine::core::data::ViewportId > helios::engine::runtime::world::Session::viewportIds() const noexcept
Returns the currently active viewport IDs.
Read-only span of viewport identifiers.
References helios::engine::runtime::world::Session::viewportIds.
Referenced by helios::engine::runtime::world::Session::setViewportIds, helios::engine::runtime::world::Session::viewportIds.
void helios::engine::runtime::world::Session::clearViewportIds() noexcept
Clears all active viewport IDs.