helios.engine.ecs.EntityManager
std::vector<std::unique_ptr<SparseSetBase> > helios::engine::ecs::EntityManager::components_
Component storage indexed by type ID.
@odo sort after size()
EntityRegistry& helios::engine::ecs::EntityManager::registry_
Reference to the entity registry for handle management.
const size_t helios::engine::ecs::EntityManager::capacity_
initial capacity for the underlying sparsesets.
helios::engine::ecs::EntityManager::EntityManager(EntityRegistry &registry, size_t capacity=ENTITY_MANAGER_DEFAULT_CAPACITY)
Constructs an EntityManager with the given registry.
registry The EntityRegistry used for handle allocation and validation.
EntityHandle helios::engine::ecs::EntityManager::create()
Creates a new entity.
Delegates to the underlying `EntityRegistry` to allocate a new handle. A valid `EntityHandle` for the newly created entity. EntityRegistry::create
bool helios::engine::ecs::EntityManager::isValid(const EntityHandle handle) const noexcept
Checks if an entity handle is valid.
handle The handle to validate. `true` if the handle refers to a living entity.
References helios::engine::ecs::EntityManager::handle.
bool helios::engine::ecs::EntityManager::isValid(const EntityId entityId) const noexcept
Checks if an entity ID is valid.
entityId The entity ID to validate. `true` if the entity ID refers to a living entity.
References helios::engine::ecs::EntityManager::handle.
bool helios::engine::ecs::EntityManager::destroy(const EntityHandle &handle)
Destroys an entity and invalidates its handle.
Increments the entity's version in the registry, making all existing handles to this entity stale. Does not automatically remove components from storage. handle The handle of the entity to destroy. `true` if the entity was destroyed, `false` if already invalid.
References helios::engine::ecs::EntityManager::handle, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::EntityManager::raw.
T * helios::engine::ecs::EntityManager::get(const EntityHandle handle) const
Retrieves a component for the given entity.
T The component type to retrieve. handle The entity whose component to retrieve. Pointer to the component, or `nullptr` if the entity is invalid or does not have the requested component.
References helios::engine::ecs::EntityManager::handle, helios::engine::ecs::EntityManager::has, helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::EntityManager::emplaceOrGet.
SparseSet< T > * helios::engine::ecs::EntityManager::getSparseSet()
Returns the SparseSet for a component type.
T The component type. Pointer to the SparseSet, or `nullptr` if the type has no storage.
References helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::value.
const SparseSet< T > * helios::engine::ecs::EntityManager::getSparseSet() const
Returns the SparseSet for a component type (const).
T The component type. Const pointer to the SparseSet, or `nullptr` if the type has no storage.
References helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::value.
bool helios::engine::ecs::EntityManager::has(const EntityHandle handle) const
Checks whether an entity has a specific component.
T The component type to check for. handle The entity to query. `true` if the entity has the component, `false` if the handle is invalid or the component is not attached.
References helios::engine::ecs::EntityManager::handle, helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::EntityManager::clone, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::get, helios::engine::ecs::EntityManager::raw, helios::engine::ecs::EntityManager::remove.
bool helios::engine::ecs::EntityManager::has(const EntityHandle handle, const helios::engine::core::data::ComponentTypeId typeId) const
Checks whether an entity has a component by type ID.
handle The entity to query. typeId The component type identifier. `true` if the entity has the component, `false` otherwise.
References helios::engine::ecs::EntityManager::handle, helios::engine::core::data::ComponentTypeId::value.
void helios::engine::ecs::EntityManager::enable(const EntityHandle handle, const helios::engine::core::data::ComponentTypeId typeId) const
Enables a component by type ID.
Calls the component's `enable()` method if registered. handle The entity whose component to enable. typeId The component type identifier.
References helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::handle.
Referenced by helios::engine::ecs::EntityManager::disable, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::enable.
void helios::engine::ecs::EntityManager::disable(const EntityHandle handle, const helios::engine::core::data::ComponentTypeId typeId) const
Disables a component by type ID.
Calls the component's `disable()` method if registered. handle The entity whose component to disable. typeId The component type identifier.
References helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::handle.
void helios::engine::ecs::EntityManager::enable(const EntityHandle handle, const helios::engine::core::data::ComponentTypeId typeId, const bool enable) const
Enables or disables a component by type ID.
handle The entity whose component to modify. typeId The component type identifier. enable `true` to enable, `false` to disable.
References helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::handle, helios::engine::ecs::EntityManager::has, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::EntityManager::raw.
T * helios::engine::ecs::EntityManager::emplace(const EntityHandle handle, Args &&...args)
Constructs and attaches a component to an entity.
If the component type has not been registered yet, a new `SparseSet` is created. The component is constructed in-place with the provided arguments. Return nullptre if the component already exists or if the handle was invalid. T The component type to emplace. Args Constructor argument types. handle The entity to attach the component to. args Arguments forwarded to the component constructor. Pointer to the newly created component, or `nullptr` if the handle is invalid.
References helios::engine::ecs::EntityManager::handle, helios::engine::core::data::ComponentTypeId::id, helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::EntityManager::emplaceOrGet.
T * helios::engine::ecs::EntityManager::emplaceOrGet(const EntityHandle handle, Args &&...args)
Returns existing component or creates a new one.
T The component type. Args Constructor argument types. handle The entity. args Arguments forwarded to the constructor if creating. Pointer to the existing or newly created component, or `nullptr` if the handle is invalid.
References helios::engine::ecs::EntityManager::emplace, helios::engine::ecs::EntityManager::get, helios::engine::ecs::EntityManager::handle, helios::engine::ecs::EntityManager::raw.
bool helios::engine::ecs::EntityManager::remove(const EntityHandle &handle)
Removes a specific component from an entity.
Unlike `destroy()`, this only removes a single component type while keeping the entity and other components intact. T The component type to remove. handle The entity whose component to remove. `true` if the component was removed, `false` if the handle was invalid, the component was not attached, or removal was blocked by `onRemove`. destroy SparseSet::remove
References helios::engine::ecs::EntityManager::handle, helios::engine::ecs::EntityManager::has, helios::engine::core::data::ComponentTypeId::id, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::EntityManager::raw.
std::generator< helios::engine::core::data::ComponentTypeId > helios::engine::ecs::EntityManager::componentTypeIds(const EntityHandle handle) const
Returns a generator over all component type IDs attached to an entity.
handle The entity to query. Generator yielding ComponentTypeId for each attached component.
References helios::engine::ecs::EntityManager::handle.
Referenced by helios::engine::ecs::EntityManager::clone.
void helios::engine::ecs::EntityManager::clone(const EntityHandle source, const EntityHandle target)
Clones all components from source entity to target entity.
Iterates through all components on the source and copies them to the target using the registered clone function. Skips components that already exist on the target. source The entity to clone from. target The entity to clone to.
References helios::engine::ecs::EntityManager::componentTypeIds, helios::engine::ecs::EntityManager::has, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::EntityManager::raw.
void * helios::engine::ecs::EntityManager::raw(const EntityHandle handle, const helios::engine::core::data::ComponentTypeId typeId) const
Returns raw void pointer to a component.
handle The entity. typeId The component type identifier. Raw pointer to the component, or `nullptr` if not found.
References helios::engine::ecs::EntityManager::handle, helios::engine::ecs::EntityManager::has, helios::engine::core::data::ComponentTypeId::value.
Referenced by helios::engine::ecs::EntityManager::clone, helios::engine::ecs::EntityManager::destroy, helios::engine::ecs::EntityManager::emplaceOrGet, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::remove.
EntityHandle helios::engine::ecs::EntityManager::handle(const EntityId entityId) const
Reconstructs an EntityHandle from an EntityId.
entityId The entity ID. EntityHandle with current version from the registry.
Referenced by helios::engine::ecs::EntityManager::componentTypeIds, helios::engine::ecs::EntityManager::destroy, helios::engine::ecs::EntityManager::disable, helios::engine::ecs::EntityManager::emplace, helios::engine::ecs::EntityManager::emplaceOrGet, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::enable, helios::engine::ecs::EntityManager::get, helios::engine::ecs::EntityManager::has, helios::engine::ecs::EntityManager::has, helios::engine::ecs::EntityManager::isValid, helios::engine::ecs::EntityManager::isValid, helios::engine::ecs::EntityManager::raw, helios::engine::ecs::EntityManager::remove.