helios.engine.mechanics.gamestate.types.GameStateTransitionContext
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionContext::from_
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionContext::transitionId_
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionContext::to_
helios::engine::mechanics::gamestate::types::GameStateTransitionContext::GameStateTransitionContext(const GameState from, const GameState to, const GameStateTransitionId transitionId)
Constructs a transition context.
from The state being exited. to The state being entered. transitionId The identifier of the transition.
References helios::engine::mechanics::gamestate::types::GameStateTransitionContext::from, helios::engine::mechanics::gamestate::types::GameStateTransitionContext::to, helios::engine::mechanics::gamestate::types::GameStateTransitionContext::transitionId.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionContext::to() const noexcept
Returns the target state.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionContext::GameStateTransitionContext.
GameState helios::engine::mechanics::gamestate::types::GameStateTransitionContext::from() const noexcept
Returns the source state.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionContext::GameStateTransitionContext.
GameStateTransitionId helios::engine::mechanics::gamestate::types::GameStateTransitionContext::transitionId() const noexcept
Returns the transition identifier.
Referenced by helios::engine::mechanics::gamestate::types::GameStateTransitionContext::GameStateTransitionContext.