helios.engine.runtime.world.GameWorld
std::unordered_map<helios::util::Guid, std::unique_ptr<helios::engine::ecs::GameObject> > helios::engine::runtime::world::GameWorld::gameObjects_
Legacy storage for GameObjects indexed by Guid.
Unused since the migration to EntityRegistry/EntityManager. Retained for backward compatibility during the transition period. DeprecatedSuperseded by EntityRegistry and EntityManager.
const helios::util::log::Logger& helios::engine::runtime::world::GameWorld::logger_
The logger used with this GameWorld instance.
Defaults to HELIOS_LOG_SCOPE.
std::vector<std::unique_ptr<helios::engine::runtime::world::Manager> > helios::engine::runtime::world::GameWorld::managers_
Collection of registered Manager instances.
Managers handle cross-cutting concerns such as object pooling, spawn management, and projectile lifecycle. They are initialized via init() and flushed each frame via flushManagers().
Referenced by helios::engine::runtime::world::GameWorld::addManager, helios::engine::runtime::world::GameWorld::flushManagers, helios::engine::runtime::world::GameWorld::getManager, helios::engine::runtime::world::GameWorld::init, helios::engine::runtime::world::GameWorld::reset.
std::unique_ptr<helios::engine::runtime::world::Level> helios::engine::runtime::world::GameWorld::level_
The current level loaded in the game world.
Can be null if no level is currently active.
Referenced by helios::engine::runtime::world::GameWorld::hasLevel, helios::engine::runtime::world::GameWorld::level, helios::engine::runtime::world::GameWorld::setLevel.
helios::engine::mechanics::scoring::ScoreCommandHandler* helios::engine::runtime::world::GameWorld::scoreCommandHandler_
Registered handler for score commands.
Receives score update commands and processes them according to the scoring system logic.
Referenced by helios::engine::runtime::world::GameWorld::registerScoreCommandHandler, helios::engine::runtime::world::GameWorld::scoreCommandHandler.
helios::engine::mechanics::timing::TimerCommandHandler* helios::engine::runtime::world::GameWorld::timerCommandHandler_
Registered handler for timer commands.
Receives timer commands and routes them to the TimerManager for processing.
Referenced by helios::engine::runtime::world::GameWorld::registerTimerCommandHandler, helios::engine::runtime::world::GameWorld::timerCommandHandler.
std::vector<helios::engine::state::StateCommandHandler*> helios::engine::runtime::world::GameWorld::stateCommandHandlers_
Registered handlers for state commands, indexed by StateTypeId.
Stores pointers to TypedStateCommandHandler instances. Each state type (GameState, MatchState, etc.) has a unique index computed from StateTypeId.
Referenced by helios::engine::runtime::world::GameWorld::registerStateCommandHandler, helios::engine::runtime::world::GameWorld::stateCommandHandler.
helios::engine::modules::ui::UiActionCommandHandler* helios::engine::runtime::world::GameWorld::uiActionCommandHandler_
Registered handler for UI action commands.
Referenced by helios::engine::runtime::world::GameWorld::registerUiActionCommandHandler, helios::engine::runtime::world::GameWorld::uiActionCommandHandler.
helios::engine::runtime::spawn::SpawnCommandHandlerRegistry helios::engine::runtime::world::GameWorld::spawnCommandHandlerRegistry_
Registry for mapping spawn profiles to their command handlers.
Stores the association between SpawnProfileIds and their corresponding SpawnCommandHandlers. This allows the system to look up the correct handler (e.g., a specific object pool) when processing spawn commands.
Referenced by helios::engine::runtime::world::GameWorld::registerSpawnCommandHandler, helios::engine::runtime::world::GameWorld::spawnCommandHandler.
helios::engine::ecs::EntityRegistry helios::engine::runtime::world::GameWorld::entityRegistry_
Entity registry for handle allocation and validation.
Manages entity lifecycle including creation, destruction, and stale handle detection via versioning.
Referenced by helios::engine::runtime::world::GameWorld::GameWorld.
helios::engine::ecs::EntityManager helios::engine::runtime::world::GameWorld::em_
Entity manager for component storage.
Stores components in type-indexed SparseSets and provides methods for component manipulation. Marked `mutable` to allow const methods to use it without const_cast.
Referenced by helios::engine::runtime::world::GameWorld::addGameObject, helios::engine::runtime::world::GameWorld::clone, helios::engine::runtime::world::GameWorld::find, helios::engine::runtime::world::GameWorld::find, helios::engine::runtime::world::GameWorld::GameWorld, helios::engine::runtime::world::GameWorld::view, helios::engine::runtime::world::GameWorld::view.
Session helios::engine::runtime::world::GameWorld::session_
The current game session holding state data.
Referenced by helios::engine::runtime::world::GameWorld::GameWorld, helios::engine::runtime::world::GameWorld::reset, helios::engine::runtime::world::GameWorld::session.
helios::engine::runtime::world::GameWorld::GameWorld()
Constructs the GameWorld.
Initializes the EntityManager with the internal EntityRegistry and creates a Session backed by a dedicated GameObject.
References helios::engine::runtime::world::GameWorld::addGameObject, helios::engine::runtime::world::GameWorld::em_, helios::engine::runtime::world::GameWorld::entityRegistry_, helios::engine::runtime::world::GameWorld::session_.
Referenced by helios::engine::runtime::world::GameWorld::GameWorld, helios::engine::runtime::world::GameWorld::GameWorld, helios::engine::runtime::world::GameWorld::operator=, helios::engine::runtime::world::GameWorld::operator=.
helios::engine::runtime::world::GameWorld::GameWorld(const GameWorld &)=delete
References helios::engine::runtime::world::GameWorld::GameWorld.
GameWorld helios::engine::runtime::world::GameWorld::operator=(const GameWorld &)=delete
References helios::engine::runtime::world::GameWorld::GameWorld.
helios::engine::runtime::world::GameWorld::GameWorld(const GameWorld &&)=delete
References helios::engine::runtime::world::GameWorld::GameWorld.
GameWorld helios::engine::runtime::world::GameWorld::operator=(const GameWorld &&)=delete
References helios::engine::runtime::world::GameWorld::GameWorld.
Session & helios::engine::runtime::world::GameWorld::session()
Returns a reference to the current game session.
Reference to the Session.
References helios::engine::runtime::world::GameWorld::session_.
void helios::engine::runtime::world::GameWorld::init()
Initializes all registered managers.
Should be called after all managers have been added and before the game loop starts. Each manager's init() method is invoked with a reference to this GameWorld.
References helios::engine::runtime::world::GameWorld::managers_.
void helios::engine::runtime::world::GameWorld::setLevel(std::unique_ptr< helios::engine::runtime::world::Level > level) noexcept
Sets the current level for the game world.
level Unique pointer to the Level instance. Ownership is transferred to the GameWorld.
References helios::engine::runtime::world::GameWorld::level, helios::engine::runtime::world::GameWorld::level_.
bool helios::engine::runtime::world::GameWorld::hasLevel() const noexcept
Checks if a level is currently loaded.
True if a level is set, false otherwise.
References helios::engine::runtime::world::GameWorld::level_.
const helios::engine::runtime::world::Level * helios::engine::runtime::world::GameWorld::level() const noexcept
Retrieves the currently loaded level.
Const pointer to the active Level. Calling this method when hasLevel() returns false results in undefined behavior.
References helios::engine::runtime::world::GameWorld::level_.
Referenced by helios::engine::runtime::world::GameWorld::setLevel.
bool helios::engine::runtime::world::GameWorld::hasManager() const
Checks if a Manager of the specified type is registered.
T The Manager type to check for. True if a Manager of type T is registered, false otherwise.
References helios::engine::runtime::world::GameWorld::getManager.
Referenced by helios::engine::runtime::world::GameWorld::addManager.
T & helios::engine::runtime::world::GameWorld::addManager(Args &&... args)
Adds and registers a Manager of the specified type.
Creates a new Manager instance and adds it to the world. The manager's onAdd() callback is invoked after registration. T The Manager type to add. Must derive from Manager. Args Constructor argument types. args Arguments forwarded to the Manager constructor. Reference to the newly added Manager. No Manager of type T is already registered.
References helios::engine::runtime::world::GameWorld::hasManager, helios::engine::runtime::world::GameWorld::managers_.
bool helios::engine::runtime::world::GameWorld::registerSpawnCommandHandler(const helios::engine::core::data::SpawnProfileId spawnProfileId, helios::engine::runtime::spawn::SpawnCommandHandler &poolManager)
Registers a SpawnCommandHandler for a specific spawn profile.
Associates a handler with a spawn profile ID. The handler processes spawn and despawn requests for entities associated with that profile. spawnProfileId The spawn profile identifier to associate with the handler. poolManager Reference to the handler to register. True if registration succeeded, false if already registered.
References helios::engine::runtime::world::GameWorld::spawnCommandHandlerRegistry_.
Referenced by helios::engine::runtime::spawn::SpawnManager::init.
bool helios::engine::runtime::world::GameWorld::registerUiActionCommandHandler(helios::engine::modules::ui::UiActionCommandHandler &uiActionCommandHandler)
Registers a handler for UI action commands.
uiActionCommandHandler Reference to the handler to register. True if registration succeeded.
References helios::engine::runtime::world::GameWorld::uiActionCommandHandler, helios::engine::runtime::world::GameWorld::uiActionCommandHandler_.
Referenced by helios::engine::modules::ui::UiActionCommandManager::init.
helios::engine::modules::ui::UiActionCommandHandler * helios::engine::runtime::world::GameWorld::uiActionCommandHandler()
Retrieves the registered UI action command handler.
Pointer to the handler, or nullptr if not registered.
References helios::engine::runtime::world::GameWorld::uiActionCommandHandler_.
Referenced by helios::engine::runtime::world::GameWorld::registerUiActionCommandHandler.
helios::engine::runtime::spawn::SpawnCommandHandler * helios::engine::runtime::world::GameWorld::spawnCommandHandler(const helios::engine::core::data::SpawnProfileId spawnProfileId)
Retrieves a SpawnCommandHandler for a specific spawn profile.
Used to submit spawn/despawn commands to the handler responsible for a particular spawn profile (e.g., bullet pool, enemy pool). spawnProfileId The spawn profile identifier to look up. Pointer to the handler, or nullptr if not registered. registerSpawnCommandHandler() SpawnCommandHandler
References helios::engine::runtime::world::GameWorld::spawnCommandHandlerRegistry_.
bool helios::engine::runtime::world::GameWorld::registerScoreCommandHandler(helios::engine::mechanics::scoring::ScoreCommandHandler &scoreCommandHandler)
Registers a handler for score commands.
Associates a ScoreCommandHandler with this GameWorld. Only one handler can be registered at a time. scoreCommandHandler Reference to the handler to register. True if registration succeeded, false if already registered.
References helios::engine::runtime::world::GameWorld::scoreCommandHandler, helios::engine::runtime::world::GameWorld::scoreCommandHandler_.
Referenced by helios::engine::mechanics::scoring::ScorePoolManager::init.
helios::engine::mechanics::scoring::ScoreCommandHandler * helios::engine::runtime::world::GameWorld::scoreCommandHandler()
Retrieves the registered ScoreCommandHandler.
Pointer to the handler, or nullptr if not registered.
References helios::engine::runtime::world::GameWorld::scoreCommandHandler_.
Referenced by helios::engine::runtime::world::GameWorld::registerScoreCommandHandler.
bool helios::engine::runtime::world::GameWorld::registerTimerCommandHandler(helios::engine::mechanics::timing::TimerCommandHandler &timerCommandHandler)
Registers a handler for timer commands.
Associates a TimerCommandHandler with this GameWorld. Only one handler can be registered at a time. timerCommandHandler Reference to the handler to register. True if registration succeeded, false if already registered.
References helios::engine::runtime::world::GameWorld::timerCommandHandler, helios::engine::runtime::world::GameWorld::timerCommandHandler_.
Referenced by helios::engine::mechanics::timing::TimerManager::init.
helios::engine::mechanics::timing::TimerCommandHandler * helios::engine::runtime::world::GameWorld::timerCommandHandler()
Retrieves the registered TimerCommandHandler.
Pointer to the handler, or nullptr if not registered.
References helios::engine::runtime::world::GameWorld::timerCommandHandler_.
Referenced by helios::engine::runtime::world::GameWorld::registerTimerCommandHandler.
bool helios::engine::runtime::world::GameWorld::registerStateCommandHandler(helios::engine::state::TypedStateCommandHandler< T > &stateCommandHandler)
Registers a handler for state commands of a specific type.
Associates a TypedStateCommandHandler with the given state type. The handler receives state transition commands and routes them to the appropriate StateManager. T The state enum type (e.g., GameState, MatchState). stateCommandHandler Reference to the handler to register. True if registration succeeded, false if already registered. StateManager TypedStateCommandHandler
References helios::engine::core::data::StateTypeId::id, helios::engine::runtime::world::GameWorld::stateCommandHandler, helios::engine::runtime::world::GameWorld::stateCommandHandlers_.
Referenced by helios::engine::state::StateManager< types::GameState >::init.
helios::engine::state::TypedStateCommandHandler< T > * helios::engine::runtime::world::GameWorld::stateCommandHandler()
Retrieves the registered state command handler for a type.
T The state enum type to look up. Pointer to the handler, or nullptr if not registered.
References helios::engine::core::data::StateTypeId::id, helios::engine::runtime::world::GameWorld::stateCommandHandlers_.
Referenced by helios::engine::runtime::world::GameWorld::registerStateCommandHandler.
T * helios::engine::runtime::world::GameWorld::getManager() const
Retrieves a registered Manager by type.
T The Manager type to retrieve. Must derive from Manager. Pointer to the Manager if found, nullptr otherwise.
References helios::engine::runtime::world::GameWorld::managers_.
Referenced by helios::engine::runtime::spawn::policy::amount::SpawnAll::getAmount, helios::engine::runtime::world::GameWorld::hasManager, helios::engine::runtime::spawn::SpawnManager::init.
void helios::engine::runtime::world::GameWorld::flushManagers(helios::engine::runtime::world::UpdateContext &updateContext)
Flushes all registered managers.
Called during the game loop to allow managers to process their queued requests (e.g., spawn requests, pool returns). updateContext The current frame's update context.
References helios::engine::runtime::world::GameWorld::managers_.
Referenced by helios::engine::runtime::gameloop::GameLoop::phaseCommit.
helios::engine::ecs::GameObject helios::engine::runtime::world::GameWorld::addGameObject()
Creates a new GameObject in the world.
Allocates an entity handle via the EntityRegistry and returns a lightweight GameObject wrapper. The returned GameObject is ~16 bytes and should be passed by value. A new GameObject ready for component attachment. GameObject EntityManager::create
References helios::engine::runtime::world::GameWorld::em_.
Referenced by helios::engine::runtime::world::GameWorld::clone, helios::engine::runtime::world::GameWorld::GameWorld.
auto helios::engine::runtime::world::GameWorld::view()
Creates a View for iterating entities with specific components.
Returns a lightweight view that iterates over all entities possessing the specified component types. Use with range-based for loops and structured bindings. ```cpp for (auto [entity, transform, velocity, active] : gameWorld.view< TransformComponent, VelocityComponent, Active >().whereEnabled()) { // Process matching entities } ``` Components The component types to query for. A View for iterating matching entities. View
References helios::engine::runtime::world::GameWorld::em_.
Referenced by helios::engine::runtime::pooling::GameObjectPoolManager::init.
auto helios::engine::runtime::world::GameWorld::view() const
Creates a const View for iterating entities with specific components.
Components The component types to query for. A const View for iterating matching entities.
References helios::engine::runtime::world::GameWorld::em_.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::world::GameWorld::find(const helios::engine::ecs::EntityHandle handle)
Finds a GameObject by its EntityHandle.
Validates the handle and returns a GameObject wrapper if valid. Returns std::nullopt if the handle is stale or invalid. handle The EntityHandle to look up. Optional containing the GameObject if found, std::nullopt otherwise.
References helios::engine::runtime::world::GameWorld::em_.
Referenced by helios::engine::runtime::messaging::command::CommandBuffer::flush, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerActive, helios::engine::mechanics::match::rules::guards::DefaultMatchStateTransitionGuards::isPlayerInactive.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::world::GameWorld::find(const helios::engine::ecs::EntityHandle handle) const
Finds a GameObject by its EntityHandle (const version).
handle The EntityHandle to look up. Optional containing the GameObject if found, std::nullopt otherwise.
References helios::engine::runtime::world::GameWorld::em_.
helios::engine::ecs::GameObject helios::engine::runtime::world::GameWorld::clone(const helios::engine::ecs::GameObject gameObject)
Clones a GameObject and all its components.
Creates a new entity and copies all components from the source to the target. The new GameObject is initially inactive. Components with `onClone()` hooks will have them invoked after copy construction. gameObject The source GameObject to clone. A new inactive GameObject with cloned components. EntityManager::clone
References helios::engine::runtime::world::GameWorld::addGameObject, helios::engine::runtime::world::GameWorld::em_, helios::engine::ecs::GameObject::entityHandle.
void helios::engine::runtime::world::GameWorld::reset()
Resets all managers and the session to their initial state.
Called during level transitions or game restarts to clear accumulated state. Invokes reset() on all managers and the session.
References helios::engine::runtime::world::GameWorld::managers_, helios::engine::runtime::world::GameWorld::session_.