helios.engine.builder.gameObject.builders.configs.ObserverConfig
helios::engine::ecs::GameObject helios::engine::builder::gameObject::builders::configs::ObserverConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig(helios::engine::ecs::GameObject gameObject)
Constructs an ObserverConfig.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::ObserverConfig::lives, helios::engine::builder::gameObject::builders::configs::ObserverConfig::maxScore, helios::engine::builder::gameObject::builders::configs::ObserverConfig::runningScore, helios::engine::builder::gameObject::builders::configs::ObserverConfig::scorePool, helios::engine::builder::gameObject::builders::configs::ObserverConfig::time.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::scorePool(const helios::engine::mechanics::scoring::types::ScorePoolId scorePoolId)
Adds a ScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining. Deprecateduse runningScore()
References helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig, helios::engine::builder::gameObject::builders::configs::ObserverConfig::runningScore.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::runningScore(const helios::engine::mechanics::scoring::types::ScorePoolId scorePoolId)
Adds a ScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig.
Referenced by helios::engine::builder::gameObject::builders::configs::ObserverConfig::scorePool.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::lives(const helios::engine::ecs::GameObject gameObject)
Adds a LivesBindingComponent observing the given entity's lives.
gameObject The entity whose LivesComponent is observed. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::maxScore(const helios::engine::mechanics::scoring::types::ScorePoolId scorePoolId)
Adds a MaxScoreObserverComponent bound to the specified pool.
scorePoolId The ID of the score pool to observe. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig.
ObserverConfig & helios::engine::builder::gameObject::builders::configs::ObserverConfig::time(const helios::engine::mechanics::timing::types::GameTimerId gameTimerId)
Adds a GameTimerBindingComponent bound to the specified timer.
gameTimerId The ID of the game timer to observe. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::ObserverConfig::ObserverConfig.