helios.engine.runtime.gameloop.GameLoop
bool helios::engine::runtime::gameloop::GameLoop::initialized_
Flag indicating whether init() has been called.
Used to assert that init() is called exactly once before the first update() and to prevent multiple initializations.
const helios::util::log::Logger& helios::engine::runtime::gameloop::GameLoop::logger_
The logger used with this GameLoop instance.
helios::engine::runtime::gameloop::Phase helios::engine::runtime::gameloop::GameLoop::prePhase_
The pre-update phase, executed before main gameplay logic.
Referenced by helios::engine::runtime::gameloop::GameLoop::init, helios::engine::runtime::gameloop::GameLoop::phase, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::gameloop::Phase helios::engine::runtime::gameloop::GameLoop::mainPhase_
The main update phase for core gameplay systems.
Referenced by helios::engine::runtime::gameloop::GameLoop::init, helios::engine::runtime::gameloop::GameLoop::phase, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::gameloop::Phase helios::engine::runtime::gameloop::GameLoop::postPhase_
The post-update phase for cleanup and synchronization.
Referenced by helios::engine::runtime::gameloop::GameLoop::init, helios::engine::runtime::gameloop::GameLoop::phase, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::messaging::command::CommandBuffer helios::engine::runtime::gameloop::GameLoop::commandBuffer_
Buffer for deferred command execution.
Referenced by helios::engine::runtime::gameloop::GameLoop::commandBuffer, helios::engine::runtime::gameloop::GameLoop::onPassCommit, helios::engine::runtime::gameloop::GameLoop::phaseCommit, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::messaging::event::GameLoopEventBus helios::engine::runtime::gameloop::GameLoop::phaseEventBus_
Event bus for phase-level event propagation.
Events pushed via `UpdateContext::pushPhase()` are buffered here and become readable in the next phase via `UpdateContext::readPhase()`. The buffer swap occurs in phaseCommit(). UpdateContext::pushPhase() UpdateContext::readPhase()
Referenced by helios::engine::runtime::gameloop::GameLoop::phaseCommit, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::messaging::event::GameLoopEventBus helios::engine::runtime::gameloop::GameLoop::passEventBus_
Event bus for pass-level event propagation.
Events pushed via `UpdateContext::pushPass()` are buffered here and become readable in subsequent passes via `UpdateContext::readPass()`. The buffer swap occurs when a pass has a commit point. UpdateContext::pushPass() UpdateContext::readPass() Pass::addCommitPoint()
Referenced by helios::engine::runtime::gameloop::GameLoop::onPassCommit, helios::engine::runtime::gameloop::GameLoop::phaseCommit, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::messaging::event::GameLoopEventBus helios::engine::runtime::gameloop::GameLoop::frameEventBus_
Event bus for frame-level event propagation.
Events pushed via `UpdateContext::pushFrame()` are buffered here and become readable in the next frame via `UpdateContext::readFrame()`. The buffer swap occurs at the end of the Post phase. Frame-level events persist across all phases within a frame and are useful for cross-frame communication (e.g., collision events that should be processed in the next frame). UpdateContext::pushFrame() UpdateContext::readFrame()
Referenced by helios::engine::runtime::gameloop::GameLoop::update.
void helios::engine::runtime::gameloop::GameLoop::onPassCommit(const CommitPoint commitPoint, helios::engine::runtime::world::UpdateContext &updateContext) noexcept override
Commits pass-level state based on the specified CommitPoint flags.
Called after each pass that has a commit point configured. The CommitPoint flags determine which synchronization actions are performed: **PassEvents:** Swaps pass event bus buffers, making events pushed via `UpdateContext::pushPass()` readable in subsequent passes. **FlushCommands:** Executes pending commands from the CommandBuffer. **FlushManagers:** Processes manager requests (e.g., spawning from pools). The order is: PassEvents → FlushCommands → FlushManagers. Commands must be flushed before managers to ensure spawn requests are generated before being processed. commitPoint The flags specifying which actions to perform. updateContext The current update context. CommitPoint Pass::addCommitPoint() UpdateContext::pushPass() UpdateContext::readPass()
References helios::engine::runtime::gameloop::GameLoop::commandBuffer_, helios::engine::runtime::gameloop::FlushCommands, helios::engine::runtime::gameloop::FlushManagers, helios::engine::runtime::gameloop::GameLoop::passEventBus_, helios::engine::runtime::gameloop::PassEvents.
void helios::engine::runtime::gameloop::GameLoop::phaseCommit(helios::engine::runtime::world::GameWorld &gameWorld, helios::engine::runtime::world::UpdateContext &updateContext)
Commits phase-level events and flushes commands and managers.
Called after each phase completes. This method: 1. Swaps phase event bus buffers, making events readable in the next phase. 2. Clears pass event buffers for the new phase. 3. Flushes the command buffer, executing deferred commands. 4. Flushes managers, allowing to process any request generated by the commands. gameWorld Reference to the game world. updateContext The current update context. UpdateContext::pushPhase() UpdateContext::readPhase()
References helios::engine::runtime::gameloop::GameLoop::commandBuffer_, helios::engine::runtime::world::GameWorld::flushManagers, helios::engine::runtime::world::UpdateContext::gameWorld, helios::engine::runtime::gameloop::GameLoop::passEventBus_, helios::engine::runtime::gameloop::GameLoop::phaseEventBus_.
Referenced by helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::gameloop::GameLoop::GameLoop()=default
Default constructor.
Creates a GameLoop with empty phases. Systems must be added to the phases via `phase(PhaseType).addPass().addSystem<T>()` before calling `init()`.
helios::engine::runtime::gameloop::Phase & helios::engine::runtime::gameloop::GameLoop::phase(const helios::engine::runtime::gameloop::PhaseType phaseType) noexcept
Returns a reference to the specified phase.
phaseType The type of phase to retrieve (Pre, Main, or Post). Reference to the requested Phase.
References helios::engine::runtime::gameloop::Main, helios::engine::runtime::gameloop::GameLoop::mainPhase_, helios::engine::runtime::gameloop::Post, helios::engine::runtime::gameloop::GameLoop::postPhase_, helios::engine::runtime::gameloop::Pre, helios::engine::runtime::gameloop::GameLoop::prePhase_.
Referenced by helios::engine::runtime::gameloop::GameLoop::init, helios::engine::runtime::gameloop::GameLoop::update.
helios::engine::runtime::messaging::command::CommandBuffer & helios::engine::runtime::gameloop::GameLoop::commandBuffer() noexcept
Returns a reference to the command buffer.
Reference to the CommandBuffer owned by this GameLoop.
References helios::engine::runtime::gameloop::GameLoop::commandBuffer_.
void helios::engine::runtime::gameloop::GameLoop::init(helios::engine::runtime::world::GameWorld &gameWorld)
Initializes the GameLoop and all registered phases and passes.
Iterates through all phases (Pre, Main, Post) and calls their `init()` methods, which in turn initialize all registered passes and systems. Systems receive a reference to the GameWorld for component queries and entity access. Must be called exactly once before the first `update()` call. gameWorld Reference to the game world to initialize with. Must not have been called before (asserts on multiple calls). Phase::init() Pass::init() System::init()
References helios::engine::runtime::gameloop::Main, helios::engine::runtime::gameloop::GameLoop::mainPhase_, helios::engine::runtime::gameloop::GameLoop::phase, helios::engine::runtime::gameloop::Post, helios::engine::runtime::gameloop::GameLoop::postPhase_, helios::engine::runtime::gameloop::Pre, helios::engine::runtime::gameloop::GameLoop::prePhase_.
void helios::engine::runtime::gameloop::GameLoop::update(helios::engine::runtime::world::GameWorld &gameWorld, float deltaTime, const helios::input::InputSnapshot &inputSnapshot, std::span< const helios::rendering::ViewportSnapshot > viewportSnapshots) noexcept
Executes one full frame update across all phases.
Iterates through Pre, Main, and Post phases, updating all registered systems and committing events and commands after each phase. The frame lifecycle: 1. **Pre Phase:** Input processing, command generation, preparation 2. **Main Phase:** Core gameplay logic, physics, collision detection 3. **Post Phase:** Cleanup, synchronization, rendering preparation After each phase, `phaseCommit()` is called to: Swap phase event buffers (events become readable in next phase) Clear pass event buffers Flush command buffer Flush managers After the Post phase, the frame event bus is swapped, making frame-level events readable in the next frame. gameWorld Reference to the game world. deltaTime Time elapsed since the last frame in seconds. inputSnapshot Snapshot of the current input state. viewportSnapshots Snapshots of viewports registered with an id. init() must have been called before the first update. Phase phaseCommit() UpdateContext
References helios::engine::runtime::gameloop::GameLoop::commandBuffer_, helios::engine::runtime::gameloop::GameLoop::frameEventBus_, helios::engine::runtime::gameloop::Main, helios::engine::runtime::gameloop::GameLoop::mainPhase_, helios::engine::runtime::gameloop::GameLoop::passEventBus_, helios::engine::runtime::gameloop::GameLoop::phase, helios::engine::runtime::gameloop::GameLoop::phaseCommit, helios::engine::runtime::gameloop::GameLoop::phaseEventBus_, helios::engine::runtime::gameloop::Post, helios::engine::runtime::gameloop::GameLoop::postPhase_, helios::engine::runtime::gameloop::Pre, helios::engine::runtime::gameloop::GameLoop::prePhase_.