helios.rendering.text.TextRenderCommand
const helios::rendering::text::TextRenderPrototype* helios::rendering::text::TextRenderCommand::textRenderPrototype_
Non-owning pointer to the render prototype.
The prototype must remain valid for the lifetime of this command.
helios::rendering::shader::UniformValueMap helios::rendering::text::TextRenderCommand::objectUniformValues_
Uniform values specific to this text instance.
helios::rendering::shader::UniformValueMap helios::rendering::text::TextRenderCommand::materialUniformValues_
Material/text-specific uniform values (e.g., color).
const helios::rendering::text::TextMesh* helios::rendering::text::TextRenderCommand::textMesh_
Non-owning pointer to the text mesh containing vertex data.
The text mesh must remain valid for the lifetime of this command.
helios::rendering::text::TextRenderCommand::TextRenderCommand(const TextRenderCommand &)=delete
Deleted copy constructor.
TextRenderCommand is move-only to prevent accidental duplication.
References helios::rendering::text::TextRenderCommand::TextRenderCommand.
Referenced by helios::rendering::text::TextRenderCommand::operator=, helios::rendering::text::TextRenderCommand::operator=, helios::rendering::text::TextRenderCommand::TextRenderCommand, helios::rendering::text::TextRenderCommand::TextRenderCommand, helios::rendering::text::TextRenderCommand::TextRenderCommand, helios::rendering::text::TextRenderCommand::~TextRenderCommand.
TextRenderCommand & helios::rendering::text::TextRenderCommand::operator=(const TextRenderCommand &)=delete
Deleted copy assignment operator.
TextRenderCommand is move-only to prevent accidental duplication.
References helios::rendering::text::TextRenderCommand::TextRenderCommand.
helios::rendering::text::TextRenderCommand::TextRenderCommand(TextRenderCommand &&) noexcept=default
Move constructor.
References helios::rendering::text::TextRenderCommand::TextRenderCommand.
TextRenderCommand & helios::rendering::text::TextRenderCommand::operator=(TextRenderCommand &&) noexcept=default
Move assignment operator.
References helios::rendering::text::TextRenderCommand::TextRenderCommand.
helios::rendering::text::TextRenderCommand::~TextRenderCommand()=default
Default destructor.
References helios::rendering::text::TextRenderCommand::TextRenderCommand.
helios::rendering::text::TextRenderCommand::TextRenderCommand(const helios::rendering::text::TextMesh *textMesh, const helios::rendering::text::TextRenderPrototype *textRenderPrototype, const helios::rendering::shader::UniformValueMap &objectUniformValues, const helios::rendering::shader::UniformValueMap &materialUniformValues) noexcept
Constructs a text render command.
text The text string to render. textRenderPrototype Non-owning pointer to the prototype (must outlive this command). drawProperties Position, scale, and font selection. textUniformValues Uniform values for the text shader. `textRenderPrototype` must not be null.
References helios::rendering::text::TextRenderCommand::materialUniformValues, helios::rendering::text::TextRenderCommand::objectUniformValues, helios::rendering::text::TextRenderCommand::textMesh, helios::rendering::text::TextRenderCommand::TextRenderCommand, helios::rendering::text::TextRenderCommand::textRenderPrototype.
const helios::rendering::text::TextRenderPrototype * helios::rendering::text::TextRenderCommand::textRenderPrototype() const noexcept
Returns the render prototype.
Non-owning pointer to the prototype.
Referenced by helios::rendering::text::TextRenderCommand::TextRenderCommand.
const helios::rendering::text::TextMesh * helios::rendering::text::TextRenderCommand::textMesh() const noexcept
Returns the text mesh containing vertex data.
The mesh provides access to the pre-computed glyph vertices for rendering. Non-owning pointer to the text mesh.
Referenced by helios::rendering::text::TextRenderCommand::TextRenderCommand.
const helios::rendering::shader::UniformValueMap & helios::rendering::text::TextRenderCommand::objectUniformValues() const noexcept
Returns the text-specific uniform values.
Reference to the uniform value map.
Referenced by helios::rendering::text::TextRenderCommand::TextRenderCommand.
const helios::rendering::shader::UniformValueMap & helios::rendering::text::TextRenderCommand::materialUniformValues() const noexcept
Returns the material-specific uniform values.
Contains values such as text color and other material properties. Reference to the material uniform value map.
Referenced by helios::rendering::text::TextRenderCommand::TextRenderCommand.