helios.math.utils
float helios::math::EPSILON_LENGTH
A small epsilon value used for length-based comparisons.
This constant represents the minimum threshold value for length comparisons to account for numerical precision errors in floating-point calculations. It is often used to avoid treating very small values as significant, effectively filtering out noise in computations that involve vector-lengths.
Referenced by helios::engine::modules::physics::motion::components::DirectionComponent::setDirection, helios::engine::modules::physics::motion::components::Move2DComponent::setMoveIntent, helios::engine::modules::physics::motion::components::SteeringComponent::setSteeringIntent, helios::engine::modules::physics::motion::components::Move2DComponent::speedRatio, helios::engine::mechanics::input::systems::TwinStickInputSystem::update.
float helios::math::radians(const float angle) noexcept
Converts an angle from degrees to radians.
angle The angle value in degrees. The converted angle value in radians.
Referenced by helios::math::degrees, helios::ext::imgui::widgets::CameraWidget::draw, helios::math::rotate, helios::engine::modules::physics::motion::systems::SteeringSystem::update.
float helios::math::degrees(const float radians) noexcept
Converts an angle from radians to degrees.
radians The angle value in radians. The converted angle value in degrees.
References helios::math::radians.
Referenced by helios::engine::modules::physics::motion::systems::SteeringSystem::update.