helios.engine.ecs.GameObject
helios::engine::ecs::EntityHandle helios::engine::ecs::GameObject::entityHandle_
The underlying entity identifier.
helios::engine::ecs::EntityManager* helios::engine::ecs::GameObject::entityManager_
Non-owning pointer to the EntityManager.
helios::engine::ecs::GameObject::GameObject(const helios::engine::ecs::EntityHandle entityHandle, helios::engine::ecs::EntityManager *entityManager) noexcept
Constructs a GameObject wrapper.
entityHandle The entity handle to wrap. entityManager Pointer to the EntityManager. Must not be null.
References helios::engine::ecs::GameObject::entityHandle.
std::generator< helios::engine::ecs::types::ComponentTypeId > helios::engine::ecs::GameObject::componentTypeIds() const
Returns a generator over all component type IDs attached to this entity.
Generator yielding ComponentTypeId for each attached component.
Referenced by helios::engine::runtime::spawn::behavior::initializers::DelayedComponentEnablerInitializer< ComponentTypes >::initialize, helios::engine::ecs::GameObject::onAcquire, helios::engine::ecs::GameObject::onRelease, helios::engine::ecs::GameObject::setActive.
helios::engine::ecs::EntityHandle helios::engine::ecs::GameObject::entityHandle() noexcept
Returns the underlying entity handle.
The EntityHandle for this GameObject.
Referenced by helios::engine::modules::ui::widgets::components::MenuComponent::addMenuItem, helios::engine::runtime::world::GameWorld::clone, helios::engine::ecs::GameObject::GameObject, helios::engine::modules::ui::widgets::components::MenuComponent::insert, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
helios::engine::ecs::EntityHandle helios::engine::ecs::GameObject::entityHandle() const noexcept
Returns the underlying entity handle (const).
The EntityHandle for this GameObject.
T & helios::engine::ecs::GameObject::add(Args &&...args)
Constructs and attaches a component to this entity.
If the entity is active, calls `onActivate()` on the new component. If inactive, calls `onDeactivate()`. T The component type to add. Args Constructor argument types. args Arguments forwarded to the component constructor. Reference to the newly created component.
References helios::engine::ecs::types::ComponentTypeId::id, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::GameObject::raw.
Referenced by helios::engine::ecs::GameObject::getOrAdd.
T & helios::engine::ecs::GameObject::getOrAdd(Args &&...args)
Returns existing component or creates a new one.
T The component type. Args Constructor argument types. args Arguments forwarded to the constructor if creating. Reference to the existing or newly created component.
References helios::engine::ecs::GameObject::add.
bool helios::engine::ecs::GameObject::remove()
Removes a component from this entity.
T The component type to remove. True if the component was removed, false if not present.
void * helios::engine::ecs::GameObject::raw(const helios::engine::ecs::types::ComponentTypeId typeId)
Returns raw pointer to component by type ID.
typeId The component type identifier. Raw void pointer to the component, or nullptr if not found.
Referenced by helios::engine::ecs::GameObject::add, helios::engine::ecs::GameObject::onAcquire, helios::engine::ecs::GameObject::onRelease, helios::engine::ecs::GameObject::setActive.
T * helios::engine::ecs::GameObject::get()
Returns pointer to a component.
T The component type. Pointer to the component, or nullptr if not attached.
Referenced by helios::engine::runtime::spawn::behavior::initializers::DelayedComponentEnablerInitializer< ComponentTypes >::initialize, helios::engine::runtime::spawn::behavior::initializers::EmitterInitializer::initialize, helios::engine::runtime::spawn::behavior::initializers::RandomDirectionInitializer::initialize.
const T * helios::engine::ecs::GameObject::get() const
Returns const pointer to a component.
T The component type. Const pointer to the component, or nullptr if not attached.
bool helios::engine::ecs::GameObject::has()
Checks if this entity has a specific component type.
T The component type to check. True if the component is attached, false otherwise.
Referenced by helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::defer.
bool helios::engine::ecs::GameObject::has(helios::engine::ecs::types::ComponentTypeId typeId)
Checks if this entity has a component by type ID.
typeId The component type identifier. True if the component is attached, false otherwise.
void helios::engine::ecs::GameObject::enableComponent(const helios::engine::ecs::types::ComponentTypeId typeId)
Enables a specific component by type ID.
typeId The component type identifier.
void helios::engine::ecs::GameObject::disableComponent(const helios::engine::ecs::types::ComponentTypeId typeId)
Disables a specific component by type ID.
typeId The component type identifier.
Referenced by helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::defer.
void helios::engine::ecs::GameObject::setActive(const bool active)
Sets the activation state of this GameObject.
When deactivated: An `Inactive` tag component is added The `Active` tag component is removed `onDeactivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation When activated: The `Inactive` tag component is removed An `Active` tag component is added `onActivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation Does **not** call `enable()`/`disable()` on components. active True to activate, false to deactivate. HierarchyComponent HierarchyPropagationSystem
References helios::engine::ecs::GameObject::componentTypeIds, helios::engine::ecs::GameObject::isActive, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::GameObject::raw.
bool helios::engine::ecs::GameObject::isActive() const
Returns whether this GameObject is active.
True if the entity has the Active tag component.
Referenced by helios::engine::ecs::GameObject::setActive.
void helios::engine::ecs::GameObject::onRelease()
Notifies all components that the entity is being released to a pool.
Iterates through all attached components and calls `onRelease()` on those that implement it.
References helios::engine::ecs::GameObject::componentTypeIds, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::GameObject::raw.
void helios::engine::ecs::GameObject::onAcquire()
Notifies all components that the entity is being acquired from a pool.
Iterates through all attached components and calls `onAcquire()` on those that implement it.
References helios::engine::ecs::GameObject::componentTypeIds, helios::engine::ecs::ComponentOpsRegistry::ops, helios::engine::ecs::GameObject::raw.