helios.engine.ecs.EntityHandle
helios::engine::ecs::types::EntityId helios::engine::ecs::EntityHandle::entityId
The unique identifier for the entity within the pool.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::ecs::EntityRegistry::destroy, helios::engine::ecs::EntityHandle::operator<, helios::engine::ecs::EntityHandle::operator>, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
helios::engine::common::types::VersionId helios::engine::ecs::EntityHandle::versionId
The version number for stale handle detection.
Incremented when an entity is removed from the pool.
Referenced by helios::engine::runtime::pooling::GameObjectPool::acquire, helios::engine::ecs::EntityHandle::isValid, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove.
bool helios::engine::ecs::EntityHandle::operator==(const EntityHandle &) const =default
Compares two handles for equality.
bool helios::engine::ecs::EntityHandle::operator<(const EntityHandle &entityHandle) const noexcept
Compares two handles by entity ID (less-than).
entityHandle The handle to compare against. True if this handle's entity ID is less than the other.
References helios::engine::ecs::EntityHandle::entityId.
bool helios::engine::ecs::EntityHandle::operator>(const EntityHandle &entityHandle) const noexcept
Compares two handles by entity ID (greater-than).
entityHandle The handle to compare against. True if this handle's entity ID is greater than the other.
References helios::engine::ecs::EntityHandle::entityId.
bool helios::engine::ecs::EntityHandle::isValid() const noexcept
Checks if this handle is potentially valid.
True if the version is at least 1 (initial version).
References helios::engine::ecs::EntityHandle::versionId.
Referenced by helios::engine::runtime::pooling::GameObjectPool::addInactive, helios::engine::runtime::pooling::GameObjectPool::release, helios::engine::runtime::pooling::GameObjectPool::releaseAndRemove, helios::engine::builder::gameObject::builders::configs::ChaseConfig::target.
std::size_t std::hash< helios::engine::ecs::EntityHandle >::operator()(const helios::engine::ecs::EntityHandle &handle) const noexcept