helios.engine.modules.spatial.transform.components.TransformComponent
helios::core::spatial::Transform helios::engine::modules::spatial::transform::components::TransformComponent::transform_
The local transformation (translation, rotation, scale).
bool helios::engine::modules::spatial::transform::components::TransformComponent::isDirty_
Flag indicating if the transform has changed since the last update.
helios::math::mat4f helios::engine::modules::spatial::transform::components::TransformComponent::worldTransform_
The computed world transformation matrix.
helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent()=default
Default constructor.
Referenced by helios::engine::modules::spatial::transform::components::TransformComponent::setLocalRotation, helios::engine::modules::spatial::transform::components::TransformComponent::setLocalScale, helios::engine::modules::spatial::transform::components::TransformComponent::setLocalTranslation, helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent, helios::engine::modules::spatial::transform::components::TransformComponent::translateLocalBy.
helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent(const TransformComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent.
bool helios::engine::modules::spatial::transform::components::TransformComponent::isDirty() const noexcept
Checks if the transform is dirty.
True if the transform has changed, false otherwise.
void helios::engine::modules::spatial::transform::components::TransformComponent::clearDirty() noexcept
Clears the dirty flag.
helios::math::mat4f helios::engine::modules::spatial::transform::components::TransformComponent::localTransform() const noexcept
Returns the local transformation matrix.
The 4x4 matrix representing local translation, rotation, and scale.
TransformComponent & helios::engine::modules::spatial::transform::components::TransformComponent::setLocalScale(const helios::math::vec3f &scale) noexcept
Sets the local scale.
scale The new scale vector. Reference to this component for chaining.
References helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent.
TransformComponent & helios::engine::modules::spatial::transform::components::TransformComponent::setLocalRotation(const helios::math::mat4f &rotation) noexcept
Sets the local rotation matrix.
rotation The new rotation matrix. Reference to this component for chaining.
References helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent.
TransformComponent & helios::engine::modules::spatial::transform::components::TransformComponent::setLocalTranslation(const helios::math::vec3f &translation) noexcept
Sets the local translation (position).
translation The new position vector. Reference to this component for chaining.
References helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent.
TransformComponent & helios::engine::modules::spatial::transform::components::TransformComponent::translateLocalBy(const helios::math::vec3f &translation) noexcept
Translates the component locally by a delta vector.
translation The vector to add to the current position. Reference to this component for chaining.
References helios::engine::modules::spatial::transform::components::TransformComponent::TransformComponent.
helios::math::vec3f helios::engine::modules::spatial::transform::components::TransformComponent::localTranslation() const noexcept
Returns the local translation vector.
The position relative to the parent.
helios::math::mat4f helios::engine::modules::spatial::transform::components::TransformComponent::localRotation() const noexcept
Returns the local rotation matrix.
The rotation relative to the parent.
helios::math::vec3f helios::engine::modules::spatial::transform::components::TransformComponent::localScaling() const noexcept
Returns the local scaling vector.
The scale relative to the parent.
void helios::engine::modules::spatial::transform::components::TransformComponent::setWorldTransform(const helios::math::mat4f &m) noexcept
Sets the world transform matrix directly.
m The new world transform matrix.
const helios::math::mat4f & helios::engine::modules::spatial::transform::components::TransformComponent::worldTransform() noexcept
Returns the current world transform matrix.
Const reference to the world transform.
helios::math::vec3f helios::engine::modules::spatial::transform::components::TransformComponent::worldTranslation() noexcept
Extracts the world translation from the world transform.
The global position vector.