helios.math.types
T helios::math::mat4< T >::m[16][16]
Internal array storing matrix components.
Components are stored in column-major order, that is, each 4 subsequent elements represent a matrix column.
T helios::math::vec2< T >::v[2][2]
Internal array storing the vector components.
T helios::math::vec4< T >::v[4][4]
Internal array storing the vector components.
T helios::math::vec3< T >::v[3][3]
Internal array storing the vector components.
helios::math::mat4< T >::mat4() noexcept
Default constructor. Initializes all components to 0.
Referenced by helios::math::mat4< float >::identity.
helios::math::mat4< T >::mat4(const T f) noexcept
Creates a diagonal matrix. The diagonal components are initialized with the value f.
f The scalar value for the diagonal components.
helios::math::mat4< T >::mat4(const vec3< T > f) noexcept
Creates a diagonal matrix with the components of vec3<T> as the diagonal elements. Element at [4, 4] is set to 1.
f The scalar value for the diagonal components.
helios::math::mat4< T >::mat4(const T f0_0, const T f1_0, const T f2_0, const T f3_0, const T f0_1, const T f1_1, const T f2_1, const T f3_1, const T f0_2, const T f1_2, const T f2_2, const T f3_2, const T f0_3, const T f1_3, const T f2_3, const T f3_3)
Constructs a new `mat4` with all 16 components explicitly specified. The values are stored in column major order, that is, the first 4 arguments represent the first column, and so on.
fi_j (i==row, j == col)
static mat4< T > helios::math::mat4< T >::identity() noexcept
Convenient method to construct a 4x4 identity matrix.
T The numeric type of the matrix components. A new mat4<T>-identity matrix-
const T & helios::math::mat4< T >::operator()(const size_t row, const size_t col) const
Provides read-only access to a matrix component.
Elements are _accessed_ in column major order: `m[row + col * 4]`, while the specified indices represent an usual mxn-matrix access, i.e. for a given 2x4-matrix [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] a call to row(0, 2) returns "2", while the matrix is internally stored as (1, 4, 8, 12, 1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15). Bounds checking is performed via `assert` in debug builds. row The zero based row index. col The zero based col index. A const ref to the component at the specified position.
T & helios::math::mat4< T >::operator()(const size_t row, const size_t col)
Provides read-write access to a matrix component.
Elements are _accessed_ in column major order: `m[row + col * 4]`, while the specified indices represent an usual mxn-matrix access, i.e. for a given 2x4-matrix [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] a call to row(0, 2) returns "2", while the matrix is internally stored as (0, 4, 8, 12, 1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15). Bounds checking is performed via `assert` in debug builds. row The zero based row index. col The zero based col index. A ref to the component at the specified position.
bool helios::math::mat4< T >::same(const mat4< T > &rgt) const
Compares this matrix element's with the rgt matrix considering an epsilon value. Returns true if for all elements the equation |a-b| <= EPSILON holds.
EPSILON is set to 0.00001 rgt The other matix to compare with this matrix for equality. True is the elements of the matrices are considered equal, otherwise false. https://realtimecollisiondetection.net/blog/?p=89 Todoaccount for abs (values close to zero) and rel (larger values), move EPSILON to global constant
bool helios::math::mat4< T >::operator==(const mat4< T > &rgt) const
Strictly compares the elements of this matrix with the elements of the rgt matrix.
rgt The right matrix to compare for equal values True if all elements are equal (==), false otherwise.
mat4< T > helios::math::mat4< T >::operator*(const mat4< T > &m) const
Performs matrix-multiplication with another `mat4`. This matrix is the left operand, while `m` is the right operand.
m The right-hand side `mat4<T>` for multiplication. A new `mat4<T>`, representing the result of the matrix-multiplication.
vec4< T > helios::math::mat4< T >::operator*(const vec4< T > &v) const
Performs matrix-vector-multiplication with a `vec4<T> v`.
This matrix is the left operand, while `v` is the right operand. v The right-hand side `vec4<T>` for multiplication. A new `vec4<T>`, representing the result of the matrix-vector-multiplication.
const T * helios::math::value_ptr(const mat4< T > &m) noexcept
Returns a const pointer to the first element of the matrix's components.
Useful for APIs that expect a pointer to matrix data, like OpenGL. T The numeric type of the matrix components. m A reference to the `mat4<T>` matrix. A const pointer to the element at [0, 0].
Referenced by helios::math::mat4< float >::operator==, helios::math::mat4< float >::same.
T * helios::math::value_ptr(mat4< T > &m) noexcept
Returns a pointer to the first element of the matrix's components.
Useful for APIs that expect a pointer to matrix data, like OpenGL. T The numeric type of the matrix components. m A reference to the `mat4<T>` matrix. A pointer to the element at [0, 0].
helios::math::vec2< T >::vec2() noexcept
Creates a new vec2 with its values initialized to (0, 0).
helios::math::vec2< T >::vec2(const T x, const T y) noexcept
Constructs a new vec2 with the specified x, y components.
x The value for the x component. y The value for the y component.
const T & helios::math::vec2< T >::operator[](const size_t i) const noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A const ref to the requested component.
T & helios::math::vec2< T >::operator[](const size_t i) noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A ref to the requested component.
FloatingPointType< T > helios::math::vec2< T >::length() const noexcept
Returns the magnitude of this vec2<T>.
The magnitude of this vector as type FloatingPointType<T>.
Referenced by helios::math::vec2< float >::normalize.
vec2< FloatingPointType< T > > helios::math::vec2< T >::normalize() const noexcept
Normalizes this vec2<T>.
The normalized FloatingPointType<T> vector.
bool helios::math::vec2< T >::operator==(const vec2< T > &rgt) const
Strictly compares the elements of this vector with the elements of the rgt vector.
rgt The right vector to compare for equal values True if all elements are equal (==), false otherwise.
bool helios::math::vec2< T >::same(const vec2< T > &rgt, T epsilon=0.0001) const
Compares this vector's elements with the rgt vector considering an epsilon value. Returns true if for all elements the equation |a-b| <= epsilon holds.
rgt The other vector to compare with this vector for equality. epsilon The epsilon value to use for comparison. If omitted, the default epsilon (0.0001) is used. True if the elements of the vectors are considered equal, otherwise false. https://realtimecollisiondetection.net/blog/?p=89 Todoaccount for abs (values close to zero) and rel (larger values), move epsilon to global constant?
vec2< T > helios::math::operator*(const vec2< T > &v, const T n) noexcept
Multiplies a 2D vector by a scalar value.
T The numeric type of the vector components. v The vec2<T> vector to be multiplied. n The scalar vector to multiplay the vector by. a new vec2<T> instance representing the result of the scalar multiplication.
T helios::math::dot(const vec2< T > &v1, const vec2< T > &v2) noexcept
Computes the dot product of two 2D vectors.
T The numeric type of the vector components. v1 The first vec2<T> vector. v2 The second vec2<T> vector. The dot product as a value of type T.
helios::math::vec4< T >::vec4() noexcept
Creates a new vec4 with its values initialized to (0, 0, 0, 0).
helios::math::vec4< T >::vec4(const T x, const T y, const T z, const T w) noexcept
Constructs a new vec4 with the specified x, y, z, w components.
x The value for the x component. y The value for the y component. z The value for the z component. w The value for the w component.
helios::math::vec4< T >::vec4(const vec3< T > &vec, const T w) noexcept
Constructs a new vec4 from the vec3 vector and the w value.
vec The vec3<T> vector. w The value for the w component.
helios::math::vec4< T >::vec4(const vec3< T > &vec) noexcept
Constructs a new vec4 from the vec3 vector and sets w to 1.
vec The vec3<T> vector.
const T & helios::math::vec4< T >::operator[](const size_t i) const noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A const ref to the requested component.
T & helios::math::vec4< T >::operator[](const size_t i) noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A ref to the requested component.
const T * helios::math::value_ptr(const vec4< T > &m) noexcept
Returns a const pointer to the first element of the vector's components.
Useful for APIs that expect a pointer to vector data, like OpenGL. T The numeric type of the vector components. m A reference to the `vec4<T>` vector. A const pointer to the element at index 0.
helios::math::vec3< T >::vec3() noexcept
Creates a new vec3 with its values initialized to (0, 0, 0).
Referenced by helios::math::vec3< T >::cross, helios::math::vec3< T >::dot, helios::math::vec3< T >::normalize.
helios::math::vec3< T >::vec3(const T x, const T y, const T z) noexcept
Constructs a new vec3 with the specified x, y, z components.
x The value for the x component. y The value for the y component. z The value for the z component.
helios::math::vec3< T >::vec3(const T v) noexcept
Constructs a new vec3 with the specified value as the x,y,z components.
v The value for the components.
helios::math::vec3< T >::vec3(const helios::math::vec2< T > v) noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and vec3 set to 0.
v The vec2 to use for the x,y components.
helios::math::vec3< T >::vec3(const helios::math::vec2< T > v, T f) noexcept
Constructs a new vec3 with x,y components initialized to those of the vec2 and the z component set to the specified value.
v The vec2 to use for the x,y components. f The value for the z component.
const T & helios::math::vec3< T >::operator[](const size_t i) const noexcept
Provides read only access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A const ref to the requested component.
T & helios::math::vec3< T >::operator[](const size_t i) noexcept
Provides read-write access to the vector components. Bounds checking is performed via `assert` in debug builds.
i The index to query A const ref to the requested component.
FloatingPointType< T > helios::math::vec3< T >::length() const noexcept
Computes the Euclidean norm (magnitude) of this vector and returns it.
The norm (magnitude) of this vector as a value of type FloatingPointType<T>.
Referenced by helios::ext::imgui::widgets::CameraWidget::draw, helios::math::vec3< T >::normalize.
vec3< T > helios::math::vec3< T >::cross(const helios::math::vec3< T > &v2) const noexcept
Computes the cross product of this vector and v2.
T The numeric type of the vector components. v2 The second vec3<T> vector. The cross product as a value of type vec3<T>.
References helios::math::vec3< T >::vec3.
T helios::math::vec3< T >::dot(const helios::math::vec3< T > &v2) const noexcept
Computes the dot product of this vector and v2.
T The numeric type of the vector components. v2 The second vec3<T> vector. The dot product as a value of type T.
References helios::math::vec3< T >::vec3.
vec3< FloatingPointType< T > > helios::math::vec3< T >::normalize() const noexcept
Returns a normalized version of this vector.
T The numeric type of the vector components. A new vec3<FloatingPointType<T>> instance representing the normalized vector.
References helios::math::vec3< T >::length, helios::math::vec3< T >::vec3.
bool helios::math::vec3< T >::operator==(const vec3< T > &rgt) const
Strictly compares the elements of this vector with the elements of the rgt vector.
rgt The right vector to compare for equal values. True if all elements are equal (==), false otherwise.
bool helios::math::vec3< T >::same(const vec3< T > &rgt, T epsilon=0.0001) const
Compares this vector's elements with the rgt vector considering an epsilon value. Returns true if for all elements the equation |a-b| <= epsilon holds.
rgt The other vector to compare with this vector for equality. epsilon The epsilon value to use for comparison. If omitted, the default epsilon (0.0001) is used. True if the elements of the vectors are considered equal, otherwise false. https://realtimecollisiondetection.net/blog/?p=89 Todoaccount for abs (values close to zero) and rel (larger values), move epsilon to global constant?
vec3< T > helios::math::operator*(const vec3< T > &v, const T n) noexcept
Multiplies a 3D vector by a scalar value.
T The numeric type of the vector components. v The vec3<T> vector to be multiplied. n The scalar vector to multiplay the vector by. a new vec3<T> instance representing the result of the scalar multiplication.
vec3< T > helios::math::operator*(const T n, const vec3< T > &v) noexcept
Multiplies a scalar value by a 3D vector.
T The numeric type of the vector components. n The scalar value to multiply the vector by. v The vec3<T> vector to be multiplied. A new vec3<T> instance representing the result of the scalar multiplication.
vec3< T > helios::math::operator*(const vec3< T > &v1, const vec3< T > &v2) noexcept
Multiplies two vectors componentwise.
T The numeric type of the vector components. v1 The left-hand vec3<T> vector to be multiplied. v2 The right-hand vec3<T> vector to be multiplied. A new vec3<T> instance representing the result of the componentwise multiplication of the two vectors.
vec3< T > helios::math::operator+(const vec3< T > &v1, const vec3< T > &v2) noexcept
Calculates the componentwise sum of the two vectors.
T The numeric type of the vector components. v1 The left-hand vec3<T> vector to be added. v2 The right-hand vec3<T> vector to be added. A new vec3<T> instance representing the sum of the two vectors.
vec3< T > helios::math::cross(const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the cross product of two 3D vectors.
T The numeric type of the vector components. v1 The first vec3<T> vector. v2 The second vec3<T> vector. A new vec3<T> instance representing the cross product.
T helios::math::dot(const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the dot product of two 3D vectors.
T The numeric type of the vector components. v1 The first vec3<T> vector. v2 The second vec3<T> vector. The dot product as a value of type T.
vec3< T > helios::math::operator-(const vec3< T > &v1, const vec3< T > &v2) noexcept
Computes the difference between two vectors (vector subtraction).
T The numeric type of the vector components. v1 The first vec3<T> vector. v2 The second vec3<T> vector. A new vec3<T> instance representing the difference between v1 and v2.
using helios::math::mat4f = mat4<float>
using helios::math::mat4d = mat4<double>
using helios::math::mat4i = mat4<int>
using helios::math::vec2f = vec2<float>
using helios::math::vec2d = vec2<double>
using helios::math::vec2i = vec2<int>
using helios::math::vec4f = vec4<float>
using helios::math::vec4d = vec4<double>
using helios::math::vec4i = vec4<int>
using helios::math::vec3f = vec3<float>
using helios::math::vec3i = vec3<int>
using helios::math::vec3d = vec3<double>