helios.engine.modules.ai.components.ChaseComponent
float helios::engine::modules::ai::components::ChaseComponent::cooldown_
Time between target direction updates (seconds).
float helios::engine::modules::ai::components::ChaseComponent::cooldownTimer_
Current elapsed time since last update.
helios::engine::ecs::EntityHandle helios::engine::modules::ai::components::ChaseComponent::target_
EntityHandle of the entity to chase.
bool helios::engine::modules::ai::components::ChaseComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::ai::components::ChaseComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::ai::components::ChaseComponent::enable() noexcept
Enables this component.
void helios::engine::modules::ai::components::ChaseComponent::disable() noexcept
Disables this component.
helios::engine::modules::ai::components::ChaseComponent::ChaseComponent()=default
Default constructor.
Referenced by helios::engine::modules::ai::components::ChaseComponent::ChaseComponent, helios::engine::modules::ai::components::ChaseComponent::ChaseComponent, helios::engine::modules::ai::components::ChaseComponent::operator=, helios::engine::modules::ai::components::ChaseComponent::operator=.
helios::engine::modules::ai::components::ChaseComponent::ChaseComponent(const ChaseComponent &)=default
References helios::engine::modules::ai::components::ChaseComponent::ChaseComponent.
ChaseComponent & helios::engine::modules::ai::components::ChaseComponent::operator=(const ChaseComponent &)=default
References helios::engine::modules::ai::components::ChaseComponent::ChaseComponent.
helios::engine::modules::ai::components::ChaseComponent::ChaseComponent(ChaseComponent &&) noexcept=default
References helios::engine::modules::ai::components::ChaseComponent::ChaseComponent.
ChaseComponent & helios::engine::modules::ai::components::ChaseComponent::operator=(ChaseComponent &&) noexcept=default
References helios::engine::modules::ai::components::ChaseComponent::ChaseComponent.
helios::engine::ecs::EntityHandle helios::engine::modules::ai::components::ChaseComponent::target() const noexcept
Returns the target entity's handle.
The handle of the chase target.
References helios::engine::modules::ai::components::ChaseComponent::target.
Referenced by helios::engine::modules::ai::components::ChaseComponent::target.
float helios::engine::modules::ai::components::ChaseComponent::cooldown() const noexcept
Returns the cooldown duration.
Time between direction updates in seconds.
Referenced by helios::engine::modules::ai::components::ChaseComponent::setCooldown.
void helios::engine::modules::ai::components::ChaseComponent::setCooldown(const float cooldown) noexcept
Sets the cooldown duration.
cooldown Time between direction updates in seconds.
References helios::engine::modules::ai::components::ChaseComponent::cooldown.
float helios::engine::modules::ai::components::ChaseComponent::cooldownTimer() const noexcept
Returns the current cooldown timer value.
Elapsed time since last direction update.
void helios::engine::modules::ai::components::ChaseComponent::updateCooldownTimerBy(const float delta) noexcept
Advances the cooldown timer by delta time.
delta Time to add to the timer.
void helios::engine::modules::ai::components::ChaseComponent::setCooldownTimer(const float timer) noexcept
Sets the cooldown timer to a specific value.
timer New timer value.
void helios::engine::modules::ai::components::ChaseComponent::setTarget(const helios::engine::ecs::EntityHandle &entityHandle) noexcept
Sets the target entity to chase.
entityHandle The EntityHandle of the target entity.