helios.engine.mechanics.spawn.components.EmittedByComponent
helios::util::Guid helios::engine::mechanics::spawn::components::EmittedByComponent::source_
GUID of the entity that emitted this object.
helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent()=default
Default constructor.
Referenced by helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent.
helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent(const EmittedByComponent &other)
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References helios::engine::mechanics::spawn::components::EmittedByComponent::EmittedByComponent.
void helios::engine::mechanics::spawn::components::EmittedByComponent::setSource(const helios::util::Guid source) noexcept
Sets the source entity that emitted this object.
source GUID of the emitting entity.
References helios::engine::mechanics::spawn::components::EmittedByComponent::source.
helios::util::Guid helios::engine::mechanics::spawn::components::EmittedByComponent::source() const noexcept
Returns the GUID of the source entity.
GUID of the entity that emitted this object.
Referenced by helios::engine::mechanics::spawn::components::EmittedByComponent::setSource.
void helios::engine::mechanics::spawn::components::EmittedByComponent::reset()
Resets the component to its initial state.
References helios::core::types::no_init.
Referenced by helios::engine::mechanics::spawn::components::EmittedByComponent::onAcquire, helios::engine::mechanics::spawn::components::EmittedByComponent::onRelease.
void helios::engine::mechanics::spawn::components::EmittedByComponent::onAcquire() noexcept override
References helios::engine::mechanics::spawn::components::EmittedByComponent::reset.
void helios::engine::mechanics::spawn::components::EmittedByComponent::onRelease() noexcept override
References helios::engine::mechanics::spawn::components::EmittedByComponent::reset.