helios.engine.runtime.pooling.components.PrefabIdComponent
PrefabId helios::engine::runtime::pooling::components::PrefabIdComponent::prefabId_
The prefab identifier for this entity's template origin.
helios::engine::runtime::pooling::components::PrefabIdComponent::~PrefabIdComponent()=default
Destructor.
helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent(const PrefabIdComponent &)=delete
Copy construction is deleted (prefab identity is not cloneable).
References helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.
Referenced by helios::engine::runtime::pooling::components::PrefabIdComponent::operator=, helios::engine::runtime::pooling::components::PrefabIdComponent::operator=, helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent, helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.
PrefabIdComponent & helios::engine::runtime::pooling::components::PrefabIdComponent::operator=(const PrefabIdComponent &)=delete
Copy assignment is deleted (prefab identity is not cloneable).
References helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.
helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent(PrefabIdComponent &&)=default
Move constructor.
References helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.
PrefabIdComponent & helios::engine::runtime::pooling::components::PrefabIdComponent::operator=(PrefabIdComponent &&)=default
Move assignment operator.
References helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.
helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent(const PrefabId prefabId)
Constructs a PrefabIdComponent with the given prefab identifier.
prefabId The prefab identifier to store.
References helios::engine::runtime::pooling::components::PrefabIdComponent::prefabId.
PrefabId helios::engine::runtime::pooling::components::PrefabIdComponent::prefabId() const noexcept
Returns the stored prefab identifier.
The PrefabId identifying the prefab template.
Referenced by helios::engine::runtime::pooling::components::PrefabIdComponent::PrefabIdComponent.