helios.engine.runtime.spawn.commands.ScheduledSpawnPlanCommand
helios::engine::core::data::SpawnProfileId helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnProfileId_
helios::engine::runtime::spawn::scheduling::SpawnPlan helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnPlan_
helios::engine::runtime::spawn::SpawnContext helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnContext_
helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::ScheduledSpawnPlanCommand(const helios::engine::core::data::SpawnProfileId spawnProfileId, const helios::engine::runtime::spawn::scheduling::SpawnPlan spawnPlan, const helios::engine::runtime::spawn::SpawnContext &spawnContext)
Constructs a command with the given spawn plan.
spawnProfileId The profile ID for spawning. spawnPlan The spawn plan containing rule ID and amount. spawnContext The context for spawn operations.
References helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnContext, helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnPlan, helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnProfileId.
void helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::execute(helios::engine::runtime::world::GameWorld &gameWorld) const noexcept override
Direct execution is a no-op; dispatching is required.
This command requires a dispatcher to route it to the SpawnManager. Direct execution does nothing. gameWorld The game world (unused).
void helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::accept(helios::engine::runtime::world::GameWorld &gameWorld, helios::engine::runtime::messaging::command::WorldCommandDispatcher &dispatcher) const noexcept override
Accepts a dispatcher for command routing.
Invokes the dispatcher's dispatch method, allowing it to handle this command type appropriately (typically routing to SpawnManager). gameWorld The game world. dispatcher The dispatcher to route this command to.
helios::engine::core::data::SpawnProfileId helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnProfileId() const noexcept
Retrieves the spawn profile identifier associated with the command.
The spawn profile identifier encapsulated within the ScheduledSpawnPlanCommand.
Referenced by helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::ScheduledSpawnPlanCommand.
helios::engine::runtime::spawn::scheduling::SpawnPlan helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnPlan() const noexcept
Returns the spawn plan associated with this instance.
A structured plan that can be executed by the spawn management system.
Referenced by helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::ScheduledSpawnPlanCommand.
helios::engine::runtime::spawn::SpawnContext helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::spawnContext() const noexcept
Retrieves the spawn context associated with this instance.
The spawn context.
Referenced by helios::engine::runtime::spawn::commands::ScheduledSpawnPlanCommand::ScheduledSpawnPlanCommand.