helios.rendering.text.TextRenderPrototype
std::shared_ptr<const helios::rendering::shader::Shader> helios::rendering::text::TextRenderPrototype::shader_
The shader used for rendering text.
std::shared_ptr<const helios::rendering::text::config::TextShaderProperties> helios::rendering::text::TextRenderPrototype::textProperties_
Text-specific shader properties (e.g., color).
helios::rendering::text::FontResourceProvider* helios::rendering::text::TextRenderPrototype::fontResourceProvider_
Provider for loading fonts and retrieving glyph data.
Non-owning raw pointer. The font resource provider must remain valid for the lifetime of this prototype.
helios::rendering::text::TextRenderPrototype::TextRenderPrototype(std::shared_ptr< const helios::rendering::shader::Shader > shader, std::shared_ptr< const helios::rendering::text::config::TextShaderProperties > textProperties, helios::rendering::text::FontResourceProvider *fontResourceProvider)
Constructs a text render prototype.
shader The shader to use for text rendering. textProperties Text-specific shader properties. fontResourceProvider Raw pointer to the font resource provider (must remain valid for the lifetime of this prototype). std::invalid_argument If `shader`, `textProperties`, or `fontResourceProvider` is null.
References helios::rendering::text::TextRenderPrototype::fontResourceProvider, helios::rendering::text::TextRenderPrototype::shader, helios::rendering::text::TextRenderPrototype::textProperties.
const helios::rendering::shader::Shader & helios::rendering::text::TextRenderPrototype::shader() const noexcept
Returns the shader.
Reference to the shader used for text rendering.
Referenced by helios::rendering::text::TextRenderPrototype::TextRenderPrototype.
helios::rendering::text::FontResourceProvider & helios::rendering::text::TextRenderPrototype::fontResourceProvider() const noexcept
Returns the font resource provider.
The font resource provider is used to load fonts and retrieve glyph data for text layout and rendering. Reference to the font resource provider.
Referenced by helios::rendering::text::TextRenderPrototype::TextRenderPrototype.
const helios::rendering::text::config::TextShaderProperties & helios::rendering::text::TextRenderPrototype::textProperties() const noexcept
Returns the text shader properties.
Reference to the text-specific properties.
Referenced by helios::rendering::text::TextRenderPrototype::TextRenderPrototype.