helios.engine.mechanics.damage.components.DamageDealerComponent
std::array<float, helios::engine::core::data::MAX_COLLISION_LAYERS> helios::engine::mechanics::damage::components::DamageDealerComponent::damageRegistry_
Damage values indexed by collision layer.
helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent()=default
Referenced by helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent, helios::engine::mechanics::damage::components::DamageDealerComponent::setDamage.
helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent(const DamageDealerComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent.
DamageDealerComponent & helios::engine::mechanics::damage::components::DamageDealerComponent::setDamage(const float damage, const uint32_t otherLayerId) noexcept
Sets the damage dealt to entities on a specific layer.
damage The damage value to deal. otherLayerId The target collision layer ID (must be a power of 2). Reference to this component for method chaining.
References helios::engine::mechanics::damage::components::DamageDealerComponent::damage, helios::engine::mechanics::damage::components::DamageDealerComponent::DamageDealerComponent.
float helios::engine::mechanics::damage::components::DamageDealerComponent::damage(const uint32_t otherLayerId) const noexcept
Returns the damage dealt to entities on a specific layer.
otherLayerId The target collision layer ID (must be a power of 2). The damage value for the specified layer.
Referenced by helios::engine::mechanics::damage::components::DamageDealerComponent::setDamage.