helios.engine.tooling.FpsMetrics
std::deque<helios::engine::tooling::FrameStats> helios::engine::tooling::FpsMetrics::history_
Stores a rolling history of frame statistics.
`history_` holds the full timing data (work time, wait time, total frame time) for a specified number of recent frames. This buffer is used to compute average frame rate and frame time metrics over a configurable window. The use of a `std::deque` allows efficient addition and removal of frame timing records while maintaining the order of events.
size_t helios::engine::tooling::FpsMetrics::historySize_
Size of the history buffer for storing frame statistics.
Determines the maximum number of frames for which the frame timing data is retained to calculate performance metrics such as average FPS and frame times. A larger history size smooths out short-term variations but may reduce responsiveness to sudden changes in performance. This variable is initialized to a default value of 60 but can be adjusted based on the application's requirements for performance analysis.
float helios::engine::tooling::FpsMetrics::avgFps_
Stores the calculated average frames per second (FPS).
The `avgFps_` variable holds the computed average FPS value based on the accumulated frame timing data in `history_`. It is recomputed lazily when one of the query functions (e.g. `getFps()`) is called after new frames have been added.
float helios::engine::tooling::FpsMetrics::avgFrameTime_
Stores the average frame time in milliseconds.
Represents the total frame time (including work and wait) averaged over the frames currently stored in the history buffer. The value is stored in milliseconds and recomputed lazily when queried via the public getters after new frames have been added.
float helios::engine::tooling::FpsMetrics::lastWorkTime_
Tracks the most recent frame's work time in milliseconds.
Represents the duration of work performed during the last processed frame. This value is derived from the most recent `FrameStats` in the history and expressed in milliseconds. It is updated when the metrics are recomputed (lazy evaluation triggered by the getters).
float helios::engine::tooling::FpsMetrics::lastWaitTime_
Tracks the idle time in milliseconds for the most recent frame.
Represents the duration the system waited (idle time) during the last processed frame. This value is derived from the most recent `FrameStats` in the history and expressed in milliseconds. It is updated when the metrics are recomputed (lazy evaluation triggered by the getters).
unsigned long long helios::engine::tooling::FpsMetrics::frameCount_
Tracks the total number of frames processed since initialization.
The frameCount_ variable accumulates the count of frames that have been added via `addFrame()`. It starts at 0 and increments with each call, serving as a global counter independent of the current history size.
bool helios::engine::tooling::FpsMetrics::needsUpdate_
Indicates whether cached metrics need to be recomputed.
Set to true whenever new frame data is added or the history changes in a way that invalidates the cached values. The next call to one of the public query functions will trigger a recomputation in `update()`.
void helios::engine::tooling::FpsMetrics::update() noexcept
Recomputes cached metrics if needed.
If `needsUpdate_` is true and the history is non-empty, this function updates `lastWorkTime_`, `lastWaitTime_`, `avgFrameTime_` and `avgFps_` based on the current contents of `history_` and then clears the flag. If the history is empty or the cache is already up to date, this function returns immediately without modifying any values. This function is safe to call in hot paths and does not throw under normal conditions; it is therefore marked `noexcept`.
void helios::engine::tooling::FpsMetrics::addFrame(const helios::engine::tooling::FrameStats &stats)
Adds a frame's statistics to the metrics history.
Processes the provided FrameStats, updates the rolling history, and marks cached values as dirty so they will be recomputed on the next query. Old frames are automatically removed when the history buffer exceeds the configured size. Additionally, the `frameCount_` member is increased by one for each call. stats Frame statistics to add to the history. When used together with FramePacer, a typical usage pattern is: helios::engine::tooling::FrameStatsstats=framePacer.sync(); metrics.addFrame(stats); This should usually be called once per frame at the end of the frame loop, after timing information for the current frame has been measured.
void helios::engine::tooling::FpsMetrics::setHistorySize(size_t size)
Sets the size of the frame history buffer.
Determines how many frames are used for calculating averages. Larger values produce smoother metrics but respond slower to changes. size Number of frames to keep in history (default: 60). Common values: 30 for roughly half-second average at 60 FPS, 60 for roughly one-second average at 60 FPS.
size_t helios::engine::tooling::FpsMetrics::getHistorySize() const noexcept
Gets the current history buffer size.
Maximum number of frames kept in history.
float helios::engine::tooling::FpsMetrics::getFps() noexcept
Gets the average frames per second.
Triggers a lazy recomputation of the underlying metrics if new frames have been added since the last query. Average FPS calculated over the frames stored in the history buffer.
References helios::engine::tooling::FpsMetrics::getFps.
Referenced by helios::engine::tooling::FpsMetrics::getFps.
float helios::engine::tooling::FpsMetrics::getFrameTimeMs() noexcept
Gets the average frame time in milliseconds.
Triggers a lazy recomputation of the underlying metrics if needed. Average total frame time (work + wait) in milliseconds.
References helios::engine::tooling::FpsMetrics::getFrameTimeMs.
Referenced by helios::engine::tooling::FpsMetrics::getFrameTimeMs.
float helios::engine::tooling::FpsMetrics::getWorkTimeMs() noexcept
Gets the most recent frame's work time.
Triggers a lazy recomputation if required. Work time of the last processed frame in milliseconds.
References helios::engine::tooling::FpsMetrics::getWorkTimeMs.
Referenced by helios::engine::tooling::FpsMetrics::getWorkTimeMs.
float helios::engine::tooling::FpsMetrics::getIdleTimeMs() noexcept
Gets the most recent frame's idle time.
Triggers a lazy recomputation if required. Wait/idle time of the last processed frame in milliseconds.
References helios::engine::tooling::FpsMetrics::getIdleTimeMs.
Referenced by helios::engine::tooling::FpsMetrics::getIdleTimeMs.
unsigned long long helios::engine::tooling::FpsMetrics::getFrameCount() const noexcept
Gets the frame count.
The total number of frames that have been added via `addFrame()`.
References helios::engine::tooling::FpsMetrics::getFrameCount.
Referenced by helios::engine::tooling::FpsMetrics::getFrameCount.
float helios::engine::tooling::FpsMetrics::getFrameTimeSeconds() noexcept
Gets the average frame time in seconds.
Convenience wrapper returning the same value as `getFrameTimeMs()` converted from milliseconds to seconds. Average total frame time (work + wait) in seconds.
References helios::engine::tooling::FpsMetrics::getFrameTimeSeconds.
Referenced by helios::engine::tooling::FpsMetrics::getFrameTimeSeconds.
float helios::engine::tooling::FpsMetrics::getWorkTimeSeconds() noexcept
Gets the most recent frame's work time in seconds.
Convenience wrapper returning the same value as `getWorkTimeMs()` converted from milliseconds to seconds. Work time of the last processed frame in seconds.
References helios::engine::tooling::FpsMetrics::getWorkTimeSeconds.
Referenced by helios::engine::tooling::FpsMetrics::getWorkTimeSeconds.
float helios::engine::tooling::FpsMetrics::getIdleTimeSeconds() noexcept
Gets the most recent frame's idle time in seconds.
Convenience wrapper returning the same value as `getIdleTimeMs()` converted from milliseconds to seconds. Wait/idle time of the last processed frame in seconds.
References helios::engine::tooling::FpsMetrics::getIdleTimeSeconds.
Referenced by helios::engine::tooling::FpsMetrics::getIdleTimeSeconds.
const std::deque< helios::engine::tooling::FrameStats > & helios::engine::tooling::FpsMetrics::getHistory() const noexcept
Gets the complete frame history.
Const reference to the deque containing the full frame statistics history. Useful for rendering frame time graphs or diagnostic views in debug overlays.
References helios::engine::tooling::FpsMetrics::getHistory.
Referenced by helios::engine::tooling::FpsMetrics::getHistory.
void helios::engine::tooling::FpsMetrics::reset()
Clears all collected metrics and resets to initial state.
Removes all stored frame statistics and resets cached metrics and counters to their default values. After calling this function, all query functions will report zeros until new frames are added.
References helios::engine::tooling::FpsMetrics::reset.
Referenced by helios::engine::tooling::FpsMetrics::reset.