helios.scene.SnapshotItem
const helios::rendering::Renderable* helios::scene::SnapshotItem::renderable_
A non-owning raw pointer to the Renderable object.
The Renderable must remain valid for the lifetime of this SnapshotItem.
const helios::math::mat4f helios::scene::SnapshotItem::worldMatrix_
A copy of the world transformation matrix for the Renderable.
helios::scene::SnapshotItem::SnapshotItem(const SnapshotItem &)=delete
Prevent copying.
References helios::scene::SnapshotItem::SnapshotItem.
Referenced by helios::scene::SnapshotItem::operator=, helios::scene::SnapshotItem::SnapshotItem, helios::scene::SnapshotItem::SnapshotItem, helios::scene::SnapshotItem::SnapshotItem.
SnapshotItem & helios::scene::SnapshotItem::operator=(const SnapshotItem &)=delete
References helios::scene::SnapshotItem::SnapshotItem.
helios::scene::SnapshotItem::SnapshotItem(SnapshotItem &&) noexcept=default
Provide custom move constructor.
https://en.cppreference.com/w/cpp/language/move_constructor.html
References helios::scene::SnapshotItem::SnapshotItem.
helios::scene::SnapshotItem::SnapshotItem(const helios::rendering::Renderable *renderable, const helios::math::mat4f &worldMatrix)
Constructs a new SnapshotItem with the specified renderable and the worldMatrix.
renderable A raw pointer to the Renderable (must remain valid for the lifetime of this item). worldMatrix A const ref to the world transformation matrix, which gets copied.
References helios::scene::SnapshotItem::renderable, helios::scene::SnapshotItem::SnapshotItem, helios::scene::SnapshotItem::worldMatrix.
const helios::rendering::Renderable * helios::scene::SnapshotItem::renderable() const noexcept
Returns a raw pointer to the Renderable of this SnapshotItem.
A raw pointer to the Renderable of this SnapshotItem.
Referenced by helios::scene::SnapshotItem::SnapshotItem.
const helios::math::mat4f & helios::scene::SnapshotItem::worldMatrix() const noexcept
Returns a const ref to the worldMatrix of this SnapshotItem. The world transformation matrix is a copy from the world transformation matrix created with this SnapshotItem.
The const ref to the world matrix of this SnapshotItem.
Referenced by helios::scene::SnapshotItem::SnapshotItem.