helios.engine.mechanics.scoring.components.ScoreValueComponent
T helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::score_
The score value instance.
bool helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::enable() noexcept
Enables this component.
void helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::disable() noexcept
Disables this component.
helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent(Args &&... args)
Constructs a ScoreValueComponent with forwarded arguments.
Args Argument types for Score construction. args Arguments forwarded to the Score constructor.
Referenced by helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::operator=, helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::operator=, helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent, helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent.
helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent(const ScoreValueComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent.
ScoreValueComponent & helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::operator=(const ScoreValueComponent &other)=default
References helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent.
helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent(ScoreValueComponent &&other) noexcept=default
References helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent.
ScoreValueComponent & helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::operator=(ScoreValueComponent &&other) noexcept=default
References helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::ScoreValueComponent.
T helios::engine::mechanics::scoring::components::ScoreValueComponent< T >::score() const noexcept
Returns the stored score value.
The score instance.