helios.engine.runtime.world.System
T helios::engine::runtime::world::System::Model< T >::system_
std::unique_ptr<Concept> helios::engine::runtime::world::System::pimpl_
virtual helios::engine::runtime::world::System::Concept::~Concept()=default
virtual void helios::engine::runtime::world::System::Concept::update(UpdateContext &updateContext) noexcept=0
virtual void helios::engine::runtime::world::System::Concept::init(GameWorld &gameWorld) noexcept=0
virtual void * helios::engine::runtime::world::System::Concept::underlying() noexcept=0
virtual const void * helios::engine::runtime::world::System::Concept::underlying() const noexcept=0
helios::engine::runtime::world::System::Model< T >::Model(T sys)
void helios::engine::runtime::world::System::Model< T >::update(UpdateContext &updateContext) noexcept override
void helios::engine::runtime::world::System::Model< T >::init(GameWorld &gameWorld) noexcept override
void * helios::engine::runtime::world::System::Model< T >::underlying() noexcept override
const void * helios::engine::runtime::world::System::Model< T >::underlying() const noexcept override
helios::engine::runtime::world::System::System()=default
Default constructor creating an empty System.
Referenced by helios::engine::runtime::world::System::operator=, helios::engine::runtime::world::System::operator=, helios::engine::runtime::world::System::System, helios::engine::runtime::world::System::System.
helios::engine::runtime::world::System::System(T system)
Wraps a concrete system in a type-erased System.
T The concrete system type, must satisfy `HasUpdate<T>`. system The concrete system instance to wrap (moved into internal storage).
helios::engine::runtime::world::System::System(const System &)=delete
References helios::engine::runtime::world::System::System.
System & helios::engine::runtime::world::System::operator=(const System &)=delete
References helios::engine::runtime::world::System::System.
System & helios::engine::runtime::world::System::operator=(System &&)=default
References helios::engine::runtime::world::System::System.
helios::engine::runtime::world::System::System(System &&) noexcept=default
References helios::engine::runtime::world::System::System.
void helios::engine::runtime::world::System::update(UpdateContext &updateContext) noexcept
Delegates to the wrapped system's `update()` method.
updateContext The current frame's update context. System must be initialized (pimpl_ != nullptr).
References helios::engine::runtime::world::System::update.
Referenced by helios::engine::runtime::world::System::update.
void helios::engine::runtime::world::System::init(GameWorld &gameWorld) noexcept
Delegates to the wrapped system's `init()` method, if present.
If the concrete type satisfies `HasInit<T>`, its `init()` is called. Otherwise this is a no-op. gameWorld The GameWorld for one-time initialization. System must be initialized (pimpl_ != nullptr).
void * helios::engine::runtime::world::System::underlying() noexcept
Returns a type-erased pointer to the wrapped system instance.
Pointer to the underlying concrete system. System must be initialized (pimpl_ != nullptr).
const void * helios::engine::runtime::world::System::underlying() const noexcept
Returns a type-erased pointer to the wrapped system instance.
Pointer to the underlying concrete system. System must be initialized (pimpl_ != nullptr).