helios.engine.modules.physics.collision.components.CollisionStateComponent
helios::math::vec3f helios::engine::modules::physics::collision::components::CollisionStateComponent::contact_
World-space contact point of the collision.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isSolid_
Whether this collision is a solid (physical) collision.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isTrigger_
Whether this collision is a trigger (non-physical) collision.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isCollisionReporter_
Whether this entity is the collision reporter.
std::optional<helios::engine::ecs::EntityHandle> helios::engine::modules::physics::collision::components::CollisionStateComponent::other_
Handle of the other entity involved in the collision.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionBehavior_
The collision behavior to apply.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::hasCollision_
Flag indicating whether a collision was detected this frame.
helios::engine::modules::physics::collision::types::CollisionContext helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionContext_
Full collision context data for event publishing.
uint32_t helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionLayer_
Collision layer ID of this entity.
uint32_t helios::engine::modules::physics::collision::components::CollisionStateComponent::otherCollisionLayer_
Collision layer ID of the other entity.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::modules::physics::collision::components::CollisionStateComponent::enable() noexcept
Enables this component.
void helios::engine::modules::physics::collision::components::CollisionStateComponent::disable() noexcept
Disables this component.
helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent()=default
Default constructor.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent, helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent, helios::engine::modules::physics::collision::components::CollisionStateComponent::operator=, helios::engine::modules::physics::collision::components::CollisionStateComponent::operator=.
helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent(const CollisionStateComponent &other)
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent, helios::engine::modules::physics::collision::components::CollisionStateComponent::other.
CollisionStateComponent & helios::engine::modules::physics::collision::components::CollisionStateComponent::operator=(const CollisionStateComponent &)=default
References helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent.
helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent(CollisionStateComponent &&) noexcept=default
References helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent.
CollisionStateComponent & helios::engine::modules::physics::collision::components::CollisionStateComponent::operator=(CollisionStateComponent &&) noexcept=default
References helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::setState(helios::engine::ecs::GameObject gameObject, helios::math::vec3f contact, const bool isSolid, const bool isTrigger, const helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior, const bool isCollisionReporter, std::optional< helios::engine::ecs::EntityHandle > other=std::nullopt, const uint32_t collisionLayer=0, const uint32_t otherCollisionLayer=0)
Sets the collision state for this frame.
This method is called by the collision detection system when a collision is detected. Only the first collision per frame is recorded. contact World-space contact point. isSolid Whether this is a solid collision. isTrigger Whether this is a trigger collision. collisionBehavior The behavior to apply for this collision. isCollisionReporter Whether this entity reports the collision. other GUID of the other entity (optional). collisionLayer Collision layer ID of this entity. otherCollisionLayer Collision layer ID of the other entity. True if the state was set, false if a collision was already recorded.
References helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionBehavior, helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionLayer, helios::engine::modules::physics::collision::components::CollisionStateComponent::contact, helios::engine::modules::physics::collision::components::CollisionStateComponent::isCollisionReporter, helios::engine::modules::physics::collision::components::CollisionStateComponent::isSolid, helios::engine::modules::physics::collision::components::CollisionStateComponent::isTrigger, helios::engine::modules::physics::collision::components::CollisionStateComponent::other, helios::engine::modules::physics::collision::components::CollisionStateComponent::otherCollisionLayer, helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
void helios::engine::modules::physics::collision::components::CollisionStateComponent::reset() noexcept
Resets the collision state for a new frame.
Clears all collision flags and data. Called at the start of each frame or when the owning GameObject is acquired from a pool.
References helios::engine::modules::physics::collision::types::None.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::onAcquire.
void helios::engine::modules::physics::collision::components::CollisionStateComponent::onAcquire() noexcept
Called when the owning GameObject is acquired from a pool.
Resets all collision state to prepare for a new lifecycle.
References helios::engine::modules::physics::collision::components::CollisionStateComponent::reset.
const types::CollisionContext & helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionContext() const noexcept
Returns the full collision context data.
Reference to the CollisionContext struct containing all collision details.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::hasCollision() const noexcept
Checks whether a collision was detected this frame.
True if a collision occurred, false otherwise.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
std::optional< helios::engine::ecs::EntityHandle > helios::engine::modules::physics::collision::components::CollisionStateComponent::other() const noexcept
Returns the handle of the other entity involved in the collision.
Optional handle of the other entity, or nullopt if not set.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::CollisionStateComponent, helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isCollisionReporter() const noexcept
Checks whether this entity is the collision reporter.
True if this entity reported the collision.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isSolid() const noexcept
Checks whether this is a solid (physical) collision.
True if the collision is solid.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
bool helios::engine::modules::physics::collision::components::CollisionStateComponent::isTrigger() const noexcept
Checks whether this is a trigger (non-physical) collision.
True if the collision is a trigger.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
helios::engine::modules::physics::collision::types::CollisionBehavior helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionBehavior() const noexcept
Returns the collision behavior for this collision.
The CollisionBehavior enum value.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
helios::math::vec3f helios::engine::modules::physics::collision::components::CollisionStateComponent::contact() const noexcept
Returns the world-space contact point of the collision.
The contact point as a 3D vector.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
uint32_t helios::engine::modules::physics::collision::components::CollisionStateComponent::collisionLayer() const noexcept
Returns the collision layer ID of this entity.
The collision layer ID.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.
uint32_t helios::engine::modules::physics::collision::components::CollisionStateComponent::otherCollisionLayer() const noexcept
Returns the collision layer ID of the other entity.
The other entity's collision layer ID.
Referenced by helios::engine::modules::physics::collision::components::CollisionStateComponent::setState.