helios.engine.ecs.Component
GameObject* helios::engine::ecs::Component::gameObject_
Non-owning pointer to the owning GameObject.
Set by onAttach() when the component is added to a GameObject. nullptr until attached.
Referenced by helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::defer, helios::engine::ecs::Component::gameObject, helios::engine::ecs::Component::isAttached, helios::engine::ecs::Component::onAttach.
bool helios::engine::ecs::Component::isEnabled_
Boolean flag indicating whether this component is enabled.
Referenced by helios::engine::ecs::Component::disable, helios::engine::ecs::Component::enable, helios::engine::ecs::Component::isDisabled, helios::engine::ecs::Component::isEnabled.
virtual helios::engine::ecs::Component::~Component()=default
Virtual destructor for proper polymorphic cleanup.
helios::engine::ecs::Component::Component()=default
Default constructor.
virtual void helios::engine::ecs::Component::onAttach(GameObject *gameObject) noexcept
Called when the component is attached to a GameObject.
gameObject Pointer to the owning GameObject. Derived classes that override this method should call the base implementation to ensure gameObject_ is set correctly.
References helios::engine::ecs::Component::gameObject, helios::engine::ecs::Component::gameObject_.
virtual void helios::engine::ecs::Component::onAcquire() noexcept
Called when the component's GameObject is re-acquired from a pool.
Override this method to reinitialize component state when the owning GameObject is recycled from an object pool. This allows components to reset their internal state for reuse without requiring a full destruction and reconstruction cycle. The default implementation does nothing.
virtual void helios::engine::ecs::Component::onRelease() noexcept
Called when the component's GameObject is released to a pool.
Override this method to prune any component state when the owning GameObject is released to an object pool. This allows for reducing memory footprints of GameObjects not actively participating in the GameWorld. The default implementation does nothing.
bool helios::engine::ecs::Component::isAttached() const noexcept
Checks whether this component is attached to a GameObject.
True if the component has an owning GameObject, false otherwise.
References helios::engine::ecs::Component::gameObject_.
bool helios::engine::ecs::Component::isEnabled() const noexcept
Checks whether the component is enabled.
An enabled component is processed by systems during the game loop. A disabled component remains attached to the GameObject but is skipped by systems that check this flag. Use this for temporary deactivation of specific behaviors without removing the component entirely (e.g., temporary invulnerability, disabled collision). True if the component is enabled, false otherwise. disable() enable() isDisabled()
References helios::engine::ecs::Component::isEnabled_.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::update.
bool helios::engine::ecs::Component::isDisabled() const noexcept
Checks whether the component is disabled.
Convenience method, equivalent to `!isEnabled()`. True if the component is disabled, false otherwise. isEnabled()
References helios::engine::ecs::Component::isEnabled_.
void helios::engine::ecs::Component::enable() noexcept
Enables this component.
An enabled component will be processed by systems that check the enabled state. This is the default state for newly created components. disable() isEnabled()
References helios::engine::ecs::Component::isEnabled_.
void helios::engine::ecs::Component::disable() noexcept
Disables this component.
A disabled component remains attached to the GameObject but should be skipped by systems. This allows temporary deactivation of specific behaviors without modifying the component configuration. Example use cases: Temporary invulnerability (disable CollisionComponent) Frozen movement (disable Move2DComponent) Stealth mode (disable detection-related components) This does **not** call any lifecycle callbacks. The component remains fully attached and can be re-enabled at any time. enable() isDisabled()
References helios::engine::ecs::Component::isEnabled_.
virtual void helios::engine::ecs::Component::onActivate() noexcept
Called when the owning GameObject becomes active.
Override this method to perform initialization or state restoration when the GameObject is activated. The default implementation does nothing.
virtual void helios::engine::ecs::Component::onDeactivate() noexcept
Called when the owning GameObject becomes inactive.
Override this method to perform cleanup or state preservation when the GameObject is deactivated. The default implementation does nothing.
GameObject * helios::engine::ecs::Component::gameObject() const noexcept
Returns the owning GameObject.
Non-owning pointer to the GameObject, or nullptr if not attached.
References helios::engine::ecs::Component::gameObject_.
Referenced by helios::engine::ecs::Component::onAttach, helios::engine::mechanics::combat::components::ShootComponent::onAttach, helios::engine::modules::rendering::renderable::components::RenderableComponent::onAttach, helios::engine::modules::scene::components::SceneNodeComponent::onAttach, helios::engine::modules::spatial::transform::components::ScaleStateComponent::onAttach.
virtual helios::engine::core::data::ComponentTypeId helios::engine::ecs::Component::typeId() const noexcept=0
Returns the ComponentTypeId for this Component.
The ComponentTypeId is a static, runtime dependent value that allows for managing ComponentTypeIds in a dense array, providing O(1) access to a GameObject's component. The ComponentTypeId for this Component-Type.