helios.engine.mechanics.spawn.commands.DespawnCommand
const helios::util::Guid helios::engine::mechanics::spawn::commands::DespawnCommand::guid_
The GUID of the entity to despawn.
std::optional<helios::engine::core::data::GameObjectPoolId> helios::engine::mechanics::spawn::commands::DespawnCommand::gameObjectPoolId_
Optional pool ID to return the entity to.
helios::engine::mechanics::spawn::commands::DespawnCommand::DespawnCommand(const helios::util::Guid &guid)
Constructs a DespawnCommand without a specific pool.
guid The GUID of the entity to despawn.
References helios::engine::mechanics::spawn::commands::DespawnCommand::guid.
helios::engine::mechanics::spawn::commands::DespawnCommand::DespawnCommand(const helios::util::Guid &guid, const helios::engine::core::data::GameObjectPoolId gameObjectPoolId)
Constructs a DespawnCommand with a target pool.
guid The GUID of the entity to despawn. gameObjectPoolId The pool to return the entity to.
References helios::engine::mechanics::spawn::commands::DespawnCommand::gameObjectPoolId, helios::engine::mechanics::spawn::commands::DespawnCommand::guid.
void helios::engine::mechanics::spawn::commands::DespawnCommand::execute(helios::engine::runtime::world::GameWorld &gameWorld) const noexcept override
Direct execution is not supported; requires a dispatcher.
gameWorld The game world (unused). Asserts in debug builds if called directly.
void helios::engine::mechanics::spawn::commands::DespawnCommand::accept(helios::engine::runtime::world::GameWorld &gameWorld, helios::engine::runtime::messaging::command::WorldCommandDispatcher &dispatcher) const noexcept override
Accepts a dispatcher for command routing.
gameWorld The game world. dispatcher The dispatcher to route this command to.
const helios::util::Guid & helios::engine::mechanics::spawn::commands::DespawnCommand::guid() const noexcept
Returns the GUID of the entity to despawn.
Const reference to the entity's GUID.
Referenced by helios::engine::mechanics::spawn::commands::DespawnCommand::DespawnCommand, helios::engine::mechanics::spawn::commands::DespawnCommand::DespawnCommand.
std::optional< helios::engine::core::data::GameObjectPoolId > helios::engine::mechanics::spawn::commands::DespawnCommand::gameObjectPoolId() const noexcept
Returns the optional pool ID.
Optional containing the pool ID if specified.
Referenced by helios::engine::mechanics::spawn::commands::DespawnCommand::DespawnCommand.