helios.engine.builder.gameObject.builders.configs.LevelBoundsCollisionConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::gameObject_
Non-owning pointer to the target GameObject.
void helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::ensureLevelBoundsBehaviorComponent(const bool isAvailable) const noexcept
Validates LevelBoundsBehaviorComponent presence.
isAvailable Whether the component should exist.
helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::LevelBoundsCollisionConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a LevelBoundsCollisionConfig.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::onCollision, helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::respondWith, helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::restitution.
LevelBoundsCollisionConfig & helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::onCollision(helios::engine::modules::physics::collision::types::CollisionBehavior collisionBehavior)
Sets the collision behavior at level boundaries.
collisionBehavior The behavior (clamp, bounce, wrap, despawn). Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::LevelBoundsCollisionConfig.
LevelBoundsCollisionConfig & helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::restitution(const float restitution)
Sets the restitution coefficient for bounce behavior.
restitution Bounce factor (1.0 = perfect bounce). Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::LevelBoundsCollisionConfig, helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::restitution.
Referenced by helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::restitution.
LevelBoundsCollisionConfig & helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::respondWith(helios::engine::modules::physics::collision::types::CollisionResponse collisionResponse)
Sets the collision response type.
collisionResponse How to respond (slide, stop, etc.). Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::LevelBoundsCollisionConfig::LevelBoundsCollisionConfig.