helios.engine.runtime.pooling.GameObjectPoolManager
using helios::engine::runtime::pooling::GameObjectPoolManager::EngineRoleTag = helios::engine::common::tags::ManagerRole
helios::engine::runtime::pooling::GameObjectPoolRegistry helios::engine::runtime::pooling::GameObjectPoolManager::pools_
Registry of GameObjectPools for entity recycling.
Pools enable efficient reuse of GameObjects without repeated allocation/deallocation. Each pool is identified by a GameObjectPoolId.
helios::engine::runtime::world::GameWorld* helios::engine::runtime::pooling::GameObjectPoolManager::gameWorld_
Non-owning pointer to the associated GameWorld.
Set during `init()`. Used for cloning prefabs and looking up GameObjects by their EntityHandle.
std::unordered_map< helios::engine::runtime::pooling::types::GameObjectPoolId, std::unique_ptr<GameObjectPoolConfig> > helios::engine::runtime::pooling::GameObjectPoolManager::poolConfigs_
Pending pool configurations awaiting initialization.
Configurations are consumed during `init()` to create and populate the actual pools.
void helios::engine::runtime::pooling::GameObjectPoolManager::fillPool(const helios::engine::runtime::pooling::types::GameObjectPoolId gameObjectPoolId, helios::engine::ecs::GameObject gameObjectPrefab)
Populates a pool with cloned prefab instances and locks it.
Clones the prefab GameObject until the pool reaches its configured capacity. Each clone is: 1. Added to the GameWorld 2. Immediately deactivated (`setActive(false)`) 3. Prepared for pooling (`onRelease()`) 4. Registered as inactive in the pool After all clones are created, the pool is **locked** via `lock()`. Locking finalizes the sparse array sizing based on the min/max EntityIds and enables O(1) acquire/release operations. Once locked, no new EntityHandles can be added to the pool. gameObjectPoolId The pool to fill. gameObjectPrefab The prefab to clone. The pool is locked and ready for acquire/release operations.
GameObjectPoolManager & helios::engine::runtime::pooling::GameObjectPoolManager::addPoolConfig(std::unique_ptr< GameObjectPoolConfig > gameObjectPoolConfig)
Registers a pool configuration for later initialization.
The configuration specifies the pool ID, capacity, and prefab to use for cloning. Configurations are processed during `init()`. gameObjectPoolConfig The pool configuration to register. Reference to this manager for method chaining. std::runtime_error If a pool with the same ID is already registered.
helios::engine::runtime::pooling::GameObjectPoolSnapshot helios::engine::runtime::pooling::GameObjectPoolManager::poolSnapshot(const helios::engine::runtime::pooling::types::GameObjectPoolId gameObjectPoolId) const
Returns a snapshot of the pool's current state.
Provides the active and inactive counts for monitoring and debugging purposes. gameObjectPoolId The pool to query. A GameObjectPoolSnapshot containing active and inactive counts.
References helios::engine::runtime::pooling::GameObjectPoolManager::pool.
Referenced by helios::engine::runtime::spawn::policy::amount::SpawnAll::getAmount.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::pooling::GameObjectPoolManager::release(const helios::engine::runtime::pooling::types::GameObjectPoolId gameObjectPoolId, const helios::engine::ecs::EntityHandle &entityHandle)
Releases a GameObject back to its pool.
Marks the entity as inactive in both the pool and the GameWorld. Calls `onRelease()` on the GameObject to trigger component cleanup hooks, then deactivates it. gameObjectPoolId The pool that owns this entity. entityHandle The EntityHandle of the entity to release. Optional containing the released GameObject if found, std::nullopt if the entity was not found in the GameWorld.
References helios::engine::runtime::pooling::GameObjectPoolManager::pool.
Referenced by helios::engine::runtime::pooling::GameObjectPoolManager::reset.
std::optional< helios::engine::ecs::GameObject > helios::engine::runtime::pooling::GameObjectPoolManager::acquire(const helios::engine::runtime::pooling::types::GameObjectPoolId gameObjectPoolId)
Acquires an inactive GameObject from the pool.
Retrieves the next available inactive entity and calls `onAcquire()` to trigger component initialization hooks. The caller is responsible for activating the entity via `setActive(true)`. If an acquired entity is no longer valid in the GameWorld (stale handle), it is removed from the pool and the next available entity is tried. gameObjectPoolId The pool to acquire from. Optional containing the acquired GameObject if available, std::nullopt if the pool is exhausted.
References helios::engine::runtime::pooling::GameObjectPoolManager::pool.
void helios::engine::runtime::pooling::GameObjectPoolManager::init(helios::engine::runtime::world::GameWorld &gameWorld)
Initializes all registered pools.
Creates GameObjectPool instances from the pending configurations and populates them by cloning the specified prefabs into the GameWorld. gameWorld The GameWorld to associate with this manager.
References helios::engine::runtime::pooling::GameObjectPoolManager::pool, helios::engine::runtime::world::GameWorld::view.
void helios::engine::runtime::pooling::GameObjectPoolManager::flush(helios::engine::runtime::world::UpdateContext &update_context) noexcept
Manager flush callback (currently unused).
Reserved for future use. May be used to process deferred release requests or pool maintenance operations. gameWorld The associated GameWorld. update_context The current frame's update context.
GameObjectPool * helios::engine::runtime::pooling::GameObjectPoolManager::pool(const helios::engine::runtime::pooling::types::GameObjectPoolId gameObjectPoolId) const
Retrieves a pool by its ID.
gameObjectPoolId The pool ID to look up. Pointer to the GameObjectPool. The pool must be registered with this manager.
Referenced by helios::engine::runtime::pooling::GameObjectPoolManager::acquire, helios::engine::runtime::pooling::GameObjectPoolManager::init, helios::engine::runtime::pooling::GameObjectPoolManager::poolSnapshot, helios::engine::runtime::pooling::GameObjectPoolManager::release.
void helios::engine::runtime::pooling::GameObjectPoolManager::reset()
Resets all pools by releasing all active GameObjects.
Iterates through all registered pools and releases every active entity back to its pool. This effectively returns all pooled objects to their inactive state without destroying them. Useful for level transitions or game restarts where all pooled objects should be recycled.
References helios::engine::runtime::pooling::GameObjectPoolManager::release.