helios.engine.mechanics.spawn.components.SpawnedByProfileComponent
helios::engine::core::data::SpawnProfileId helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::spawnProfileId_
The spawn profile ID that created this entity.
Default-initialized to 0, which represents an invalid/unassigned profile.
bool helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent()=default
Default constructor.
Referenced by helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::operator=, helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::operator=, helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent, helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent.
helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent(const SpawnedByProfileComponent &other)
Copy constructor for cloning.
other The component to copy from.
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent.
SpawnedByProfileComponent & helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::operator=(const SpawnedByProfileComponent &)=default
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent.
helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent(SpawnedByProfileComponent &&) noexcept=default
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent.
SpawnedByProfileComponent & helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::operator=(SpawnedByProfileComponent &&) noexcept=default
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::SpawnedByProfileComponent.
helios::engine::core::data::SpawnProfileId helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::spawnProfileId() const noexcept
Returns the spawn profile ID.
The SpawnProfileId assigned to this entity.
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::spawnProfileId.
Referenced by helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::setSpawnProfileId, helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::spawnProfileId.
void helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::setSpawnProfileId(const helios::engine::core::data::SpawnProfileId &spawnProfileId) noexcept
Sets the spawn profile ID.
Called by the spawn manager after acquiring an entity from the pool to associate it with the correct profile for later despawning. spawnProfileId The profile ID to assign.
References helios::engine::mechanics::spawn::components::SpawnedByProfileComponent::spawnProfileId.