helios.engine.game.UpdateContext
float helios::engine::game::UpdateContext::deltaTime_
Time elapsed since the last frame, in seconds.
const helios::engine::game::InputSnapshot* helios::engine::game::UpdateContext::inputSnapshot_
Immutable snapshot of input state for the current frame.
helios::engine::game::CommandBuffer& helios::engine::game::UpdateContext::commandBuffer_
Buffer for queueing commands to be executed at end of frame.
helios::engine::game::GameWorld& helios::engine::game::UpdateContext::gameWorld_
Reference to the game world for entity lookups.
helios::engine::game::event::GameLoopEventSink helios::engine::game::UpdateContext::eventSink_
Sink for pushing game loop events during update.
Used by systems and components to publish events (e.g., collision, spawn requests) that will be processed in a later phase (N+1) of the game loop.
helios::engine::game::UpdateContext::UpdateContext(helios::engine::game::CommandBuffer &commandBuffer, helios::engine::game::GameWorld &gameWorld, const helios::engine::game::event::GameLoopEventSink &eventSink)
Constructs an UpdateContext with required dependencies.
commandBuffer Non-owning pointer to the command buffer. Must not be nullptr. gameWorld Non-owning pointer to the game world. Must not be nullptr. eventSink Sink for pushing game loop events. Used to publish events during update phases for later processing. std::invalid_argument if either commandBuffer or gameWorld are nullptr.
References helios::engine::game::UpdateContext::commandBuffer, helios::engine::game::UpdateContext::gameWorld.
Referenced by helios::engine::game::UpdateContext::setDeltaTime, helios::engine::game::UpdateContext::setInputSnapshot.
float helios::engine::game::UpdateContext::deltaTime() const noexcept
Returns the time elapsed since the last frame, in seconds.
UpdateContext & helios::engine::game::UpdateContext::setDeltaTime(float dt) noexcept
Sets the time elapsed since the last frame.
dt Delta time in seconds. Must be non-negative. A reference to this UpdateContext instance.
References helios::engine::game::UpdateContext::UpdateContext.
const helios::engine::game::InputSnapshot & helios::engine::game::UpdateContext::inputSnapshot() const noexcept
Returns the immutable input snapshot for this frame.
Const ref to the current InputSnapshot.
UpdateContext & helios::engine::game::UpdateContext::setInputSnapshot(const helios::engine::game::InputSnapshot &snapshot) noexcept
Sets the input snapshot for this frame.
snapshot Const ref to the input snapshot. A reference to this UpdateContext instance.
References helios::engine::game::UpdateContext::UpdateContext.
helios::engine::game::CommandBuffer & helios::engine::game::UpdateContext::commandBuffer() const noexcept
Returns the command buffer for queueing commands.
Ref to the CommandBuffer used with this UpdateContext.
Referenced by helios::engine::game::UpdateContext::UpdateContext.
helios::engine::game::GameWorld & helios::engine::game::UpdateContext::gameWorld() const noexcept
Returns the game world for entity lookups.
Ref to the GameWorld used with this UpdateContext.
Referenced by helios::engine::game::UpdateContext::UpdateContext.
void helios::engine::game::UpdateContext::pushEvent(Args &&... args)
Pushes an event to the game loop event bus.
This method allows systems and components to publish events during their update phase. Events are buffered and processed in a subsequent phase (N+1) of the game loop, ensuring decoupled communication between systems. E The event type to push. Args Constructor argument types for the event. args Arguments forwarded to the event constructor. Example usage: ```cpp updateContext.pushEvent<CollisionEvent>(entityA, entityB, contactPoint); ```