helios.engine.builder.gameObject.builders.configs.Move2DConfig
helios::engine::ecs::GameObject* helios::engine::builder::gameObject::builders::configs::Move2DConfig::gameObject_
Non-owning pointer to the target GameObject.
helios::engine::builder::gameObject::builders::configs::Move2DConfig::Move2DConfig(helios::engine::ecs::GameObject *gameObject)
Constructs a Move2DConfig and adds required components.
gameObject Target GameObject to configure.
Referenced by helios::engine::builder::gameObject::builders::configs::Move2DConfig::acceleration, helios::engine::builder::gameObject::builders::configs::Move2DConfig::instantAcceleration, helios::engine::builder::gameObject::builders::configs::Move2DConfig::speed.
Move2DConfig & helios::engine::builder::gameObject::builders::configs::Move2DConfig::speed(const float movementSpeed)
Sets the maximum movement speed.
movementSpeed Speed in units per second. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::Move2DConfig::Move2DConfig.
Move2DConfig & helios::engine::builder::gameObject::builders::configs::Move2DConfig::acceleration(const float movementAcceleration)
Sets the movement acceleration rate.
movementAcceleration Acceleration in units per second squared. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::Move2DConfig::Move2DConfig.
Move2DConfig & helios::engine::builder::gameObject::builders::configs::Move2DConfig::instantAcceleration(const bool useInstantAcceleration)
Enables or disables instant acceleration.
When enabled, the entity reaches max speed immediately. useInstantAcceleration True for instant acceleration. Reference to this config for chaining.
References helios::engine::builder::gameObject::builders::configs::Move2DConfig::Move2DConfig.