helios.util.Guid
uint64_t helios::util::Guid::value_
helios::util::Guid::Guid(uint64_t value) noexcept
helios::util::Guid::Guid(helios::core::types::no_init_t)
Unsafe Guid initializer for (local) var initialization.
bool helios::util::Guid::operator==(const Guid &guid) const =default
Compares two Guid instances for equality.
guid The Guid to compare against. `true` if both Guids have the same underlying value, `false` otherwise.
bool helios::util::Guid::operator!=(const Guid &guid) const =default
Compares two Guid instances for inequality.
guid The Guid to compare against. `true` if the Guids have different underlying values, `false` otherwise.
bool helios::util::Guid::operator<(const Guid &guid) const noexcept
Less-than comparison operator, enabling ordering of Guid instances.
guid The Guid to compare against. `true` if this Guid's value is less than the other, `false` otherwise.
bool helios::util::Guid::operator>(const Guid &guid) const noexcept
Greater-than comparison operator, enabling ordering of Guid instances.
guid The Guid to compare against. `true` if this Guid's value is greater than the other, `false` otherwise.
static Guid helios::util::Guid::generate() noexcept
Generates a new Guid.
This function produces a new, unique Guid value. It is safe to call from multiple threads. A newly generated `Guid` instance.
Referenced by helios::ext::glfw::app::GLFWFactory::makeWindowCfg, helios::scene::SceneNode::SceneNode, helios::scene::SceneNode::SceneNode, helios::scene::SceneNode::SceneNode.
uint64_t helios::util::Guid::value() const noexcept
Returns the raw 64-bit value of this Guid.
The underlying uint64_t value representing this Guid.
Referenced by helios::ext::glfw::app::GLFWApplication::setCurrent.
std::size_t helios::util::Guid::hash() const noexcept
Calculates a hash fot this GUID.
The hash simply defaults to the value_ of this Guid. The hash value for this Guid.
std::size_t std::hash< helios::util::Guid >::operator()(const helios::util::Guid &guid) const noexcept