helios.core.ecs.SparseSet
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::DataIt = typename std::vector<T>::iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::IdIt = typename std::vector<EntityId>::iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::iterator_category = std::forward_iterator_tag
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::value_type = T
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::difference_type = std::ptrdiff_t
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::pointer = T*
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::reference = T&
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::DataIt = typename std::vector<T>::const_iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::IdIt = typename std::vector<EntityId>::const_iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::iterator_category = std::forward_iterator_tag
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::value_type = T
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::difference_type = std::ptrdiff_t
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::pointer = const T*
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::reference = const T&
auto helios::core::ecs::Tombstone
Sentinel value indicating an empty slot in the sparse array.
Aliased from `helios::core::types::EntityTombstone`.
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::contains, helios::core::ecs::SparseSet< T, TAllowRemoval >::emplace, helios::core::ecs::SparseSet< T, TAllowRemoval >::get, helios::core::ecs::SparseSet< T, TAllowRemoval >::get, helios::core::ecs::SparseSet< T, TAllowRemoval >::insert, helios::core::ecs::SparseSet< T, TAllowRemoval >::remove.
std::vector<size_t> helios::core::ecs::SparseSet< T, TAllowRemoval >::sparse_
Maps EntityId to dense storage index.
Contains `Tombstone` for empty slots.
std::vector<EntityId> helios::core::ecs::SparseSet< T, TAllowRemoval >::denseToSparse_
Reverse mapping from dense index to EntityId.
Used during swap-and-pop removal to update the sparse array.
std::vector<T> helios::core::ecs::SparseSet< T, TAllowRemoval >::storage_
Contiguous storage of elements.
DataIt helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator*, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator->, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==.
IdIt helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::entityId, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++.
DataIt helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator*, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator->, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==.
IdIt helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::entityId, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++.
virtual helios::core::ecs::SparseSetBase::~SparseSetBase()=default
Virtual destructor for proper cleanup of derived classes.
virtual bool helios::core::ecs::SparseSetBase::remove(EntityId id)=0
Removes the element at the given index.
id The EntityId of the element to remove. True if the element was removed, false if not found or removal was cancelled.
virtual bool helios::core::ecs::SparseSetBase::contains(EntityId id) const =0
Checks whether an element exists for the specified EntityId.
id The EntityId to test. True if the set contains the EntityId.
virtual void * helios::core::ecs::SparseSetBase::raw(EntityId id)=0
Returns a raw void pointer to the element at the given index.
id The EntityId to look up. Raw pointer to the element, or `nullptr` if not found.
helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet()=default
Default constructor creating an empty sparse set.
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::operator=, helios::core::ecs::SparseSet< T, TAllowRemoval >::operator=, helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet, helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet.
helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet(const size_t capacity)
Constructs a sparse set with pre-allocated capacity.
capacity The initial capacity to reserve for all internal vectors.
helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet(const SparseSet &)=delete
Copy operations are deleted to prevent accidental duplication.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet.
SparseSet & helios::core::ecs::SparseSet< T, TAllowRemoval >::operator=(const SparseSet &)=delete
Copy assignment is deleted.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet.
helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet(SparseSet &&) noexcept=default
Move constructor.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet.
SparseSet & helios::core::ecs::SparseSet< T, TAllowRemoval >::operator=(SparseSet &&) noexcept=default
Move assignment operator.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::SparseSet.
T * helios::core::ecs::SparseSet< T, TAllowRemoval >::emplace(const EntityId idx, Args &&...args)
Constructs and inserts an element at the given index.
Forwards arguments to construct `T` in-place. Args Constructor argument types. idx The EntityId to associate with the element. args Arguments forwarded to the `T` constructor. Pointer to the inserted element, or `nullptr` if the index is already occupied.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::emplace, helios::core::ecs::Tombstone.
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::emplace.
T * helios::core::ecs::SparseSet< T, TAllowRemoval >::insert(const EntityId idx, T &&obj)
Inserts an element at the given index.
If the sparse array is too small, it is resized to accommodate the index. Empty slots are filled with `Tombstone`. idx The EntityId to associate with the element. obj The element to insert (moved). Pointer to the inserted element, or `nullptr` if the index is already occupied.
References helios::core::ecs::Tombstone.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::remove(const EntityId idx) override
Removes the element at the given index using swap-and-pop.
Uses the swap-and-pop technique for O(1) removal: 1. Move the last element to the position of the removed element 2. Update the sparse array entry for the moved element 3. Pop the last element from dense storage 4. Mark the removed slot as Tombstone If `TAllowRemoval` is false, triggers an assertion failure. idx The EntityId of the element to remove. True if the element was removed, false if not found.
References helios::core::ecs::Tombstone.
T * helios::core::ecs::SparseSet< T, TAllowRemoval >::get(const EntityId idx)
Retrieves the element at the given index.
idx The EntityId to look up. Pointer to the element, or `nullptr` if not found.
References helios::core::ecs::Tombstone.
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::raw.
const T * helios::core::ecs::SparseSet< T, TAllowRemoval >::get(const EntityId idx) const
Retrieves the element at the given index.
idx The EntityId to look up. Const pointer to the element, or `nullptr` if not found.
References helios::core::ecs::Tombstone.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::contains(const EntityId idx) const override
Checks whether an element is registered for the specified EntityId.
idx The EntityId to test. True if this sparse set contains the EntityId.
References helios::core::ecs::Tombstone.
void * helios::core::ecs::SparseSet< T, TAllowRemoval >::raw(const EntityId id) override
Returns a raw void pointer to the element at the given index.
id The EntityId to look up. Raw pointer to the element, or `nullptr` if not found.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::get.
helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator()=default
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==.
helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator(DataIt dataIt, IdIt idIt)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_.
reference helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator*() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_.
pointer helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator->() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_.
EntityId helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==(const Iterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=(const Iterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
Iterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++(int)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
Iterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++()
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator()=default
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==.
helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator(DataIt dataIt, IdIt idIt)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.
reference helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator*() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
pointer helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator->() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
EntityId helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==(const ConstIterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=(const ConstIterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
ConstIterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++(int)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator.
ConstIterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++()
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.
Iterator helios::core::ecs::SparseSet< T, TAllowRemoval >::begin()
Returns an iterator to the beginning of the dense storage.
Iterator pointing to the first element.
Iterator helios::core::ecs::SparseSet< T, TAllowRemoval >::end()
Returns an iterator to the end of the dense storage.
Iterator pointing past the last element.
ConstIterator helios::core::ecs::SparseSet< T, TAllowRemoval >::begin() const
Returns a const iterator to the beginning of the dense storage.
ConstIterator pointing to the first element.
ConstIterator helios::core::ecs::SparseSet< T, TAllowRemoval >::end() const
Returns a const iterator to the end of the dense storage.
ConstIterator pointing past the last element.