helios.engine.mechanics.lifecycle.components.DelayedComponentEnabler
float helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DeferredComponent::delta
Remaining time in seconds until activation.
helios::engine::core::data::ComponentTypeId helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DeferredComponent::componentTypeId
Type identifier of the deferred component.
std::vector<DeferredComponent> helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::deferredComponents_
List of components pending delayed activation.
helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler()=default
Default constructor.
Referenced by helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler, helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler, helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::operator=, helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::operator=.
helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler(const DelayedComponentEnabler &other)
Copy constructor for cloning during spawn.
other The source component to copy from.
References helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler.
DelayedComponentEnabler & helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::operator=(const DelayedComponentEnabler &)=default
References helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler.
helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler(DelayedComponentEnabler &&) noexcept=default
References helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler.
DelayedComponentEnabler & helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::operator=(DelayedComponentEnabler &&) noexcept=default
References helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::DelayedComponentEnabler.
std::span< DeferredComponent > helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::deferredComponents() noexcept
Returns a view of all currently deferred components.
Span of DeferredComponent entries with remaining delays.
References helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::deferredComponents.
Referenced by helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::deferredComponents.
void helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::sync(std::span< helios::engine::core::data::ComponentTypeId > removeList)
Removes activated components from the deferred list.
Called by the system after enabling components to clean up entries that have completed their delay period. removeList Component type IDs to remove from tracking.
void helios::engine::mechanics::lifecycle::components::DelayedComponentEnabler::defer(helios::engine::ecs::GameObject gameObject, helios::engine::core::data::ComponentTypeId componentTypeId, const float delta)
Schedules a component for delayed activation.
The specified component is immediately disabled and added to the deferred list. If the component is already deferred, its delay is updated to the new value. componentTypeId Type identifier of the component to defer. delta Delay in seconds before activation. Asserts if delta <= 0 or if the component does not exist on the entity.
References helios::engine::ecs::GameObject::disableComponent, helios::engine::ecs::GameObject::has.