helios.engine.core.data.SpawnRuleId
uint32_t helios::engine::core::data::SpawnRuleId::id_
The underlying numeric identifier.
helios::engine::core::data::SpawnRuleId::SpawnRuleId(uint32_t id) noexcept
Constructs a SpawnRuleId with the given numeric value.
id The numeric identifier value.
Referenced by helios::engine::core::data::SpawnRuleId::operator<, helios::engine::core::data::SpawnRuleId::operator==, helios::engine::core::data::SpawnRuleId::operator>.
uint32_t helios::engine::core::data::SpawnRuleId::value() const noexcept
Returns the underlying numeric value.
The raw identifier value.
bool helios::engine::core::data::SpawnRuleId::operator<(const SpawnRuleId &other) const noexcept
Less-than comparison for ordered containers.
other The SpawnRuleId to compare against. True if this ID is less than the other.
References helios::engine::core::data::SpawnRuleId::SpawnRuleId.
bool helios::engine::core::data::SpawnRuleId::operator>(const SpawnRuleId &other) const noexcept
Greater-than comparison for ordered containers.
other The SpawnRuleId to compare against. True if this ID is greater than the other.
References helios::engine::core::data::SpawnRuleId::SpawnRuleId.
std::size_t std::hash< helios::engine::core::data::SpawnRuleId >::operator()(const helios::engine::core::data::SpawnRuleId &id) const noexcept
Computes the hash value for a SpawnRuleId.
id The SpawnRuleId to hash. The hash value based on the underlying numeric identifier.