helios.engine.modules.spatial.transform.components.TranslationStateComponent
helios::math::vec3f helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation_
The current translation vector.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent()=default
Default constructor.
Referenced by helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent(const TranslationStateComponent &other)
Copy constructor.
other The component to copy from.
References helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent.
helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent(const helios::math::vec3f translation)
Creates a new TranslationStateComponent with the specified translation vector.
translation The translation vector this component should be initialized with.
References helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::onAcquire() noexcept override
Resets the translation vector to 0-vector when acquired.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::onRelease() noexcept override
Resets the translation vector to 0-vector when released.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::setTranslation(helios::math::vec3f translation)
Sets the absolute translation.
translation The new position vector.
References helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation.
void helios::engine::modules::spatial::transform::components::TranslationStateComponent::translateBy(helios::math::vec3f translation)
Translates the current position by a delta vector.
translation The vector to add to the current position.
References helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation.
helios::math::vec3f helios::engine::modules::spatial::transform::components::TranslationStateComponent::translation() const noexcept
Returns the current translation vector.
The current position.
Referenced by helios::engine::modules::spatial::transform::components::TranslationStateComponent::setTranslation, helios::engine::modules::spatial::transform::components::TranslationStateComponent::translateBy, helios::engine::modules::spatial::transform::components::TranslationStateComponent::TranslationStateComponent, helios::engine::modules::ai::systems::ChaseSystem::update.