helios.engine.mechanics.match.types.MatchStateTransitionRule
using helios::engine::mechanics::match::types::GuardCallback = bool(*)( helios::engine::runtime::world::UpdateContext&, MatchStateTransitionRequest )
Function pointer type for transition guard callbacks.
updateContext The current update context. request The transition request being evaluated. True if the transition should proceed.
MatchState helios::engine::mechanics::match::types::MatchStateTransitionRule::from_
MatchStateTransitionId helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionId_
MatchState helios::engine::mechanics::match::types::MatchStateTransitionRule::to_
MatchStateTransitionType helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionType_
GuardCallback helios::engine::mechanics::match::types::MatchStateTransitionRule::guard_
helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule(const MatchState from, const MatchStateTransitionId transitionId, const MatchState to, const MatchStateTransitionType transitionType, GuardCallback guard=nullptr)
Constructs a transition rule.
from The source state. transitionId The transition identifier. to The target state. transitionType The type of transition. guard Optional guard callback.
References helios::engine::mechanics::match::types::MatchStateTransitionRule::from, helios::engine::mechanics::match::types::MatchStateTransitionRule::guard, helios::engine::mechanics::match::types::MatchStateTransitionRule::to, helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionId, helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionType.
MatchState helios::engine::mechanics::match::types::MatchStateTransitionRule::from() const noexcept
Returns the source state.
Referenced by helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule.
MatchState helios::engine::mechanics::match::types::MatchStateTransitionRule::to() const noexcept
Returns the target state.
Referenced by helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule.
MatchStateTransitionType helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionType() const noexcept
Returns the transition type.
Referenced by helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule.
MatchStateTransitionId helios::engine::mechanics::match::types::MatchStateTransitionRule::transitionId() const noexcept
Returns the transition identifier.
Referenced by helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule.
GuardCallback helios::engine::mechanics::match::types::MatchStateTransitionRule::guard() const noexcept
Returns the guard callback, or nullptr if none.
Referenced by helios::engine::mechanics::match::types::MatchStateTransitionRule::MatchStateTransitionRule.