helios.core.ecs.Entity
using helios::core::ecs::Entity< THandle, TEntityManager >::ComponentTypeId_type = ComponentTypeId<THandle>
using helios::core::ecs::Entity< THandle, TEntityManager >::ComponentOpsRegistry_type = ComponentOpsRegistry<THandle>
using helios::core::ecs::Entity< THandle, TEntityManager >::HierarchyComponent_type = components::HierarchyComponent<THandle>
THandle helios::core::ecs::Entity< THandle, TEntityManager >::entityHandle_
The underlying entity identifier.
TEntityManager* helios::core::ecs::Entity< THandle, TEntityManager >::entityManager_
Non-owning pointer to the EntityManager.
helios::core::ecs::Entity< THandle, TEntityManager >::Entity(const THandle entityHandle, TEntityManager *entityManager) noexcept
Constructs a Entity wrapper.
entityHandle The entity handle to wrap. entityManager Pointer to the EntityManager. Must not be null.
std::generator< ComponentTypeId_type > helios::core::ecs::Entity< THandle, TEntityManager >::componentTypeIds() const
Returns a generator over all component type IDs attached to this entity.
Generator yielding ComponentTypeId for each attached component.
Referenced by helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::onAcquire, helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::onRelease, helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::setActive.
THandle helios::core::ecs::Entity< THandle, TEntityManager >::handle() noexcept
Returns the underlying entity handle.
The EntityHandle for this Entity.
THandle helios::core::ecs::Entity< THandle, TEntityManager >::handle() const noexcept
Returns the underlying entity handle (const).
The EntityHandle for this Entity.
T & helios::core::ecs::Entity< THandle, TEntityManager >::add(Args &&...args)
Constructs and attaches a component to this entity.
If the entity is active, calls `onActivate()` on the new component. If inactive, calls `onDeactivate()`. T The component type to add. Args Constructor argument types. args Arguments forwarded to the component constructor. Reference to the newly created component.
Referenced by helios::core::ecs::Entity< typename TEntityManager::Handle_type, TEntityManager >::getOrAdd.
T & helios::core::ecs::Entity< THandle, TEntityManager >::getOrAdd(Args &&...args)
Returns existing component or creates a new one.
T The component type. Args Constructor argument types. args Arguments forwarded to the constructor if creating. Reference to the existing or newly created component.
bool helios::core::ecs::Entity< THandle, TEntityManager >::remove()
Removes a component from this entity.
T The component type to remove. True if the component was removed, false if not present.
void * helios::core::ecs::Entity< THandle, TEntityManager >::raw(const ComponentTypeId_type typeId)
Returns raw pointer to component by type ID.
typeId The component type identifier. Raw void pointer to the component, or nullptr if not found.
T * helios::core::ecs::Entity< THandle, TEntityManager >::get()
Returns pointer to a component.
T The component type. Pointer to the component, or nullptr if not attached.
const T * helios::core::ecs::Entity< THandle, TEntityManager >::get() const
Returns const pointer to a component.
T The component type. Const pointer to the component, or nullptr if not attached.
bool helios::core::ecs::Entity< THandle, TEntityManager >::has() const noexcept
Checks if this entity has a specific component type.
T The component type to check. True if the component is attached, false otherwise.
bool helios::core::ecs::Entity< THandle, TEntityManager >::has(ComponentTypeId_type typeId) const noexcept
Checks if this entity has a component by type ID.
typeId The component type identifier. True if the component is attached, false otherwise.
void helios::core::ecs::Entity< THandle, TEntityManager >::enableComponent(const ComponentTypeId_type typeId)
Enables a specific component by type ID.
typeId The component type identifier.
void helios::core::ecs::Entity< THandle, TEntityManager >::disableComponent(const ComponentTypeId_type typeId)
Disables a specific component by type ID.
typeId The component type identifier.
void helios::core::ecs::Entity< THandle, TEntityManager >::setActive(const bool active)
Sets the activation state of this Entity.
When deactivated: An `Inactive` tag component is added The `Active` tag component is removed `onDeactivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation When activated: The `Inactive` tag component is removed An `Active` tag component is added `onActivate()` is called on components that support it If a `HierarchyComponent` is present, it is marked dirty for propagation Does **not** call `enable()`/`disable()` on components. active True to activate, false to deactivate. HierarchyComponent_type HierarchyPropagationSystem
bool helios::core::ecs::Entity< THandle, TEntityManager >::isActive() const
Returns whether this Entity is active.
True if the entity has the Active tag component.
void helios::core::ecs::Entity< THandle, TEntityManager >::onRelease()
Notifies all components that the entity is being released to a pool.
Iterates through all attached components and calls `onRelease()` on those that implement it.
void helios::core::ecs::Entity< THandle, TEntityManager >::onAcquire()
Notifies all components that the entity is being acquired from a pool.
Iterates through all attached components and calls `onAcquire()` on those that implement it.