helios.util.log.LogManager
bool helios::util::log::LogManager::loggingEnabled_
Flag indicating whether log output should be globally enabled or disabled.
std::unordered_set<std::string> helios::util::log::LogManager::enabledSinks_
Set of currently enabled sink type identifiers.
std::vector<std::shared_ptr<LogSink> > helios::util::log::LogManager::registeredSinks_
Registered sinks (all available sinks, regardless of enabled state).
std::unordered_map<std::string, std::unique_ptr<Logger> > helios::util::log::LogManager::loggers_
Unordered map holding unique pointers to the loggers managed by this class, guaranteed to be not null.
const std::unique_ptr<Logger> helios::util::log::LogManager::defaultLogger_
Default logger if a logger for a specific scope was not found.
std::mutex helios::util::log::LogManager::mapMutex_
Mutex providing mutually exclusive access to the loggers map.
std::mutex helios::util::log::LogManager::sinkMutex_
Mutex for sink access.
helios::util::log::LogManager::LogManager()
Creates the LogManager and registers an unscoped default logger.
void helios::util::log::LogManager::updateLoggerSinks()
Reconfigures all logger sinks based on currently enabled sinks.
Called internally after sink enable/disable changes.
static const Logger & helios::util::log::LogManager::loggerForScope(const std::string &scope) noexcept
Convenience accessor to obtain a logger for a textual scope via the singleton.
This static helper forwards to `LogManager::getInstance().logger(scope)` and returns a reference to the logger registered for the given scope. scope The textual scope name of the requested logger. The logger registered with the scope, or the default logger if none was found.
References helios::util::log::LogManager::getInstance, helios::util::log::LogManager::registerLogger.
helios::util::log::LogManager::~LogManager()=default
helios::util::log::LogManager::LogManager(const LogManager &)=delete
Enforce singleton (see Meyer's Singleton) https://en.wikipedia.org/wiki/Singleton_pattern
LogManager & helios::util::log::LogManager::operator=(const LogManager &)=delete
static LogManager & helios::util::log::LogManager::getInstance() noexcept
Returns the LogManager singleton instance.
Reference to the global LogManager instance.
Referenced by helios::util::log::LogManager::loggerForScope, helios::util::log::LogManager::setScopeFilter.
const Logger & helios::util::log::LogManager::logger() const noexcept
Returns a const reference to the default logger managed with this LogManager.
The default Logger instance.
Referenced by helios::util::log::LogManager::registerLogger.
const Logger & helios::util::log::LogManager::logger(const std::string &scope) const noexcept
Returns a const reference to the logger instance for the specified scope.
Will fall back to the default logger if the scope was not registered yet. This method is thread safe for map look-ups. scope The textual scope name of the requested logger. The logger registered with the scope, or the default logger if none was found.
Logger & helios::util::log::LogManager::registerLogger(const std::string &scope) noexcept
Registers a new logger with this manager.
This method is thread safe for map modifications. scope The scope requested for the logger to create. The logger registered with the scope, or the logger already registered with the LogManager under the given scope.
References helios::util::log::LogManager::logger.
Referenced by helios::util::log::LogManager::loggerForScope, helios::util::log::LogManager::setScopeFilter.
void helios::util::log::LogManager::enableLogging(bool enable) noexcept
Enables or disables all log output of the Loggers registered with this LogManager.
enable True to enable log output with the registered loggers, otherwise false.
void helios::util::log::LogManager::setScopeFilter(const std::string &scope) noexcept
Sets the filter scope for the logger.
Will do nothing if logging is not enabled. If the logger for the scope does not exist, it will get implicitly created. scope The scope to filter. Only log messages with this scope will be logged.
References helios::util::log::LogManager::getInstance, helios::util::log::LogManager::registerLogger.
void helios::util::log::LogManager::registerSink(std::shared_ptr< LogSink > sink)
Registers a sink and enables it by default.
The sink is added to the pool and immediately enabled for output. sink The sink to register.
References helios::util::log::LogManager::registerSink.
Referenced by helios::util::log::LogManager::registerSink.
void helios::util::log::LogManager::registerSink(std::shared_ptr< LogSink > sink, bool enabled)
Registers a sink with optional auto-enable.
sink The sink to register. enabled Whether to enable the sink immediately (default: true).
void helios::util::log::LogManager::enableSink(SinkTypeId typeId)
Enables a sink by its type identifier.
If a sink with the given typeId is registered, it will be enabled. If no sink with that typeId is registered, this call has no effect. typeId The unique type identifier of the sink (e.g., "console", "imgui").
void helios::util::log::LogManager::enableSink(std::shared_ptr< LogSink > sink)
Enables a sink, registering it first if necessary.
If the sink is not yet registered, it will be added to the pool. The sink is then enabled for output. sink The sink instance to enable (and register if needed).
void helios::util::log::LogManager::disableSink(SinkTypeId typeId)
Disables a sink by its type identifier.
typeId The unique type identifier of the sink.
Referenced by helios::util::log::LogManager::disableSink.
void helios::util::log::LogManager::disableSink(std::shared_ptr< LogSink > sink)
Disables a sink by instance.
sink The sink instance to disable.
References helios::util::log::LogManager::disableSink.
bool helios::util::log::LogManager::isSinkEnabled(SinkTypeId typeId) const noexcept
Checks if a sink with the given type identifier is currently enabled.
typeId The unique type identifier of the sink. True if the sink is enabled.
void helios::util::log::LogManager::enableAllSinks()
Enables all registered sinks.
void helios::util::log::LogManager::disableAllSinks()
Disables all sinks.