helios.core.types.StrongId
StrongId_t helios::core::types::StrongId< Tag >::id_
The underlying ID value.
helios::core::types::StrongId< Tag >::StrongId(const std::string_view str) noexcept
Constructs from a compile-time string.
Uses FNV-1a hashing to convert the string to an ID. str The string to hash.
Referenced by helios::core::types::StrongId< Tag >::operator<, helios::core::types::StrongId< Tag >::operator==, helios::core::types::StrongId< Tag >::operator>, helios::core::types::StrongId< Tag >::StrongId.
helios::core::types::StrongId< Tag >::StrongId(const StrongId_t id) noexcept
Constructs from a raw underlying value.
id The raw ID value.
helios::core::types::StrongId< Tag >::StrongId(no_init_t)
Constructs an uninitialized ID.
no_init_t Tag type indicating no initialization.
helios::core::types::StrongId< Tag >::StrongId()
Default constructor creating an uninitialized ID.
References helios::core::types::no_init, helios::core::types::StrongId< Tag >::StrongId.
bool helios::core::types::StrongId< Tag >::isValid() const noexcept
Returns true if the strong id is considered valid.
True if the StrongId is considered valid, else false.
StrongId_t helios::core::types::StrongId< Tag >::value() const noexcept
Returns the underlying ID value.
The raw underlying value.
helios::core::types::StrongId< Tag >::operator bool() const noexcept
Checks if the ID is valid (non-zero).
True if the ID is non-zero.
bool helios::core::types::StrongId< Tag >::operator<(const StrongId &other) const noexcept
Less-than comparison for ordering.
other The other ID to compare. True if this ID is less than the other.
References helios::core::types::StrongId< Tag >::StrongId.
bool helios::core::types::StrongId< Tag >::operator>(const StrongId &other) const noexcept
Greater-than comparison for ordering.
other The other ID to compare. True if this ID is greater than the other.
References helios::core::types::StrongId< Tag >::StrongId.
helios::core::types::StrongId_t std::hash< helios::core::types::StrongId< Tag > >::operator()(const helios::core::types::StrongId< Tag > &id) const noexcept