helios.engine.runtime.world.Manager
T helios::engine::runtime::world::Manager::Model< T >::manager_
std::unique_ptr<Concept> helios::engine::runtime::world::Manager::pimpl_
virtual helios::engine::runtime::world::Manager::Concept::~Concept()=default
virtual void helios::engine::runtime::world::Manager::Concept::flush(UpdateContext &updateContext) noexcept=0
virtual void helios::engine::runtime::world::Manager::Concept::init(GameWorld &gameWorld) noexcept=0
virtual void helios::engine::runtime::world::Manager::Concept::reset() noexcept=0
virtual void * helios::engine::runtime::world::Manager::Concept::underlying() noexcept=0
virtual const void * helios::engine::runtime::world::Manager::Concept::underlying() const noexcept=0
helios::engine::runtime::world::Manager::Model< T >::Model(T sys)
void helios::engine::runtime::world::Manager::Model< T >::flush(UpdateContext &updateContext) noexcept override
void helios::engine::runtime::world::Manager::Model< T >::init(GameWorld &gameWorld) noexcept override
void helios::engine::runtime::world::Manager::Model< T >::reset() noexcept override
void * helios::engine::runtime::world::Manager::Model< T >::underlying() noexcept override
const void * helios::engine::runtime::world::Manager::Model< T >::underlying() const noexcept override
helios::engine::runtime::world::Manager::Manager()=default
Default constructor creating an empty Manager.
Referenced by helios::engine::runtime::world::Manager::Manager, helios::engine::runtime::world::Manager::Manager, helios::engine::runtime::world::Manager::operator=, helios::engine::runtime::world::Manager::operator=.
helios::engine::runtime::world::Manager::Manager(T manager)
Wraps a concrete manager in a type-erased Manager.
T The concrete manager type, must satisfy `IsManagerLike<T>`. manager The concrete manager instance to wrap (moved into internal storage).
helios::engine::runtime::world::Manager::Manager(const Manager &)=delete
References helios::engine::runtime::world::Manager::Manager.
Manager & helios::engine::runtime::world::Manager::operator=(const Manager &)=delete
References helios::engine::runtime::world::Manager::Manager.
Manager & helios::engine::runtime::world::Manager::operator=(Manager &&)=default
References helios::engine::runtime::world::Manager::Manager.
helios::engine::runtime::world::Manager::Manager(Manager &&) noexcept=default
References helios::engine::runtime::world::Manager::Manager.
void helios::engine::runtime::world::Manager::flush(UpdateContext &updateContext) noexcept
Delegates to the wrapped manager's `flush()` method.
Called by the GameLoop at each commit point after CommandBuffers have been flushed. Managers process their accumulated requests in batch. updateContext The current frame's update context. Manager must be initialized (pimpl_ != nullptr).
References helios::engine::runtime::world::Manager::flush.
Referenced by helios::engine::runtime::world::Manager::flush.
void helios::engine::runtime::world::Manager::init(GameWorld &gameWorld) noexcept
Delegates to the wrapped manager's `init()` method, if present.
If the concrete type satisfies `HasInit<T>`, its `init()` is called. Otherwise this is a no-op. Typically used by managers to register their TypedCommandHandlers with the GameWorld. gameWorld The GameWorld for one-time initialization. Manager must be initialized (pimpl_ != nullptr).
void helios::engine::runtime::world::Manager::reset() noexcept
Delegates to the wrapped manager's `reset()` method, if present.
If the concrete type satisfies `HasReset<T>`, its `reset()` is called. Otherwise this is a no-op. Used during level transitions or game restarts to clear accumulated state. Manager must be initialized (pimpl_ != nullptr).
void * helios::engine::runtime::world::Manager::underlying() noexcept
Returns a type-erased pointer to the wrapped manager instance.
Pointer to the underlying concrete manager. Manager must be initialized (pimpl_ != nullptr).
const void * helios::engine::runtime::world::Manager::underlying() const noexcept
Returns a type-erased pointer to the wrapped manager instance.
Pointer to the underlying concrete manager. Manager must be initialized (pimpl_ != nullptr).