helios.engine.mechanics.damage.components.LastDamageComponent
helios::engine::common::types::DamageContext helios::engine::mechanics::damage::components::LastDamageComponent::damageContext_
Context of the most recent damage received.
bool helios::engine::mechanics::damage::components::LastDamageComponent::isEnabled_
Whether this component is enabled.
bool helios::engine::mechanics::damage::components::LastDamageComponent::isEnabled() const noexcept
Checks whether this component is enabled.
True if enabled, false otherwise.
void helios::engine::mechanics::damage::components::LastDamageComponent::enable() noexcept
Enables this component.
void helios::engine::mechanics::damage::components::LastDamageComponent::disable() noexcept
Disables this component.
helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent()=default
Referenced by helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent, helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent, helios::engine::mechanics::damage::components::LastDamageComponent::operator=, helios::engine::mechanics::damage::components::LastDamageComponent::operator=.
helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent(const LastDamageComponent &other)=default
Copy constructor (creates empty state).
other The component to copy from (state is not copied).
References helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent.
LastDamageComponent & helios::engine::mechanics::damage::components::LastDamageComponent::operator=(const LastDamageComponent &)=default
References helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent.
helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent(LastDamageComponent &&) noexcept=default
References helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent.
LastDamageComponent & helios::engine::mechanics::damage::components::LastDamageComponent::operator=(LastDamageComponent &&) noexcept=default
References helios::engine::mechanics::damage::components::LastDamageComponent::LastDamageComponent.
void helios::engine::mechanics::damage::components::LastDamageComponent::setDamageContext(const DamageContext &damageContext) noexcept
Sets the last damage context.
damageContext The damage context to store.
References helios::engine::mechanics::damage::components::LastDamageComponent::damageContext, helios::engine::mechanics::damage::components::LastDamageComponent::setDamageContext.
Referenced by helios::engine::mechanics::damage::components::LastDamageComponent::setDamageContext.
DamageContext helios::engine::mechanics::damage::components::LastDamageComponent::damageContext() const noexcept
Returns the last damage context.
The stored AttackContext.
Referenced by helios::engine::mechanics::damage::components::LastDamageComponent::setDamageContext.
void helios::engine::mechanics::damage::components::LastDamageComponent::reset()
Resets the component to its initial state.
Referenced by helios::engine::mechanics::damage::components::LastDamageComponent::onAcquire, helios::engine::mechanics::damage::components::LastDamageComponent::onRelease.
void helios::engine::mechanics::damage::components::LastDamageComponent::onAcquire() noexcept
Called when this entity is acquired from a pool.
Resets the damage context to ensure no stale data.
References helios::engine::mechanics::damage::components::LastDamageComponent::reset.
void helios::engine::mechanics::damage::components::LastDamageComponent::onRelease() noexcept
Called when this entity is released back to a pool.
Resets the damage context to ensure no stale data.
References helios::engine::mechanics::damage::components::LastDamageComponent::reset.