helios.engine.modules.scene.types.SceneToViewportMap
std::vector<Scene*> helios::engine::modules::scene::types::SceneToViewportMap::scenes_
All registered scenes.
std::vector<Viewport*> helios::engine::modules::scene::types::SceneToViewportMap::viewports_
All registered viewports.
std::unordered_map<SceneId, std::vector<ViewportId> > helios::engine::modules::scene::types::SceneToViewportMap::sceneIdsToViewportIds_
Maps scene IDs to their associated viewport IDs.
std::unordered_map<SceneId, std::vector<Viewport*> > helios::engine::modules::scene::types::SceneToViewportMap::viewportMap_
Cached mapping from scene IDs to viewport pointers.
bool helios::engine::modules::scene::types::SceneToViewportMap::needsUpdate_
Flag indicating the cache needs rebuilding.
helios::engine::modules::scene::types::SceneToViewportMap::SceneToViewportMap()=default
Default constructor.
void helios::engine::modules::scene::types::SceneToViewportMap::updateCache() const
Rebuilds the internal cache if modifications were made.
Called lazily by query methods. Rebuilds the viewportMap_ from the scene-to-viewport-ID mappings.
References helios::engine::modules::scene::types::SceneToViewportMap::viewport.
Referenced by helios::engine::modules::scene::types::SceneToViewportMap::scene, helios::engine::modules::scene::types::SceneToViewportMap::viewport, helios::engine::modules::scene::types::SceneToViewportMap::viewports.
void helios::engine::modules::scene::types::SceneToViewportMap::add(Scene *scene, Viewport *viewport)
Registers a scene-viewport association.
Adds the viewport to the scene's viewport list. A scene can have multiple viewports, but each viewport can only be added once. scene Pointer to the scene. Must not be null. viewport Pointer to the viewport. Must not be null or already registered.
References helios::engine::modules::scene::types::SceneToViewportMap::hasScene, helios::engine::modules::scene::types::SceneToViewportMap::scene, helios::engine::modules::scene::types::SceneToViewportMap::viewport.
Scene * helios::engine::modules::scene::types::SceneToViewportMap::scene(ViewportId viewportId) const noexcept
Returns the scene associated with a viewport ID.
viewportId The viewport identifier to look up. Pointer to the scene, or nullptr if not found.
References helios::engine::modules::scene::types::SceneToViewportMap::scene, helios::engine::modules::scene::types::SceneToViewportMap::updateCache.
Referenced by helios::engine::modules::scene::types::SceneToViewportMap::add, helios::engine::modules::scene::types::SceneToViewportMap::scene.
std::span< Viewport * > helios::engine::modules::scene::types::SceneToViewportMap::viewports(SceneId sceneId) const noexcept
Returns all viewports associated with a scene.
sceneId The scene identifier to look up. Span of viewport pointers, or empty span if not found.
References helios::engine::modules::scene::types::SceneToViewportMap::hasScene, helios::engine::modules::scene::types::SceneToViewportMap::updateCache.
std::span< Scene * > helios::engine::modules::scene::types::SceneToViewportMap::scenes() const noexcept
Returns all registered scenes.
Span of scene pointers.
bool helios::engine::modules::scene::types::SceneToViewportMap::hasScene(const SceneId sceneId) const noexcept
Checks if a scene is registered.
sceneId The scene identifier to check. True if the scene is registered, false otherwise.
Referenced by helios::engine::modules::scene::types::SceneToViewportMap::add, helios::engine::modules::scene::types::SceneToViewportMap::viewport, helios::engine::modules::scene::types::SceneToViewportMap::viewports.
Viewport * helios::engine::modules::scene::types::SceneToViewportMap::viewport(SceneId sceneId, ViewportId viewportId) const noexcept
Returns a specific viewport for a scene.
sceneId The scene identifier. viewportId The viewport identifier. Pointer to the viewport, or nullptr if not found.
References helios::engine::modules::scene::types::SceneToViewportMap::hasScene, helios::engine::modules::scene::types::SceneToViewportMap::updateCache, helios::engine::modules::scene::types::SceneToViewportMap::viewport.
Referenced by helios::engine::modules::scene::types::SceneToViewportMap::add, helios::engine::modules::scene::types::SceneToViewportMap::updateCache, helios::engine::modules::scene::types::SceneToViewportMap::viewport.