helios.core.container.buffer.TypeIndexedDoubleBuffer
std::vector<std::unique_ptr<DoubleBuffer> > helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::buffers_
Type-erased storage for message buffers, indexed by type.
TypeIndexedDoubleBuffer* helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::db_
Non-owning pointer to the parent buffer.
TypeIndexedDoubleBuffer* helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::db_
Non-owning pointer to the parent buffer.
static size_t helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::index()
Returns the buffer index for message type T.
T The message type. The index assigned to type T by the Indexer.
helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::~TypeIndexedDoubleBuffer()=default
Default destructor.
helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::TypeIndexedDoubleBuffer()=default
Default constructor.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::ReadSource, helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::WriteSink.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::push(Args &&... args)
Pushes a message of type T to the write buffer.
T The message type. Args Constructor argument types for T. args Arguments forwarded to T's constructor.
std::span< const T > helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::read() const noexcept
Returns a read-only view of all messages of type T.
Returns messages that were written before the last `swapBuffers()` call. If no messages of type T exist, returns an empty span. T The message type to read. A span over all messages of type T in the read buffer.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::reserve(size_t size)
Pre-allocates capacity for messages of type T.
Call during initialization to avoid allocations during gameplay. T The message type. size The number of messages to reserve capacity for.
ReadWriteDoubleBuffer< T > & helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::getOrCreateBuffer()
Gets or creates the buffer for message type T.
T The message type. Reference to the ReadWriteDoubleBuffer for type T.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::push, helios::core::container::buffer::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::reserve.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::swapBuffers()
Swaps read and write buffers for all message types.
Call once per frame at a consistent point (e.g., end of update phase). After this call, messages pushed in the current frame become readable.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::clearReadBuffers()
Clears all read buffers.
Typically not needed as `swapBuffers()` clears read buffers automatically.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::clearAll.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::clearWriteBuffers()
Clears all write buffers without swapping.
Use to discard messages that were pushed but should not be processed.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< helios::core::data::TypeIndexer< GameLoopEventBusGroup > >::clearAll.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::clearAll()
Clears both read and write buffers for all message types.
Completely resets the buffer state, discarding all messages.
helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::WriteSink(TypeIndexedDoubleBuffer &db) noexcept
Constructs a WriteSink from a TypeIndexedDoubleBuffer reference.
db The buffer to write to. Must remain valid for the lifetime of this sink.
References helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::TypeIndexedDoubleBuffer.
void helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push(Args &&... args) noexcept
Constructs and pushes a message of type E to the buffer.
E The message type. Args Constructor argument types for E. args Arguments forwarded to E's constructor.
References helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::WriteSink::push.
helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::ReadSource(TypeIndexedDoubleBuffer &db) noexcept
Constructs a ReadSource from a TypeIndexedDoubleBuffer reference.
db The buffer to read from. Must remain valid for the lifetime of this source.
References helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::TypeIndexedDoubleBuffer.
std::span< const E > helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::read() const noexcept
Returns a read-only view of messages of type E.
E The message type to read. A span over all messages of type E in the read buffer.
References helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::read.
Referenced by helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::ReadSource::read.
WriteSink helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::writeSink() noexcept
Creates a WriteSink handle for this buffer.
A WriteSink that can push messages to this buffer.
ReadSource helios::core::container::buffer::TypeIndexedDoubleBuffer< Indexer >::readSource() noexcept
Creates a ReadSource handle for this buffer.
A ReadSource that can read messages from this buffer.