helios::core::ecs::SparseSet::Iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::DataIt = typename std::vector<T>::iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::IdIt = typename std::vector<EntityId>::iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::iterator_category = std::forward_iterator_tag
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::value_type = T
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::difference_type = std::ptrdiff_t
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::pointer = T*
using helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::reference = T&
DataIt helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator*, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator->, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==.
IdIt helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::entityId, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++.
helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator()=default
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==.
helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator(DataIt dataIt, IdIt idIt)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_.
reference helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator*() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_.
pointer helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator->() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_.
EntityId helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator==(const Iterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator!=(const Iterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
Iterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++(int)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.
Iterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::operator++()
References helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::idIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::Iterator::Iterator.