helios::engine::core::data::SpawnRuleId
uint32_t helios::engine::core::data::SpawnRuleId::id_
The underlying numeric identifier.
helios::engine::core::data::SpawnRuleId::SpawnRuleId(uint32_t id) noexcept
Constructs a SpawnRuleId with the given numeric value.
id The numeric identifier value.
Referenced by operator<, operator==, operator>.
uint32_t helios::engine::core::data::SpawnRuleId::value() const noexcept
Returns the underlying numeric value.
The raw identifier value.
bool helios::engine::core::data::SpawnRuleId::operator<(const SpawnRuleId &other) const noexcept
Less-than comparison for ordered containers.
other The SpawnRuleId to compare against. True if this ID is less than the other.
References SpawnRuleId.
bool helios::engine::core::data::SpawnRuleId::operator>(const SpawnRuleId &other) const noexcept
Greater-than comparison for ordered containers.
other The SpawnRuleId to compare against. True if this ID is greater than the other.
References SpawnRuleId.
bool operator==(SpawnRuleId, SpawnRuleId) noexcept=default
Default equality comparison.
References SpawnRuleId.