helios::engine::ecs::SparseSet::ConstIterator
using helios::engine::ecs::SparseSet< T >::ConstIterator::DataIt = typename std::vector<T>::const_iterator
using helios::engine::ecs::SparseSet< T >::ConstIterator::IdIt = typename std::vector<EntityId>::const_iterator
using helios::engine::ecs::SparseSet< T >::ConstIterator::iterator_category = std::forward_iterator_tag
using helios::engine::ecs::SparseSet< T >::ConstIterator::value_type = T
using helios::engine::ecs::SparseSet< T >::ConstIterator::difference_type = std::ptrdiff_t
using helios::engine::ecs::SparseSet< T >::ConstIterator::pointer = const T*
using helios::engine::ecs::SparseSet< T >::ConstIterator::reference = const T&
DataIt helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_
Referenced by helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::engine::ecs::SparseSet< T >::ConstIterator::operator!=, helios::engine::ecs::SparseSet< T >::ConstIterator::operator*, helios::engine::ecs::SparseSet< T >::ConstIterator::operator++, helios::engine::ecs::SparseSet< T >::ConstIterator::operator->, helios::engine::ecs::SparseSet< T >::ConstIterator::operator==.
IdIt helios::engine::ecs::SparseSet< T >::ConstIterator::idIt_
Referenced by helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::engine::ecs::SparseSet< T >::ConstIterator::entityId, helios::engine::ecs::SparseSet< T >::ConstIterator::operator++.
helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator()=default
Referenced by helios::engine::ecs::SparseSet< T >::ConstIterator::operator!=, helios::engine::ecs::SparseSet< T >::ConstIterator::operator++, helios::engine::ecs::SparseSet< T >::ConstIterator::operator++, helios::engine::ecs::SparseSet< T >::ConstIterator::operator==.
helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator(DataIt dataIt, IdIt idIt)
References helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_, helios::engine::ecs::SparseSet< T >::ConstIterator::idIt_.
reference helios::engine::ecs::SparseSet< T >::ConstIterator::operator*() const
References helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_.
pointer helios::engine::ecs::SparseSet< T >::ConstIterator::operator->() const
References helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_.
EntityId helios::engine::ecs::SparseSet< T >::ConstIterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::engine::ecs::SparseSet< T >::ConstIterator::idIt_.
bool helios::engine::ecs::SparseSet< T >::ConstIterator::operator==(const ConstIterator &other) const
References helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_.
bool helios::engine::ecs::SparseSet< T >::ConstIterator::operator!=(const ConstIterator &other) const
References helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_.
ConstIterator & helios::engine::ecs::SparseSet< T >::ConstIterator::operator++(int)
References helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator.
ConstIterator & helios::engine::ecs::SparseSet< T >::ConstIterator::operator++()
References helios::engine::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::engine::ecs::SparseSet< T >::ConstIterator::dataIt_, helios::engine::ecs::SparseSet< T >::ConstIterator::idIt_.