helios::core::memory::ErasedUnique
void* helios::core::memory::ErasedUnique::ptr
Raw pointer to the owned object.
Referenced by operator=, reset.
void(* helios::core::memory::ErasedUnique::destroy) (void *) noexcept)(void *) noexcept
Stateless deleter that knows the concrete type.
Referenced by operator=, reset.
helios::core::memory::ErasedUnique::ErasedUnique()=default
Default constructor. Creates an empty (non-owning) instance.
Referenced by ErasedUnique, operator=.
helios::core::memory::ErasedUnique::ErasedUnique(std::unique_ptr< T > p) noexcept
Constructs from a unique_ptr, taking ownership.
Releases the unique_ptr and captures a typed deleter. T The owned type. p The unique_ptr to take ownership from.
helios::core::memory::ErasedUnique::ErasedUnique(ErasedUnique &&obj) noexcept
Move constructor. Transfers ownership.
obj The source instance (nulled after move).
References ErasedUnique.
ErasedUnique & helios::core::memory::ErasedUnique::operator=(ErasedUnique &&obj) noexcept
Move assignment. Transfers ownership after releasing current.
obj The source instance (nulled after move). Reference to this instance.
References destroy, ErasedUnique, ptr, reset.
helios::core::memory::ErasedUnique::~ErasedUnique()
Destructor. Destroys the owned object if present.
References reset.
void helios::core::memory::ErasedUnique::reset() noexcept
Destroys the owned object and resets to empty.
References destroy, ptr.
Referenced by operator=, ~ErasedUnique.