helios::engine::ecs::SparseSet::Iterator
using helios::engine::ecs::SparseSet< T >::Iterator::DataIt = typename std::vector<T>::iterator
using helios::engine::ecs::SparseSet< T >::Iterator::IdIt = typename std::vector<EntityId>::iterator
using helios::engine::ecs::SparseSet< T >::Iterator::iterator_category = std::forward_iterator_tag
using helios::engine::ecs::SparseSet< T >::Iterator::value_type = T
using helios::engine::ecs::SparseSet< T >::Iterator::difference_type = std::ptrdiff_t
using helios::engine::ecs::SparseSet< T >::Iterator::pointer = T*
using helios::engine::ecs::SparseSet< T >::Iterator::reference = T&
DataIt helios::engine::ecs::SparseSet< T >::Iterator::dataIt_
Referenced by helios::engine::ecs::SparseSet< T >::Iterator::Iterator, helios::engine::ecs::SparseSet< T >::Iterator::operator!=, helios::engine::ecs::SparseSet< T >::Iterator::operator*, helios::engine::ecs::SparseSet< T >::Iterator::operator++, helios::engine::ecs::SparseSet< T >::Iterator::operator->, helios::engine::ecs::SparseSet< T >::Iterator::operator==.
IdIt helios::engine::ecs::SparseSet< T >::Iterator::idIt_
Referenced by helios::engine::ecs::SparseSet< T >::Iterator::entityId, helios::engine::ecs::SparseSet< T >::Iterator::Iterator, helios::engine::ecs::SparseSet< T >::Iterator::operator++.
helios::engine::ecs::SparseSet< T >::Iterator::Iterator()=default
Referenced by helios::engine::ecs::SparseSet< T >::Iterator::operator!=, helios::engine::ecs::SparseSet< T >::Iterator::operator++, helios::engine::ecs::SparseSet< T >::Iterator::operator++, helios::engine::ecs::SparseSet< T >::Iterator::operator==.
helios::engine::ecs::SparseSet< T >::Iterator::Iterator(DataIt dataIt, IdIt idIt)
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_, helios::engine::ecs::SparseSet< T >::Iterator::idIt_.
reference helios::engine::ecs::SparseSet< T >::Iterator::operator*() const
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_.
pointer helios::engine::ecs::SparseSet< T >::Iterator::operator->() const
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_.
EntityId helios::engine::ecs::SparseSet< T >::Iterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::engine::ecs::SparseSet< T >::Iterator::idIt_.
bool helios::engine::ecs::SparseSet< T >::Iterator::operator==(const Iterator &other) const
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_, helios::engine::ecs::SparseSet< T >::Iterator::Iterator.
bool helios::engine::ecs::SparseSet< T >::Iterator::operator!=(const Iterator &other) const
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_, helios::engine::ecs::SparseSet< T >::Iterator::Iterator.
Iterator & helios::engine::ecs::SparseSet< T >::Iterator::operator++(int)
References helios::engine::ecs::SparseSet< T >::Iterator::Iterator.
Iterator & helios::engine::ecs::SparseSet< T >::Iterator::operator++()
References helios::engine::ecs::SparseSet< T >::Iterator::dataIt_, helios::engine::ecs::SparseSet< T >::Iterator::idIt_, helios::engine::ecs::SparseSet< T >::Iterator::Iterator.