helios::ecs::SparseSet::Iterator
using helios::ecs::SparseSet< T >::Iterator::DataIt = typename std::vector<T>::iterator
using helios::ecs::SparseSet< T >::Iterator::IdIt = typename std::vector<EntityId>::iterator
using helios::ecs::SparseSet< T >::Iterator::iterator_category = std::forward_iterator_tag
using helios::ecs::SparseSet< T >::Iterator::value_type = T
using helios::ecs::SparseSet< T >::Iterator::difference_type = std::ptrdiff_t
using helios::ecs::SparseSet< T >::Iterator::pointer = T*
using helios::ecs::SparseSet< T >::Iterator::reference = T&
DataIt helios::ecs::SparseSet< T >::Iterator::dataIt_
Iterator into the dense data storage.
Referenced by helios::ecs::SparseSet< T >::Iterator::Iterator, helios::ecs::SparseSet< T >::Iterator::operator!=, helios::ecs::SparseSet< T >::Iterator::operator*, helios::ecs::SparseSet< T >::Iterator::operator++, helios::ecs::SparseSet< T >::Iterator::operator->, helios::ecs::SparseSet< T >::Iterator::operator==.
IdIt helios::ecs::SparseSet< T >::Iterator::idIt_
Iterator into the dense-to-sparse ID mapping.
Referenced by helios::ecs::SparseSet< T >::Iterator::entityId, helios::ecs::SparseSet< T >::Iterator::Iterator, helios::ecs::SparseSet< T >::Iterator::operator++.
helios::ecs::SparseSet< T >::Iterator::Iterator()=default
Referenced by helios::ecs::SparseSet< T >::Iterator::operator!=, helios::ecs::SparseSet< T >::Iterator::operator++, helios::ecs::SparseSet< T >::Iterator::operator++, helios::ecs::SparseSet< T >::Iterator::operator==.
helios::ecs::SparseSet< T >::Iterator::Iterator(DataIt dataIt, IdIt idIt)
References helios::ecs::SparseSet< T >::Iterator::dataIt_, helios::ecs::SparseSet< T >::Iterator::idIt_.
reference helios::ecs::SparseSet< T >::Iterator::operator*() const
References helios::ecs::SparseSet< T >::Iterator::dataIt_.
pointer helios::ecs::SparseSet< T >::Iterator::operator->() const
References helios::ecs::SparseSet< T >::Iterator::dataIt_.
EntityId helios::ecs::SparseSet< T >::Iterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::ecs::SparseSet< T >::Iterator::idIt_.
bool helios::ecs::SparseSet< T >::Iterator::operator==(const Iterator &other) const
References helios::ecs::SparseSet< T >::Iterator::dataIt_, helios::ecs::SparseSet< T >::Iterator::Iterator.
bool helios::ecs::SparseSet< T >::Iterator::operator!=(const Iterator &other) const
References helios::ecs::SparseSet< T >::Iterator::dataIt_, helios::ecs::SparseSet< T >::Iterator::Iterator.
Iterator helios::ecs::SparseSet< T >::Iterator::operator++(int)
References helios::ecs::SparseSet< T >::Iterator::Iterator.
Iterator & helios::ecs::SparseSet< T >::Iterator::operator++()
References helios::ecs::SparseSet< T >::Iterator::dataIt_, helios::ecs::SparseSet< T >::Iterator::idIt_, helios::ecs::SparseSet< T >::Iterator::Iterator.