helios::ecs::SparseSet::ConstIterator
using helios::ecs::SparseSet< T >::ConstIterator::DataIt = typename std::vector<T>::const_iterator
using helios::ecs::SparseSet< T >::ConstIterator::IdIt = typename std::vector<EntityId>::const_iterator
using helios::ecs::SparseSet< T >::ConstIterator::iterator_category = std::forward_iterator_tag
using helios::ecs::SparseSet< T >::ConstIterator::value_type = T
using helios::ecs::SparseSet< T >::ConstIterator::difference_type = std::ptrdiff_t
using helios::ecs::SparseSet< T >::ConstIterator::pointer = const T*
using helios::ecs::SparseSet< T >::ConstIterator::reference = const T&
DataIt helios::ecs::SparseSet< T >::ConstIterator::dataIt_
Const iterator into the dense data storage.
Referenced by helios::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::ecs::SparseSet< T >::ConstIterator::operator!=, helios::ecs::SparseSet< T >::ConstIterator::operator*, helios::ecs::SparseSet< T >::ConstIterator::operator++, helios::ecs::SparseSet< T >::ConstIterator::operator->, helios::ecs::SparseSet< T >::ConstIterator::operator==.
IdIt helios::ecs::SparseSet< T >::ConstIterator::idIt_
Const iterator into the dense-to-sparse ID mapping.
Referenced by helios::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::ecs::SparseSet< T >::ConstIterator::entityId, helios::ecs::SparseSet< T >::ConstIterator::operator++.
helios::ecs::SparseSet< T >::ConstIterator::ConstIterator()=default
Referenced by helios::ecs::SparseSet< T >::ConstIterator::operator!=, helios::ecs::SparseSet< T >::ConstIterator::operator++, helios::ecs::SparseSet< T >::ConstIterator::operator++, helios::ecs::SparseSet< T >::ConstIterator::operator==.
helios::ecs::SparseSet< T >::ConstIterator::ConstIterator(DataIt dataIt, IdIt idIt)
References helios::ecs::SparseSet< T >::ConstIterator::dataIt_, helios::ecs::SparseSet< T >::ConstIterator::idIt_.
reference helios::ecs::SparseSet< T >::ConstIterator::operator*() const
References helios::ecs::SparseSet< T >::ConstIterator::dataIt_.
pointer helios::ecs::SparseSet< T >::ConstIterator::operator->() const
References helios::ecs::SparseSet< T >::ConstIterator::dataIt_.
EntityId helios::ecs::SparseSet< T >::ConstIterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::ecs::SparseSet< T >::ConstIterator::idIt_.
bool helios::ecs::SparseSet< T >::ConstIterator::operator==(const ConstIterator &other) const
References helios::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::ecs::SparseSet< T >::ConstIterator::dataIt_.
bool helios::ecs::SparseSet< T >::ConstIterator::operator!=(const ConstIterator &other) const
References helios::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::ecs::SparseSet< T >::ConstIterator::dataIt_.
ConstIterator helios::ecs::SparseSet< T >::ConstIterator::operator++(int)
References helios::ecs::SparseSet< T >::ConstIterator::ConstIterator.
ConstIterator & helios::ecs::SparseSet< T >::ConstIterator::operator++()
References helios::ecs::SparseSet< T >::ConstIterator::ConstIterator, helios::ecs::SparseSet< T >::ConstIterator::dataIt_, helios::ecs::SparseSet< T >::ConstIterator::idIt_.