helios::math::aabb
helios::math::vec3<T> helios::math::aabb< T >::min_
Minimum corner point of the bounding box.
Contains the smallest x, y, and z coordinates across all points within the AABB.
helios::math::vec3<T> helios::math::aabb< T >::max_
Maximum corner point of the bounding box.
Contains the largest x, y, and z coordinates across all points within the AABB.
helios::math::aabb< T >::aabb() noexcept
Constructs an empty AABB with inverted min/max values.
The AABB is initialized with min set to the maximum representable value and max set to the minimum representable value. This allows the first `add()` call to properly establish the initial bounds.
Referenced by helios::math::aabb< float >::applyTransform.
helios::math::aabb< T >::aabb(const T minX, const T minY, const T minZ, const T maxX, const T maxY, const T maxZ) noexcept
Constructs an AABB from individual component values.
minX Minimum X coordinate. minY Minimum Y coordinate. minZ Minimum Z coordinate. maxX Maximum X coordinate. maxY Maximum Y coordinate. maxZ Maximum Z coordinate.
helios::math::aabb< T >::aabb(const helios::math::vec3< T > min, const helios::math::vec3< T > max) noexcept
Constructs an AABB from two corner points.
min The minimum corner point (smallest x, y, z). max The maximum corner point (largest x, y, z).
const helios::math::vec3< T > & helios::math::aabb< T >::min() const noexcept
Returns the minimum corner point of the AABB.
Const reference to the minimum corner point.
Referenced by helios::engine::runtime::spawn::behavior::placements::AxisSpawnPlacer::getPosition, helios::engine::runtime::spawn::behavior::placements::ColumnSpawnPlacer::getPosition, helios::engine::runtime::spawn::behavior::placements::RandomSpawnPlacer::getPosition, helios::math::operator*, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::worldBoundsToGridBounds.
const helios::math::vec3< T > & helios::math::aabb< T >::max() const noexcept
Returns the maximum corner point of the AABB.
Const reference to the maximum corner point.
Referenced by helios::engine::runtime::spawn::behavior::placements::AxisSpawnPlacer::getPosition, helios::engine::runtime::spawn::behavior::placements::ColumnSpawnPlacer::getPosition, helios::engine::runtime::spawn::behavior::placements::RandomSpawnPlacer::getPosition, helios::math::operator*, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::updateCollisionCandidate, helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::worldBoundsToGridBounds.
helios::math::vec3< T > helios::math::aabb< T >::center() const noexcept
Computes the center point of the AABB.
The center point, calculated as `(min + max) / 2`.
helios::math::vec3< T > helios::math::aabb< T >::size() const noexcept
Computes the size of the AABB over all axes.
A vector representing the width, height, and depth of the AABB.
Referenced by helios::engine::runtime::spawn::behavior::placements::AxisSpawnPlacer::getPosition, helios::engine::runtime::spawn::behavior::placements::ColumnSpawnPlacer::getPosition.
bool helios::math::aabb< T >::contains(const helios::math::aabb< T > &box) const noexcept
Checks if this AABB fully contains another AABB.
Tests whether all corners of the specified bounding box lie within the bounds of this AABB. Both minimum and maximum corners must be contained. box The AABB to test for containment. True if the specified box is fully contained within this AABB, false otherwise.
Referenced by helios::engine::runtime::spawn::behavior::placements::AxisSpawnPlacer::getPosition.
bool helios::math::aabb< T >::contains(const helios::math::vec3< T > &point) const noexcept
Checks if this AABB fully contains the specified point. point The vec3 to test for containment. True if the specified point is fully contained within this AABB, otherwise false.
bool helios::math::aabb< T >::intersects(const helios::math::aabb< T > &box) const noexcept
Checks if this AABB intersects or touches another AABB.
box The AABB to test for intersection. True if the specified box intersects this AABB, false otherwise.
Referenced by helios::engine::modules::physics::collision::systems::GridCollisionDetectionSystem::solveCell.
helios::math::aabb< T > helios::math::aabb< T >::translate(const helios::math::vec3< T > &v) const noexcept
Translates the AABB by a given vector.
Creates a new AABB by adding the components of the given translation vector to the minimum and maximum corner points of the current AABB. v The translation vector to apply to the AABB. A new AABB translated by the given vector.
Referenced by helios::engine::runtime::spawn::behavior::placements::AxisSpawnPlacer::getPosition, helios::math::operator+.
void helios::math::aabb< T >::add(const helios::math::vec3< T > &point) noexcept
Expands the AABB to include a given point.
Updates the minimum and maximum bounds to ensure the specified point lies within the AABB. Each component is compared independently: If a component of the point is smaller than the current minimum, the minimum is updated. If a component of the point is larger than the current maximum, the maximum is updated. point The 3D point to include in the bounding box.
aabb< T > helios::math::aabb< T >::applyTransform(const mat4< T > &mat) const noexcept
Transforms the AABB by a 4x4 transformation matrix.
Applies a transformation matrix to the AABB and returns a new axis-aligned bounding box that fully contains the transformed original. This method preserves the axis-aligned property by computing new min/max bounds from the transformed corners. The algorithm efficiently transforms only the min/max corners instead of all 8 vertices, using Arvo's optimization technique from Graphics Gems. mat The 4x4 transformation matrix to apply. A new AABB that fully contains the transformed bounding box. [Gla95, pp. 548-550] "Transforming Axis-Aligned Bounding Boxes" by James Arvo