helios::core::ecs::SparseSet::ConstIterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::DataIt = typename std::vector<T>::const_iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::IdIt = typename std::vector<EntityId>::const_iterator
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::iterator_category = std::forward_iterator_tag
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::value_type = T
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::difference_type = std::ptrdiff_t
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::pointer = const T*
using helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::reference = const T&
DataIt helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator*, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator->, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==.
IdIt helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::entityId, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++.
helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator()=default
Referenced by helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==.
helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator(DataIt dataIt, IdIt idIt)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.
reference helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator*() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
pointer helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator->() const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
EntityId helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::entityId() const
Returns the EntityId for the current element.
The EntityId associated with the current element.
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator==(const ConstIterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
bool helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator!=(const ConstIterator &other) const
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_.
ConstIterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++(int)
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator.
ConstIterator & helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::operator++()
References helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::ConstIterator, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::dataIt_, helios::core::ecs::SparseSet< T, TAllowRemoval >::ConstIterator::idIt_.