#ifndef NDEBUG
    #define HELIOS_DEBUG 1
#endif


#define RENDERQUEUE_MESHRENDER_COMMANDS_SIZE 100
#define RENDERQUEUE_TEXTRENDER_COMMANDS_SIZE 100

#define ENTITY_MANAGER_DEFAULT_CAPACITY 1000

#define UI_ACTION_COMMAND_HANDLER_DEFAULT_CAPACITY 100